### ISSUE TITLE
Unwanted animation of popup controller's view hierarchy 

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#10]
When popup view controller is being presented for the first time it's view hierarchy animates (expands from the bottom left corner) inline with the popup presentation animation. It can be reproduced in the sample app "Apple Music". Expected behaviour would be to see the view coming from the bottom.

**Comment by LeoNatan** [comment]
@Kastet Can you please record a video of this? I have not seen this in the demo app. What OS did you reproduce this on?

**Comment by Kastet** [comment]
@LeoNatan It's iOS9 Simulator running iPad Air2, Xcode 7 GM1

video: https://owncloud.bigtincan.com/owncloud/public.php?service=files&t=80527f0a974aa41a78a53db25274f28c

**Comment by LeoNatan** [comment]
Thanks, will take a look.

**Comment by LeoNatan** [comment]
Hmm, something seems very broken in that video. What did Apple do between beta 5 and GM? :(

**Comment by Kastet** [comment]
Thanks!
