### ISSUE TITLE
iOS 8 Crash registerForPreviewingWithDelegate:sourceView: unrecognized selector

### ISSUE THREAD

**Issue by atulvuliv** [LeoNatan/LNPopupController#100]
Getting error: 

`[TATabBarController registerForPreviewingWithDelegate:sourceView:]: unrecognized selector sent to instance
`
when trying to run the project on iOS8 device. Working fine on iOS9.

**Comment by LeoNatan** [comment]
Oh no!
Well, I'll be considering if iOS 8 is worth the effort, with iOS 10 already out. How long do you anticipate to have iOS 8 support?
