### ISSUE TITLE
Branch 2.0 Demo is not working...

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#108]
unrecognized selector sent to instance

**Comment by LeoNatan** [comment]
Need more details, please. What OS, what selector, etc.
For instance, iOS 8 is not a priority for branch 2.0. If you need that, please specify explicitly.

**Comment by LeoNatan** [comment]
@yarodevuci ?

**Comment by yarodevuci** [comment]
Tried on iOS 8. That's why

**Comment by LeoNatan** [comment]
Please try now. I made some changes.

**Comment by yarodevuci** [comment]
Works now! I wish you could change pause button on mini player next to "Next" Button and having album pic on the left like I have in my app https://github.com/yarodevuci/VKMusic
For now I cannot use your code :( 
But it is the best so far what I found

**Comment by LeoNatan** [comment]
That's exactly how it is in 2.0 branch.

**Comment by yarodevuci** [comment]
![simulator screen shot nov 6 2016 1 26 05 pm](https://cloud.githubusercontent.com/assets/13408859/20041872/a25b5312-a424-11e6-833d-044f8735346f.png)

I only see the pause button on the left

**Comment by LeoNatan** [comment]
I am sorry, I should make it clear. Right now, on iOS 10 and above, you will have the new bar and on iOS 9.0 and below, you will have the older behavior. This will be customizable, and you will be able to make it look like the new bar for all systems. Customization is not yet supported, so for now, I suggest you try on iOS 10 simulator and/or device.

**Comment by LeoNatan** [comment]
Regarding your iOS 8 use, I am not sure I want to continue support. iOS 8 has very low remaining usage, with iOS 10 already being at 60% and iOS 9 30%. iOS 8 has already made me do some things in a "strange way". I am not sure I want that. Please consider moving your target to iOS 9 and above.

**Comment by yarodevuci** [comment]
Sure, you are right.. Thanks for quick support
