### ISSUE TITLE
How to add action to UIBarButton item?

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#109]
I tried        
 let pause = UIBarButtonItem(image: UIImage(named: "pause"), style: .plain, target: nil, action: #selector((pauseButtonPressed)))
Did not work... iOS 9

**Comment by LeoNatan** [comment]
Please see the example project. You create the bar button items, and then have to assign them to either `leftBarButtonItems` or `rightBarButtonItems` of the popup item.

**Comment by LeoNatan** [comment]
You set the target to `nil`. Set it to the object you want to receive the action.

**Comment by yarodevuci** [comment]
Perfect! That is what I missed

**Comment by yarodevuci** [comment]
@LeoNatan rightBarButtonItems is readonly property, what to do?

**Comment by LeoNatan** [comment]
Huh?
Please read the documentation.

**Comment by yarodevuci** [comment]
@LeoNatan Got it, sorry about that.

**Comment by LeoNatan** [comment]
Cheers
