### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by gapl** [LeoNatan/LNPopupController#113]
Can we please get cocoapods support? I would love to have this as a part of my dependencies :)

**Comment by NikAshanin** [comment]
Pod::Spec.new do |s|
  s.name         = 'LNPopupController'

  s.version      = '2.0.0'

  s.summary      = 'framework for presenting view controllers'
  s.description  = 'LNPopupController is a framework for presenting view controllers as popups of other view controllers, much like the Apple Music and Podcasts apps.'
  s.homepage     = 'https://github.com/LeoNatan/LNPopupController'
  s.license      = 'MIT'
  s.author             = { "Leo Natan" => "lnatan@wix.com" }
  s.source       = { :git => 'https://github.com/LeoNatan/LNPopupController.git', :tag => 'v' <<   s.version.to_s }
  s.source_files  = 'LNPopupController/*.{h,m}', 'LNPopupController/**/*.{h,m}'
  s.requires_arc = true
  s.ios.deployment_target = '8.0'
  
  s.dependency 'MarqueeLabel', '3.0.0'
end

Just add it pls as LNPopupController.podspec file and push it to cocoapods :) Apparenlty, you will save a lot of hours for other developers.

**Comment by LeoNatan** [comment]
Guys, I have said it in the past - CocoaPods is not supported. There are many reasons for this. Instead of CocoaPods, use Carthage. You can continue using CocoaPods for for your other dependencies and Carthage for `LNPopupController`.

**Comment by gapl** [comment]
Allrighty - did not know this was said in the past. To avoid future questions it would be best to state this in the README.md file then :)

**Comment by LeoNatan** [comment]
You are right, I will add a comment about it.
