### ISSUE TITLE
New updates changed the popBar Color

### ISSUE THREAD

**Issue by RajChanchal** [LeoNatan/LNPopupController#115]
With the new updates to 2.0.1, the bar color does remain as of tabbar. Following is an example from your example project: Tabbar is black, but tabbar is kinda white. Same goes with my own project too. It was working fine previously though.
<img width="1275" alt="screen shot 2016-12-08 at 10 48 25 am" src="https://cloud.githubusercontent.com/assets/7058465/21000572/1dedf902-bd35-11e6-8efd-676df7807916.png">

**Comment by LeoNatan** [comment]
Thanks for reporting, will look into this issue.

**Comment by RajChanchal** [comment]
After updating, it did change the color. But I wrote the following code and everything went fine:

```
self.tabBarController?.tabBar.barStyle = .black
self.updatePopupBarAppearance()
```

**Comment by LeoNatan** [comment]
Did you set the bar style after presenting? If that is the case, you need to update. If you set it before presenting, and still needed to update, there may be a big out there.

**Comment by RajChanchal** [comment]
In the previous release, I was not setting any bar style, only thing I was doing was to change `tintColor `property of `tabbar `to `black` and it was working. And was expecting the same in the new update, as you can see in the screenshot above, I have the `tintColor `from storyboard and was expecting the bar to be black color.

**Comment by LeoNatan** [comment]
So it's a bug. Let's leave it open.
