### ISSUE TITLE
Keyboard Problem

### ISSUE THREAD

**Issue by RajChanchal** [LeoNatan/LNPopupController#116]
Another problem has occurred after the update 2.0.1, no any text field works fine. Keyboard appears when tapping a text field but buttons on on-screen keyboard are not type able. Try doing it into your own example project too. I did it, it even ruins the view too. It was fine in previous version.
![simulator screen shot 08-dec-2016 5 52 10 pm](https://cloud.githubusercontent.com/assets/7058465/21012375/187f6e62-bd6f-11e6-88ca-2c36282690d8.png)

**Comment by LeoNatan** [comment]
Strange issue. I will debug.

**Comment by DCDJ** [comment]
Can confirm this is happening for me too. Thanks for the quick responses with the issues @LeoNatan  :)

**Comment by LeoNatan** [comment]
Hmm seems to be related to my fix for #83. 😢 Some buggy iOS behavior. Looking at what can be done.

**Comment by mennolaan** [comment]
Took me some time to find the cause for my weird keyboard issue. Im tracking this bug report as wel, if I find something in the meantime I'll notify you. This version was really looking good. Great work Leo!

**Comment by LeoNatan** [comment]
Fixed!
