### ISSUE TITLE
Pop up close button de-shaped

### ISSUE THREAD

**Issue by RajChanchal** [LeoNatan/LNPopupController#117]
It may not be an issue. As no one has reported it yet. I am facing the problem of de-shaped close button. See in the image:
<img width="374" alt="screen shot 2016-12-08 at 7 54 51 pm" src="https://cloud.githubusercontent.com/assets/7058465/21016762/3a3d38d4-bd80-11e6-9f52-5b7c49a0c337.png">

And it was prior to 2.0.1 too and is still in 2.0.1 release too. Though, it looks very fine in your example project. Have any guess why it may have turned out to be like this? Though I am sure, I haven't customised this button.

**Comment by LeoNatan** [comment]
Hmm looks strange. What are you attempting to achieve and how? Can you create a demo project?

**Comment by LeoNatan** [comment]
I am unable to reproduce. Please provide a demo project where this occurs so I can debug.

**Comment by RajChanchal** [comment]
Will try reoccurring it and upload the demo by today. Thanks for being so cooperative and keep up with the repo.

**Comment by LeoNatan** [comment]
Thanks!

**Comment by RajChanchal** [comment]
@LeoNatan can you please tell me what does this line does: `[self.popupContentView.popupCloseButton sizeToFit];`

And when I try to print the frame of the close button in my contentView in its viewDidAppear method like this:
```
let closeBtn:LNPopupCloseButton = self.popupContentView.popupCloseButton!
print("frame: \(closeBtn.frame)")
```
It outputs it as: frame: (0.0, 0.0, 0.0, 0.0)
But despite so, it works perfectly fine (though little de-shaped).

**Comment by LeoNatan** [comment]
`sizeToFit` causes the button to change its bounds to the correct size according to its style. So for the round button style, you get a round size.

Tell me, do you by any change have large font?

**Comment by RajChanchal** [comment]
Large font, where? In popup bar? If yes, I have different font, but not large. Following are two snapshots:
**Bar**
<img width="312" alt="screen shot 2016-12-12 at 2 54 47 pm" src="https://cloud.githubusercontent.com/assets/7058465/21096860/12579c76-c07b-11e6-8641-1a1446a34cd8.png">

**Content View**
![simulator screen shot 12-dec-2016 2 55 17 pm](https://cloud.githubusercontent.com/assets/7058465/21096985/cea04716-c07b-11e6-9a67-20784b76aa02.png)

**Comment by LeoNatan** [comment]
I meant in display settings of iOS. I guess not if you are not familiar. 😄 

Can you create a demo project that reproduces it?

**Comment by RajChanchal** [comment]
I tried creating a demo, even with the same content view with same autolayout constraints (infact copied whole view controller from storyboard), but it doesn't de-shape!! :-) I think, we should close it as it is happening with me only.

[LNPopDemo 2.zip](https://github.com/LeoNatan/LNPopupController/files/646870/LNPopDemo.2.zip)

**Comment by LeoNatan** [comment]
No, I'll do a change to the code to see if it helps.

**Comment by RajChanchal** [comment]
Appreciate your dedication and love to code.

**Comment by LeoNatan** [comment]
If you use the `LNPopupCloseButtonStyleChevron` button style, does it look correctly (like in screenshots), or is it distorted also?

**Comment by RajChanchal** [comment]
It works very fine. No distortions in it.

**Comment by LeoNatan** [comment]
Please try with the HEAD version to see if it solves the issue.

**Comment by RajChanchal** [comment]
I have tried HEAD too, still same problem. But I can for sure say, it is not problem with you code, it's something I am doing wrong. Because I tried creating demo project, it didn't work even with same view constraints.
Then in the same project, I am working in. I tried adding an empty uiviewcontrollers and made it contentView, it did also showed de-shaped back button too. So, I should say, you can close this issue as it's specific to me only. 
I tried checking even the .appearance methods I was calling in appdelegate like:

```
LNPopupBar.appearance(whenContainedInInstancesOf: [UITabBarController.self]).titleTextAttributes = [NSForegroundColorAttributeName: goldColor,NSFontAttributeName:UIFont.init(name: ArabicFont, size: 17),NSParagraphStyleAttributeName: paragraphStyle]
        LNPopupBar.appearance(whenContainedInInstancesOf: [UITabBarController.self]).tintColor = .white
        LNPopupBar.appearance(whenContainedInInstancesOf: [UITabBarController.self]).backgroundColor = .black
```
But, they were not effecting the close button. Do you think it has to do anything with .appearance methods they may cause deshaping of it?

Though I am not calling any appearance method on UIButton too. 
Thanks for your support, @LeoNatan

**Comment by LeoNatan** [comment]
I can't see how appearance would interfere with button layout. This is the strangest of issues.
