### ISSUE TITLE
Error 'LNPopupController/LNPopupContentView.h' file not found

### ISSUE THREAD

**Issue by guijob** [LeoNatan/LNPopupController#119]
Hi!

I'm trying to use this popupbar in my project but I'm facing this error:

_Error 'LNPopupController/LNPopupContentView.h' file not found_

Does anyone knows how to solve it?

I already had a bridging-header so I've just added @import LNPopupController; to it but I'm getting few errors. I installed via Carthage.

![image](https://cloud.githubusercontent.com/assets/5354644/21101194/21408840-c05f-11e6-95a7-c7319351fa62.png)

**Comment by LeoNatan** [comment]
How did you import the project? Carthage?

**Comment by LeoNatan** [comment]
How did you integrate? Did you drag the project to your project?
Please compare to my Swift example project.

**Comment by guijob** [comment]
Thank you for your answer.

I've just installed via Carthage. I notice in your Example Project I need to open .xcodeproject file but I'm still must open .xorkspace file in my project because I have some cocoapods installed. Could this cause the error?

**Comment by LeoNatan** [comment]
No, I don't think so. You can open the workspace, but you have to drag LNPopupController.xcproj into your main project, and then follow the instructions in the README.

**Comment by guijob** [comment]
Ok, I thought installing via Carthage could be enough. I'll give a try dragging so.

**Comment by LeoNatan** [comment]
All Carthage does is bring it locally to you, and update it for you when necessary. You have to integrate in your project yourself. That's why I like it. 😄

**Comment by guijob** [comment]
It worked! Thank you very much!

**Comment by LeoNatan** [comment]
👍
