### ISSUE TITLE
Accessing popupContentView causes multiple instances of LNPopupController 

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#12]
This code

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.popupContentView.popupCloseButton.hidden = YES;
}

created multiple instances of LNPopupController and causes unpredicted behaviour. 

To test launch Allocations Instruments and filter by LN
<img width="1396" alt="screen shot 2015-09-24 at 3 14 31 pm" src="https://cloud.githubusercontent.com/assets/611542/10065948/56daae4c-62d0-11e5-9110-ac722dc1617c.png">

**Comment by LeoNatan** [comment]
Thanks, will investigate.

Other than multiple objects, what unpredicted behavior are you seeing?

**Comment by LeoNatan** [comment]
@Kastet I cannot reproduce. I think you may be calling `popupContentView` on the incorrect controller? How are you presenting the popup?

**Comment by Kastet** [comment]
@LeoNatan to reproduce make the following modifications in your sample app:

1. In DemoPopupContentViewController.m add 
- (void)viewDidLoad {
    [super viewDidLoad];
    self.popupContentView.popupCloseButton.hidden = YES;
}

The intention is to hide the close button

2. In LNPopupController.m place a breakpoint in initWithContainerViewController: or launch Allocations 

When you launch it and open the demo popup it'll create two instances of LNPopupController and the close button will not be hidden.

**Comment by LeoNatan** [comment]
You are using the wrong controller's `popupContentView`. Do not set it for `DemoPopupContentViewController` but in `FirstViewController`. Also, make sure you should set for `self` not `self.navigationController` or `self.tabBarController`. Remember, each view controller has a `popupContentView` of its own, and you should access it on the controller on which you call `present` on.
