### ISSUE TITLE
Hit Area

### ISSUE THREAD

**Issue by itjunkii83** [LeoNatan/LNPopupController#120]
Hello,

I have noticed that when including two bar buttons, one on left and one right the hit area for the left button expands too close to the middle and I believe it will affect the users dragging up experience. Also, since its a music control it will also cause people to pause music when they think they are expanding. I am especially concerned for my fitness app because that could affect someones workout.

I have tested on multiple iPhone sims, here is a screenshot on an iPhone 5 with the left limit of hit pointed out.

![iphone5buttonhitlimit](https://cloud.githubusercontent.com/assets/21177062/21316661/6dfce1d4-c5c7-11e6-8022-a93199d51a1a.jpg)

**Comment by LeoNatan** [comment]
Interesting issue. It's something normally controlled by the system, but I will take a look.

**Comment by LeoNatan** [comment]
Fixed this in 2.0.3. Please upgrade your version and test. 😄

**Comment by itjunkii83** [comment]
works perfect!!
