### ISSUE TITLE
Deallocation Issue

### ISSUE THREAD

**Issue by itjunkii83** [LeoNatan/LNPopupController#121]
Hello,

I have a storyboard just like in the example with several IBOutles.

When I dismiss my view that is calling presentPopupBarWithContentViewController: I get this crash:

NSInternalInconsistencyException: An instance 0x7ff27b760a30 of class LNPopupBar was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000382bea0> (
<NSKeyValueObservance 0x610008447dd0: Observer: 0x7ff27b44fca0, Key path: barStyle, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x610008447e90>

If I add this code:

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self dismissPopupBarAnimated:NO completion:nil];
}

The crash is avoided however if I return to the same dismissed view to create a new "music session" for the user the UIViewController does not respond to touch and LNPopupController does not present.

Do you think this is user error or a potential bug?

**Comment by LeoNatan** [comment]
Hi,

This was solved in a commit. I just have not made a release yet. I will create one now.

**Comment by itjunkii83** [comment]
Thanks Leo, I have updated via Carthage to 2.0.2 and the crash is no longer happening. However if I dismiss the presenting view controller then present it again it no longer responds to touch events and will not present a new instance of the popup controller. This happens if I do or don't invoke dismissPopUpBarAnimated in viewwilldissappear. If I never present the popup I can dismiss and present my vc with no issues.

**Comment by LeoNatan** [comment]
Please open a different issue and attach a demo project reproducing the issue, or a step by step. Thanks.

**Comment by itjunkii83** [comment]
Thanks Leo, appreciate you being so responsive!
