### ISSUE TITLE
Marquee not scrolling

### ISSUE THREAD

**Issue by itjunkii83** [LeoNatan/LNPopupController#122]
Hello,

I have noticed that I can't get my marquee to scroll on version > 2.0.2

I am calling self.popupBar.marqueeScrollEnabled = YES; 

I have also verified this is the case in the LN demo project under the Apple Music menu.

Thank you!

**Comment by LeoNatan** [comment]
I just tested and it works for me. The trick is to have the `.marqueeScrollEnabled = YES;` after presenting the popup bar (after calling `presentPopupBarWithContentViewController:animated:completion:`). The reason for this is the popup bar is not created until after the presentation. Calling right after presentation will not cause visual artifacts regardless if you are presenting with or without animation.

I agree this is not optimal and will think of a way to improve the API. Perhaps offer appearance support for that property for easier management.

**Comment by LeoNatan** [comment]
I have improved the API for 2.1. Now, what you originally did will work. The popup bar is created on demand, and will work as you originally expected.

**Comment by yetdog** [comment]
I am having the same problem. However, neither method works. I've tried calling self.popupBar.marqueeScrollEnabled = YES; from the initiating view, as well as inside the popup view itself. Neither seems to have an effect and my subtitle (which is far longer than the field can display) does not scroll.

**Comment by LeoNatan** [comment]
@yetdog Sorry, I just now am seeing your comment. Please elaborate. If you feel there is a bug, please open another issue.

The you should access the `popupBar` property on the presenting controller.
