### ISSUE TITLE
Changing the style to compact breaks ability to touch buttons on tab bar

### ISSUE THREAD

**Issue by aljosac** [LeoNatan/LNPopupController#123]
After using presentPopupBar and then setting the barStyle to .compact, I am unable to touch any of the tabBar buttons. It just causes the tabBar content view controller to show when attempting to touch a button. This can be replicated in the example app by adding: `tabBarController?.popupBar?.barStyle = .compact`
right under `tabBarController?.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: nil)`
in DemoAlbumTableViewController.swift

**Comment by LeoNatan** [comment]
Thanks for reporting. I will take a look.

**Comment by btc** [comment]
I can second this. iOS 9.3

**Comment by LeoNatan** [comment]
Fixed. @aljosac @btc Please test latest master code - no release yet.
