### ISSUE TITLE
Gesture Recognizer Hit Area

### ISSUE THREAD

**Issue by Bark17** [LeoNatan/LNPopupController#124]
Hi!
I'm trying to decrease hit area of GestureRecognizer which close popupController, but no results.
For example, is it possible to set draggable only the top half of the view?
Because sometimes it conflicts with other controls on view controller.
Thank you.

**Comment by LeoNatan** [comment]
Implement

`- (__kindof UIView*)viewForPopupInteractionGestureRecognizer;`

and provide a view to which the gesture recognizer will be limited to.

**Comment by Bark17** [comment]
Thank you!

**Comment by Bark17** [comment]
Sorry, I tried all ways. It doesn't work.
I can't provide new view through
`- (__kindof UIView*)viewForPopupInteractionGestureRecognizer;`

**Comment by Bark17** [comment]
Got it! Thank you
