### ISSUE TITLE
Jumpy snap behaviour on iOS 10

### ISSUE THREAD

**Issue by danurna** [LeoNatan/LNPopupController#125]
Just checked out the latest master and experienced a bug when panning upwards on the popup content view (see appended gif). Even when only panning slightly downwards it jumps the fixed amount. I guess this is unwanted behaviour.

![ios-10-up-pan-bug](https://cloud.githubusercontent.com/assets/1837452/21562752/ab6b4882-ce7b-11e6-8a15-db66b123156e.gif)

I already debugged this and found the issue [here (LNPopupController.m:585).](https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/Private/LNPopupController.m#L585) 
In the mentioned scenario using the iPhone 7 Plus simulator with iOS 10 the targetCenterY is increased from -32 to around -19, even when the panning gesture is upwards. 

I've identified two possible fixes:
- Only apply snap-specific code, if `targetCenterY` is greater than zero. (Would cover both cases, panning upwards and downwards.)
- Only apply snap-specific code, if the gesture direction is downwards. 

Which would you prefer or have you got any more input on this issue?
 

Btw. thanks for the great work. 👍 for taking care of accessibility, even in your sample code!

**Comment by LeoNatan** [comment]
Thank you. Will check it out.

**Comment by LeoNatan** [comment]
There is another issue I've identified; if the bar is closed but presented, if you pan your finger left on the bar, the system performs a close animation incorrectly. It is quite ugly. I am looking at both of these issues together.

**Comment by LeoNatan** [comment]
Fixed. Please test latest master code - no release yet.

**Comment by danurna** [comment]
Works like a charm now. I am definitely going to use it. Thank you!

**Comment by LeoNatan** [comment]
May I ask what app are you developing? 😄

**Comment by danurna** [comment]
I am in the process of creating a better version of an already existing radio streaming app. I'll probably display the audio player just like in your example 😀

**Comment by btc** [comment]
Thanks for fixing this one. I noticed it as well. Animation is super smooth now.
