### ISSUE TITLE
Change contentMode of popupItem's UIImageView?

### ISSUE THREAD

**Issue by btc** [LeoNatan/LNPopupController#126]
I would like to change the content mode of the popupItem's image view. Right now, it stretches my images (see below). Is this configurable (safely)?

<img width="436" alt="pasted_image_12_31_16__1_02_pm" src="https://cloud.githubusercontent.com/assets/734339/21579242/8f565608-cf59-11e6-85f2-b9a684dd7050.png">

**Comment by LeoNatan** [comment]
There isn't access to the image view directly, but I consider this a bug. The content mode should be aspect fit. I will add that.

**Comment by LeoNatan** [comment]
Fixed.

**Comment by btc** [comment]
Thank you
