### ISSUE TITLE
Multiple fingers required to drag down and dismiss content view

### ISSUE THREAD

**Issue by btc** [LeoNatan/LNPopupController#127]
Multiple fingers are required to drag and dismiss the content view (controller).

at 0e3111e78916d6f79474c3ccd2b2f7ff6bb33b72

**Comment by LeoNatan** [comment]
I don't understand.

**Comment by btc** [comment]
I apologize if I am getting the terminology wrong.

When the popupItem is tapped, the content view appears. 

When I try to drag down on the content view to dismiss it (and go back to the small popupItem), nothing happens. However, if I use multiple fingers (sometimes up to 4 required), then it finally responds to my drag down action and slides down.

**Comment by LeoNatan** [comment]
I don't see how this would happen.

**Comment by btc** [comment]
I will provide one.

**Comment by btc** [comment]
This bug happens when presenting from a UINavigationController. Since you don't support UINavigationController, I don't know if you care to address this one.

**Comment by LeoNatan** [comment]
I do support navigation controllers. There is only case where they are not supported, and that's your other issue.

**Comment by btc** [comment]
I experienced the issue while the toolbar was hidden. That's actually what I meant.

**Comment by LeoNatan** [comment]
Navigation controller issue has been solved. See if it helps you with this one.

**Comment by jahnsrud** [comment]
I was also experiencing this issue. Luckily, the latest release solved it. Thanks for creating this great library 👍

**Comment by LeoNatan** [comment]
@jahnsrud Thank you for the kind words!

**Comment by LeoNatan** [comment]
Does this still reproduce?
