### ISSUE TITLE
Content view disappears when presenting a popup while transitioning

### ISSUE THREAD

**Issue by btc** [LeoNatan/LNPopupController#129]
#### Description

The contentViewController disappears if its content changes during the transition.

#### Steps to Reproduce

1. Click on popupBar. (slide up animation begins)
1. Change the content/subviews of the contentViewController during its slide up animation.
1. Observe that the view disappears during the transition. Only the chevron remains. Dragging down doesn't work. Only tapping the chevron can dismiss the overlaid screen.

The bug only happens when the content of the contentViewController changes during the animation.

#### Video Evidence

There are two videos in this zip file. The first is "Normal". It shows the LNPopupController behaving normally. The second is "Bug". It shows the view controller disappearing during the animation.

[Archive.zip](https://github.com/LeoNatan/LNPopupController/files/681333/Archive.zip)

### Versions

iPhone 6, 7
iOS ~> 10
Xcode 8.2.1

**Comment by LeoNatan** [comment]
Thanks

**Comment by LeoNatan** [comment]
How do you change the content view controller's view?

**Comment by btc** [comment]
I removed all content modifications and the issue still occurs. It looks like it might actually be related to calling `presentPopupBar` while the animation is in progress. Does that seem more likely?

I fixed it by changing the code to:

```
if presenter?.popupBar.isHidden {
    presenter?.presentPopupBar()
}
```

This avoids my code calling presentPopupBar if it's already visible. This appears to fix the problem.

Do you still consider it a bug? (that the view disappears if presentPopupBar is called during animation?)

**Comment by LeoNatan** [comment]
Presenting a popup bar while the popup is in transition is not supported, but I couldn't reproduce this issue even as you say. I tried presenting while in transition and it didn't reproduce. I would like to fix it, even if not supported, so if you could provide a demo project, I'd take a look. Thanks.

BTW, instead of using `popupBar.isHidden`, use `popupPresentationState`, which tells you the state of the popup presentation.

**Comment by LeoNatan** [comment]
I am unable to reproduce the issue. Tried with different delays, but still won't fade like in the video. In any case, this is not supported.
