### ISSUE TITLE
Need API to dismiss popup controller in one step

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#13]
Currently it's two steps: close popup and dismiss bar. Would be nice to be able to dismiss popup in one step.

**Comment by LeoNatan** [comment]
You can use the dismiss method to close the popup in one step.

**Comment by Kastet** [comment]
Ah ok. I didn't try that because the method dismissPopupBarAnimated name wasn't clear. 
Thank you!
