### ISSUE TITLE
Setting popupBar tintColor has no effect

### ISSUE THREAD

**Issue by terryworona** [LeoNatan/LNPopupController#130]
#### Description
Setting the tintColor of a popupBar has no effect. Popup is attached to a tab bar (bottom of view controller).

#### Steps to Reproduce

```
self.popupBar.tintColor = UIColor.red
self.updatePopupBarAppearance() 
```

Screenshot attached after the above lines are executed. 

#### Device, OS and Xcode Versions
iOS 10 - both simulator and hardware. 

![popup-tint](https://cloud.githubusercontent.com/assets/358709/21597372/db5dac9e-d0fe-11e6-9dcb-c418c7302df0.png)

**Comment by LeoNatan** [comment]
The issue is, you are calling `updatePopupBarAppearance()`. What this method does is take the style of the bottom bar. Try without it. Check the music app sample, where a ronit color is set that is different from the tab bar's.

**Comment by terryworona** [comment]
I'm sorry I should have mentioned all the permutations that I tried. 

I have indeed tried:

`self.popupBar.tintColor = UIColor.red`

Same results - the bar continues to inherit from the tab bar.

**Comment by LeoNatan** [comment]
Which is `self` in your example? I just tested and everything works as expected; setting a tint color works.

**Comment by terryworona** [comment]
I present the popup via my root navigation controller:

'self.navigationController?.presentPopupBar(withContentViewController: self.trackViewController!, animated: true, completion: nil)'

For `self`, I've tried both both the presenting controller & the controller itself:

`self.navigationController?.popupBar.tintColor = UIColor.red`

and 

'self.trackViewController?.popupBar.tintColor = UIColor.red'

No luck with either attempt.

**Comment by LeoNatan** [comment]
Please look at the example project.

**Comment by terryworona** [comment]
Will do thanks!
