### ISSUE TITLE
Coordinate marqueeScroll disabled redrawing

### ISSUE THREAD

**Issue by matuslittva** [LeoNatan/LNPopupController#132]
When i disable coordinateMarqueeScroll and close PopupController title and subtitle are not drawn immediately, they appears only when i open and close PopupController again. When coordinateMarqueeScroll is enabled it behaves normally

iOS 10.2.1
Xcode 8.2.1

**Comment by LeoNatan** [comment]
Thanks, I'll take a look soon.

**Comment by LeoNatan** [comment]
@matuslittva Sorry, I cannot reproduce the issue. I disabled marquee coordination, I closed and opened the popup, and everything behaves normally. Could you please state in detail how to reproduce the issue?

**Comment by matuslittva** [comment]
hmm sudenly it works ... i cant investigate now why it failed before

**Comment by LeoNatan** [comment]
Thanks
Let me know if manage to reproduce.
