### ISSUE TITLE
LNPopupBar customize appearance

### ISSUE THREAD

**Issue by trane294** [LeoNatan/LNPopupController#134]
#### Description
I am trying to change appearance of LNPopupBar (different color & font). I am using swift 3. I think that I am doing smth wrong but couldn't find any materials how else todo it in swift 3. Thank you

#### Steps to Reproduce
LNPopupBar.appearance(whenContainedInInstancesOf: UINavigationController.self).setTitleTextAttributes = [NSFontAttributeName: UIFont(name: "Montserrat-Regular", size: 14)!]

I am getting error "Cannot convert value of type 'UINavigationController.Type' to expected argument type '[UIAppearanceContainer.Type]'"

**Comment by LeoNatan** [comment]
You are using the appearance API incorrectly. Did you read Apple's documentation?
`appearance(whenContainedInInstancesOf:)` receives an **array of classes**, not a single class. Pass `[UINavigationController.self]` instead.

**Comment by trane294** [comment]
Thank you it it working. But now it is giving error on any of methods that: 

```
Value of type 'LNPopupBar' has no member 'setTitleTextAttributes'
Value of type 'LNPopupBar' has no member 'setSubtitleTextAttributes'
Value of type 'LNPopupBar' has no member 'setBarStyle'
```

Also, I tried to access same methods through tabBarController?.popupBar

**Comment by trane294** [comment]
Okay, at least I can access it like this, but then why in documentation is  setTitleTextAttributes?

```tabBarController?.popupBar.titleTextAttributes```

**Comment by LeoNatan** [comment]
That part of the documentation is written in Objective C.

**Comment by LeoNatan** [comment]
You can use `titleTextAttributes` with the `appearance(whenContainedInInstancesOf:)` API.
