### ISSUE TITLE
Xcode 8.2.1 Warnings: Null is returned from a method that is expected to return a non-null value

### ISSUE THREAD

**Issue by GorbAnthony** [LeoNatan/LNPopupController#135]
When running Xcode 8.2.1 Analyzer, the following warning is returned

![2017-02-09 11 51 20](https://cloud.githubusercontent.com/assets/21270640/22778275/176e1a42-eebf-11e6-8dd5-19d465f1dc92.png)

**Comment by LeoNatan** [comment]
What is the method?

**Comment by GorbAnthony** [comment]
`- (UIView *)containerView
{
	return nil;
}`

after re-installation framework errors disappeared
