### ISSUE TITLE
Title label overlaps with rightBarButtonItems if more than one exists

### ISSUE THREAD

**Issue by johnnygao** [LeoNatan/LNPopupController#136]
#### Description
Using the current master branch in the iPhone 7, iOS 10 simulator.

I've added two buttons to the right side of the bar but the title label overlaps with the leftmost item.

![](http://i.imgur.com/pvVdF2A.png)

#### Steps to Reproduce
    // barbuttons
		let pause = UIBarButtonItem(image: UIImage(named: "ic_play_arrow"), style: .plain, target: nil, action: nil)
		let skip = UIBarButtonItem(image: UIImage(named: "ic_skip_next"), style: .plain, target: nil, action: nil)
		let pilot = UIBarButtonItem(image: UIImage(named: "ic_star"), style: .plain, target: nil, action: nil)
		
		self.popupItem.leftBarButtonItems = [pilot]
		self.popupItem.rightBarButtonItems = [pause, skip]

I believe the problem is this block in LNPopupBar.m, from line 474:

		[self.rightBarButtonItems enumerateObjectsWithOptions:NSEnumerationReverse usingBlock:^(UIBarButtonItem* barButtonItem, NSUInteger idx, BOOL* stop)
		 {
			 UIView* itemView = [barButtonItem valueForKey:@"view"];
			 
			 if(firstRightItemView == nil)
			 {
				 firstRightItemView = itemView;
			 }
		 }];
		
		rightMargin = (firstRightItemView == nil ? self.bounds.size.width - 10 : firstRightItemView.frame.origin.x) - (_resolvedStyle == LNPopupBarStyleProminent ? 5 : 10);
		
It currently tries to find the firstRightItemView by using NSEnumerationReverse, which returns the rightmost item, then since firstRightItemView is nil, the coordinates of the rightmost item are set for it. After that, the `if(firstRightItemView == nil)` never gets called again, so that the rightmost item's `frame.origin.x` is used to calculate the right margin.  

This could be fixed by either enumerating in the normal order, so that the leftmost rightBarButtonItem's coordinates are used for the margin, or changing the if-clause, for example to `if((itemView.frame.origin.x < firstRightItemView.frame.origin.x) || firstRightItemView == nil)`, so the block finds the leftmost item's coordinates.

**Comment by LeoNatan** [comment]
Thanks for reporting, I will check when I can. Pull requests are welcome.
