### ISSUE TITLE
cannot replace the close button

### ISSUE THREAD

**Issue by justin999** [LeoNatan/LNPopupController#137]
#### Description
I'm trying to replace the close button. I tried the code below, but it didn't work. 

    tabBarController.popupContentView.popupCloseButtonStyle = .default
    tabBarController.popupContentView.popupCloseButton.frame = CGRect(x: self.view.width - 50, y: 30, width: 30, height: 30)

![img_1015](https://cloud.githubusercontent.com/assets/3691498/22819477/99103c64-efb5-11e6-911e-62aade904765.jpg)

I check the code and figured out the position depends on PopupCloseButtonStyle.  I'd like to know if there's way to replace close button, and if it has, how to do it.

#### Device, OS and Xcode Versions

iOS 10.2.1
Xcode 8.2.1

Thanks,

**Comment by LeoNatan** [comment]
I don't understand what the problem is. Did you read the documentation?
If you want the round button style on the right, use `.round`. If you want to use a custom button, set the button style to `.none`, and add a button of your own in your view controller's view hierarchy and use the API to close the popup.

**Comment by justin999** [comment]
Your comment was really helped me. I will try with button style .none and custom button. I was trying to move the default button, which is impossible. Thanks for your help

**Comment by justin999** [comment]
for who strugglng with the same issue, this issue is also helpful 
https://github.com/LeoNatan/LNPopupController/issues/80

**Comment by LeoNatan** [comment]
The API is documented in the readme.
