### ISSUE TITLE
1px white line on the top of popup bar

### ISSUE THREAD

**Issue by stayclar** [LeoNatan/LNPopupController#139]
#### Description

<img width="376" alt="screen shot 2017-02-25 at 11 35 41" src="https://cloud.githubusercontent.com/assets/26022933/23330536/6e384dc8-fb50-11e6-8f59-17f29ee018ec.png">
Actually my problem is that I have a (around 1px) white line on the top of the popup bar. It appears only if I use the compact style. I figured out that the code reason is: self.tabBarController?.popupBar.barStyle = .compact

It is not depends on tabbar tintColor or things like this, I have tested out.

**Comment by LeoNatan** [comment]
This is on purpose. The compact bar uses a UIToolbar internally, and that one has that shadow hairline. It is like that on Apple as well. I do not plan change this. You can either use the prominent style, or you can create a custom bar content without the hairline, but then you have to manage the entire bar functionality.

**Comment by stayclar** [comment]
And can I change the color of that somehow?

2017-02-25 15:30 GMT+01:00 Leo Natan <notifications@github.com>:

**Comment by stayclar** [comment]
Or maybe change/remove it from your source in my project?

**Comment by LeoNatan** [comment]
Hmm, I see the white line. It’s too … white. The tab bar separator is a different shade of grey. Let me look.

**Comment by LeoNatan** [comment]
Fixed for iOS 10. 😄 
Didn’t check on iOS 9.

**Comment by stayclar** [comment]
Thanks a lot :D 
Oh and one last question, how can I hide the satusbar when I pull up (and show again when pull down) the popup controller? I mean where should I implement/change the statusbarhidden property?

**Comment by LeoNatan** [comment]
In the poppy content controller. Set the status bar settings there, and it will honor them.
