### ISSUE TITLE
UIPanGestureRecognizer from external view

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#14]
Hi Leo!

In my app I have scrollable content inside a popup so the built in UIPanGestureRecognizer doesn't work in my situation. I want to have a UIPanGestureRecognizer on the top bar of my view controller only, not on the whole screen.
Would it be possible add API to pass a UIPanGestureRecognizer to LNPopupController or to pass a UIView to which I want the recogniser to be added?

**Comment by LeoNatan** [comment]
Hey,

Let's see. I fear as it is built right now, a custom gesture recognizer is a problem, because the same gesture recognizer is used for both the bar and the content view. I think it would create mess the flows somewhat.

Let me see what I can do regarding a custom view.

**Comment by LeoNatan** [comment]
Implemented.
In your presented view controller, implement ```- (__kindof UIView *)viewForPopupInteractionGestureRecognizer``` and return the view you you wish to add the gesture recognizer to.

**Comment by Kastet** [comment]
Awesome! Thanks!
