### ISSUE TITLE
Disable feature "swipe down to dismiss ViewController" ?

### ISSUE THREAD

**Issue by lemanhtien** [LeoNatan/LNPopupController#140]
Firstly, I want to thank you for your great library. I am developing my application and using your library. My popupVC is embed in NavigationController. Then from my PopupVC, I push to a ViewControllerA. But when I in ViewControllerA, if I swipe down, the ViewControllerA will be dismissed.
Therefore, I want to ask you that is there a way to disable the feature that swiping down from the top to dismiss VC?
Thank you so much

**Comment by lemanhtien** [comment]
`/**
 *  Return the view to which the popup interaction gesture recognizer will be added to.
 *
 *  A default implementation is provided, where the popupContentView is returned. @see UIViewController.popupContentView
 *
 *  @return The view to which the popup interaction gesture recognizer will be added to.
 */
- (__kindof UIView*)viewForPopupInteractionGestureRecognizer`

I have solved my problem. Implement this function in the Navigation that hold popup view

**Comment by SoyArpad** [comment]
@lemanhtien hi, how did you disabled the swiping down from the top? can you give me an example?

**Comment by LeoNatan** [comment]
@SoyArpad What are you trying to achieve?

**Comment by SoyArpad** [comment]
I don't want the gesture of swipe down to dismiss because is blocking the gestures of my custom slider

**Comment by LeoNatan** [comment]
You can implement `viewForPopupInteractionGestureRecognizer` to return `nil`. This will disable the interactive gesture for open popups.

**Comment by SoyArpad** [comment]
So I need to subclass my navigation controller and override that property? But is it an optional? Can you give me a little example?

**Comment by LeoNatan** [comment]
You need to subclass the controller you are presenting in the popup controller. If you are presenting a navigation controller, you need to subclass that.

**Comment by LeoNatan** [comment]
Read the header file documentation for this. It explains how to use.

**Comment by LeoNatan** [comment]
You can now implement the delegate for the interaction gesture recognizer and disable the interaction if there is attempt to simultaneously interact with the slider. This way, you keep the interactive dismiss, while the slider works as expected.

**Comment by yarodevuci** [comment]
@LeoNatan  I am still confused how I suppose to implement that delegate ?

**Comment by iDevelopper** [comment]
You can disable the swipe down like this:

```
        targetVC.popupContentView.popupInteractionGestureRecognizer.delegate = self
        // ...

    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        return false
    }

```
