### ISSUE TITLE
Chevron appears over uinavigationitem sometimes

### ISSUE THREAD

**Issue by kajensen** [LeoNatan/LNPopupController#146]
#### Description
https://puu.sh/uKOCP/4febfec94c.png

#### Steps to Reproduce
Default setup with tabbar, presenting the popup with a uinavigation controller with set rootVC. The chevron appears over the default navigationitem.title sometimes. I would say roughly half the time. Drag down, and represent the same popupVC, the chevron will appear the below the navigation bar as expected. Presenting the popup straight from initialization.
Note: prefersStatusBarHidden does not make a difference.
#### Device, OS and Xcode Versions
Latest releases. Both simulator and real device.

**Comment by farshadmb** [comment]
use 
``` objective-c popupContentView.popupCloseButtonStyle = LNPopupCloseButtonStyleNone```
``` swift popupContentView.popupCloseButtonStyle = .None ``` @kajensen

**Comment by kajensen** [comment]
That doesnt work @farshadmb.

Its probably an issue with layout subviews with an adjust scroll view insets but i'll defer to someone with more experience with the library.

**Comment by LeoNatan** [comment]
I haven't seen this reproduce. Could you provide an example project?

**Comment by kajensen** [comment]
Yeah here: https://github.com/kajensen/LNPopupControllerBug. Not entirely sure its a bug in LNPopupController though. It happens when setting the left navigationitem button in tableVC.

**Comment by farshadmb** [comment]
@kajensen according to your image attached

> https://puu.sh/uKOCP/4febfec94c.png 

You create a UINavigationController with rootViewController which is a tableViewController or UIViewController contain UITableView. Also Create 2 UIBarButtonItem

One Note I must mention that is `LNPopupController` add UINavigationController view to its [`popupContentViewController`](https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/Private/LNPopupController.m) 

So must set this property 
`
objective-c self.popupBar.popupContentView.popupCloseButtonStyle = LNPopupCloseButtonStyleNone
swift self?.popupBar?.popupContentView.popupCloseButtonStyle = .None
'

**Comment by LeoNatan** [comment]
@kajensen Thanks for the demo project!
I will take a look soon.

The framework does a hit test under where the close button is supposed to appear normally. If a navigation bar answers the test, I move the close button below that bar. It has worked before, so I'm interested to see what is preventing this system from working here.

**Comment by LeoNatan** [comment]
@kajensen Using the demo project, I was able to reproduce. Looks like a weird bug with layout. Investigating.
