### ISSUE TITLE
Presenting view controllers on detached view controllers is discouraged

### ISSUE THREAD

**Issue by kajensen** [LeoNatan/LNPopupController#147]
When displaying a popupcontroller of a uinavigationcontroller with set rootVC, presenting another VC on top (UIalertcontroller, sfsafariVC, etc) results in "Presenting view controllers on detached view controllers is discouraged"

**Comment by LeoNatan** [comment]
I know why this happens. Controllers presented in the popup are not added as child view controllers. They used to be, but this had nasty side effects. 
Need to think how to solve this.

**Comment by kajensen** [comment]
The real issue i'm seeing in regards to this is a sfsafarVC just doesn't load the website if its presented like this (UIalertCs work fine). I've tried presenting from the navigationC, VC, and both have this warning. Presenting from the tabVC (which presents the popover) results in "tavbVC is already presenting a vc" and nothing happens. If theres a workaround to present without issue by climbing the hierarchy somehow thats fine for now. Suggestions?

**Comment by LeoNatan** [comment]
Hmm interesting.
The framework does not use the `UIViewController` presentation APIs. So when I first read your issue, my instinct was to recommend presenting on the tab bar / navigation controller. For instance, using the delegate pattern to notify some controller that the user has performed an interaction that requires presenting a safari view controller, and do that presentation there.

Normally, if you have a `UITabBarController` -> `UINavigationController` -> `UIViewController` controller hierarchy, and you present a view controller on the inner view controller, the UIKit system actually traverses all the way up to the tab bar controller and presents on that. So it really shouldn't matter where you present.

**Comment by kajensen** [comment]
The solution is to present from popupPresentationContainer

**Comment by kajensen** [comment]
in this case, vc.navigationController.popupPresentationContainer

**Comment by LeoNatan** [comment]
@kajensen The issue has been solved. Please use the latest 2.2 release.

**Comment by kajensen** [comment]
Thanks for your attention and hard work @LeoNatan Great lib!

**Comment by LeoNatan** [comment]
@kajensen Thank you for using my framework!

**Comment by iDylanK** [comment]
Hey @LeoNatan, we have this same issue on v2.18.3, which causes issues with the implementation of a new screen. This screen is presented from the rootVC inside the navigiation controller.

[DemoPopup.zip](https://github.com/LeoNatan/LNPopupController/files/14166284/DemoPopup.zip)

**Comment by LeoNatan** [comment]
@iDylanK Please open a new issue and attach a video of the issue and the demo project you have attached here. Thanks
