### ISSUE TITLE
ParagraphStyle support

### ISSUE THREAD

**Issue by MetaImi** [LeoNatan/LNPopupController#15]
In 0c98357b1d23197a5cb07aab9c7f0664d2de595b you have removed the default centered text alignment. Now I tried to set the alignment with paragraphStyle, but it does not work. 

 NSMutableParagraphStyle *paragraph= [[NSMutableParagraphStyle alloc] init];
    [paragraph setAlignment:NSTextAlignmentCenter];
    [[LNPopupBar appearanceWhenContainedInInstancesOfClasses:@[[UINavigationController class]]] setTitleTextAttributes:@{NSFontAttributeName: [UIFont fontWithName:@"Chalkduster" size:14], NSForegroundColorAttributeName: [UIColor yellowColor],NSParagraphStyleAttributeName : paragraph}];

**Comment by LeoNatan** [comment]
Thanks, I will take a look.

**Comment by LeoNatan** [comment]
@MetaImi It seems like an issue with cbpowell/MarqueeLabel. I have opened an issue in the original repository (cbpowell/MarqueeLabel#116). Until then, I have added a workaround for alignment.
