### ISSUE TITLE
Navigation bar of presented view controller to be the popup bar itself

### ISSUE THREAD

**Issue by mattstrong** [LeoNatan/LNPopupController#151]
#### Description
Is this currently possible? I can only see examples where the popup bar itself seems separate from the presented view controller and scrolls up above the screen in presented mode.

Great component! Thanks for making it :)

**Comment by LeoNatan** [comment]
That’s an interesting use case.
It’s not possible right now, even with the custom popup view.

I think it could be done. I will take a look when I have time.

In the mean time, you can fake it with a custom popup bar controller, and hide it during presentation. I do that in the “Maps” example in the demo project.

**Comment by mattstrong** [comment]
Thanks a lot Leo

"Maps" example seems like a good approach to this

I think I'll try writing something from scratch. My initial thought would be to combine a Container View Controller structure with UIView​Controller​Interactive​Transitioning. 

My assumption is that containment is needed for multiple view controllers to be on screen at the same time and UIView​Controller​Interactive​Transitioning can be used to transition the popup VC from minimized to expanded state

Would you approach this in the same way? Any warnings or feedback is very much appreciated!


https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html
https://developer.apple.com/reference/uikit/uiviewcontrollerinteractivetransitioning

**Comment by LeoNatan** [comment]
What are you trying to accomplish?
`UIView​Controller​Interactive​Transitioning` does not help with controller containers, it only helps with modal presentation.

**Comment by mattstrong** [comment]
I'm essentially trying to accomplish what you showed in the Maps demo, but preferably with the presented view controller to actually be the popup bar itself. In the minimized state, this view controller would still be on screen

Here are two very interesting articles that outline how to achieve this functionality:

https://www.objc.io/issues/12-animations/custom-container-view-controller-transitions/
http://www.iosnomad.com/blog/2014/5/12/interactive-custom-container-view-controller-transitions

I haven't started implementation yet. Do you see any clear drawbacks with this approach?

**Comment by mattstrong** [comment]
The article does however not mention if the approach is suitable when there are multiple child view controllers on screen before or after the transition

Any insight you might have on this Leo would be extremely helpful

**Comment by LeoNatan** [comment]
Those articles mention specifically what that method is good for:

- Navigation controller pushes and pops
- Tab bar controller selection changes
- Modal presentations and dismissals

I don't this is what you need. You will need to implement all of the interaction yourself for the cards, like this framework. The fact that you are working with view controllers is irrelevant; there are only views on screen. You will have to manage all of it.

**Comment by LeoNatan** [comment]
I intend to work on your usecase soon, regardless. 

If you start your own implementation, let me know. I'd like to take a look. 

I also had in mind to create a Maps-like cards interface. I just haven't been able to decide whether it should be part of this framework or another.

**Comment by LeoNatan** [comment]
I am closing this issue. The framework has undergone a lot of changes over the years, and I have some plans for the future. I don't think this use-case will be given a high enough priority.
