### ISSUE TITLE
App crashes in iOS 9, working fine in iOS 10

### ISSUE THREAD

**Issue by RajChanchal** [LeoNatan/LNPopupController#153]
#### Description
App crashes in iOS 9. Following is the Fatal Exception:

> [<_UITabbarBackgroundView> valueForUndefinedKey:]: this class is not key value coding-compliant for the key shadowView
StackTrace indicates the issue in LNPopupController.m file's line numebr 854:
`self.popupBar.systemShadowColor = [_bottomBar valueForKeyPath:str2];`
<img width="1267" alt="screen shot 2017-04-05 at 8 52 48 am" src="https://cloud.githubusercontent.com/assets/7058465/24696299/0d6c677c-19fa-11e7-8002-5a927fa74c9f.png">

#### Steps to Reproduce
1. Call the following method, it crashes always:` [self.tabBarController presentPopupBarWithContentViewController:VC animated:YES completion:nil];` 

It was working fine in 2.1.0. Upgrading it to 2.2.0 caused the crash.

Regarding demo project, I tried running example project with this repo, and it did also crash (I tried tabbed bar with navigation and without navigation both).
<img width="1280" alt="screen shot 2017-04-05 at 12 48 28 pm" src="https://cloud.githubusercontent.com/assets/7058465/24697443/3b30e03a-19fe-11e7-8a97-ac60e7b01968.png">

#### Device, OS and Xcode Versions
iOS = 9.x.x
XCode = 8.2
Simulator = iPhone 6 Plus (9.3)

**Comment by LeoNatan** [comment]
Thanks!
Will fix this soon.

**Comment by LeoNatan** [comment]
Please use v2.2.2 release.

**Comment by RajChanchal** [comment]
Thanks a lot, Leo. Seems like the property of shadowView is inaccessible in iOS 9.
