### ISSUE TITLE
hitTest in customBarViewController's view

### ISSUE THREAD

**Issue by swasta** [LeoNatan/LNPopupController#156]
#### Description
I have a UITabBarController containing UIViewController. In this UIViewController I do 

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    customPopupBarViewController = storyboard!.instantiateViewController(withIdentifier: "CustomPopupBarViewController") as! CustomPopupBarViewController
    tabBarController?.popupBar.customBarViewController = customPopupBarViewController
}
```

My CustomPopupBarViewController has a button, which is partially outside the bounds of its parent view. Red part of the button should be touchable, but it isn't. When I touch the red part of the button, the view under the popup bar reacts on the touch, but not the button itself.
![untitled diagram](https://cloud.githubusercontent.com/assets/5530878/25784943/5f1a3af2-337e-11e7-817d-52fe0aa4140c.png)

I subclassed UIView as BarView and made the root view of CustomPopupBarViewController to be BarView.

```swift
class BarView: UIView {
    @IBOutlet weak var playButton: UIButton!
    
    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let pointForTargetView = playButton.convert(point, from: self)
        if playButton.bounds.contains(pointForTargetView) {
            return playButton.hitTest(point, with: event)
        }
        return super.hitTest(point, with: event)
    }
}
```

But it didn't work out, because hitTest doesn't get called if I touch red part of the button. How can I fix this? I want the whole area of the button to be tappable. 

#### Device, OS and Xcode Versions
iOS: 10.3.1
Xcode: 8.3.2

**Comment by LeoNatan** [comment]
Could you provide a demo project? 
I need to brush up my `hitTest` memory.

**Comment by swasta** [comment]
I created [the demo project](https://github.com/swasta/Demo-for-LNPopupController), could you please check that out? If you tap on the top and bottom parts of the button, you'll see that outer part of the button doesn't react on touches. To fix this, I tried to follow
https://developer.apple.com/library/content/qa/qa2013/qa1812.html
http://stackoverflow.com/a/30431157/4933617

But hitTest() in my BarView simply doesn't get called when I tap the top part of the button.

**Comment by LeoNatan** [comment]
Thank you. I will take a look soon.

**Comment by LeoNatan** [comment]
You can now implement this using the interaction gesture recognizer delegate. Implement `shouldReceiveTouch` and calculate if touch is inside.
