### ISSUE TITLE
Popup bar does not fade correctly when opening the popup programmatically

### ISSUE THREAD

**Issue by user3587412** [LeoNatan/LNPopupController#157]
#### Description

When opening a popup with `openPopup`, the popup bar immediately disappears as the presenting animation starts. Opening the popup normally (e.g., `wantsDefaultTapGestureRecognizer = true`) fades out the popup bar while the popup opens. 

#### Steps to Reproduce

The provided custom popup bar example "Maps" shows an example of this behavior. 

<img src="https://cloud.githubusercontent.com/assets/8388844/25795263/365802fe-339a-11e7-929e-13d9fe7e71c4.png" alt="simulator screen shot may 8 2017 2 53 21 am" width="375" height="667">
<img src="https://cloud.githubusercontent.com/assets/8388844/25795142/a6c10d02-3399-11e7-8d6e-52f001a0e44d.png" alt="simulator screen shot may 8 2017 2 53 43 am" width="375" height="667">

The first image shows the popup bar disappeared while the popup is opening, while it would normally fade out. The bottom image shows the popup bar fading in when the popup is being closed. 

#### Device, OS and Xcode Versions

OS: 10.12.4
Xcode: 8.3.2
Simulator: iPhone 7 iOS 10.3

**Comment by LeoNatan** [comment]
Thanks for reporting, I will take a look.

**Comment by LeoNatan** [comment]
This issue has been resolved in master. I will have a new release soon.

**Comment by user3587412** [comment]
Thank you!

**Comment by LeoNatan** [comment]
Thank you for using my framework!
