### ISSUE TITLE
Delegate for PopupController disappeared

### ISSUE THREAD

**Issue by dunqi** [LeoNatan/LNPopupController#158]
Hello,

is there a delegate that will be called, wenn I close the PopUpController with dragging?
Cause viewWillAppear / viewDidAppear will not be called.

I want to update the StatusBar-Style and some other things, If the PopUp closes.

**Comment by LeoNatan** [comment]
There is no delegate method right now. What is your use-case here?

**Comment by dunqi** [comment]
I want to reset StatusbarStyle - cause the PopUpController has .lightContent and the normal Tabak has .default

**Comment by dunqi** [comment]
I make a workaround and make it in "viewWillDisappear" and "viewWillAppear", but thats no beautiful...

**Comment by LeoNatan** [comment]
You should be using the view controller-based API. The `UIApplication` API is deprecated by Apple and not supported by `LNPopupController`.

**Comment by dunqi** [comment]
You mean preferredStatusbarStyle? It didn't called, when the popup closes - but I will give it a second try

**Comment by LeoNatan** [comment]
You might have disabled this in your Info.plist. Make sure view controller-based status bar management is either not present in Info.plist or set to `YES`. See the example project.
