### ISSUE TITLE
Crash when title or subtitle nil

### ISSUE THREAD

**Issue by MetaImi** [LeoNatan/LNPopupController#16]
I've got a crash when the title or subtitle property is nil on presentation. 
The crash is in the LNPopupBar : _layputTitles method, at line 281:
_titleLabel.attributedText = [[NSAttributedString alloc] initWithString:_title attributes:defaultTitleAttribures];

of course the error is the following: 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteAttributedString initWithString:: nil value'

For the subtitle, I did not check, but based on the code, it is the same :)

**Comment by LeoNatan** [comment]
Oops. Thanks, will fix soon.
