### ISSUE TITLE
Present popupBar only for one of the tabs

### ISSUE THREAD

**Issue by swasta** [LeoNatan/LNPopupController#160]
#### Description
I have a `UITabBarController` with 3 `UIViewController`s. I'd like popupBar to be visible only on the 2nd ViewController, not on the 1st and 3rd ones. To achieve this I `presentPopupBar(withContentViewController: contentViewController, animated: true, completion: nil)` in my 2nd ViewController. And I also have a `dockingView` to prevent popupBar from being behind tabBar.

```swift
let yOffset = UIScreen.main.bounds.height - tabBarController!.tabBar.frame.height
let dockingFrame = CGRect(x: 0, y: yOffset, width: UIScreen.main.bounds.width, height: tabBarController!.tabBar.frame.height)
let dockingView = UIView(frame: dockingFrame)
```

```swift
override var bottomDockingViewForPopupBar: UIView? {
    return dockingView
}
    
override var defaultFrameForBottomDockingView: CGRect {
    let yOffset = UIScreen.main.bounds.height - tabBarController!.tabBar.frame.height
    return CGRect(x: 0, y: yOffset, width: UIScreen.main.bounds.width, height: tabBarController!.tabBar.frame.height)
}
```

Now popupBar shows only on the 2nd viewController, but when I tap or drag popupBar upward to open contentViewController, tabBar remains at the bottom of the screen:(

When I present it on UITabBarController and then open it, tabBar hides perfectly.
```swift
tabBarController?.presentPopupBar(withContentViewController: placeViewController, animated: true, completion: nil)``
``` 
but I don't want popupBar to show on all viewControllers in UITabBarController:(

Is there any way to solve this?

#### Device, OS and Xcode Versions
iOS 10.3.2
XCode 8.3.3

**Comment by LeoNatan** [comment]
Interesting. This is not possible currently, and I am not sure it will be. 
Let’s try an idea; what happens if you return the tab bar as your docking view?

**Comment by swasta** [comment]
If I do

```swift
override var bottomDockingViewForPopupBar: UIView? {
    return tabBarController!.tabBar
}
    
override var defaultFrameForBottomDockingView: CGRect {
    return tabBarController!.tabBar.frame
}
```

in my 2nd viewController, the popupBar shows on each tab. Even though I present it not on tabBarController, but on my 2nd viewController.
With this, opening the popupBar hides the tabBar, but closing the popup makes the popupBar go under the screen and there's a white space instead of tabBar.

**Comment by LeoNatan** [comment]
Hmm right, as I actually add the popup content to the superview of the bottom bar.

You could hide and show the popup bar with `animated: NO`. What happens if you do that?

**Comment by swasta** [comment]
Thanks, it worked! I dismiss popupBar for all tabs and present it for my 2nd tab.

**Comment by LeoNatan** [comment]
Great. I will close the issue, as I do not have plans to add support for this in the API. Happy coding!
