### ISSUE TITLE
Is there a way to adjust the popup bar height dynamically?

### ISSUE THREAD

**Issue by antiraum** [LeoNatan/LNPopupController#161]
Thanks for this great component.

I'm using a `customBarViewController` for my popup bar. Depending on the horizontal size class I want to have different heights for the popup bar. My `LNPopupCustomBarViewController` subclass sets the `preferredContentSize` accordingly and the bar has the correct height when it's shown. But I'm not able to have the bar height change when the horizontal size class changes while the bar is visible.

I'm updating the `preferredContentSize` from `traitCollectionDidChange` and calling
```
containingPopupBar.setNeedsLayout()
containingPopupBar.layoutIfNeeded()
```
afterwards to trigger `LNPopupBar`s `layoutSubviews`. But this has no effect.

Any ideas how to get this to work?

**Comment by LeoNatan** [comment]
Hmm this seems to be an oversight on my part. I will look to fix this soon.
In the mean time as a workaround, when the trait collection changes, dismiss and present the popup bar with no animation to trigger the height change.

**Comment by LeoNatan** [comment]
I implemented this. I will soon release a new version.

**Comment by antiraum** [comment]
works great. thx!
