### ISSUE TITLE
Compile error for case sensitive file system 

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [LeoNatan/LNPopupController#163]
#### Description

Typo in file LNPopupBar.h
#import <LNPOpupController/LNPopupCustomBarViewController.h>
leads to build error for case sensitive file system

#### Steps to Reproduce
Try to use framework in OS with case sensitive file system

#### Device, OS and Xcode Versions
MacOS: 10.12.4 
Xcode: 8.3.2
File system:
Content (IOContent):      Apple_HFSX
   File System Personality:  Case-sensitive Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Case-sensitive, Journaled)

**Comment by LeoNatan** [comment]
Oops! Thanks for reporting!
