### ISSUE TITLE
Is there a way to hide progress totally?

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [LeoNatan/LNPopupController#164]
#### Description
The LNPopupController is very handful tool. But I did not find a way to hide Progress view at all. It is possible?

If not, can you implement this feature?

**Comment by LeoNatan** [comment]
In order to hide the progress view, set it to hidden.

**Comment by YuriyVelichkoPI** [comment]
Sorry @LeoNatan, but can you point me how to o this. The progres view is a property in the private file. I have hide it by marking progress view by accessability identifier and extracting it from views hierarchy. But I supose that should be a more convinirnt way.
Thanks!

**Comment by LeoNatan** [comment]
Hmm, I see. I’ll reopen this issue for now.
