### ISSUE TITLE
Does LNPopupCloseButtonStyle work correctly? (iOS 10 release version)

### ISSUE THREAD

**Issue by MosheBerman** [LeoNatan/LNPopupController#165]
#### Description

I'm using the framework as a git submodule, and have been using it since one of the earlier versions. I think I found an issue with LNPopupCloseButtonStyleNone. It seems that no matter how (`UIAppearance`  or by setting it directly on content view) or when (at app launch, or any of the view controller lifecycle methods) the property is ignored.

I'm using the latest version of the framework. (`git log` shows c2ab08ac1828fbd5502826707c6df4d5e39f2a6a as the latest commit, which is consistent with the releases page, showing 2.2.3 referencing that commit.)

I looked at the KVO implementation in LNPopupController.m, line 1022, and it seems to do what I would expect, but something isn't right.

(I have an Xcode project that I can give @LeoNatan access to if necessary.)

#### Steps to Reproduce

1. Call `[LNContentView.appearance setPopupCloseButtonStyle:LNPopupCloseButtonStyleNone];`
2. Present a navigation controller with a child view controller.

Or, inside of your content view controller:

1. In `viewDidLoad` set `self.contentView.popupCloseButtonStyle = LNPopupCloseButtonStyleNone;`
2. Present the content view at runtime

In both cases, the expected behavior is for there to be no framework provided close button. Instead, the default button is appearing. 

The button is expected to disappear, but instead it shows up in the Default style. I also confirmed in the Xcode debugger that the style looks like it's getting set to `LNPopupCloseButtonStyleNone` at some point, but please don't take my word for it.

#### Device, OS and Xcode Versions

I'm using Xcode 8.3.3 and the iPhone 7 - iOS 10 simulator.

**Comment by MosheBerman** [comment]
Looks like I missed a Swift version of the enum `.none` in search... This is embarrassing, but I'm going to close this.

**Comment by LeoNatan** [comment]
No worries, cheers!
