### ISSUE TITLE
UITabBar item titles get misplaced

### ISSUE THREAD

**Issue by swasta** [LeoNatan/LNPopupController#167]
#### Description
I have a UITabBarController and I want to show popupBar only for one of the VCs, so I dismiss popupBar for every VC except one. My custom popupBar is red with a blue button in the middle. But something is wrong with tabBar.
![simulator screen shot 27 jun 2017 00 01 50](https://user-images.githubusercontent.com/5530878/27560571-5d065eaa-5acd-11e7-8fe4-24ed40bacbbc.png)
![simulator screen shot 27 jun 2017 00 01 46](https://user-images.githubusercontent.com/5530878/27560573-5d323e62-5acd-11e7-9af4-94d891001621.png)

As you may see, for the `SecondVC` tabBar titles are lower than they should be. Switching between these to VCs shows that tabBar strangely shrinks or goes slightly below the screen on the `SecondVC`. Although on the `FirstVC` it gets back to normal.

I noticed, that the bigger height in `prefferedContentSize` for popupBar, the lower titles in tabBar are placed.

Also, is it possible to hide progress bar from the popupBar? There're only two options: top and bottom.

#### Steps to Reproduce
[Here](https://github.com/swasta/DemoProject) is a test project that reproduces the issue

#### Device, OS and Xcode Versions
Xcode  8.3.3
iOS 10.3.2
iPhone SE

**Comment by LeoNatan** [comment]
This is a strange issue. I will look soon in your test project.

Regarding hiding the progress bar, the enhancement is tracked in #164. I will be implementing it soon.

**Comment by swasta** [comment]
By the way, on iOS 11 tabBar stays where it should be. However in my log I see

```
"<NSAutoresizingMaskLayoutConstraint:0x1c4299140 h=--& v=--& _LNPopupToolbar:0x1128083e0.width == 0   (active)>",
    "<NSLayoutConstraint:0x1c048f050 H:|-(20)-[_UIButtonBarStackView:0x11280a5b0]   (active, names: '|':_UIToolbarContentView:0x112809f90 )>",
    "<NSLayoutConstraint:0x1c048f0a0 _UIButtonBarStackView:0x11280a5b0.trailing == _UIToolbarContentView:0x112809f90.trailing - 20   (active)>",
    "<NSLayoutConstraint:0x1c0285870 _UIToolbarContentView:0x112809f90.trailing == _LNPopupToolbar:0x1128083e0.trailing   (active)>",
    "<NSLayoutConstraint:0x1c0294500 H:|-(0)-[_UIToolbarContentView:0x112809f90]   (active, names: '|':_LNPopupToolbar:0x1128083e0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1c048f0a0 _UIButtonBarStackView:0x11280a5b0.trailing == _UIToolbarContentView:0x112809f90.trailing - 20   (active)>
```

My structure is:

UITabBarController has UIViewController which calls tabBarController?.presentPopupBar.

But moreover, when I present anything modally from my `customPopupBarViewController` on iOS11, after dismissing it, instead of opened `popupBar` with `customPopupBarViewController` I see my UIViewController without tabBar and popupBar. I guess, both disappeared because of constraint conflicts.

**Comment by LeoNatan** [comment]
iOS 11 issues should be reported in the iOS 11 thread. Thanks. I have not had time to investigate possible issues in iOS 11. Seems like a lot has changed under the hood.

**Comment by LeoNatan** [comment]
This issue will be tracked in issue #180.

**Comment by LeoNatan** [comment]
Fixed. Please test 2.5.0 release and let me know.
