### ISSUE TITLE
function of custom popupInteractionGestureRecognizer delegate is not called

### ISSUE THREAD

**Issue by antiraum** [LeoNatan/LNPopupController#170]
Using version 2.3.1, iOS 10, Xcode 8.

I'm assigning a custom delegate to the `popupInteractionGestureRecognizer` like this:

```
popupContentView.popupInteractionGestureRecognizer?.delegate = self
```

My implementation of `gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch)` is not called:

```
extension TabBarController: UIGestureRecognizerDelegate {

    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        // this is called
        return true
    }

    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        // this is _not_ called
        return true
    }
}
```

**Comment by kjantzer** [comment]
I'm trying to do this as well and the following is called

`gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool`

But returning `false` does not keep the view from closing. Am I missing something?

**Comment by LeoNatan** [comment]
I will look into these issues this weekend.

**Comment by LeoNatan** [comment]
Fixed.

**Comment by antiraum** [comment]
thx
