### ISSUE TITLE
Title and Buttons are misaligned in the bar 

### ISSUE THREAD

**Issue by wytemusic** [LeoNatan/LNPopupController#171]
#### Description
While implementing LNPopupController into my Swift project I came across one "bug". At this point I'm not entirely sure if it is based on the framework itself or my implementation of it. Though I believe it is the latter.
After having the bar appeared the labels (title, subtitle) and the buttons (left and right) are misaligned. They are shifted quite far to the left of the screen. Also tapping on the bar won't open it. Sliding up works, though. 
After exiting the app (not removing its memory out of the ram), locking the device, choosing different tracks, switching menus in the tabBar of the app, countless times, first the button aligned properly and after opening the bar by swiping and closing it again the labels aligned correctly, too. 
That "fix" was applicable all the time for me.

Here is an image of the content of the bar being misaligned: 
![img_8214](https://user-images.githubusercontent.com/29824653/28847645-4f87f202-7710-11e7-98cf-47a6411df61b.PNG)

Here is one of the whole content of the bar aligned properly:
![img_8213](https://user-images.githubusercontent.com/29824653/28847744-a96161aa-7710-11e7-9875-f263579dc05b.PNG)

(As of now the button only is a white circle, that is intended.)

#### Steps to Reproduce
1) Implement [code](https://gist.github.com/wytemusic/c7e15fbbb495e24b50e81621d782248c) 
2) Open app
3) Trigger the bar to appear

[Here is my code regarding LNPopupController](https://gist.github.com/wytemusic/c7e15fbbb495e24b50e81621d782248c). 

Here is an image of my storyboard:
<img width="109" alt="screen shot 2017-08-01 at 23 38 16" src="https://user-images.githubusercontent.com/29824653/28848255-8a9354e8-7712-11e7-9c8d-c60f7dcd7f7e.png">

#### Device, OS and Xcode Versions
Tested on iPhone 9,3 (iPhone 7) iOS 11 Developer Preview 4 (15A5327g). Please note that your example project, from which my code has been taken, works perfectly on the named device. 

PS: I really want to thank you for taking the time creating such a great framework! It looks really well.

**Comment by LeoNatan** [comment]
I’m not sure what to look for here. I frankly don’t understand what is going on. From a very quick look at the code, nothing pops out.
Please provide a demo project where this issue reproduces.
