### ISSUE TITLE
Cannot get popup gesture to disable

### ISSUE THREAD

**Issue by kjantzer** [LeoNatan/LNPopupController#173]
Per the docs, it appears I should be able to disable the pan gesture, but the following is not working

```
self.popupContentView.popupInteractionGestureRecognizer?.isEnabled = false
```
Any ideas why that might be?

#### Device, OS and Xcode Versions
iPhone 7 simulator iOS 10+ Xcode 8.3.3 (swift)

**Comment by LeoNatan** [comment]
What are you attempting to accomplish?

**Comment by LeoNatan** [comment]
Ping

**Comment by kjantzer** [comment]
I want to disable the gesture when a user begins dragging a uislider. It's annoying to be changing the slider value and then the popup closes.

**Comment by LeoNatan** [comment]
I see. You can achieve this by setting the gesture recognizer's delegate and doing some logic there to prevent it.
