### ISSUE TITLE
Tapping Popup Bar extends but is a blank view, not the included View?

### ISSUE THREAD

**Issue by yetdog** [LeoNatan/LNPopupController#174]
I've instantiated a view controller with the following code, the popup bar displays, but when I tap the popup bar, it extends to fill the screen, but none of the view displays. It's just a white screen. Normally, if I push the NPViewController onto a scene, I see how I've built the view. How can I get the popup "stretch" to the top to show the view in the VC?

NPViewController* demoVC = [[NPViewController alloc] init];
    demoVC.view.backgroundColor = [UIColor whiteColor];
    demoVC.popupItem.title = @"Hello World";
    demoVC.popupItem.subtitle = @"And a subtitle!";
    demoVC.popupItem.progress = 0.34;

[self.navigationController presentPopupBarWithContentViewController:demoVC animated:YES completion:nil];

**Comment by LeoNatan** [comment]
Hello,
Not sure I understand. Do you mean open the popup programmatically?

**Comment by yetdog** [comment]
Thank you for the response!

I have a UIButton that calls the code I showed. I'm sure I'm misunderstanding how to correctly utilize your (excellent) library. 

When I tap my button, the pop up bar displays. However, when I tap the pop up bar, the screen extends/slides up (as designed). However, it's a blank screen. I am trying to have it display my VC when it slides up (NPViewController in this example)

Thanks again!

**Comment by LeoNatan** [comment]
How does NPViewController set up its view? In `loadView`/`viewDidLoad`?

**Comment by yetdog** [comment]
It's linked to a Scene in a storyboard.

**Comment by LeoNatan** [comment]
If it’s set up from a storyboard, you shouldn’t `alloc] init]` it. Instead, you should give your controller an identifier, and use `-[UIStoryboard instantiateViewControllerWithIdentifier:]` to get the view controller object.

**Comment by yetdog** [comment]
That absolutely did the trick - apologies for the noob-style question. Been coding my iOS app for a while but still obviously don't have the firmest grasp on all concepts. Thank you *so* much for being so responsive, and again for providing such a great library!

**Comment by LeoNatan** [comment]
Cheers! Happy coding!
