### ISSUE TITLE
Does not adjust Layout of TableViewController in Xib

### ISSUE THREAD

**Issue by olbrichj** [LeoNatan/LNPopupController#176]
#### Description
Hey
I'm not using storyboards. Displaying the popupbar within a UITableViewController (using Xibs) displays the popupbar above the most bottom cell. Thus you can not select the most bottom cell.
I guess it's not adjusting correctly adjusting it's container(?) view.

My current solution is not using a UITableViewController and creating it myself in a Xib file. Using layout constraints I can move the tableView bottom 63 points upwards to show the cell.
Not really the best way to go. Maybe I'm just using the framework wrong?
Any ideas?

#### Steps to Reproduce
My setup is this:
create UITableViewController with Xib

in AppDelegate:
- create TabBarController
- Create NavigationController
- Create TableViewController
- set windows root to TabBarController

Display the popupbar via 
`tabBarController?.presentPopupBar(withContentViewController: contentController, animated: true, completion: nil)`

#### Device, OS and Xcode Versions
Xcode 9beta5
Swift 4

iOS 10
iPhone 6s

**Comment by LeoNatan** [comment]
You should not be using constraints for this case. Instead, you should be setting the insets of the table view. See the music example project how to achieve that.
