### ISSUE TITLE
Changing popup bar background color makes title and subtitle disappear

### ISSUE THREAD

**Issue by joaovbalmeida** [LeoNatan/LNPopupController#177]
#### Description
Changing the popup bar background color, either by changing the tab bar bartintcolor or by popup bar barTintColor, makes the title and subtitle disappear from view. Although both left and right buttons stay visible and working normally.

#### Steps to Reproduce
Set PopupBar Custom barTintColor after setting any title or subtitle that was visible

playerController.popupItem.subtitle = track.artistName (subtitle still visible)
tabBarController?.popupBar.barTintColor = UIColor.red (after this line, bar background turns red, and subtitle disappear)

**Comment by LeoNatan** [comment]
Thanks for reporting. I will take a look soon.

**Comment by LeoNatan** [comment]
Unfortunately, I am unable to reproduce this issue.

Here is how I am testing. In `FirstViewController.m`, under `_presentBar:`, I made the following change after presentation:

```
[targetVC presentPopupBarWithContentViewController:demoVC animated:YES completion:^{
		dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
			demoVC.popupItem.title = [LoremIpsum sentence];
			demoVC.popupItem.subtitle = [LoremIpsum sentence];
			
			[targetVC.popupBar setBarTintColor:[UIColor redColor]];
		});
	}];
```

This works as expected.

**Comment by joaovbalmeida** [comment]
Strange...i have tested using the exact same code as you did there, and still happens the same thing. I can see the title and subtitle being set, and when the bar changes its color, they both disappear. One thing i noticed, is that if i print both labels, they show that the labels are populated with the correct text. Don't know how to proceed to investigate more, any advise? (maybe the labels are getting behind other objects?!

**Comment by LeoNatan** [comment]
Use the View Inspector in Xcode to see what’s going on.

**Comment by joaovbalmeida** [comment]
Good tip! I'm uploading the results. Apparently, when i set the background color, the UIVisualEffectView that contains both labels, disappear from hierarchy. Removing the line where i set the background color, maintains the UIVisualEffectView alongside the labels.

![captura de tela 2017-08-28 as 21 56 14](https://user-images.githubusercontent.com/16760751/29799739-3e59195c-8c3c-11e7-82c5-74f4eb32904b.png)
![captura de tela 2017-08-28 as 21 59 38](https://user-images.githubusercontent.com/16760751/29799738-3e564060-8c3c-11e7-8554-7028a6f2f431.png)

**Comment by LeoNatan** [comment]
What OS are you testing on? What version of Xcode?

**Comment by LeoNatan** [comment]
Also, make sure you are using the latest framework version.

**Comment by joaovbalmeida** [comment]
Yeah, that was the problem. I had the iOS and Xcode updated, but not the framework. Problem solved, now its working! Thanks for your time and help!!

**Comment by LeoNatan** [comment]
Great.
