### ISSUE TITLE
3D Touch isn't working in a popup

### ISSUE THREAD

**Issue by MaticConradi** [LeoNatan/LNPopupController#181]
#### Description
I can't setup 3D touch in a tableView, that's placed inside the popup.

That's how I register the tableView for previewing:

`if traitCollection.forceTouchCapability == .available {
                registerForPreviewing(with: self, sourceView: tableView)
            }`

`func previewingContext(_ previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController?` never gets called for some reason. I did add `UIViewControllerPreviewingDelegate` to my class. Any ideas?

#### Device, OS and Xcode Versions
Xcode 9 Beta 6, iPhone 7+ (iOS 11 beta 8)

**Comment by LeoNatan** [comment]
Thanks for your report. I will take a look when I have some time.

Just to make sure, does `traitCollection.forceTouchCapability == .available` return `true`?

**Comment by MaticConradi** [comment]
Um... that's weird. It doesn't. I'm using 3D touch elsewhere in the app, so it should...

**Comment by LeoNatan** [comment]
And that trait collection is the one on the controller, right? At what point of controller lifecycle do you perform this check?

**Comment by MaticConradi** [comment]
Yes, it's located in the `viewDidLoad`

**Comment by LeoNatan** [comment]
So this is the issue; `viewDidLoad` is too early to use `traitCollection`.

https://forums.developer.apple.com/thread/7854

https://stackoverflow.com/questions/30007701/view-traitcollection-horizontalsizeclass-returning-undefined-0-in-viewdidload

And so on.

Instead, either move your code further down the lifecycle or use [traitCollectionDidChange(_:)](https://developer.apple.com/documentation/uikit/uitraitenvironment/1623516-traitcollectiondidchange) to be notified with the trait collection is availalble.

**Comment by LeoNatan** [comment]
Maybe [`didMove(toParentViewController:)`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621405-didmove) is a good place for you. Just make to handle the edge case of `parent` being `nil` (when you dismiss the popup bar).

**Comment by MaticConradi** [comment]
Yup, that did it, `traitCollectionDidChange(_:)` did the job.

**Comment by LeoNatan** [comment]
Make sure to account for future changes. That method can be called numerous times, but you should only register for force touch once if I recall correctly.

**Comment by MaticConradi** [comment]
I did add a boolean and change it to true, once I registered the tableView.
