### ISSUE TITLE
Can't swipe down to dismiss when tableView is inside the Tab Bar Controller

### ISSUE THREAD

**Issue by MaticConradi** [LeoNatan/LNPopupController#182]
Swipe down is possible in `tableView` when view hierarchy looks like this:
`- Main View Controller`
`-- Popup View`
`--- Table View Controller`

In this case, when user scrolls to top, they can swipe down to dismiss the popup.

I want to include a Tab Bar inside a Popup:
`- Main View Controller`
`-- Popup View`
`--- Tab Bar Controller`
`---- Table View Controller`
`---- Another View Controller`

But in this case, swipe down to dismiss isn't possible inside the `tableView`. If you swipe down to dismiss outside the `tableView`, or in another `View Controller`, everything works fine.

So, is it possible to retain the swipe down to dismiss action even when the `Table View Controller` is inside a `Tap Bar Controller`.

**Comment by LeoNatan** [comment]
Interesting. I wonder why it's not working, as it is suppose to work, at least from me looking at the code in the browser 😄 

What happens if you return `nil` from `viewForPopupInteractionGestureRecognizer`? If you have problems with nullability, just change the header for testing purposes.

**Comment by MaticConradi** [comment]
I mean... maybe it does, but then I don't know how to set it up. I've added this to the View Controller which is responsible for the tableView (and not the Tab Bar): `override var viewForPopupInteractionGestureRecognizer: UIView? { return nil }`. I've tryed to return the `tableView` but nothing has changed either.

**Comment by LeoNatan** [comment]
That method should be implemented on the controller that is presented from the pop up.

**Comment by MaticConradi** [comment]
How can I access the `tableView` from the `Tab Bar Controller`

**Comment by MaticConradi** [comment]
Well I've tryed with `override var viewForPopupInteractionGestureRecognizer: UIView { return detailsViewController().tableView }` but that didn't work, neither did when I programmaticaly added the TableViewController to the tap bar and returned `detailsViewController.tableView`. That resulted in a crash where `tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)` couldn't deque a cell with identifier `cell` (that has worked before). Am I doing something wrong?

**Comment by LeoNatan** [comment]
No no, you shouldn’t return the table view. Just test what happens if you return `nil`. I will look into this soon.

**Comment by MaticConradi** [comment]
Oh, sorry. Here are the results: everything works fine, except now I cant swipe down on any of the views to dismiss the popup, but I can manually dismiss it via a button tap.

**Comment by LeoNatan** [comment]
Thanks! I will take a look soon.

**Comment by LeoNatan** [comment]
Fixed. Please test 2.5.0 release and let me know.

**Comment by MaticConradi** [comment]
I will ASAP

**Comment by MaticConradi** [comment]
Works as expected, though I must mention that now even a mapView or a datePicker is used as a valid view for dismiss gesture recognizer.

**Comment by LeoNatan** [comment]
I’m not sure there is a silver bullet. Perhaps the solution should be forwarded to the user, by requiring they implement the gesture recognized delegate and making the descision there if the recognized should take.

**Comment by MaticConradi** [comment]
Is there a way to exclude a view so gesture isn't taken in it?

**Comment by LeoNatan** [comment]
Do you mean in the delegate methods? Yes:

`gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:`

**Comment by MaticConradi** [comment]
Oh, didn't think that would work, thanks!

**Comment by LeoNatan** [comment]
It works. I implemented some magic that allows the user to set the gesture recognizer delegate and implement those methods, while internally my own delegate methods are called.

**Comment by LeoNatan** [comment]
BTW, do you mind sharing what your apps is?

**Comment by MaticConradi** [comment]
Yea, sure. It's [Helios - Magic hour calculator](https://itunes.apple.com/us/app/helios-golden-hour-blue-hour-calculator/id1260649184?mt=8)

I'll add it to the "Proud users of LNPopupController"

**Comment by LeoNatan** [comment]
❤

**Comment by LeoNatan** [comment]
That's a beautiful app!
I am seeing some slowdowns when opening the popup for the first time on the Today tab.

**Comment by LeoNatan** [comment]
I'm guessing you are using layer shadows? Instead, try perhaps setting a shadow path—that should give you some performance boost. If that doesn't help, a stretchable PNG will be best.

**Comment by LeoNatan** [comment]
Also, I see that disabling location permission renders the app unusable. While this is understandable, consider that some users might not have a choice—for instance, some enterprises use configuration profiles to disable location services. It would be better to allow the user to pick their location.

**Comment by LeoNatan** [comment]
Anyway 🤣 sorry. Love the app!

**Comment by MaticConradi** [comment]
Thanks, apprechiate the feedback and advice
