### ISSUE TITLE
iPhone X is not supported

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#183]
Related to #179.

**Comment by LeoNatan** [comment]
I think I finally stabilized the support for iPhone X as well as iOS 11 in general. The new safe area API required some tinkering, but I think I finally got it working.

One change that I had to make is how `hidesBottomBarWhenPushed` is handled. Until now, the popup bar would transition out of view together with the system bar. However, this has many complications and thus, the transition will behave differently from now on—the popup bar will animate to the bottom of the safe area of the controller. Now that I’ve tried this, it actually looks better to me, so I don’t even see it as a compromise.

Coming soon.

**Comment by yetdog** [comment]
Thank you for your prompt work on this, Leo! 

Maybe anecdotal and not all that consequential, but I've had a bit of a different experience with iOS  11. I found that the view no longer "corrected" as I stated in #179 after interacting with an element in the view (button, table item etc). Instead, in iOS 11 the view simply stayed tucked up behind the status bar. Given the predictability of this, I adjusted the elements in my view to sit lower, so they do not overlap with the status bar/X notch. I also found the popup bar to be acceptable. I'll share screenshots below just for your information - thanks for fixing this! When you release the commit I'll check the differences between it and what I have now and test swapping them in to see which works better for my implementation.
![ios11-1](https://user-images.githubusercontent.com/6452866/30520994-aa7cb5dc-9b6c-11e7-85d0-8698686f2ea7.png)
![ios11-2](https://user-images.githubusercontent.com/6452866/30520995-aa7e81be-9b6c-11e7-85e7-f6f747bd6ee1.png)

**Comment by LeoNatan** [comment]
There were many issues with the X and the framework. Most of that has been ironed out. Insets, margins and layout guides should now also work correctly between iOS 10 and iOS 11 (I have not tested iOS 9).

**Comment by LeoNatan** [comment]
For best results, you will need to either use the safe area guides or top + bottom layout guides, just like how Apple recommends.

**Comment by LeoNatan** [comment]
Implemented. Please report any issues you may have. I have a feeling that the real issues will start pouring in when iPhone X devices are released. 😥 So I hope for a month of quiet… 😆
