### ISSUE TITLE
PSA: Safe area / layout guides are not managed correctly when system bottom bar is not translucent.

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#184]
I don't really have plans to fix it.

Instead, make the bottom bar translucent and just set a background color to white (for example) to make it appear as if not.

**Comment by alexkitcoff** [comment]
Has there been any update on this issue? I'm still having issues with the popup bar overlapping other views unless I set the tab bar style to translucent.

**Comment by LeoNatan** [comment]
Unfortunately, no. Play around with the extended edges under bars settings; it is possible to find a combination of them that works well.

**Comment by alexkitcoff** [comment]
Thanks for the quick reply. I wasn't able to find a combination that works.

Also, I don't know if it would help with troubleshooting or not, but setting the tab bar to translucent does not set the popup bar to translucent. It does solve the overlapping issue and take the tint color of the tab bar, but it's always opaque.

**Comment by LeoNatan** [comment]
Wait, that sounds strange.
Could you please upload a few screenshots of the different problems? I want to make sure, because this issue is a very specific problem, while the rest seem unrelated to me.

**Comment by alexkitcoff** [comment]
Here's a screenshot with the tab bar set to translucent with a black tint. The popup bar takes on the black tint, but not the translucence. The popup bar does not overlap the tableview above. If I set the popup bar back to opaque, it overlaps. I can attach more screenshots if necessary later.

https://i.imgur.com/6e7dz00.png

**Comment by LeoNatan** [comment]
I'd love a demo project so I can investigate the issues. Maybe you could reproduce it on the existing example project.

**Comment by LeoNatan** [comment]
I think I see the problem. Trying to fix.

**Comment by LeoNatan** [comment]
@alexkitcoff I will push a fix soon for tint color. It will appear much better than before.

**Comment by LeoNatan** [comment]
@alexkitcoff Please try v2.5.5. It has much improved tint color support.

**Comment by alexkitcoff** [comment]
Sorry I've been gone for a few days. Thank you so much for the awesome
work. I will try this out later and report back.

**Comment by trispo** [comment]
I've come up with a solution for iOS 11. After presenting the `popupBar` I do the following:

```swift
var newSafeArea = UIEdgeInsets()
newSafeArea.bottom += tabBarController.tabBar.bounds.height
tabBarController.viewControllers?.forEach {
    $0.additionalSafeAreaInsets = newSafeArea
}
```

This insets all the view controllers of my UITabBarController correctly.

**Comment by phyominthu** [comment]
Thanks @trispo! Your code did the work in iOS 11. Have you found any solution for older iOS versions?

**Comment by trispo** [comment]
Unfortunately not. I only needed iOS 11 compatibility.

**Comment by alexkitcoff** [comment]
I have finally gotten around to trying it out, but I'm still experiencing issues. I will take a look at the constraints I'm using. @trispo's solution seems to help.

**Comment by LeoNatan** [comment]
The original issue I observed is still open. I don't really have plans to fix it, but it should remain open to let people know. The workaround is to make the bottom bar translucent and just set a background color to white (for example) to make it appear as if not.

**Comment by LeoNatan** [comment]
Tint color on the other hand is now much improved compared to when you reported.

**Comment by iDevelopper** [comment]
Does anyone know why additionalSafeAreaInsets does not work when the bar is not transparent? I could not find this information in the Apple documentation.

**Comment by LeoNatan** [comment]
Probably a bug that they don’t care to fix. Non-translucent bars are very buggy in general.
