### ISSUE TITLE
Customize not working for compact or popupInteractionStyle

### ISSUE THREAD

**Issue by Matiaz** [LeoNatan/LNPopupController#185]
**Tech details**

- Using: LNPopupController
- Version: Latest
- Carthage: YES
- Xcode 11
- Swift 3.0
- Storyboards

Hi, I'm having a problem trying to setup the LNPopupController Menu, I'm trying to set it up to use the compact style but looks like it doesn't work, I want to mimic the Apple Music App, this is my setup, I have a TabBarController as a main rootcontroller and I want to show the PopupBar. 

The ViewController that will be presented is a standard ViewController, I embed it into a navigation controller. The problem that I'm having is that when I have to setup the PopupBar it never changes the style to .compact, alse the popupInteractionStyle is not working. Do you know what can be the problem, this is sniped of my setup code.

Thanks in advance.

> let storyboard = UIStoryboard(name: "Player", bundle: nil)
>         guard let playerController = storyboard.instantiateViewController(withIdentifier:"PlayerViewController")
>             as? PlayerViewController else {
>                 fatalError("No dashboardController found")
>         }
> 
>         playerController = playerController
>         playerController.popupInteractionStyle = .drag
>         playerController.navigationController?.popupBar.barStyle = .compact
>         playerController.popupItem.title = "a title"
>         playerController.popupItem.subtitle = "a subtitle"
>         playerController.popupItem.progress = 0.40
>         playerController.updatePopupBarAppearance()
>         self.presentPopupBar(withContentViewController: playerController, animated: true) {
>             print("presented")
>         }

**Comment by LeoNatan** [comment]
Hello, than you for using my framework.

When customizing the popup bar, you need to access the property on the presenting controller. In your case, it should be `self.popupBar.barStyle = .compact`

**Comment by Matiaz** [comment]
Hey man, you rock ! That solved the problem, I'll let you know when I finish my App :)

**Comment by LeoNatan** [comment]
Fantastic!
