### ISSUE TITLE
gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: doesn't do much

### ISSUE THREAD

**Issue by MaticConradi** [LeoNatan/LNPopupController#186]
Hopefully I'm not too annoying at this point, but after playing around I've noticed that `gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool` doesn't do much.

#### Description
`gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool` DOES get called but doesn't influence on whether dismiss gesture recognizer should recognize a pan. I've tried returning `false` and `true` but it doesn't affect anything at all.

**Comment by LeoNatan** [comment]
The implementation forwards delegate calls directly. So I suspect this is a gesture recognizer logic bug on your end. Let’s see.

You may also need to implement `gestureRecognizer:shouldRequireFailureOfGestureRecognizer:`

**Comment by LeoNatan** [comment]
Ohh, wait. Now that I think about it, could be another issue as well. I am also listening directly to other gesture recognizers, such as the scroll view delegates. I will set this as a bug and investigate.

**Comment by MaticConradi** [comment]
I will investigate, whether `gestureRecognizer:shouldRequireFailureOfGestureRecognizer:` solves the issue.

**Comment by LeoNatan** [comment]
I don’t think it will now. I might need to add some code for it to work.

**Comment by dral3x** [comment]
I'm facing the same problem myself.

I have a horizontal carousel inside the popupContentView and I want that horizontal scrolling does not affect the state of the popContentView, of course.

On iOS9 it closes very frequently, even without Y movement (checked attaching a delegate to `popupContentView.popupInteractionGestureRecognizer`).
It seems to work better on iOS11. I need to drag vertically way more for closing it.

**Comment by LeoNatan** [comment]
Fixed. Please use `shouldRequireFailureOfGestureRecognizer:` or `shouldRecognizeSimultaneouslyWith:` to exclude the critical views.

**Comment by MaticConradi** [comment]
I'm returning false in `shouldRequireFailureOfGestureRecognizer`, `shouldBeRequiredToFailByGestureRecognizer` and `shouldRecognizeSimultaneouslyWith`, yet I can still drag to dismiss the popup. Methods are getting called and I set the delegate here: `popupContentView.popupInteractionGestureRecognizer.delegate = self`. To be clear, I'm returning false only to check, if I can disable the `popupInteractionGestureRecognizer`. I will implement the code to exclude all critical views later. Am I doing anything wrong here?

**Comment by LeoNatan** [comment]
What I did was take the example project and change the popup content controller to `UITableViewController`.
Then implemented `shouldRecognizeSimultaneouslyWith` and returned `NO` if the gr’s view is kind of scroll view.

It worked as expected for me. 

Are you sure you are using the latest framework? Do you mind helping me debug? Can you breakpoint here: https://github.com/LeoNatan/LNPopupController/blob/9ff60456f8c1395a52ce30f5948aae105eace03c/LNPopupController/LNPopupController/Private/LNPopupController.m#L563 and see what’s going on?

**Comment by MaticConradi** [comment]
I've found out something: all UIScrollViews are unscrollable while UIDatePicker is. In both cases I can still dismiss the popup. Also, the line 563 never got called, so setting a breakpoint there didn't do anything.

**Comment by LeoNatan** [comment]
Hm, so the point of failure is somewhere else. Can you please provide a demo project where the issue reproduces?

**Comment by MaticConradi** [comment]
Here you go: [demo project](https://drive.google.com/open?id=0BzzZ_pUYYNM7OGVaRWl6T1pQUW8)

Note: I've implemented a delay option into the `presentPopup` method for my app.

**Comment by MaticConradi** [comment]
Ping

**Comment by LeoNatan** [comment]
Oops, sorry. I am looking into LNPopupController issues and will look into this as well.

**Comment by LeoNatan** [comment]
Two remarks. I will push a small update soon that will include an improvement for your use case. Also, in `gestureRecognizer(_, shouldRequireFailureOf:)`, you should return `true` to disable scrollviews from dismissing the popup.

**Comment by MaticConradi** [comment]
Great. I’ll take a look asap. Thanks!

**Comment by MaticConradi** [comment]
Works great, thanks!
