### ISSUE TITLE
Framework contains unsupported architectures 

### ISSUE THREAD

**Issue by darkForestCat** [LeoNatan/LNPopupController#187]
#### Description

When I am trying to upload my app to the AppStore via Xcode it starting swearing on the framework.Here is the screenshot: [screenshot](https://pp.userapi.com/c841027/v841027826/20059/s1x0uMJFA10.jpg)

#### Steps to Reproduce
Product -> Archive and then Upload to the AppStore 

#### Device, OS and Xcode Versions
Xcode 9.0 , LNPopupController v2.5.0
Bitcode seted to "NO" in Project

**Comment by LeoNatan** [comment]
How did you integrate the framework in your project?

**Comment by darkForestCat** [comment]
Using Carthage.When it was iOS 10 everything was good, but when I have updated the framework and Xcode the error occured. [Screenshot of updating Carthage](https://pp.userapi.com/c837236/v837236442/56488/T-n6d_65CV0.jpg)

**Comment by LeoNatan** [comment]
You probably forgot the `copy-frameworks` stage:
https://stackoverflow.com/a/39269506/983912

**Comment by LeoNatan** [comment]
I’ll add this information to the README.

**Comment by darkForestCat** [comment]
But I wrote it there when I was at first installing the framework, so I think the problem is not there 
<img width="595" alt="schermata 2017-09-25 alle 22 15 38" src="https://user-images.githubusercontent.com/25624923/30828873-61b5753a-a23f-11e7-83a2-bc3f0518f213.png">

**Comment by LeoNatan** [comment]
Something has broken. 
If you feel adventurous, don’t build using Carthage, only checkout. Then add the project directly to your project (as a subproject), and add the .framework to the “Embed Binaries” section. Try submitting then. 

If it succeeds, you have not setup Carthage correctly.

**Comment by LeoNatan** [comment]
Also could be some weird compatibility with Bitcode. Any reason you are submitting without?

**Comment by darkForestCat** [comment]
I am submitting without because Appodeal framework does not working correctly with it.

**Comment by darkForestCat** [comment]
Today I enabled bitcode and updated carthage and your framework and this errors still appearing.Also I tried older versions of Xcode and there I still get these errors, so I guess it's not bitcode or Xcode problem...

**Comment by Kleemann** [comment]
I solved this by adding the input and output files. 
See the [Carthage installation guide ](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) step 4-6

**Comment by Kleemann** [comment]
I solved this by adding the input and output files. 
See the [Carthage installation guide ](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) step 4-6

**Comment by LeoNatan** [comment]
@darkForestCat Try to do this:

> If you feel adventurous, don’t build using Carthage, only checkout. Then add the project directly to your project (as a subproject), and add the .framework to the “Embed Binaries” section. Try submitting then.

**Comment by darkForestCat** [comment]
This problem was solved, I came here to say that this problem can be because of problems with Carthage.

**Comment by LeoNatan** [comment]
Why was the issue?

**Comment by darkForestCat** [comment]
Because Carthage installed the framework incorrectly.I needed to remove everything and install again.May be because of old version of Carthage.Who knows, it was really strange issue.

**Comment by LeoNatan** [comment]
Thanks for letting me know.
