### ISSUE TITLE
Changing prefersStatusBarHidden value of a view controller that is presented as a popup content controller has no effect on views attached to topLayoutGuide/safeAreaLayoutGuide

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#188]
#### Description

Changing `prefersStatusBarHidden` value of a view controller that is presented as a popup content controller has no effect on views attached to `topLayoutGuide/safeAreaLayoutGuide`.

#### Steps to Reproduce
1. Attach a subview to `topLayoutGuide/safeAreaLayoutGuide`
2. Toggle `prefersStatusBarHidden` (without changing the device orientation) and call `setNeedsStatusBarAppearanceUpdate`
3. Observe the status bar disappear together with the chevron while the subview stays 
4. After rotation, it fixes itself

#### Device, OS and Xcode Versions
iOS 11 and Xcode9

<img width="1537" alt="screen shot 2017-09-26 at 10 13 51 am" src="https://user-images.githubusercontent.com/611542/30836807-f7fbc756-a2a3-11e7-83ed-53283ffef7d5.png">

[LNPopupController-2.5.0_sample.zip](https://github.com/LeoNatan/LNPopupController/files/1331318/LNPopupController-2.5.0_sample.zip)

**Comment by LeoNatan** [comment]
Hmm. Thanks for the report, will look soon.

**Comment by Kastet** [comment]
Have you had any luck with this?

**Comment by LeoNatan** [comment]
Unfortunately, I have not yet looked. A holiday is coming up here very soon, so I may be able to look then.

**Comment by LeoNatan** [comment]
Found the issue and will push a fix in a few minutes.

**Comment by LeoNatan** [comment]
Just a friendly reminder that hiding the status bar on iPhone X does not really make sense as the notch cannot hide also (if only… 😜). Nevertheless, the framework will support that scenario as well.

**Comment by Kastet** [comment]
Thanks a lot!
