### ISSUE TITLE
popupContentViewController can dismiss

### ISSUE THREAD

**Issue by leftsider123** [LeoNatan/LNPopupController#191]
I use a custom transitions behind it，back to ,popupContentViewController will dismiss

**Comment by LeoNatan** [comment]
I don’t understand anything. Please use proper English to state your issue clearly.

**Comment by leftsider123** [comment]
![tap](https://user-images.githubusercontent.com/9531871/31654172-bd1d20d4-b357-11e7-878f-ad3f6036e5a3.gif)

**Comment by LeoNatan** [comment]
I am sorry, I still don’t understand what the problem is.
What controller are you presenting the popup on? You should present it on the navigation controller.

**Comment by leftsider123** [comment]
Custom transitions animation, popupContentViewController will disappear

**Comment by leftsider123** [comment]
the tableview controller is presented ,click the cell ,custom transitions animation ,back, the tableviewcontroller  is disappear

**Comment by LeoNatan** [comment]
Please create a demo project and attach here.

**Comment by leftsider123** [comment]
[popup.zip](https://github.com/LeoNatan/LNPopupController/files/1390525/popup.zip)

**Comment by leftsider123** [comment]
I want to change the size and location of the controller by present

**Comment by LeoNatan** [comment]
This is not supported. You should not be presenting a view controller on the popup content view controller (in your case, `TableViewController`).

**Comment by leftsider123** [comment]
could push?

**Comment by leftsider123** [comment]
push?
