### ISSUE TITLE
Popupitem not updating title while scrolling in TableView

### ISSUE THREAD

**Issue by jonezdotcom** [LeoNatan/LNPopupController#192]
#### Description
I use this library for a timer feature in my app. Therefor I frequently update the popupitem's title (1 time / sec). While simultaneously scrolling in the currently displayed ViewController the popupitem's title does not update. Only when scrolling completely stops the title resumes to get updated. 

#### Steps to Reproduce
Please see the attached video for a demonstration.
[Popupitem Demonstration.mp4.zip](https://github.com/LeoNatan/LNPopupController/files/1388652/Popupitem.Demonstration.mp4.zip)

#### Device, OS and Xcode Versions
iPhone 6s, iOS11, Xcode 9

**Comment by LeoNatan** [comment]
How have you set up your timer?

**Comment by LeoNatan** [comment]
If using NSTimer, make sure you have scheduled in the correct running modes. On iOS, when scrolling a scroll view, the runloop switches to common modes from default, so if you have scheduled in default mode, your timer will not fire.

**Comment by jonezdotcom** [comment]
Yep that was exactly the case, had to schedule the timer to RunLoop with commonModes. Thank you very much!

**Comment by LeoNatan** [comment]
Cheers
