### ISSUE TITLE
Hide popupBar in one of ViewControllers of TabBar 

### ISSUE THREAD

**Issue by darkForestCat** [LeoNatan/LNPopupController#193]
#### Description
I am trying do hide popupItem in one of ViewControllers of my tabbar.
In view will appear I use this code :

`-(void)viewWillAppear:(BOOL)animated{`
  ` [super viewWillAppear:animated];`
  ` [self.tabBarController.popupBar setHidden:YES]; 
}`

But nothing happens, it does not disappear.
Note that I don't want to dismiss it, I just want to hide it, when user will go to other VC I will show it.

**Comment by LeoNatan** [comment]
Hiding is not supported. You should dismiss and present.
