### ISSUE TITLE
Can i show my player controller without any animation?

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [LeoNatan/LNPopupController#195]
Hello! I just want to show my player controller without any animation.
How can i set different transition style for popupContentController like .crossDissolve?

**Comment by LeoNatan** [comment]
Cross-dissolving is an animation also.
That's not supported. You can either set `animated: YES` to get the slide animation or `animated: NO` to get it to show up with no animation.

You could use `UIView`'s transition API to achieve what you want, but that is untested and unsupported.
