### ISSUE TITLE
prominent display left image corner radius

### ISSUE THREAD

**Issue by dwolfgram** [LeoNatan/LNPopupController#197]
Is it possible to update the corner/border radius of the left image on the prominent view? I have been playing around with the custom view controller but with no luck. Thank you for this add-on it has been super easy to use and incredibly helpful!!

**Comment by LeoNatan** [comment]
Hm, not possible right now because the image view is not exposed.
As a workaround, use `[self.popupBar valueForKey:@"imageView"]` to obtain it.

**Comment by dwolfgram** [comment]
got it! thanks!

**Comment by LeoNatan** [comment]
Exposed the popup bar image view.
