### ISSUE TITLE
Can we modify the Y threshold of when the popup controller gets dismissed?

### ISSUE THREAD

**Issue by wiencheck** [LeoNatan/LNPopupController#198]
Hi, I've implemented the framework to my project without any issues but I have a question. 
Can we modify the Y threshold of when the popup controller gets dismissed? It is too easy to accidentally drag the controller down when there are sliders on screen, or scrollviews. This isn't too big of a problem with modern style popup, but with classic dragging it just a little is enough to dismiss it. I would like to give a value of around 50% of screen's height so it wouldn't get accidentally dismissed

**Comment by LeoNatan** [comment]
It’s not possible right now. I’m not sure if I want to expose this, but I may want to touch the sensitivity a little. Is the problematic case a drag interaction with a scroll view embedded in it?

**Comment by wiencheck** [comment]
Yes, I have a scrollable UITextView in the center of the screen

**Comment by LeoNatan** [comment]
I’ve been playing with this a bit for the past two hours. 
I don’t think making this change will be beneficial for the general case.

Instead, I would suggest implementing the interaction gesture delegate and implementing the logic yourself. For instance, you can implement `shouldRecognizeSimultaneouslyWithGestureRecognizer:` and check there whether the scroll view’s content offset is at zero and not scrolling.
