### ISSUE TITLE
Code signing

### ISSUE THREAD

**Issue by mennolaan** [LeoNatan/LNPopupController#199]
I know this is a long shot but you never know it the solution is here. I have added the library manually to my project and everything builds fine, I can upload to TestFlght. But as everybody knows, testflight is not really userfriendly. I came across app center of microsoft and tried it out. However, the xcode build server seems to fail on LNPopupController. I suspect this is a microsoft issue and not this project but maybe I accidently changed a parameter and messed things up.

The xcode server of app center complains about this:
[command]/usr/bin/xcodebuild -exportArchive -archivePath /Users/vsts/agent/2.124.0/work/1/output/build/archive/LNPopupController.xcarchive -exportPath /Users/vsts/agent/2.124.0/work/1/output/build/export/_XcodeTaskExport_LNPopupController
xcodebuild: error: The flag -exportOptionsPlist is required when specifying -exportArchive.
##[error]Error: /usr/bin/xcodebuild failed with return code: 64

Please close this issue if you find this unrelated, i understand completely, but I'm at loss here to find the solution. Microsoft came with code_signing_allowed  = no parameter, but is hasn't changed a bit.

**Comment by LeoNatan** [comment]
Hmm, something is strange here. Why are you/they trying to archive the framework? Only the main project should be archived.

**Comment by mennolaan** [comment]
Wow that was quick, well thats not me as far as I know, it's due to app center? Pardon my ignorance, but is this something I can define in xcode to prevent it to archive. Local xcode works fine and i can even distribute to testflight through organiser,.

**Comment by LeoNatan** [comment]
I am not familiar with how AppCenter works. Perhaps you have misconfigured which scheme is built/archived?

**Comment by mennolaan** [comment]
That could be the case indeed. I never had to manage the schems, so I'll look into it.

**Comment by mennolaan** [comment]
I removed the project en framework completely and started over, how ever I see duplicates, could this be the issue, or is this intended behaviour?

![image](https://user-images.githubusercontent.com/20553134/33375820-793b824a-d50b-11e7-81ac-09816ecf1391.png)

**Comment by LeoNatan** [comment]
This is how it appears in Xcode. It's normal. You just have to make sure you are archiving the scheme containing your target for "ListeIn".

**Comment by mennolaan** [comment]
If im not mistaken, you mean the scheme definition here right:

![image](https://user-images.githubusercontent.com/20553134/33376444-014b0a46-d50e-11e7-9bbf-409065e32f3a.png)

**Comment by LeoNatan** [comment]
Yes. If you archive locally on your computer, does it work correctly?

**Comment by mennolaan** [comment]
Yeah, not a problem, like I said I have been sending my project to TestFlight for more than 1 year. So I assume everything is in order, probably the xcode server on AppCenter on microsoft end is configured differently. I mean if even TestFlight accepts it, it must be all bueno right?

**Comment by mennolaan** [comment]
And than you leo for responding so quickly!

**Comment by LeoNatan** [comment]
It's a configuration issue. Since I am not familiar with how AppCenter works, I cannot assist, sadly. Is there support you can contact? It could be some bug on their end.

**Comment by mennolaan** [comment]
Yeah microsoft is responding, they suggested this:
"It seems that the problem is that your project is not generating an embedded provisioning profile.
Can you please check in your configuration settings file if this value is set?
CODE_SIGNING_ALLOWED = NO  "

I think it's hard for them to debug as well as they do not have the sourcecode to look into, this is by design as the vm's to build are only up when a git web hook is triggered and deleted after a build.

**Comment by LeoNatan** [comment]
They are pointing to an incorrect issue. Framework projects do not contain signing information since Xcode signs them with the main binary signing identity.

**Comment by LeoNatan** [comment]
Any news?
I don’t think this is a problem with the framework and will close the issue. But we can keep discussing here.
