### ISSUE TITLE
Is it possible to use my own  custom transition?

### ISSUE THREAD

**Issue by darkForestCat** [LeoNatan/LNPopupController#200]
#### Description
I want to make a custom card-like transition like in Apple Music, when the player view controller is  presented background view becomes smaller.
#### Steps to Reproduce
//controller is my player viewcontroller 

 let transitionDelegate = DeckTransitioningDelegate()
            controller.transitioningDelegate = transitionDelegate
            controller.modalPresentationStyle = .custom

//but it doesn't work.It presents with standard animation.
#### Device, OS and Xcode Versions
I use the newest software

**Comment by LeoNatan** [comment]
This is tracked in #143.
