### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by zakhej** [LeoNatan/LNPopupController#201]
Hi LeoNatan! 
Sorry to bother you and thank you for the library! 
It's not an actual issue but a question.
How can I achieve a result then popup bar on an iPhone X isn't cutted by safeAreaInsets but going down to the bottom of the screen?
Here is an example of current situation and desired result (photoshopped for illustration):
![current](https://user-images.githubusercontent.com/340680/33705716-67d425ec-db42-11e7-8e3f-3f314b5fd161.png)
![desired](https://user-images.githubusercontent.com/340680/33705722-6bf7c070-db42-11e7-825e-56ff6d144bf7.png)
Now I'm using full custom popup controller. Is this possible?

**Comment by LeoNatan** [comment]
Hello,

It is not currently possible to extend the popup bar itself. 

You can achieve this by adding a bottom view to your presenting controller. If you set that view to be a `UIVisualEffectView` with the blur type if the popup bar, you will have the effect you are looking for.

I intend to add this functionality at some point, but haven’t figured yet how to offer a generic API for this. It will also require somewhat of a refactor to achieve.

**Comment by LeoNatan** [comment]
Add a UIVisualEffectView and set it as the bottom docking view using the `bottomDockingViewForPopup` property.
