### ISSUE TITLE
Accessibility - "Speak Screen" reads the view behind

### ISSUE THREAD

**Issue by neilkinniburghbtc** [LeoNatan/LNPopupController#202]
#### Description

iOS has a "Speak Screen" accessibility feature.  This reads the content of the screen when the user swipes from the top with two fingers.

This isn't working with the LNPopupController.  Instead of reading the popup's content, it reads the content from the view behind.

#### Steps to Reproduce

1. Enable the "Speak Screen" accessibility feature (Settings -> General -> Accessibility -> Speech -> Speak Screen).
2. Open the LNPopupController example application.
3. Open the "Apple Music" demo app, select an item and tap to show the popup content full screen.
4. Using two fingers, swipe down from the top of the screen.

At this point the reader starts reading "Demo Album...  Demo Artist" (from the screen behind the popup).  The popup's content is not read.

#### Device, OS and Xcode Versions

Xcode 9.2 (9C40b)
iOS 11.1.2
LNPopupController version at commit 711aab9

**Comment by LeoNatan** [comment]
Ooof!
I will look at this when I have time. I don't remember playing with voiceover the last time I played around with accessibility support. Do you happen to know if this is a degradation?

**Comment by neilkinniburghbtc** [comment]
Thanks.  I've got no idea if this is a degredation or not.  It's present in the latest code and in 2.5.1.  It sounds similar to the last paragraph of this bug report (https://github.com/LeoNatan/LNPopupController/issues/64#issue-151710947) so possibly it's the same root cause.

**Comment by LeoNatan** [comment]
So apparently, I already handled this in the past, using `accessibilityViewIsModal`. I’m not sure what is going on, but the Speak Screen does not look at that and just reads what’s underneath. Investigating.

**Comment by LeoNatan** [comment]
Fixed. :)

**Comment by neilkinniburghbtc** [comment]
Looks good - thanks Leo
