### ISSUE TITLE
The popup item text appears to be dark in color with black tabbar

### ISSUE THREAD

**Issue by vdharankar** [LeoNatan/LNPopupController#204]
#### Description

If you use black tint color to tabbar the text on miminized popup above the tabbar also appears to be black. 

#### Steps to Reproduce

Set the tabbar tint color to black and launch the popup , in minimised state it shows text in black color hard to see, I tried it with demo app as well

#### Device, OS and Xcode Versions

iOS 11.0 , Xcode 9, ObjectiveC

**Comment by petrutms** [comment]
I also have the same problem. I have an app with black tab bar, and can’t find a way to customize the color of the miniplayer text and background. Any ideas? Thanks

**Comment by LeoNatan** [comment]
You can use `titleTextAttributes` and `subtitleTextAttributes` to customize the look of the popup bar labels. See the example project for an example.

Now, could you please describe how you have set your bars to dark and perhaps upload a screenshot of the problem?

**Comment by LeoNatan** [comment]
@vdharankar This is the intended behavior. If you only set a black bar tint, the text remains black. Instead, use the `barStyle` to set it to `.black` to get the effect you are after. This is the exact same behavior of a navigation bar and tab bar.

**Comment by LeoNatan** [comment]
I will open a new issue for the tint color inaccuracies which I am fixing now.
