### ISSUE TITLE
How to manage touch up inside of pause/play button on popup bar

### ISSUE THREAD

**Issue by mukulm24** [LeoNatan/LNPopupController#205]
How can i manage the touch event on play pause button shown on popup bar displayed right above tab bar.

**Comment by thanhlazio** [comment]
It work for me
`let pause = UIBarButtonItem(image: #imageLiteral(resourceName: "play"), style: .plain, target: self, action: #selector(self.play))
        demoVC.popupItem.leftBarButtonItems = [pause]
        
        let next = UIBarButtonItem(image: #imageLiteral(resourceName: "nextFwd"), style: .plain, target: self, action: #selector(self.nextSong))
        demoVC.popupItem.rightBarButtonItems = [next]`

**Comment by LeoNatan** [comment]
As described by @thanhlazio, create a custom bar button item with a target and selector, or a custom view bar button with a `UIButton` inside it for even more precision.

**Comment by kurry421** [comment]
@LeoNatan  apologies for the noob question but I still dont understand how to know when the button is clicked. Do I need to create a @IBAction and then include:
```
 let pause = UIBarButtonItem(image: #imageLiteral(resourceName: "play"), style: .plain, target: self, action: #selector(self.play))
demoVC.popupItem.leftBarButtonItems = [pause]
```
