### ISSUE TITLE
How to config position of `popupItem.image` and `popupItem.leftBarButtonItem`

### ISSUE THREAD

**Issue by thanhlazio** [LeoNatan/LNPopupController#206]
I want to move `play` button to the left `image` of albumArtwork.
Is it posible?

**Comment by LeoNatan** [comment]
This is not possible. The layout is provided as is. You can, however, create a custom bar on your own, and layout to your heart's desire. See `LNPopupCustomBarViewController` for more information, and the example project for an example of how to accomplish a custom bar.

**Comment by thanhlazio** [comment]
![alt text](https://image.prntscr.com/image/XzQsDea7RSWQsny7Y4_aPw.png "Logo Title Text 1")
I try to custom popup music like that. Thank you.

**Comment by LeoNatan** [comment]
Yes, I understand. You can achieve this using a custom bar, but you will have to manage all the layout yourself (basically reimplement the logic of LNPopupBar.m). Consider fully if this is what you wish to focus on that.

**Comment by LeoNatan** [comment]
Another option is to fork this repository and modify LNPopupBar.m layout logic, but then you will have to manually merge changes as this repo advances.

**Comment by thanhlazio** [comment]
Ok, thanks for good work!

**Comment by LeoNatan** [comment]
Cheers! Thank you for using my framework!
