### ISSUE TITLE
Translucency of popup bar

### ISSUE THREAD

**Issue by amosavian** [LeoNatan/LNPopupController#208]
Hi,

iOS native bars (`UIToolbar`, `UINavigationBar` and `UITabBarController`) has a separate property for translucency. I've noticed popup bar is translucent when `barTintColor` is `nil`.

Is it possible to define a separate property for translucency regardless of tint color? (probably we have to set default value regarding tabbar's value)

**Comment by LeoNatan** [comment]
Hey

I am actually trying to fix the bar tint color, as it is not very accurate with the system bar tint color implementation when using a prominent bar (the modern look of Apple).
I am investigating how to properly colorize a `UIVisualEffectView` while retaining a look and feel close to the bottom bar (toolbar, tab bar).

Regarding translucency, it is possible to add that. Let me see what I manage to do first with bar tint color and then I'll add this as well.

**Comment by amosavian** [comment]
Thanks a lot
