### ISSUE TITLE
Respecting navigationController.isToolbarHidden value

### ISSUE THREAD

**Issue by amosavian** [LeoNatan/LNPopupController#209]
When I set `navigationController.isToolbarHidden` to `true` and simoultaniously try to to present popup bar, Popup bar would cover toolbar. Screenshots may help to find what I mean:

![img_ace49a15c47c-1](https://user-images.githubusercontent.com/6725192/34905742-78194aa0-f874-11e7-9a28-c86adad7eaf0.jpeg)

![img_68a209cef6c7-1](https://user-images.githubusercontent.com/6725192/34905740-66e2f70e-f874-11e7-9987-085d76e1bd84.jpeg)

**Comment by LeoNatan** [comment]
I am not sure what the problem is here. From the screenshots, it seems to be have as expected. If you hide the toolbar, the popup bar appears in its place.

**Comment by amosavian** [comment]
I didn't hide the toolbar. Indeed popup bar covered it in second screenshot.

 I don't know if your code hides it deliberately or not.

**Comment by LeoNatan** [comment]
I am still not sure what the problem is.
Do you mean that the toolbar is on top of the popup bar?

**Comment by amosavian** [comment]
I believe popupbar should be installed on the top of toolbar, instead of tabbar. Indeed we should have **three** bar in second screenshot, popup on the top, toolbar on the middle and tabbar on the bottom. While we have two and toolbar is missed. When I dismiss popup bar, toolbar appears.

I believe you must change bottom anchor. it must be `toolbar.topAnchor` rather than `tabbarContoller.view.topAnchor`.

Please note toolbar is a navigationbar's view, while I present popup bar from `tabbarController`.

**Comment by LeoNatan** [comment]
If you present the popup bar on the tab bar controller, the popup will be docked to the tab bar. Instead, you should present on the navigation controller.

However, if you set `isToolbarHidden` to `YES`, it will hide the toolbar.

**Comment by amosavian** [comment]
> Instead, you should present on the navigation controller.

When tabor and navigation bar are both present, using this option will put popup bar below tab bar! Thus I have to use present  on then tab bar controller.
