### ISSUE TITLE
LNPopupController: The popup controller is already in transition. Will ignore this transition request.

### ISSUE THREAD

**Issue by Neena-Mishra** [LeoNatan/LNPopupController#212]
Hi Leo,

I am stuck in a process which occurs sometimes but yes its an issue for me. I am using **"LNPopupCustomBarViewController"** and presenting a view controller using

```
let popup = storyboard?.instantiateViewController(withIdentifier: "myControllerID") as! MYCONTROLLER
self.navigationController?.popupContentView.popupCloseButtonStyle = .round
self.navigationController?.presentPopupBar(withContentViewController: popup, openPopup: true, animated: true, completion:nil)
```

After presenting and dismissing view controller multiple times simultaneously, I am getting the issue of complete UI distortion. When I debug this issue, I got the output

**LNPopupController: The popup controller is already in transition. Will ignore this transition request.**

It seems that it is due to presenting a view controller when it is still in the transition state. I am clicking the button which is presenting the view controller simultaneously.

How can I stop or restrict user interaction on the view? Or is there any way to check the current transition state of the view?

**Comment by LeoNatan** [comment]
Hello,

In general, you should not present and dismiss while animation (transition) is in progress. Instead, set a completion handler when you present and dismiss, and call the next command after the completion handler has been called.

**Comment by Neena-Mishra** [comment]
Thanks Leo for the quick reply. But, in my case I am presenting it on a button click and it is happening while presenting view again and again.

**Comment by LeoNatan** [comment]
You should disable the button while the transition is occurring. You can then re-enable it in the completion handler.

**Comment by Neena-Mishra** [comment]
How can we get that transition is occurring or not?

**Comment by LeoNatan** [comment]
Disable your button before calling `presentPopupBar` and `dismissPopupBar`. In the completion handler of each, re-enable the button.
