### ISSUE TITLE
User Interaction conflicts

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#213]
#### Description
I have a slider (MPVolumeView) at the bottom of my container view witch does not respond to user interactions.
#### Steps to Reproduce
If I don't present the popupBar, just push the controller, the slider respond. If I present the popupBar and open the container view controller by tapping on the bar, the slider does not respond.
#### Device, OS and Xcode Versions
Xcode 9, ios 11.2.2, iPhone 6S

#### Code
```
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        // KO: Slider does not respond
        /*
        let items = self.album.items
        playViewController.itemsToPlay = items
        let item = indexPath.row - 1
        playViewController.itemToPlay = item
        rootNC.presentPopupBar(withContentViewController:playViewController, animated: true, completion: nil)
        playViewController.sender = self
        playViewController.convertToPCM()
        */
        
        // OK: Slider respond
        let items = self.album.items
        playViewController.itemsToPlay = items
        let item = indexPath.row - 1
        playViewController.itemToPlay = item
        
        //rootNC.presentPopupBar(withContentViewController:playViewController, animated: true, completion: nil)
        
        playViewController.sender = self
        playViewController.convertToPCM()
        
        self.navigationController?.pushViewController(playViewController, animated: true)
    }
```

##### Slider does not respond
![img_2980](https://user-images.githubusercontent.com/1782450/35107644-ce1a26d0-fc71-11e7-943f-195385585ed1.png)

![img_2981](https://user-images.githubusercontent.com/1782450/35107678-dc6b17c6-fc71-11e7-8be6-6b5ad7d37e29.png)

##### Slider respond
![img_2982](https://user-images.githubusercontent.com/1782450/35107713-ee777036-fc71-11e7-98d4-a5edfdf102bd.png)

**Comment by iDevelopper** [comment]
I think there is a conflict between your Pan Gesture Recognizer and the MPVolumeView gesture recognizer. It would be nice to allow the content view controller to receive the UIGestureRecognizerDelegate methods, in particular:

- (BOOL) gestureRecognizer: (UIGestureRecognizer *) gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer: (UIGestureRecognizer *) otherGestureRecognizer

**Comment by LeoNatan** [comment]
But that is already available. Set the delegate if the interaction gesture recognized and implemented t the logic you need.

**Comment by iDevelopper** [comment]
Is my class actually like this:

class PlayViewController: UIViewController, StreamingPlayerDelegate {

sould be:

class PlayViewController: LNPopupController, StreamingPlayerDelegate {

**Comment by LeoNatan** [comment]
`LNPopupController` is not a public class, and is not a subclass of `UIViewController`.

**Comment by LeoNatan** [comment]
I am not sure what you are trying to accomplish. Setting the delegate should be just like setting any other gesture recognizer's delegate.

**Comment by iDevelopper** [comment]
Can you provide an example with a MPVolumeView instead a Slider, in Demo Music?

**Comment by iDevelopper** [comment]
Your library add an UIPanGestureRecognizer to the content view of the controller associated with the popup Bar. So I think, the library should redistribute the delegate methods to the content view controller.

**Comment by LeoNatan** [comment]
The delegate method is already available. Please see header files. I cannot assist you more.

**Comment by iDevelopper** [comment]
I can't see how to adopt your pan gesture delegate as there is no protocol for this!

**Comment by LeoNatan** [comment]
I do not understand what protocol you want.
The protocol is `UIGestureRecognizerDelegate`. Implement this in your controller and then set the delegate like so: `self.popupContentView.popupInteractionGestureRecognizer.delegate = self`.

**Comment by LeoNatan** [comment]
In the example above, `self` is the same controller you present the popup on. You have to make sure to set the correct delegate.

**Comment by iDevelopper** [comment]
Yeah! Thanks, sorry I did not well understand...

In my container view controller:
```
        // Will set a forwardedDelegate
        self.popupContentView.popupInteractionGestureRecognizer.delegate = self
```
And:
```
extension PlayViewController: UIGestureRecognizerDelegate {
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }
}
```
After that the MPVolumeView slider respond like a charm!

**Comment by LeoNatan** [comment]
Great!

**Comment by iDevelopper** [comment]
In fact, my MPVolumeView respond because I modified the controller in my storyboard! I don't know exactly what I have done.

The delegate method is not called! When I set the delegate to self:
```
        self.popupContentView.popupInteractionGestureRecognizer.delegate = self
```
For example, set a break point in LNPopupInteractionPanGestureRecognizer.m at:
```
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
{
	LNPopupInteractionStyle resolvedStyle = _LNPopupResolveInteractionStyleFromInteractionStyle(_popupController.containerController.popupInteractionStyle);
	
	BOOL rv = resolvedStyle != LNPopupInteractionStyleNone;
	
	if(rv && [self.forwardedDelegate respondsToSelector:_cmd])
	{
		return [self.forwardedDelegate gestureRecognizerShouldBegin:gestureRecognizer];
	}
	
	return rv;
}
```
You will see that self.forwardedDelegate is always nil. I don't understand why!

So the forwardedDelegate (for me the container view controller) is never called.

I was about to help for issue #214 and I discovered this...

Regards,

**Comment by LeoNatan** [comment]
That means that you have set the delegate of the incorrect view controller’s popup content view. It has to be the one you present the popup bar on.

**Comment by iDevelopper** [comment]
Ok, my mistake, I have to do this:
```
        rootNC.popupContentView.popupInteractionGestureRecognizer.delegate = playViewController
        rootNC.presentPopupBar(withContentViewController:playViewController, animated: true, completion: nil)
```
I was doing it in the playViewController:
```
        self.popupContentView.popupInteractionGestureRecognizer.delegate = self
```
It works! Thanks!

**Comment by MaurixFx** [comment]
@iDevelopper  please you can share how implement MPVolume?

**Comment by iDevelopper** [comment]
Call this in viewWilAppear()

self.volumeContainerView is an IBOutlet from the storyboard.

```
    func createVolumeView() {
        if (self.volumeContainerView.viewWithTag(100) == nil) {
            self.volumeContainerView.backgroundColor = UIColor.clear
            let volumeView = MPVolumeView()
            volumeView.tag = 100
            let size = volumeView.sizeThatFits(CGSize(width: self.volumeContainerView.bounds.size.width - 40, height: 0))
            volumeView.frame = CGRect(x: 20 , y: (self.volumeContainerView.bounds.size.height - size.height) / 2, width: size.width, height: size.height)
            volumeView.autoresizingMask = .flexibleWidth
            
            let image = #imageLiteral(resourceName: "Airplay")
            volumeView.setRouteButtonImage(image, for: .normal)
            self.volumeContainerView.addSubview(volumeView)
        }
    }
```
