### ISSUE TITLE
Cant dismiss popup from the target VC

### ISSUE THREAD

**Issue by vdharankar** [LeoNatan/LNPopupController#215]
#### Unable to dismiss popup from the target view controller which is being shown as a popup.
I am trying to dismiss the popupbar using a button form popupbar itself . When its clicked I am calling dismissPoup method but this doesn't work, however when I do it from other view controller I am able to dismiss the popup. I am not sure if this a bug or a feature .

#### Device, OS and Xcode Versions
iPhone, iOS 11.2 , Xcode9.2

**Comment by LeoNatan** [comment]
You are not calling `closePopup` or `dismissPopup` on the correct view controller. You need to call it on the one you presented on.
