### ISSUE TITLE
Actions in popupItem buttons 

### ISSUE THREAD

**Issue by MaurixFx** [LeoNatan/LNPopupController#216]
Hello,

Thanks for the wonderfull proyect. How add target action to popupItem buttons, for example when I touch pause button execute action in class DemoMusicPlayerController?.

[http://res.cloudinary.com/maurixfx/image/upload/v1516824874/Captura_de_pantalla_2018-01-24_a_la_s_17.14.07_ramltj.png](url)

Regards.

**Comment by iDevelopper** [comment]
These are UIBarButtonItems, so:

```
        self.popupPlayButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "pause-small"), style: .plain, target: self, action: #selector(playPauseAction(_:)))
        self.popupPlayButtonItem?.tintColor = UIColor.black
        
        self.popupNextButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "next-small"), style: .plain, target: self, action: #selector(next(_:)))
        self.popupNextButtonItem?.tintColor = UIColor.black
        
        self.popupItem.rightBarButtonItems = [popupPlayButtonItem!, popupNextButtonItem!]
```

**Comment by LeoNatan** [comment]
Yes, as @iDevelopper says.

**Comment by MaurixFx** [comment]
Thanks Leo and iDevelopper its works 👍

**Comment by MaurixFx** [comment]
Leo, how change popupCloseButton?

**Comment by LeoNatan** [comment]
Change to what?

**Comment by MaurixFx** [comment]
other image or more customizable

**Comment by LeoNatan** [comment]
If you want a custom button, set the system button style to `none` and put a button of your own that calls `closePopup`.

**Comment by MaurixFx** [comment]
closePopup(animated: true, completion: nil) . not dismiss popup

**Comment by iDevelopper** [comment]
I think it will be useful to add a LNPopupCloseButtonStyleCustom case as we can't replace the chevron class by another custom button.

**Comment by LeoNatan** [comment]
Why not? You can place you own button wherever you want on the content view or popup content view controller. A custom dismiss button is just a button you can add already, so there is no point.

**Comment by MaurixFx** [comment]
@iDevelopper do you have a example for that?

**Comment by LeoNatan** [comment]
If you want a custom chevron, I have this library: https://github.com/LeoNatan/LNChevronView

**Comment by MaurixFx** [comment]
I try close popup with this 

@IBAction func didCloseButton(_ sender: UIButton) {
      closePopup(animated: true, completion: nil)
 }

not works.

**Comment by LeoNatan** [comment]
You need to call `closePopup` on the correct view controller (the one you presented on).

**Comment by iDevelopper** [comment]
I think he would like to have this:

[LNPopupCloseButton.zip](https://github.com/LeoNatan/LNPopupController/files/1664089/LNPopupCloseButton.zip)

**Comment by MaurixFx** [comment]
extension DemoAlbumTableViewController: DemoMusicPlayerControllerDelegate {
    func didClosePopup(sender: DemoMusicPlayerController) {
        tabBarController?.closePopup(animated: true, completion: nil)
    }
}

its works. Thanks :D

**Comment by LeoNatan** [comment]
@iDevelopper Achieving this with UIButton is very easy. I don’t see a reason to complicate the framework’s code.

**Comment by iDevelopper** [comment]
It would be interesting for positioning and all the others properties relatives to this button. The user of the library just have to chose an image for the button...

**Comment by MaurixFx** [comment]
Hi @LeoNatan  and @iDevelopper. I'm sorry for being here again asking, how can I detect when the pop up appears?.

Regards.

**Comment by MaurixFx** [comment]
I need  see know when popupBar appears beacuse actually Play music in the end of method didSelectRowAt, but the popupBar appears after the music play

        tabBarController?.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: nil)
        tabBarController?.popupContentView.popupCloseButtonStyle = .round
	    tabBarController?.popupBar.tintColor = UIColor(white: 38.0 / 255.0, alpha: 1.0)
	    tabBarController?.popupBar.imageView.layer.cornerRadius = 5
	    tabBarController?.popupBar.backgroundStyle = .extraLight
        popupContentController.listUrl = listURL
        popupContentController.rowSelected = indexPath.row
        AudioPlayerManager.shared.play(urlStrings: listURL, at: indexPath.row)

**Comment by iDevelopper** [comment]
Use the completion block:

```
            tabBarController?.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: {
                // Presented
                // ...
            })
```
