### ISSUE TITLE
I can not change close button style....

### ISSUE THREAD

**Issue by darkForestCat** [LeoNatan/LNPopupController#217]
#### Description
I wan't to change close button style to .round because it is more comfortable to use.I do everything like in documentation but nothing is changing.

#### Steps to Reproduce
It is working actually nowhere!
You think it will work before you present it?
`            controller.popupContentView.popupCloseButtonStyle = .round
`
No, it won't !

You think it will work if you will place it inside Presenting View Controller class?(You can put it everywhere, just in all functions in one time!)
Ha-ha, nope!
`        self.popupContentView.popupCloseButtonStyle = .round
`

#### Device, OS and Xcode Versions
All new

So what I actually need to do to change this button?I have tried everything!

**Comment by LeoNatan** [comment]
I just checked in the example project and it works. You are likely setting it to the wrong controller. Please see example project.

**Comment by darkForestCat** [comment]
Actually it is also not working in your's demo project.
DemoAlbumTableViewController.swift file
didSelectRow method
`        popupContentController.popupContentView.popupCloseButtonStyle = .round
`
Also:
DemoMusicPlayerController.swift
viewDidLoad method
`        popupContentView.popupCloseButtonStyle = .round
`

Nothing changes.
May be I do this in a wrong place, can you please help me saying where do I actually need to change this.Thank you

**Comment by LeoNatan** [comment]
Look at the ObjC side. It checks if some user default value is set and sets the button type from there.

**Comment by darkForestCat** [comment]
Ok I went to FirstViewController.m
and changed that line with NSUserDefaults to 
`    [targetVC.popupContentView setPopupCloseButtonStyle:LNPopupCloseButtonStyleRound];
`

And nothing has changed(

**Comment by LeoNatan** [comment]
To see if something is broken, let's start from clean git project.
Run the demo project.
In the main screen, tap the (i) button and select round button style.
Now select any of the standard scenes.
What kind of a button appears?

**Comment by darkForestCat** [comment]
Just a new project.
Round button style is not available.
<img width="566" alt="bildschirmfoto 2018-01-26 um 21 15 59" src="https://user-images.githubusercontent.com/25624923/35458841-3ad66474-02de-11e8-997b-33292e3fdfb7.png">

**Comment by LeoNatan** [comment]
What?
I asked you to press this button when the app is running and select round button there.

**Comment by darkForestCat** [comment]
For me "open a project" means open Xcode, not iOS App.I was a little bit confused when you said that.
After this manipulations it is not working...
<img width="328" alt="bildschirmfoto 2018-01-26 um 21 27 54" src="https://user-images.githubusercontent.com/25624923/35459320-df9c5508-02df-11e8-8703-dc78e734118a.png">
<img width="318" alt="bildschirmfoto 2018-01-26 um 21 27 32" src="https://user-images.githubusercontent.com/25624923/35459321-dfb5b476-02df-11e8-9fac-9ae16a362a14.png">

**Comment by LeoNatan** [comment]
But you opened the music popup. The customization settings only work in the standard scenes, as I said before.

**Comment by darkForestCat** [comment]
How can I customise this one?Is it possible o no?

**Comment by LeoNatan** [comment]
It is. I asked you to confirm whether the standard scenes work.
If they do, that means the framework works.
You should look at how the standard scenes enable the customization and do the same in the music controller.

**Comment by darkForestCat** [comment]
Yes, standard one are working.
I can't find no one .m or swift file of the standard scene.I can find only music scene.I am really confused. Where can I find them??
<img width="383" alt="bildschirmfoto 2018-01-26 um 22 31 45" src="https://user-images.githubusercontent.com/25624923/35462020-913d21e8-02ea-11e8-9cfb-10ad84cc56aa.png">

**Comment by LeoNatan** [comment]
This is the code responsible for setting the close button style:
https://github.com/LeoNatan/LNPopupController/blob/51621c33754ecc1ff8c2e0d802d872b7e44f9aa9/LNPopupControllerExample/LNPopupControllerExample/FirstViewController.m#L147

**Comment by darkForestCat** [comment]
And I have already changed it.And in Music part of your example project nothing changes also in my project if I do like this nothing changes.My question is how to change exactly this part.
By the logic is must be changed if I change a property but it does not.

**Comment by darkForestCat** [comment]
Finally I did it by removing all other styles.The only one way it is working for me.

**Comment by LeoNatan** [comment]
What styles did you remove?

**Comment by darkForestCat** [comment]
I left only rounded and none.All other I have removed.

**Comment by iDevelopper** [comment]
Why did you remove the styles? You have modified the library... It works without this action.

**Comment by darkForestCat** [comment]
Actually if be correct i removed the part where if it the version of iOS > 10 the style changes, after that everything began to work, I have forgotten to say this.Without doing this nothing was working, I have tried everything.
