### ISSUE TITLE
Crashes on iOS 9.3.5

### ISSUE THREAD

**Issue by phyominthu** [LeoNatan/LNPopupController#219]
Hi Leo,

The app crashes when I try to present popup bar using `tabBarController?.presentPopupBar` in iOS **9.3.5** (iPad Air).

**LNPopupBar.m**
<img width="735" alt="screen shot 2018-02-04 at 8 56 10 pm" src="https://user-images.githubusercontent.com/6995089/35778937-ca30fa00-09f3-11e8-8368-836a6f889318.png">

**Console**
<img width="769" alt="screen shot 2018-02-04 at 8 57 04 pm" src="https://user-images.githubusercontent.com/6995089/35778939-cf6c268e-09f3-11e8-9a44-545e3390ef4e.png">

My Tab Bar's translucency is set to `false`. Everything works fine on iOS 11 (tested on both Simulator and actual device).

The issue is happening in the latest release (**v2.5.6**) of LNPopupController.

Thanks!

**Comment by phyominthu** [comment]
I used LNPopupController **v2.5.4** before. So I rolled back and tested with that version just now, and I found the app is working fine on **v2.5.4**. This issue occurs after upgrading to **v2.5.6** (because I wanted `isTranslucent` property and hairline of popup bar.)

**Comment by LeoNatan** [comment]
Oh. Thanks for reporting, will fix soon.

**Comment by phyominthu** [comment]
Thanks! I'll be looking forward to it.

**Comment by phyominthu** [comment]
Now it's working. Thanks a lot, Leo!

**Comment by LeoNatan** [comment]
Thank you for using my framework!
