### ISSUE TITLE
Change imageView's alpha in Popup Bar while transitioning

### ISSUE THREAD

**Issue by phyominthu** [LeoNatan/LNPopupController#220]
Hey Leo,

I'm using `popupInteractionStyle = .drag` and `barStyle = .prominent`. When I drag the popup bar upwards, the title and subtitle of popup bar slowly fades away as my finger reach to the top of the screen, and vice versa when I drag it down.

But the `imageView` of popup bar doesn't fade out or fade in like the titles do. I think it feels more intuitive if the `imageView` has the same behavior like the titles.

I mingled around **LNPopupBar.m** and could get the desired result by replacing `[self addSubview:_imageView];` with `[_toolbar addSubview:_imageView];`.

That's just my own workaround, and it'd be great if you could implement that in a proper way.

Thanks!

**Comment by LeoNatan** [comment]
Ooh, I must have missed that. It's a bug and should indeed happen. Will fix this soon.

**Comment by phyominthu** [comment]
Alright, Leo!
