### ISSUE TITLE
viewWillAppear and viewDidAppear never called after dismissing content view controller

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#222]
#### Description
viewWillAppear and viewDidAppear never called after dismissing content view controller

#### Steps to Reproduce

Your example:

In DemoAlbumTableViewController, viewWillAppear is not called when we drag down the DemoMusicPlayerController.

#### Device, OS and Xcode Versions

iPhone 6S, iOS 11.2.2, Xcode 9.2 (9C40b)

**Comment by LeoNatan** [comment]
This is the intended behavior. I do not plan to make changes around this area.

**Comment by iDevelopper** [comment]
Can we at least have some delegate methods or notifications to know when the contentController will/did open and will/did close?

**Comment by LeoNatan** [comment]
That's something I've considered in the past.

But what are you trying to accomplish?

**Comment by iDevelopper** [comment]
When close the contentController by drag or tap button, there is a other controller behind it! It would be nice if this one could receive a notification when it becomes visible to be able to achieve some actions. I think it is not very complicated to do!

**Comment by iDevelopper** [comment]
I do this in my library: https://github.com/iDevelopper/PBRevealViewController

Everyone is asking for more and more information!

**Comment by iDevelopper** [comment]
Do you agree with that?

**Comment by LeoNatan** [comment]
Not sure about delegate vs notification. Need to sit with the API and think about it. There probably should only be one presenter and dismisser, so a notification wouldn't fit. But not sure.

**Comment by iDevelopper** [comment]
Notification is better in your case, I think, because the popup content view can be open over any other controller!

**Comment by iDevelopper** [comment]
This is not the question. What I would like is that the controller that is below the popup content controller can be notified when the popup content controller has been closed either programmatically or by the user (button or drag down).
