### ISSUE TITLE
UIGestureRecognizerDelegate is not responding 

### ISSUE THREAD

**Issue by darkForestCat** [LeoNatan/LNPopupController#223]
#### Description
I have an UISlider inside my contentView.When user starts sliding I want to disable the gestures, so the user can get better user experience while using the app by not triggering the content view, while he does not want to do it.

#### Steps to Reproduce
As I understood I just need to catch the gestureRecognizerShouldBegin.
So in my class in `willTransition` method I did this:
`        self.popupContentView.popupInteractionGestureRecognizer.delegate = self
`

And then I wrote this
```
extension ACPlayerController: UIGestureRecognizerDelegate {
    
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
      
        return true
    }
    
    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        print("GESTURE BEGAN!!!!!!\n\n") //I have never seen this printed when I was hiding the contnentview
        return true
    }
}
```
But `gestureRecognizerShouldBegin` is never called when I am trying to hide the content view.
I guess I have implemented something wrongly?Can you please give me an advise on this issue?
Thank you.

**Comment by iDevelopper** [comment]
You have to set the delegate from the controller that presents ACPlayerController. So, for example:

```
            rootNC.presentPopupBar(withContentViewController:playerViewController, animated: true, completion: nil)
            rootNC.popupContentView.popupInteractionGestureRecognizer.delegate = playerViewController
```

**Comment by darkForestCat** [comment]
Still it is not working for me.Even I have tried to make delegate in the class where I do the presentPopupBar.Also I have tried setting the delegate not `self` but `controller ` and that is not working too.
 Here is the code 

 ```
self.tabBarController?.popupContentView.popupInteractionGestureRecognizer.delegate = self
            self.tabBarController?.presentPopupBar(withContentViewController: controller, animated: true, completion: {
                
            })
```

**Comment by iDevelopper** [comment]
No, controller must be the delegate, not self:

```
self.tabBarController?.popupContentView.popupInteractionGestureRecognizer.delegate = controller
           self.tabBarController?.presentPopupBar(withContentViewController: controller, animated: true, completion: {
               
           })
```

**Comment by darkForestCat** [comment]
As I sad to you I did try this, it was NOT working.
As I sad before: "Also I have tried setting the delegate not `self` but `controller` and that is not working too."

**Comment by darkForestCat** [comment]
It just began working by itself.I did not modified anything.No comments.

**Comment by iDevelopper** [comment]
Yep! Sorry for my bad reading!

It works for me, could you upload a sample?

**Comment by iDevelopper** [comment]
Ah, OK! Great!
