### ISSUE TITLE
Retain the popup content view controller, even when popupBar is closed?

### ISSUE THREAD

**Issue by alexkitcoff** [LeoNatan/LNPopupController#224]
Is there a simple way to retain the popup content view controller when the popupBar is closed? I have content that I would like to remain active whenever the popupBar is presented, whether it's open or closed, but the popup content view controller gets dismissed when minimizing the popup bar.

**Comment by LeoNatan** [comment]
The popup content controller is retained strongly. It will only be released if you dismiss the popup. Opening and closing should not release the content controller. Are you seeing a different behavior? If so, please attach a demo project where this reproduces. 

Thanks

**Comment by iDevelopper** [comment]
Save a global reference to your content controller somewhere in your project.

**Comment by alexkitcoff** [comment]
I tried that just to be sure and there was no difference in behavior. I don’t think it’s necessary since the content view controller is already retained. I think this is behavior specific to just the YouTube embedded video, where the embed will stop playback if it detects that it’s view controller has been dismissed. I’m trying to figure out if there is a way to keep the content view controller in a presented state at all times, even if it’s not actually visible on screen (popupBar is closed).

**Comment by iDevelopper** [comment]
I do that in a music player witch use StreaminkKit. I first create an instance of it, save it in my project, and she is always alive.

**Comment by LeoNatan** [comment]
Are you using a webview? It's a Google thing. They detect in JS that the view has disappeared and stop playback. It's against Google TOS to allow background playback unless the user has YouTube RED. It's nonsense but they started enforcing it recently. One way to evade that is to display the desktop version of YouTube. Try setting a custom user agent.

**Comment by LeoNatan** [comment]
You can reproduce this same issue on MobileSafari. 

If you are up for forking the project, you can disable calling `removeFromSuperview` which will keep your web view in the hierarchy and will fool the JavaScript to think it is still open.

**Comment by alexkitcoff** [comment]
You beat me to it, but I ended up commenting out each removeFromSuperview call, which did the trick. Thanks so much for all your help.
