### ISSUE TITLE
Xcode beta 2 errors

### ISSUE THREAD

**Issue by MaticConradi** [LeoNatan/LNPopupController#227]
So many errors in the latest Xcode beta... most of them are fixable but 3 errors persist saying:
`implementing depricated method`

**Comment by LeoNatan** [comment]
Thanks.
It's a compiler flag I need to disable.

**Comment by LeoNatan** [comment]
Which methods?

**Comment by MaticConradi** [comment]
Oh nevermind, I changed the iOS deployment target to iOS 10 for some reason, should be iOS 9 as far as I know. I'm stilletting this error though:

![screen shot 2018-02-13 at 20 08 27](https://user-images.githubusercontent.com/5693961/36168543-bd952b56-10f9-11e8-8deb-fafeab2888f3.png)

**Comment by LeoNatan** [comment]
Hm? In that file, `#import "_LNPopupBase64Utils.h"` should make that symbol visible.

**Comment by MaticConradi** [comment]
In which file?

**Comment by LeoNatan** [comment]
LNPopupController.m

**Comment by MaticConradi** [comment]
Um... that file already has it imported 🤔

**Comment by LeoNatan** [comment]
Yes, exactly. Just to make sure, have you defined `LNPopupControllerEnforceStrictClean` in your project?

**Comment by MaticConradi** [comment]
Here? I uncommented this line but no success

![screen shot 2018-02-13 at 20 29 09](https://user-images.githubusercontent.com/5693961/36169577-e0056c7a-10fc-11e8-9c20-7b3956dee76e.png)

**Comment by LeoNatan** [comment]
Just compiled the example project in Xcode 9.3 beta 2 and have no warnings or errors. Are you seeing this in your own project?

**Comment by LeoNatan** [comment]
Ping

**Comment by MaticConradi** [comment]
Downloaded the project again, dragged it into the Xcode and got the same error as before:

`Linker command failed with exit code 1 (use -v to see invocation)`

**Comment by LeoNatan** [comment]
If you open the demo project, does it compile normally?

**Comment by MaticConradi** [comment]
Yup it does... what...

**Comment by LeoNatan** [comment]
Are you building using the new build system or the old one?

**Comment by MaticConradi** [comment]
What's the new build system? I clicked "ok", "continue" and all once I first ran the project in Xcode beta. It prompted me to allow some changes to be made. Could that be it?

**Comment by LeoNatan** [comment]
Xcode 9 comes with a beta of a new build system, rewritten from scratch. Still rather buggy the last time I tried it. I asked because maybe with Xcode 9.3 Apple decided to enable it by default. The new build system is unsupported as I have not tried it at all with this framework.

To check, open the project settings and see there.

**Comment by MaticConradi** [comment]
Noup. Still using the standard build system.

**Comment by LeoNatan** [comment]
Can you attach your project so I can test?
Since I cannot reproduce this, I cannot help any further.

**Comment by MaticConradi** [comment]
Oh what the... I redownloaded the project and it built fine. Xcode is sometimes just so weird...

**Comment by LeoNatan** [comment]
😂
