### ISSUE TITLE
iPhone X landscape labels' overlapping on image

### ISSUE THREAD

**Issue by amosavian** [LeoNatan/LNPopupController#229]
Hi, Sorry it's me again :)

I think LNPopupController doesn't taks safe area insets into account for title and subtitle labels.

![img_b3ecca2d62f3-1](https://user-images.githubusercontent.com/6725192/36345814-576e29d0-1447-11e8-882e-7c4a83148d13.jpeg)

**Comment by LeoNatan** [comment]
Hmm, it should. I will take a look on my end.

**Comment by LeoNatan** [comment]
I've made changes to how the layout system works for the RTL support. I will make sure X is working well for that system.

**Comment by LeoNatan** [comment]
Out: https://github.com/LeoNatan/LNPopupController/releases/tag/v2.5.9
Please test on iPhone X and open new issues if you see more problems.

**Comment by amosavian** [comment]
Checked it's fixed. Also RTL. Thanks
