### ISSUE TITLE
Add coverart image to minified player

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#23]
I would like to have a small coverart image of the current playing song in the minified version of the player.

I tried to set the coverart image instead of the play/pause button, however it messed up the whole layout. Maybe because it is a large image? I expected it to be scaled...

Any tips on how to do that?

**Comment by bangtoven** [comment]
Hi there!
Did you set the frame of the imageView properly?
You may use the constructor UIBarButtonItem(customView: ...)
Below is the code that I tested, and it worked nicely.
```
        let imageView = UIImageView(image: UIImage(named: "default_cover_art"))
        imageView.frame = CGRectMake(0, 0, 24, 24)
        popupItem = UIBarButtonItem(customView: imageView)
```

Anyway, Thank you for the great work, LeoNatan. 
Your project made my app super awesome!

**Comment by funkenstrahlen** [comment]
> Below is the swift code that I tested, and it worked nicely.

Thanks a lot for your tip! This worked great!

Why did you set the frame exactly to 24x24?

**Comment by LeoNatan** [comment]
@bangtoven Thanks for letting me know! 
I will keep this issue open. When I have time, I might add a native image view in there. A bit busy at the moment, but we'll see.

**Comment by LeoNatan** [comment]
@funkenstrahlen @bangtoven This is now supported properly when using a prominent bar (like iOS 10 Music app).

**Comment by funkenstrahlen** [comment]
👍😃
