### ISSUE TITLE
customBarViewController is nil after dismissPopupBar but still retained by LNPopupBar

### ISSUE THREAD

**Issue by antiraum** [LeoNatan/LNPopupController#232]
I'm setting a customBarViewController like this: 

```
let popupBarVC = PopupBarViewController()
let contentVC = PopupContentViewController()

popupBar.customBarViewController = popupBarVC

presentPopupBar(withContentViewController: contentVC, openPopup: true, animated: true, completion: nil)
```

when I'm dismissing the popupBar the `customBarViewController` property becomes nil

```
// popupBar.customBarViewController is still set here

dismissPopupBar(animated: true) {
    // self.popupBar.customBarViewController is nil here
}
```

However the `PopupBarViewController` instance is not deallocated and according to Xcode's Memory Graph Debugger it is still retained by an instance of `LNPopupBar`.

If I repeat to present and dismiss the popupBar like this I accumulate instances of `PopupBarViewController` that are all retained by different instances of `LNPopupBar`.

![screen shot 2018-02-21 at 10 35 32](https://user-images.githubusercontent.com/52741/36472790-225b8162-16f3-11e8-83aa-c0c993400109.PNG)
![screen shot 2018-02-21 at 10 36 04](https://user-images.githubusercontent.com/52741/36472792-22727746-16f3-11e8-8453-187147a77491.PNG)

If I keep a reference to the `PopupBarViewController` instance myself and reuse that to set it to the `popupBar.customBarViewController` property everytime I'm going to present the popupBar, the `PopupBarViewController` instance will be retained by many `LNPopupBar` instances.

Seems to me that `LNPopupBar` instances are not released when they should be (after dismissPopupBar).

I'm using
LNPopupController v2.5.10
Xcode 9.2

**Comment by LeoNatan** [comment]
Thank you for the great report!
I will look into this ASAP.

**Comment by LeoNatan** [comment]
Considering how the system works, the popup bar itself is created on demand and only released when the presenting controller is released. This is to allow, for example, customization done by the user to persist between presentations.

I do however see a problem where cleanup should be performed after dismissing the popup.

**Comment by antiraum** [comment]
It would be fine for me if the popup bar is not released. But it seems a new popup bar instance is created on every present.

**Comment by LeoNatan** [comment]
Only one bar should be created per presentation per presenting controller.

**Comment by LeoNatan** [comment]
Yes, I see what you mean. Investigating

**Comment by LeoNatan** [comment]
```objc
//No longer need to retain the popup controller after dismissing.
		objc_setAssociatedObject(self, _LNPopupControllerKey, nil, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
```

Well that about will do it 😆

**Comment by LeoNatan** [comment]
OK, found a leak that caused previous bars to remain in memory.

But I still think the correct behavior of the system should be to only release the bar upon the presentation controller release.

**Comment by LeoNatan** [comment]
Please try now with 2.5.11.

Thanks

**Comment by antiraum** [comment]
fix confirmed. thanks!
