### ISSUE TITLE
Hides popup bar when pushed

### ISSUE THREAD

**Issue by Ded77** [LeoNatan/LNPopupController#233]
Hi,

Firstly thank you for your great component 😊 
But I have an issue with it.

 My app is built with a tabbar with 3 items :

UITabbarController
- UINavigationController
- UINavigationController
- UINavigationController

I present the popup bar on my tabbar controller. That works great.
But I want to hide (or dismiss) the popup bar when I push a view controller from each navigation controller (I only want to show the popup bar on the root view controllers).

There is no flag on UIViewController categories like `hidesPopupBarWhenPushed` or something like that.
How can I do that ?

Thank you

**Comment by iDevelopper** [comment]
By implementing UINavigationControllerDelegate, no?

**Comment by LeoNatan** [comment]
Either implement the delegate as explained above, or use any other state management you prefer to dismiss the bar when pushing.

**Comment by Ded77** [comment]
It seems to be a good idea, I will try, thank you. 😊

**Comment by carloskekwa** [comment]
![img_1510](https://user-images.githubusercontent.com/5887468/53014297-c219a780-3450-11e9-9a56-5ecc684a3a11.JPG)
![img_1511](https://user-images.githubusercontent.com/5887468/53014298-c219a780-3450-11e9-9f99-9beb63b7e08f.JPG)
![img_1512](https://user-images.githubusercontent.com/5887468/53014299-c2b23e00-3450-11e9-8fe8-1098b70546ff.JPG)
Hello, 

I am having the same issue and i don't think it is resolved. 
you can see the pictures. First picture is when everything is alright.  I also included my storyboard structure so you can have a better view of what i am saying. when i push to another view controller (image 2) , this is the result ) 
this is the code in my from View Controller. 
![screen shot 2019-02-19 at 2 18 30 pm](https://user-images.githubusercontent.com/5887468/53014473-42d8a380-3451-11e9-961e-2542857b9d93.png)

`- (id<UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController
                                  animationControllerForOperation:(UINavigationControllerOperation)operation
                                               fromViewController:(UIViewController *)fromVC
                                                 toViewController:(UIViewController *)toVC{
    
    if (operation == UINavigationControllerOperationPush){
        self.tabBarController.popupBar.hidden = YES;
    }else{
         self.tabBarController.popupBar.hidden = NO;
    }
    return  nil;
}
`

please help me to fix this issue

**Comment by CivelXu** [comment]
I really need hidesPopupBarWhenPushed features。
