### ISSUE TITLE
How to present popup bar on top of SWRevealController

### ISSUE THREAD

**Issue by PrakashMaharjan** [LeoNatan/LNPopupController#234]
Hi friends,
Any Suggestion how can the pop up be shown in all views when used with sidebar menu like SWRevealController so that pop up can be shown in every view rear, front and right view.

**Comment by iDevelopper** [comment]
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.revealButtonItem.target = self.revealViewController()
        self.revealButtonItem.action = #selector(PBRevealViewController.revealLeftView)

        popContentVC = self.storyboard?.instantiateViewController(withIdentifier: "PopupContentViewController") as! PopupContentViewController
        
        self.revealViewController()?.presentPopupBar(withContentViewController: popContentVC, animated: true, completion: {
            popContentVC.popupItem.image = #imageLiteral(resourceName: "genre1")
            popContentVC.popupItem.title = "Title"
            popContentVC.popupItem.subtitle = "Subtitle"
        })
    }
```

[PBRevealPopupBar.zip](https://github.com/LeoNatan/LNPopupController/files/1767289/PBRevealPopupBar.zip)

**Comment by PrakashMaharjan** [comment]
Thank you so much.. @iDevelopper @LeoNatan for wonderful libraries..

**Comment by PrakashMaharjan** [comment]
Hi, @iDevelopper @LeoNatan, i managed to show the LNPopup bar to everyview as shown in above code in Revelmenu. The popup bar shows correctly but, when i switched to other view from left menu, then the button in the bar action does not work. How to get button instance work from every view when moved to all views via left menu. Is is possible?

I have attached the project file where i navigate to new views from left menu. The buttons action only work in main view. How to control button from all views.

Any suggestion?

[LNPopUpWithReveal.zip](https://github.com/LeoNatan/LNPopupController/files/1902919/LNPopUpWithReveal.zip)

Thanks

**Comment by iDevelopper** [comment]
When the main view controller is ProfileVC for example, homeVC is dismissed then the selectors cannot be called. You can save a reference to homeVC for example in the left menu controller.

After that, when the selector is fired when you are in ProfileVC, homeVC has no parent (self.revealViewController is then nil. So you can retrieve the reveal view controller, it is in your case the application's root view controller.

Other solution, you can move the two selectors in the popup view controller. Search '// PB' in the project.

[PBSideBarTest.zip](https://github.com/LeoNatan/LNPopupController/files/1903375/PBSideBarTest.zip)

**Comment by PrakashMaharjan** [comment]
Thank you so much for response @iDevelopper . Grateful.

**Comment by iDevelopper** [comment]
With pleasure! I think this issue (question) is relative to https://github.com/iDevelopper/PBRevealViewController not here.

Thanks,

**Comment by iDevelopper** [comment]
What about this? My category (extension) could return the revealViewController if it is the root view controller?

This is the actual code:

```
public extension UIViewController {
    
    // An extension of UIViewController to let childViewControllers easily access their parent PBRevealViewController.
    func revealViewController() -> PBRevealViewController? {
        var viewController: UIViewController? = self
        
        if viewController != nil && viewController is PBRevealViewController {
            return viewController! as? PBRevealViewController
        }
        while (!(viewController is PBRevealViewController) && viewController?.parent != nil) {
            viewController = viewController?.parent
        }
        if viewController is PBRevealViewController {
            return viewController as? PBRevealViewController
        }
        return nil
    }
    
}
```
