### ISSUE TITLE
iOS 10.2 tableview footer is not resizing when music toolbar is present

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#235]
I noticed that on iOS 10 tableview footer is not resizing when music toolbar is present, so when scrolling down music bar hides bottom cells. on iOS 11 I don't have that issue. I am not exact sure is this library fault or it's how actually tableview works? any ideas @LeoNatan ?

**Comment by LeoNatan** [comment]
In iOS 10, you have to manually set the insets of the table view. This is a limitation of iOS 10 and below. 

You can look at the demo project to see how I do it:

```swift
if ProcessInfo.processInfo.operatingSystemVersion.majorVersion <= 10 {
	let insets = UIEdgeInsetsMake(topLayoutGuide.length, 0, bottomLayoutGuide.length, 0)
	tableView.contentInset = insets
	tableView.scrollIndicatorInsets = insets
}
```

**Comment by yarodevuci** [comment]
@LeoNatan Thank you, but it did not help, anything else I can try to do?

**Comment by iDevelopper** [comment]
```

**Comment by LeoNatan** [comment]
If `bottomLayoutGuide` is not updated correct, there may be an issue.
How are you presenting your popup? @yarodevuci

**Comment by yarodevuci** [comment]
@LeoNatan 

```
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let audio = audioFiles[indexPath.row]
        let popupContentController = storyboard?.instantiateViewController(withIdentifier: "MusicPlayerController") as! MusicPlayerController
        popupContentController.songTitle = audio.title
        popupContentController.albumTitle = audio.artist
        popupContentController.albumArt = #imageLiteral(resourceName: "artwork")
        popupContentController.trackDurationSeconds = audio.duration
        
        popupContentController.popupItem.title = audio.artist
        popupContentController.popupItem.subtitle = audio.title
        
        navigationController?.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: nil)
```

**Comment by LeoNatan** [comment]
What is the `bottomLayoutGuide.length` value for the table controller?

**Comment by yarodevuci** [comment]
@LeoNatan 0

**Comment by LeoNatan** [comment]
I will look.

**Comment by iDevelopper** [comment]
Same for me: bottomLayoutGuide.length = 0, this is why I added rootNC.popupBar.bounds.size.height to it. rootNC is my root navigation controller. The controller that contains the table view is a UIViewController, not a UITableViewController.

**Comment by LeoNatan** [comment]
Could I please ask you to check what happens if the toolbar is visible for the navigation controller? Does that make a difference?

**Comment by iDevelopper** [comment]
What toolbar? Navbar? PopupBar?

**Comment by LeoNatan** [comment]
You are presenting the popup on a navigation controller. That nvc has `toolbarHidden` property.

**Comment by iDevelopper** [comment]
Yes it make a difference. There is a gap of 40 at the bottom.

**Comment by iDevelopper** [comment]
This is a sample with four table views. Left and second are in table view controllers. And right and main are in table view controllers. Only left and second need to set insets when iOS version <= 10. And sometimes it depends how we open left or right (with button item or by swipe)... Can you test it?

[PBRevealPopupBar.zip](https://github.com/LeoNatan/LNPopupController/files/1775172/PBRevealPopupBar.zip)

**Comment by iDevelopper** [comment]
The simplest way to test is with this sample: navigation controller with two table views: One in UITAbleViewController, and the other in UIViewController. You will see that bottomLayoutGuide.length is equal to zero. In the SecondTableViewController, I added popupBar.bounds.size.height to bottomLayoutGuide.length. (Also the image is not shown in the popupBar when iOS version == 9.3).

[PBNavPopupBarSample.zip](https://github.com/LeoNatan/LNPopupController/files/1775761/PBNavPopupBarSample.zip)

**Comment by LeoNatan** [comment]
Thanks @iDevelopper I will look soon.

**Comment by iDevelopper** [comment]
Hi @LeoNatan , how and where in your library the constraints of presenting view controller are updated? With iOS11, all is working great, on iOS 10 there are issues. Not for only table view but also for view controller. I added to the sample a view controller with two labels on top and bottom and a view with two other labels on top and bottom of this view.

iOS11:
![simulator screen shot - iphone 6 - 2018-03-09 at 14 33 01](https://user-images.githubusercontent.com/1782450/37209841-e7f1d2f4-23a6-11e8-971d-fe85380670e2.png)

iOS10:
![simulator screen shot - iphone 6 - 2018-03-09 at 14 32 23](https://user-images.githubusercontent.com/1782450/37209872-f84e4be6-23a6-11e8-9ef5-941ee632b4a5.png)

**Comment by LeoNatan** [comment]
It's a mess. I will look into it.

**Comment by iDevelopper** [comment]
Oh!

**Comment by LeoNatan** [comment]
I think I found the problem. Checking it won't break something else.

**Comment by iDevelopper** [comment]
Could you tell me where these constraints are set?

**Comment by LeoNatan** [comment]
Fixed

**Comment by iDevelopper** [comment]
Thanks, it works. Your library is not easy to read!

**Comment by LeoNatan** [comment]
Believe me, I know. That's the cost of supporting iOS 9, iOS 10 and iOS 11 and doing things Apple didn't open API properly for.

**Comment by yarodevuci** [comment]
Apple hires some cheap low quality developers...

**Comment by LeoNatan** [comment]
Hey, I criticize Apple's quality of recent years as much as anyone, but from my experience, it's usually not the developer's fault this happens. It's bad management and terrible timetables.

**Comment by yarodevuci** [comment]
@LeoNatan very good point. Horrible management..

**Comment by iDevelopper** [comment]
Yes, sure!

**Comment by iDevelopper** [comment]
Another question, not relative to your great library.

You use:

		 UIView* itemView = [barButtonItem valueForKey:@"view"];

This seems not working in Swift on iOS 11. For another project, I need to find the frame of an UIBarButtonItem in a toolbar.

Any idea, please?
