### ISSUE TITLE
Unable to match color of popupBat with navBar

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#237]
![simulator screen shot - iphone se - 2018-03-01 at 19 33 31](https://user-images.githubusercontent.com/13408859/36882269-aea05158-1d87-11e8-8e89-3dbd0b2dcc8d.png)
I went through example, tried different code and I am getting weird results.

Here is my code. What I am doing wrong? I don't have tabBarController. I am using just regular TableViewController with NavBar. Hopefully @LeoNatan can help.

```
func setupMimiMusicPlayerView() {
		
		UIProgressView.appearance(whenContainedInInstancesOf: [LNPopupBar.self]).tintColor = .pinkColor
		navigationController?.popupBar.progressViewStyle = .top
		navigationController?.popupInteractionStyle = .drag
		
		navigationController?.toolbar.tintColor = .splashBlue
		navigationController?.toolbar.barStyle = .black
		
		self.navigationController?.navigationBar.barStyle = .blackTranslucent
		//self.navigationController?.updatePopupBarAppearance()
		navigationController?.popupBar.tintColor = .white//UIColor(white: 38.0 / 255.0, alpha: 1.0)
		self.navigationController?.updatePopupBarAppearance()
       
//        UIProgressView.appearance(whenContainedInInstancesOf: [LNPopupBar.self]).tintColor = .red
//
//        navigationController?.popupBar.tintColor = UIColor(white: 38.0 / 255.0, alpha: 1.0)
//        navigationController?.popupBar.imageView.layer.cornerRadius = 5
//        navigationController?.popupBar.barStyle = .default
//        navigationController?.popupInteractionStyle = .drag
//        navigationController?.popupBar.progressViewStyle = .top
//        navigationController?.popupBar.barTintColor = .splashBlue
//		navigationController?.popupBar.isTranslucent = true
//		if #available(iOS 10.0, *) {
//			navigationController?.popupBar.backgroundStyle = .light
//		} else {
//			// Fallback on earlier versions
//		}
//		self.navigationController?.updatePopupBarAppearance()
    }
```

**Comment by LeoNatan** [comment]
Forgive my untrained eye, but I don't see a radical change in popup bar and navigation bar color. The prominent popup bar is intended to have a very slight shift in color. Remember that it takes its coloring from the toolbar, not the navigation bar, so apply all customization on that as well.

**Comment by yarodevuci** [comment]
yes but on your example nav and popupbar having exact same colors. So i need to set toolbar color to whatever color is for nav bar @LeoNatan ? 
I did that if you saw that navigationController?.toolbar.tintColor = .splashBlue and there is no changes

**Comment by LeoNatan** [comment]
You are using the wrong tint color property. Use `barTintColor`.

**Comment by yarodevuci** [comment]
@LeoNatan it is still looks slightly darker. My nav bar is Translucent and I set translucency to bottom bar too but that does not help. Anything else I can try ?

My cleaned up code is

```
navigationController?.toolbar.barStyle = .black
navigationController?.toolbar.barTintColor = .splashBlue
navigationController?.popupBar.tintColor = .white
navigationController?.updatePopupBarAppearance()
```

**Comment by LeoNatan** [comment]
Try adding a little alpha to the `.splashBlue`.

**Comment by yarodevuci** [comment]
@LeoNatan is there anyway to disable UIVisualEffectView?

**Comment by LeoNatan** [comment]
If you disable the popup bar translucency, the effect view is hidden and only the bar tint color will remain. But you lose translucency, which is not what you want, I think.

**Comment by yarodevuci** [comment]
Right, I even took this line code off navigationController?.toolbar.barTintColor = .splashBlue and color remained the same

**Comment by LeoNatan** [comment]
You can apply the customization directly to the popup bar. Set `inheritsVisualStyleFromDockingView` to `false`, and then apply your customization there.

For more info, https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/LNPopupBar.h

**Comment by yarodevuci** [comment]
Did not helped either, but I ll close the issue for now. @LeoNatan
