### ISSUE TITLE
Confused with LNPopupController latest version

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#238]
According to description latest version is 2.5.11
Downloaded project says 2.5.0.. 
How do I know if I use latest version? 
<img width="727" alt="screen shot 2018-03-02 at 5 54 02 pm" src="https://user-images.githubusercontent.com/13408859/36929241-d8cd4ca4-1e42-11e8-85b7-edbe61dc1a65.png">

**Comment by LeoNatan** [comment]
It was just too much of a maintenance to keep up with patch versions, so I left just major and minor. Now that I am using an automated script for versioning, I might eventually update the plist as well. But not planned.
