### ISSUE TITLE
Marquee not scrolling for some reason

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#240]
I tried using 		
`popupBar.marqueeScrollEnabled = true
`
but labels on popupBar does not want to scroll.. :( @LeoNatan 
In the example feature neither works. What's going on with that?

**Comment by LeoNatan** [comment]
What do you mean, doesn't work? In the example project, tap the (i) button in the main menu, scroll down and enable marquee scroll. Then open one of the upper example screens (like tab bar). Does it not work for you?

**Comment by yarodevuci** [comment]
@LeoNatan sorry about that, I had to do this 		navigationController?.popupBar.marqueeScrollEnabled = true
to fix the issue. Before I had just popupBar.marqueeScrollEnabled = true
