### ISSUE TITLE
Present Popup Bar on Top

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#241]
It would be nice to have an option to position a popup bar below navigation controller just like on screenshot below.. Unless it is a possibility
![ss](https://user-images.githubusercontent.com/13408859/36956768-045f026a-1fe5-11e8-8d30-0a6bfca27464.jpg)
 to do that already that I am not aware about.

**Comment by LeoNatan** [comment]
It’s not possible right now, and will require very large modifications. Not planned right now.

**Comment by yarodevuci** [comment]
@LeoNatan thank you.
