### ISSUE TITLE
Change modalPresentationStyle

### ISSUE THREAD

**Issue by iKushalManiyar** [LeoNatan/LNPopupController#242]
Hello, 
I want to change modalPresentationStyle while presenting presentPopupBar.  
#### Description

   popupContentController.modalPresentationStyle = .overCurrentContext    tabBarController?.modalPresentationStyle = .overCurrentContext
        
tabBarController?.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: nil)

#### Steps to Reproduce

I want tabbar while presenting.

Thanks in advance.

**Comment by LeoNatan** [comment]
I don't understand what you are attempting to achieve.

**Comment by iKushalManiyar** [comment]
I want Presenting a new View Controller Keeping Tab Bar. So I will achive through overCurrentContext but it will not performing while I use presentPopupBar.

Thanks in advance!

**Comment by LeoNatan** [comment]
Not possible. When a popup is presented, it is presented in full screen always.

**Comment by BeamerCola** [comment]
Yeah I agree that this would be ideal.  Being able to present a 3/4 sheet
