### ISSUE TITLE
How to turn presented view controller landscape and portrait?

### ISSUE THREAD

**Issue by JayceBryce** [LeoNatan/LNPopupController#243]
**I'm having trouble rotating my playerViewController landscape or portrait.** 

I have a PlayerViewController which I present like so:

```
let storyboard = UIStoryboard(name: "Main", bundle: nil)

let playerViewController = storyboard.instantiateViewController(withIdentifier: "PlayerViewController") as! PlayerViewController

tabBarController.presentPopupBar(withContentViewController: playerViewController, openPopup: true, animated: true, completion: nil)
```

Inside my tabBarController and view controllers for the tabs, I have this but it is not inside of playerViewController (because we want playerViewController to go landscape): 

```
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
		return UIInterfaceOrientationMask.portrait
	}
	
	override var shouldAutorotate: Bool {
		return false
	}
```

Inside PlayerViewController I have this:

```
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
		return UIInterfaceOrientationMask.allButUpsideDown
	}
	
	override var shouldAutorotate: Bool {
		return true
	}
```

The tabBarController which presents playerViewController, is set to portrait only. Basically we don’t want the tabBarController to ever go into landscape mode. However, we do want the playerViewController to be able to go landscape and portrait. playerViewController is currently presented inside of the popUpBar.

** When I first instantiate my playerViewController the code above gets executed. It seems like when I try to turn my playerViewController landscape the code above gets called on its presenting view controller and doesn’t get called on the playerViewController itself anymore **

My current hierarchy is as follows:

TabBarController
NavigationController 
MainViewController (instantiates playerViewController)
PlayerViewController

Is there any way you can help out?

**Comment by LeoNatan** [comment]
Hi,

This is not a supported use case. I'd also say it is bad UX. If you open the popup in portrait and then rotate the device to landscape, your users would expect to dismiss it in landscape. But the presenting controller is in portrait, thus would look bad. I do not intend to support this.

I guess, if you insist, you could implement the rotation on your own and use the `transform` property of your player controller's view to rotate it as the users rotates the device.
