### ISSUE TITLE
Bug with presenting PopupBar

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#244]
I have another loading status toolbar that I use in my app. So if popupBar was never called initially and I called: 

`navigationController?.setToolbarHidden(false, animated: true)` and then
`self.navigationController?.setToolbarHidden(true, animated: true)`
And after when i call 
`navigationController?.presentPopupBar(withContentViewController: musicPlayerController, animated: true, completion: nil)` it's not showing up :( Because it's probably hidden somewhere

Any solution how to fix this @LeoNatan ?

**Comment by LeoNatan** [comment]
Need to investigate. Thanks

**Comment by LeoNatan** [comment]
Managed to reproduce, will look into it.

**Comment by LeoNatan** [comment]
Fixed in latest release

**Comment by yarodevuci** [comment]
@LeoNatan Thank you so much, you the best!
