### ISSUE TITLE
How to change height of popupBar in compact mode?

### ISSUE THREAD

**Issue by JayceBryce** [LeoNatan/LNPopupController#245]
#### Description

Currently I'm using the compact style of the popupBar like so:

`tabBarController.popupBar.barStyle = .compact`

**The question is how can I adjust the height of the popupBar?  I would still like to use compact style like I have it but just want to increase the height a bit to better match my app.** 

Thank you!

**Comment by LeoNatan** [comment]
Hello,

Compact and prominent bars come with a predefined height. It is not possible to change that height, as they are intended to be as close as possible to Apple's implementation. I do not plan to change this behavior.

You can create a custom bar, but that will require you to manage the bar all on your own, so this is less than optimal.

If you insist on this change, you can fork the repo and make the change in the source, but I cannot comment how the bar layout will behave for a higher bar height. You will also need to periodically merge my latest improvements.
