### ISSUE TITLE
Compact bar does not layout titles correctly.

### ISSUE THREAD

**Issue by JayceBryce** [LeoNatan/LNPopupController#247]
I am currently using the compact size bar. I have a button on each side of the bar which I am adding a custom images to.

What is the correct size of the image I should add?

Also the title is not centered exactly in the middle inside the bar? I do not know if this is because the image sizes I am setting is wrong?

**Here is how I am setting my buttons** 

```
closeBarButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "close"), style: .plain, target: self, action: #selector nil)
playPauseButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "pause"), style: .plain, target: self, action: #selector nil)

		self.popupItem.leftBarButtonItems = [closeBarButtonItem]
		self.popupItem.rightBarButtonItems = [playPauseButtonItem]
```

Here is an example of the issue in terms of the text not being centered which I tried to highlight using Sketch.

![screen shot 2018-03-13 at 12 31 30 am](https://user-images.githubusercontent.com/37093552/37322773-06e93ef2-2656-11e8-9f14-4f9bae4c9232.png)

**Comment by JayceBryce** [comment]
@LeoNatan are you ever going to answer this or am I going to have to open up another question? Thank you

**Comment by LeoNatan** [comment]
I missed this question. 
I don’t have any numbers for you. I’d say same size as normal toolbar bar items. 

Regarding centering, I’d have to check. Do you have marquee scrolling enabled?

**Comment by iDevelopper** [comment]
@JayceBryce , are you sure your two images (close and pause) have the same size? Perhaps the close image is smaller, no?

**Comment by JayceBryce** [comment]
@LeoNatan Ok I used the same size images you have in your sample project now and the centering is still off. I do have marquee scrolling enabled. Thanks for the help

**Comment by JayceBryce** [comment]
@iDevelopper At the moment I'm using the same size images that @LeoNatan is using on his sample project. The largest image being 96X96. I don't know if this is the issue though and not something to do with the marquee label not being centered. I also tried different image sizes and it didn't work

**Comment by LeoNatan** [comment]
My images are just example images. Don't take any of the example project too seriously; it is only meant to demonstrate the functionality of the framework.

The reason the example project may not behave correctly for a compact-style bar is that they are optimized for the prominent bar. 

If two images of the same size produce a correctly centered label, the issue is in the provided images and not in the layout.

**Comment by iDevelopper** [comment]
Pay attention to the image's resolution too. And you could check easily your image size in the view hierarchy in Xcode by clicking on the Debug View Hierarchy button.

**Comment by JayceBryce** [comment]
@LeoNatan @iDevelopper ok so what is the correct size I should try to import my images? 1X, 2X, 3X?

i.e 20X20 , 40X40, 60X60 ?

**Comment by LeoNatan** [comment]
Read Apple's toolbar guidelines. The same sizes should apply. Also familiarize yourself with what 1x 2x and 3x stand for. I think we have discussed this issue enough.

**Comment by iDevelopper** [comment]
You can use the size you want. Suppose you have a standard resolution @1x image that’s 25px × 25px, for example. The @2x version of this image would be 50px × 50px. The @3x version would be 75px × 75px. You set your images in the "Assets.xcassets" interface of Xcode.

Also, in your case, if you want the title to be centered you have to use the same size for close and pause images.

https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/image-size-and-resolution/

**Comment by LeoNatan** [comment]
https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/custom-icons/

So 24x24 @1x

**Comment by JayceBryce** [comment]
@iDevelopper @LeoNatan I tried both of the things you said. Both my icons are 24X24 and is sized correctly for each one. The label in the middle is still not centered. There has to be something going on with the library. This doesnt make sense. Here are both my icons.

[small-player-play-button.pdf](https://github.com/LeoNatan/LNPopupController/files/1839675/small-player-play-button.pdf)

[small-player-close-button.pdf](https://github.com/LeoNatan/LNPopupController/files/1839674/small-player-close-button.pdf)

**Comment by LeoNatan** [comment]
I'll test tomorrow. If there is an issue, I can always reopen.

**Comment by iDevelopper** [comment]
Tested with your buttons:

![2018-03-23_07-23-57](https://user-images.githubusercontent.com/1782450/37814649-50606098-2e6b-11e8-9a14-197024446516.png)

```
import UIKit

class ThirdViewController: UIViewController {

    var popupCloseButtonItem: UIBarButtonItem?
    var popupPlayButtonItem: UIBarButtonItem?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        popContentVC = self.storyboard?.instantiateViewController(withIdentifier: "PopupContentViewController") as! PopupContentViewController
        
        self.setupButtons()
    }

    @IBAction func presentPopBar(_ sender: Any) {
        self.tabBarController?.popupBar.barStyle = .compact
        popContentVC.popupItem.title = "Hello"
        popContentVC.popupItem.rightBarButtonItems = [self.popupCloseButtonItem!]
        popContentVC.popupItem.leftBarButtonItems = [self.popupPlayButtonItem!]

        let paragraphStyle = NSParagraphStyle.default.mutableCopy() as! NSMutableParagraphStyle
        paragraphStyle.alignment = .center
        self.tabBarController?.popupBar.titleTextAttributes = [NSAttributedStringKey.paragraphStyle: paragraphStyle, NSAttributedStringKey.backgroundColor: UIColor.gray, NSAttributedStringKey.foregroundColor: UIColor.red, NSAttributedStringKey.font: UIFont.systemFont(ofSize: 24)]
        
        self.tabBarController?.presentPopupBar(withContentViewController: popContentVC, animated: true, completion: {
        })
    }
    
    @IBAction func dismissPopBar(_ sender: UIButton) {
        self.tabBarController?.dismissPopupBar(animated: true) {
        }
    }
    
    func setupButtons() {
        self.popupCloseButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "small-player-close-button"), style: .plain, target: self, action: #selector(close(_:)))
        self.popupCloseButtonItem?.tintColor = UIColor.black

        self.popupPlayButtonItem = UIBarButtonItem(image: #imageLiteral(resourceName: "small-player-play-button"), style: .plain, target: self, action: #selector(play(_:)))
        self.popupPlayButtonItem?.tintColor = UIColor.black
    }
    
    @IBAction func close(_ sender: UIButton) {
    }
    
    @IBAction func play(_ sender: UIButton) {
    }
}
```

**Comment by LeoNatan** [comment]
I reproduced the problem with your images. The title is slightly shifted.

**Comment by LeoNatan** [comment]
I think it's the marquee label incorrectly aligning. 

Compare marquee scrolling enabled:
![simulator screen shot - iphone 8 plus - 2018-03-24 at 05 03 57](https://user-images.githubusercontent.com/2270433/37859173-443020ea-2f21-11e8-9609-d46b7bd9e7a1.png)

With marquee scrolling disabled:
![simulator screen shot - iphone 8 plus - 2018-03-24 at 05 04 06](https://user-images.githubusercontent.com/2270433/37859174-444f33e0-2f21-11e8-99dd-6ca7b7031495.png)

**Comment by iDevelopper** [comment]
Yes if marqueeScrollEnabled is true, I can also reproduce the problem. I think the problem is here, in LNPopBar.m:

![2018-03-24_15-20-32](https://user-images.githubusercontent.com/1782450/37865061-61b6bc68-2f77-11e8-8832-c8516944623a.png)

**Comment by iDevelopper** [comment]
Yes I think you can remove that! Other question: How do you do to have a red background title view? In your screenshots it is a compact bar or a custom?

**Comment by iDevelopper** [comment]
You can also removing "rv.trailingBuffer = 15;"

But the better you could do it's the labels can be some properties accessibles by the users of your framework. Not only the title and subTitle' string.

**Comment by LeoNatan** [comment]
That would mean exposing the marquee label stuff, which would be a bit problem. Internally I use normal `UILabel`s when marquee is not enable to save resources. So then the user needs to be aware of this implementation detail also. I don't like that.

I need to see what the leading and trailing buffers do.

**Comment by iDevelopper** [comment]
Trailing Buffer:

![2018-03-25_08-48-58](https://user-images.githubusercontent.com/1782450/37905738-1adbe95a-3100-11e8-9a4e-b94b65258201.png)

**Comment by LeoNatan** [comment]
Thank you!

So maybe the leading buffer value can be moved to the trailing buffer to keep the same look and feel, while removing the slight leading shift. I'll do it again.

Thank you for your assistance.

**Comment by iDevelopper** [comment]
Do you have a response for this, please?

> Other question: How do you do to have a red background title view? In your screenshots it is a compact bar or a custom?

**Comment by LeoNatan** [comment]
Sorry, I missed that. I just went into LNPopupBar.m and changed the titles container view's background color. The privilege of having the source code. 😃

**Comment by iDevelopper** [comment]
There are surprising things: fadeLength provide also a 'trailing buffer".

```
	MarqueeLabel* rv = [[MarqueeLabel alloc] initWithFrame:_titlesView.bounds rate:20 andFadeLength:10];
	rv.leadingBuffer = 0.0;
	rv.trailingBuffer = 0.0;
	rv.animationDelay = 2.0;
	rv.marqueeType = MLContinuous;
	return rv;
```
With trailingBuffer = 0.0 and fadeLength = 10
![2018-03-26_14-29-54](https://user-images.githubusercontent.com/1782450/37906471-8800e560-3102-11e8-98f0-5b6137843020.png)
```
	MarqueeLabel* rv = [[MarqueeLabel alloc] initWithFrame:_titlesView.bounds rate:20 andFadeLength:0];
	rv.leadingBuffer = 0.0;
	rv.trailingBuffer = 0.0;
	rv.animationDelay = 2.0;
	rv.marqueeType = MLContinuous;
	return rv;
```
With trailingBuffer = 0.0 and fadeLength = 0
![2018-03-26_14-40-59](https://user-images.githubusercontent.com/1782450/37906932-f292449a-3103-11e8-9ff0-310a1119f80c.png)

**Comment by LeoNatan** [comment]
Right, I am guessing the last one is what I tried to avoid 😂

**Comment by iDevelopper** [comment]
Maybe you could make the two labels available (properties) and the users of the framework will do what they want with them (UILabel, Marquee, etc ...)?

**Comment by iDevelopper** [comment]
And your framework will no longer be dependent on MarqueeLabel...

**Comment by LeoNatan** [comment]
> Maybe you could make the two labels available (properties) and the users of the framework will do what they want with them (UILabel, Marquee, etc ...)?

That's not possible. Either the framework exposes the labels, or it exposes a canvas and the user adds labels. `LNPopupController` does both—you can use predefined modes (compact, prominent) or a completely custom one that you can design as you want using `LNPopupCustomBarViewController`.

**Comment by LeoNatan** [comment]
Not supported. 🙂

The point of the framework is to give as close representation of Apple's. There are already enough customization options. Since marquee is going away in iOS anyway, I bet most users don't even stumble upon that option, unless they go looking for it (it's disabled by default on iOS 10 and above).

**Comment by JayceBryce** [comment]
@LeoNatan thanks for helping out! Any chance you made that small update yet for the labels not being centered? Were trying to push up a new build and would be great if this was fixed! =]

**Comment by iDevelopper** [comment]
@LeoNatan , we can't evoke a close representation of Apple's as there is not API for this. Only the music app can show it. We could also talk about the animation witch is really different. Within Apple music app, the mini player image becomes the big image with an animation beginning from bottom-left corner of the mini player to the image of the content view. And I'm not talking about the rounded corners of the rear view etc... However, you did a very good job but I think there is way to propose more parameters. Thanks.

**Comment by LeoNatan** [comment]
I don’t plan on exposing more params. 

@JayceBryce Yes, tonight.

**Comment by iDevelopper** [comment]
@JayceBryce , why do you set marqueeScrollEnabled to true as "Hello" will not scroll as the size is < label.size?

**Comment by iDevelopper** [comment]
@LeoNatan , I understood, damage!
