### ISSUE TITLE
iOS < 11 View Additional Insets

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#248]
#### Description
It is not an issue but a question, relative to your experience:

Hi @LeoNatan ,

I would like to add a child view controller below the bottom layout guide off a view controller view.

For iOS version >= 11, I am using additionalSafeAreaInsets property, it works.

For iOS version < 11, I modified the insets of the view but the view added below the bottom layout guide does not responds to events so what should be the solution?

Thanks in advance.

Regards,

**Comment by LeoNatan** [comment]
Hey

Not sure I fully understand. Do you have a child view controller who you'd like to receive correct top/bottom layout guides, or do you want to put the child controller's view attached to the bottom layout guide? What events doesn't it respond to?

**Comment by iDevelopper** [comment]
I want to put the child controller's view attached to the bottom layout guide, but under (the top of the child controller's view under the bottom layout guide of the container view. Exactly like your library does.

![2018-03-20_15-03-42](https://user-images.githubusercontent.com/1782450/37659406-2e58827c-2c50-11e8-99f6-1bd7a64a716d.png)

If I have a button in this child view it does not responds.

# In fact I would like to reproduce what we can do with the new additionalSafeAreaInsets property (iOS 11) on iOS < 11.

**Comment by LeoNatan** [comment]
It's not really possible without implementing a lot of the logic that this framework does.
Until iOS 11, there was no official way to move the controller layout guides. So in the framework, I fiddle with internal functionality to move the bottom layout guide above the popup bar.

I'm not sure why, in your case, touches are swallowed. You should debug and see which object is consuming them. 

For your specific case, you can use LNPopupController with a custom controller as the popup bar (see documentation), and let my system handle it for you. You can then disable opening of the popup if you don't need it.

**Comment by iDevelopper** [comment]
In fact if I understand my child view controller have to be a container view controller, and the main view controller a child view controller...

**Comment by LeoNatan** [comment]
Hm, I don't think that is necessary.
If you subclass `LNPopupCustomBarViewController` as your child, you can then use that as your popup bar (`popupBar.customBarViewController = child`) and then present it normally.

**Comment by LeoNatan** [comment]
See the map example. The bottom search bar is presented from a custom bar controller. That can be your "child".

**Comment by iDevelopper** [comment]
Thanks Leo, I will have a look
