### ISSUE TITLE
Having big problems when using with UITabBarController that has more than 4 tabs 

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#25]
It's a major one - when used with UITabBarController that has more than 4 tabs the LNPopupController gets embedded into the UITabBarController as an additional tab. This happens not on the initial presentation but when the screen size changes (iOS9 multitasking on iPad Air2 and newer).

Steps:
1) In the example app open Main.storyboard and add one more tab to the tab bar controller to make 5 tabs in total
2) Compile and launch on iPad Air2 iOS9 simulator 
3) When the LNPopupController is docked change the screen size to 50/50

Result: 
The LNPopupController ends up being an additional tab of the tab bar controller

**Comment by Kastet** [comment]
<img width="880" alt="screen shot 2015-10-27 at 1 19 09 pm" src="https://cloud.githubusercontent.com/assets/611542/10748016/d7f5621c-7caf-11e5-94bc-409caf4921d5.png">
<img width="880" alt="screen shot 2015-10-27 at 1 22 47 pm" src="https://cloud.githubusercontent.com/assets/611542/10748015/d7f4f3b8-7caf-11e5-84d8-25a22ced3817.png">

**Comment by LeoNatan** [comment]
Yuck!
Thanks for reporting. Will take a look eventually but will take me some time.

**Comment by Kastet** [comment]
Hello Leo! 
Have you got any chance to look at this bug?

**Comment by Kastet** [comment]
Hi Leo,

but how is this issue related to adding support for Carthage? Is it a mistake? 

Thanks

**Comment by LeoNatan** [comment]
Sorry, it was a mistake. 
I have not yet had chance to look.

**Comment by LeoNatan** [comment]
@Kastet Fixed the issue. Please try and enjoy the library.

**Comment by Kastet** [comment]
Hm, in my project the issue is still reproducible but in the sample project it's not... I've triple checked to make sure the I have the latest version. Any idea?

**Comment by Kastet** [comment]
Sorry, my bad. After cleaning up my Xcode project the latest version of the framework got compiled and everything seems to be working well.
