### ISSUE TITLE
presentPopupBar(openPopup: true) presents popupBar first and then opens popupContent

### ISSUE THREAD

**Issue by heruvilius** [LeoNatan/LNPopupController#250]
First of all thank you for the tools. It is very handy. I am having a couple of issues with it though, and one of them I'd like to resolve here.

I am using **presentPopupBar(withContentViewController controller: UIViewController, openPopup: Bool, animated: Bool, completion: (() -> Void)? = nil)** inside a **UITabBarController** to display a **custom** popup. I need this method to display **popupContent** right away, without displaying **popupBar**. The default behaviour however is not what I need it to be: firstly, a **popupBar** is displayed, and after its animation is complete, **popupContent** is shown.

I've tried overriding the method to hide **popupBar**, then display **popupContent**, and then make **popupBar** visible back again like so:

	override func presentPopupBar(withContentViewController controller: UIViewController, openPopup: Bool, animated: Bool, completion: (() -> Void)? = nil) {
		popupBar.isHidden = true
        customBarViewController.view.isHidden = true
        super.presentPopupBar(withContentViewController: controller, openPopup: openPopup, animated: animated) {
            self.popupBar.isHidden = false
            self.customBarViewController.view.isHidden = false
            completion?()
        }
    }

However some kind of blurry frame is still visible. And its appearance is animated before **popupContent** is shown. I am running XCode 9 and target iOS version is 11.

So the question is: does **LNPopupController** support presenting **popupBar** in a way that hides it while **popupContent** is being opened for the first time? If not, is there a way to get the required behavior? Hope I've described what I need in an understandable way. Thanks for your time either way.

**Comment by iDevelopper** [comment]
Did you try to setup the popupItem properties in the completion block, example:

```
        self.presentPopupBar(withContentViewController: popContentVC, openPopup: true, animated: true) {
            popContentVC.popupItem.image = #imageLiteral(resourceName: "image")
            popContentVC.popupItem.title = "Title"
            popContentVC.popupItem.subtitle = "Subtitle"
            popContentVC.popupItem.leftBarButtonItems = [self.popupPauseButtonItem!, self.popupPlayButtonItem!, self.popupNextButtonItem!]
        }
```

**Comment by LeoNatan** [comment]
I don't think that's supported. The `openPopup:` variant is meant as a convenience method. You could try presenting with no animation, but that would, again, make it feel unnatural.

What are you attempting to do? I don't think this requirement fits LNPopupController.

**Comment by heruvilius** [comment]
@LeoNatan If I understand correctly there are two animations going on in **openPopup:** variant: first one makes **popupBar** appear from the bottom of the screen. The second one makes **popupContent** appear from the bottom of the screen. This makes me wait for **popupBar** to appear before I am able to see **popupContent**. I need to display **popupContent** right away when **presentPopupBar** is invoked. 

I thought of doing one of two things:
1. Change these animations' order (**popupContent** appears first, **popupBar** appears second, but this second animation is not visible to the user since **popupBar** coordinates are off the screen). I'm sure this is impossible without me getting under the hood of the framework. 
2. Hide **popupBar** completely until **popupContent** has been opened. But as I've mentioned in the issue description, **popupBar** is not hidden completely for some reason.

**Comment by iDevelopper** [comment]
@heruvilius , try my solution, it works!

**Comment by heruvilius** [comment]
@iDevelopper I am using **customBarViewController**. Filling labels and images with contents inside the completion block does not help: **popupBar** is still visible during animation of displaying **popupContent**.

**Comment by LeoNatan** [comment]
@heruvilius I still don't understand, if all you want to present is the popup content controller and do not want the bar, why are you using `LNPopupController` and not present your controller modally?

**Comment by heruvilius** [comment]
@LeoNatan I want the bar, but I need it to be invisible in the process of presenting and dismissing. 

Let's call my **popupContent** object **A**. When I present **popupBar** with object **A**, **popupBar** is presented, and only after that - my object **A**. 
The same happens when object **A** is presented and I invoke `dismiss:` method:  object **A** slides down into **popupBar**. And only afterwards **popupBar** is being dismissed. 

These are the only **two** situations where I **don't** need **popupBar** to be displayed: during the process of presenting object **A** for **the first time** and during the process of dismissing the **popupBar**, when I am hiding object **A for good**. 

The rest of the neat features e.g. swipe gestures, minimizing object **A** into **popupBar** (i.e. closing popup) I **do need**.

Hope I made things clearer. Please don't be mad at my poor explanation skills. =)

**Comment by LeoNatan** [comment]
Oh no no, I am not mad. 
I understand better now. I am not sure this possible. The bar position is very tightly bound to the content view position and size. So any trick with the animations will be imperfect at best.

**Comment by heruvilius** [comment]
Impossible. Got it. Thanks for the feedback, the issue can be closed now.

**Comment by LeoNatan** [comment]
Thank you.
