### ISSUE TITLE
Label is not centered correctly in prominent bar style

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#253]
#### Description

Misplacements of title if I set it to be centered. Should not it be centered relatively to the content view and not the title view?

![2018-03-27_09-47-21](https://user-images.githubusercontent.com/1782450/37954366-dce1d438-31a5-11e8-8059-45729b68921b.png)

Without image:
![2018-03-27_09-49-01](https://user-images.githubusercontent.com/1782450/37954412-fa161ac8-31a5-11e8-87ae-383d4845d2f6.png)

Compact:
![2018-03-27_10-06-31](https://user-images.githubusercontent.com/1782450/37954623-a6146f00-31a6-11e8-9486-caa3497a1925.png)

#### Steps to Reproduce
Code:
```
    @IBAction func presentPopBar(_ sender: Any) {
        guard let targetVC = self.navigationController else { return}
        
        //targetVC.popupBar.barStyle = .compact
        //popContentVC.popupItem.image = #imageLiteral(resourceName: "genre1")
        popContentVC.popupItem.title = "Hello!"
        popContentVC.popupItem.rightBarButtonItems = [self.popupCloseButtonItem!]
        popContentVC.popupItem.leftBarButtonItems = [self.popupPlayButtonItem!]
        
        let paragraphStyle = NSParagraphStyle.default.mutableCopy() as! NSMutableParagraphStyle
        paragraphStyle.alignment = .center
        targetVC.popupBar.titleTextAttributes = [NSAttributedStringKey.paragraphStyle: paragraphStyle, NSAttributedStringKey.backgroundColor: UIColor.clear, NSAttributedStringKey.foregroundColor: UIColor.red, NSAttributedStringKey.font: UIFont.systemFont(ofSize: 24)]
        
        targetVC.presentPopupBar(withContentViewController: popContentVC, animated: true, completion: {
            //
        })
    }
```

#### Device, OS and Xcode Versions
iOS 10, 11 Xcode 9

**Comment by LeoNatan** [comment]
Please open a second issue about the chevron.

**Comment by LeoNatan** [comment]
Heh, now that I think about it, it makes sense that centering is broken. The label takes the space between image and buttons.
I wonder what is a good approach to centering. No good solution I can think of.

**Comment by iDevelopper** [comment]
It is not a bug! It is a choice. I open an issue for the chevron.

> I wonder what is a good approach to centering. No good solution I can think of.

Some UILabel Styles...

**Comment by LeoNatan** [comment]
I don't think it's styling issue. I need to think.

**Comment by LeoNatan** [comment]
While this is a bug, I have decided to not to dedicate time to solve it, as there is no silver bullet here. Either some space will not be used when label is aligned to the left, causing artifacts, or the current issue will exist.

One workaround is to create button items on the right at the same width as the image on the left, which will "fix" the centering issue.
