### ISSUE TITLE
Popup progress bar doesn't show up. Even in sample app. iOS 11.2

### ISSUE THREAD

**Issue by derickito** [LeoNatan/LNPopupController#255]
#### Description

I'm running the sample app in iOS 11.2 in the Simulator and in my iPhone 7 with iOS 11.2.6 and the progress bar for the popup doesn't show up. Not sure if I'm doing something wrong. I'm assuming your supposed to set popupItem.progress correct?

#### Steps to Reproduce

1) Download the repo
2) Compile and run the sample app
3) Click on (Demo App) Apple Music
4) Click on any table cell, the popup should come up, but no progress bar on the popup
5) If you tap on the popup you'll notice that the progress bar in "music player" is progressing, but nothing in the popup
#### Device, OS and Xcode Versions

Simulator iOS 11.2
iPhone 7 iOS 11.2.6

**Comment by LeoNatan** [comment]
Hello,

As with Apple's iOS 10 and 11 apps, the progress bar is hidden by default. Set the `progressViewStyle` property to have it show up. https://github.com/LeoNatan/LNPopupController/blob/d0abfc4a2febe8358e6dcfbf36b3167bb87193b8/LNPopupController/LNPopupController/LNPopupBar.h#L124

**Comment by derickito** [comment]
Thanks. Looking through your sample code I found that I was setting the progressViewStyle on the wrong view controller.
For anyone else that may have this issue you have to set the progressViewStyle in the presenting view controller not the contentViewController
For example:
`tabBarController?.popupBar.progressViewStyle = .bottom`

**Comment by LeoNatan** [comment]
Indeed, the popup bar does not belong to the content view controller, it belongs to the presenting view controller.
