### ISSUE TITLE
Show animation

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#259]
#### Description

I don't think it is a LNPopupController issue, but a question. Do you know the reason of this weird animation?

Vidéo:

[2018-04-14_13-58-04.mp4.zip](https://github.com/LeoNatan/LNPopupController/files/1910359/2018-04-14_13-58-04.mp4.zip)

#### Steps to Reproduce

Your sample: Tab Bar Controller + Navigation Controller

#### Device, OS and Xcode Versions

xcode 9, iOS 10 & 11

**Comment by iDevelopper** [comment]
The latter one. It happens only when pushing the same class. Even so it is a new instance!

**Comment by LeoNatan** [comment]
These problems used to happen only when pushing a controller that has translucent bars disabled. Make sure this isn’t the case for you.
