### ISSUE TITLE
Labels overlapping buttons when UIBarButtonItem has custom view in it

### ISSUE THREAD

**Issue by dral3x** [LeoNatan/LNPopupController#260]
#### Description

If you use a UIBarButton with customview inside, the position of the labels are wrong and so they overlap (goes behind actually) the buttons.

From the following screenshot, the left button is the "custom" one, while the right one is a UIBarButtonItem with an image.

<img width="414" alt="screen shot 2018-04-27 at 10 42 09" src="https://user-images.githubusercontent.com/447976/39367930-79a9098a-4a38-11e8-9bf2-d3d5c4dbddc2.png">

It does not matter if you provide (via constraints) an fixed size to the custom view inside, the problem still happens.

#### Steps to Reproduce

Add 2 buttons, one with custom view (fixed size will do) and another with an image.

#### Device, OS and Xcode Versions

I just tested on iOS11 but I've the feeling is not just in this version.

**Comment by iDevelopper** [comment]
First of all, your constraints are not active:

Fix it:
```
    [fixedButton.widthAnchor constraintEqualToConstant:40].active = YES;
    [fixedButton.heightAnchor constraintEqualToConstant:40].active = YES;
```

After that, the labels do not overlap the custom button but there is no margin. We should make a leading constraint but we don't have access to the label properties.

**Comment by LeoNatan** [comment]
That should be handled by the framework. 

Can you post a screenshot with the constraints fixed?

**Comment by iDevelopper** [comment]
Before:
![2018-04-28_07-48-42](https://user-images.githubusercontent.com/1782450/39392597-f40433aa-4ab8-11e8-9ed0-30f1864188ee.png)
After activate the constraints:
![2018-04-28_07-50-12](https://user-images.githubusercontent.com/1782450/39392600-06b3b962-4ab9-11e8-89e1-2451cad96a18.png)
It remains a small overlap but less important.

**Comment by LeoNatan** [comment]
Doesn’t look good.

**Comment by dral3x** [comment]
FYI I did some debugging and it seems that the framework is not able to detect the margin the buttons's container (a UIStackView on iOS11) has with its superview. 

I was checking inside this method https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/Private/LNPopupBar.m#L626

**Comment by dral3x** [comment]
@LeoNatan have you any update on this?

Thanks

**Comment by LeoNatan** [comment]
Sorry, I have been very busy lately. I will look soon. Please don't delete your demo project.

**Comment by LeoNatan** [comment]
Fixed
