### ISSUE TITLE
PopupBar background should extend under safeArea

### ISSUE THREAD

**Issue by dral3x** [LeoNatan/LNPopupController#262]
#### Description

When I present the popup bar on "plain" controller (without tab bar), I was expecting that the background color of the popupBar went down to the edge of the screen while the content should (obviously) stay out of the safeArea.

Sadly, this is not the case

<img width="414" alt="screen shot 2018-04-27 at 10 42 09" src="https://user-images.githubusercontent.com/447976/39367930-79a9098a-4a38-11e8-9bf2-d3d5c4dbddc2.png">

The "red" color should fill the bottom part of the screen.

Of course, it makes sense only when tabbar is not present.

#### Steps to Reproduce

Run the Example project on iPhone X simulator and select the "View Controller" scene in the Gallery

#### Device, OS and Xcode Versions

iOS 11.+, iPhone X

**Comment by dral3x** [comment]
@LeoNatan Any feedback on this?

I was able to make it work in a past version of LNPopupController but not on the latest one.

Thank you

**Comment by LeoNatan** [comment]
This is a very big problem to solve in a general case.

You can solve this yourself, by placing a view in your own controller (which should be at the height of the bottom safe area guide), and have that as the bottom view of your controller.

**Comment by dral3x** [comment]
Thanks for the hint
