### ISSUE TITLE
Popupbar inserting a UIVisualEffectView as a sub view !

### ISSUE THREAD

**Issue by mahi008** [LeoNatan/LNPopupController#263]
Hello again guys,
        For a long period of time I am trying to achieve this but no success :( 
Here's my problem (Its certainly not an issue of LNP, but lack of my knowledge) I want to insert a UIVisuelEffectView as a subview of my popupbar like this

````
    func setupPopupBar(){
        self.popupBar.inheritsVisualStyleFromDockingView = false
        let blurEffect = UIBlurEffect(style: .dark)
        let blurEffectView = UIVisualEffectView(effect: blurEffect)
        self.popupBar.insertSubview(blurEffectView, at: 0)
 }
````` 
no effect, I also tried using a custom popupbar by inheriting LNPCBViewController thats didn't work.
so basically what I'm trying to accomplish is the music player like the Example project with some custom effects on my popupbar. 

Just one last question, my custom code goes into my MainViewController ? not on the presented PlayerView ?

Thank you very much in advance!

**Comment by LeoNatan** [comment]
Modifying the hiearachy of the built-in popup bar styles is not supported. 

You should create a custom popup bar. The example project includes an example with a custom bar.

**Comment by LeoNatan** [comment]
Still not sure what you are trying to accomplish. 

Just remember that a custom bar requires you to implement all layout logic if you want to make it look like music.

**Comment by iDevelopper** [comment]
What about setting a frame?

            blurEffectView.frame = self.popupBar.bounds

If self is your presenting controller.

**Comment by mahi008** [comment]
But in your example project, there are only 2 methods and one property, but i didn't find any other methods like Draw() to implement my custom views. I just wanted to copy your music player example and insert an new uivisualeffectview as a background view.
here's an exaple of custombar i tried : 

 ````
class CustomPopupBar: LNPopupCustomBarViewController {
    override var wantsDefaultPanGestureRecognizer = true

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .red
    }
}
``````
With this code, I'm supposed to have a red background ? isn't it ? but my popupbar is still white !

**Comment by LeoNatan** [comment]
I don't understand why you'd want to do that. The popup bar is already a visual effect view, and you can control all its properties, such as effect style.

**Comment by LeoNatan** [comment]
I just tried setting the background style to dark and here is the result:

![simulator screen shot - iphone 8 plus - 2018-05-10 at 21 24 53](https://user-images.githubusercontent.com/2270433/39886604-a09b5416-5498-11e8-9f80-6108c1370fd1.png)

**Comment by LeoNatan** [comment]
```objc
targetVC.popupBar.inheritsVisualStyleFromDockingView = NO;
targetVC.popupBar.backgroundStyle = UIBlurEffectStyleDark;
```

**Comment by mahi008** [comment]
![screen shot 2018-05-10 at 20 51 42](https://user-images.githubusercontent.com/3605960/39888103-2f1196b0-5494-11e8-89b2-18cc4fe3e6a5.png)
I don't know what I'm doing wrong but no luck for me :(

**Comment by iDevelopper** [comment]
@mahi008 , You can add your blurEffectView only in the completion block, when popupBar is presented. But as @LeoNatan said, there is already a visual effect view at index 0.

**Comment by LeoNatan** [comment]
You are changing the the popup bar of the incorrect controller. @mahi008

**Comment by iDevelopper** [comment]
popupContentController is not the presenting controller.

**Comment by mahi008** [comment]
Well, I tried the alternative self.popupbar to reference the popupbar of the current view controller, no success !

**Comment by LeoNatan** [comment]
It should be the same controller that you call `present` on.

**Comment by LeoNatan** [comment]
Most likely, `tabBarController.popupBar`

**Comment by mahi008** [comment]
Wow! thats the culprit! now its working perfectly. Just by curiosity what the use of the global self.popupbar for ? 

And once again 🙏 thank you so much guys for your precious time. (I promise that I will credit you guys in my first and first iOS app)  @LeoNatan @iDevelopper 😃

**Comment by LeoNatan** [comment]
Great! Happy coding!

The reason for this design is to allow general usage. Each controller has a popup item (for data) and each has a bar (for presentation). But, there is one presenting controller with a bar, but potentially many presented controllers (think each song is a new content controller); you want the bar to remain the same, while only changing the data. 

This design is the only one that makes sense to me, but people sometimes have a hard time wrapping their heads around it. Maybe the documentation can be improved to better define the roles of the presenting controller, content controller and custom bar controller.
