### ISSUE TITLE
Popup Bar Behind NavigationBar

### ISSUE THREAD

**Issue by lp2008** [LeoNatan/LNPopupController#265]
#### Description
After click the PopupBar contentViewController appear but its behind the navigation bar. I see the example the navigationBar not appear on content view controller. but when i implementing it the contentviewcontroller behind the navigation bar.
My initial view controller has navigation controller. 
![simulator screen shot - iphone 8 plus - 2018-05-16 at 15 24 03](https://user-images.githubusercontent.com/6837443/40108748-abe61bec-591d-11e8-9392-34953f617bc4.png)

![simulator screen shot - iphone 8 plus - 2018-05-16 at 15 13 06](https://user-images.githubusercontent.com/6837443/40108765-b707df56-591d-11e8-81b2-fefd84080cb4.png)

#### Device, OS and Xcode Versions
Xcode 9.3.1 iOS 11.3

**Comment by LeoNatan** [comment]
You are not presenting the popup on the correct controller. In your case, you should present on the navigation controller.

**Comment by lp2008** [comment]
I am using this code.       

 let popupContentController = ContainerVC()
        popupContentController.songTitle = "Awesome Title"
        popupContentController.albumTitle = "Awesome Subtitle"
        popupContentController.albumArt = UIImage()
        self.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: nil)
        self.popupBar.tintColor = UIColor(white: 38.0 / 255.0, alpha: 1.0)
        self.popupBar.imageView.layer.cornerRadius = 5

**Comment by LeoNatan** [comment]
`self.presentPopupBar` is your problem.
