### ISSUE TITLE
Wrong bottom offset when tab bar is translucent

### ISSUE THREAD

**Issue by tomaszpieczykolan** [LeoNatan/LNPopupController#266]
#### Description
When presenting the popup bar on `UITabBarController`, normally the content of the tab controller's view controllers is offset at the bottom by the height of the popup bar. If tab controller's tab bar has it's property `isTranslucent` set to `false`, there is no offset and the popup bar covers the content.

#### Steps to Reproduce
```
import UIKit
import LNPopupController

class RootViewController: UITabBarController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewControllers = [MainViewController()]
        
        presentPopupBar(withContentViewController: PopupViewController(), animated: true, completion: nil)
        
        tabBar.isTranslucent = false // This line causes problems
    }
}
```
`MainViewController`'s content is covered by popup bar.

#### Device, OS and Xcode Versions
I'm using my own CocoaPods fork, unmodified (besides adding podspec) and updated to the latest version of LNPopupController (2.5.16)
Reproduced on iPhone 7 running iOS 11.3
Xcode 9.3.1

**Comment by LeoNatan** [comment]
Hello

I see several problems here. First, you are presenting the popup bar on viewDidLoad, which is not advised. 
Also, you changed the bar properties after starting presentation. It is recommended to start presentation after the bar has been prepared. 

What happens if you move the

**Comment by LeoNatan** [comment]
What happens if you set `extendedLayoutIncludesOpaqueBars` of the tab bar controller’s child controllers to true?

There are known issues with non translucent bars, which I have decided is too much work to fix. Such as #184
In general, I suggest adding a background color to the bar instead.

**Comment by tomaszpieczykolan** [comment]
Setting `extendedLayoutIncludesOpaqueBars` to `true` solves my issue! Thanks!

Anyways, it would be cool if no workaround was needed, but I understand your point of view. If you feel like it's not worth working on, feel free to close this issue, but it might be good idea to mention about this in documentation.

**Comment by LeoNatan** [comment]
The thing is, Apple themselves have many bugs when bars are not translucent, be it tab bar or navigation controllers. And the internals behave so strangely, I gave up on supporting them. 

I will update the docs.

**Comment by LeoNatan** [comment]
Added a few words in the documentation, as well as a few workarounds.
