### ISSUE TITLE
Navigation Bar and Status Bar Issue

### ISSUE THREAD

**Issue by Steve-Wall** [LeoNatan/LNPopupController#267]
#### Description
After updating to current version, my app stopped working as it did before this build. Before the `contentViewController` would present perfectly but the status bar animation was not correct. With the new build I get strange behavior - the easiest way to explain is to simply watch the video:

(Basically, the presented VC is transparent now and the screen goes blurry. Also, the app freezes)

![bug](https://user-images.githubusercontent.com/38816624/40245971-1be7d62e-5a95-11e8-8c92-8aa9b001e668.gif)

#### Steps to Reproduce
In my app, I call this:
`myTabBarController.presentPopupBar(withContentViewController: myVC, openPopup: true, animated: true, completion: completion)`

#### Device, OS and Xcode Versions
iPhone 8, iOS 11.2.6, Xcode 9.3.1

**Comment by LeoNatan** [comment]
Hmm, somehow the `openPopup: true` was broken. Investigating.

**Comment by Steve-Wall** [comment]
Thank you for being so responsive! Looking forward to what you come up with : )

**Comment by LeoNatan** [comment]
Please try now 😓

**Comment by Steve-Wall** [comment]
@LeoNatan It fixed : ) And it looks awesome and feels great now!

I will continue to test and see if any bugs related to this but so far so good
