### ISSUE TITLE
viewWillAppear and viewDidAppear called twice 

### ISSUE THREAD

**Issue by Steve-Wall** [LeoNatan/LNPopupController#268]
#### Description
This is a question. Not sure if it is a bug.

In this libraries sample app using Apple Music example, when the popup is first presented, `viewWillAppear` and `viewDidAppear` are called twice.

Before testing the sample app, I made this change inside of `DemoAlbumTableViewController`. I added the parameter `openPopup: true` to:
 `tabBarController?.presentPopupBar(withContentViewController: popupContentController, openPopup: true, animated: true, completion: nil)`

So the code looks like this in the sample app after the change:
```
	override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
		let popupContentController = storyboard?.instantiateViewController(withIdentifier: "DemoMusicPlayerController") as! DemoMusicPlayerController
		popupContentController.songTitle = titles[(indexPath as NSIndexPath).row]
		popupContentController.albumTitle = subtitles[(indexPath as NSIndexPath).row]
		popupContentController.albumArt = images[(indexPath as NSIndexPath).row]
		
		popupContentController.popupItem.accessibilityHint = NSLocalizedString("Double Tap to Expand the Mini Player", comment: "")
		tabBarController?.popupContentView.popupCloseButton.accessibilityLabel = NSLocalizedString("Dismiss Now Playing Screen", comment: "")
		
		tabBarController?.presentPopupBar(withContentViewController: popupContentController, openPopup: true, animated: true, completion: nil)
		tabBarController?.popupBar.tintColor = UIColor(white: 38.0 / 255.0, alpha: 1.0)
		tabBarController?.popupBar.imageView.layer.cornerRadius = 5
		
		tableView.deselectRow(at: indexPath, animated: true)
	}
```

Here is a screenshot with `print` statements showing this:
<img width="900" alt="multiple-calls" src="https://user-images.githubusercontent.com/38816624/40270756-cf4eede4-5b60-11e8-9387-4a4a7d89e3af.png">

#### Steps to Reproduce
Call `tabBarController?.presentPopupBar(withContentViewController: popupContentController, openPopup: true, animated: true, completion: nil)` in the sample app using Apple Music example. Make sure to use the parameter `openPopup: true`.

#### Device, OS and Xcode Versions
iPhone 8, iOS 11.2.6, Xcode 9.3.1

**Comment by LeoNatan** [comment]
Doesn’t look right. 

Is this only happening when using the `openPopup:` variant?

**Comment by Steve-Wall** [comment]
Not sure, I can try it

**Comment by Steve-Wall** [comment]
@LeoNatan Yes, from my test just now, it's only happening when using the openPopup: variant

**Comment by LeoNatan** [comment]
As per your recent observations, you can see how tested that particular flow is or how widely it is used by the community. 😆

I will look into it.

**Comment by Steve-Wall** [comment]
Thank you for looking into it! I'm glad you have support for `openPopup: true` because most video apps do this - they open the small player to full player when a new selection occurs. For example YouTube, Vevo, and Apple Music (Apple Music only for videos)

**Comment by LeoNatan** [comment]
Fixed.

**Comment by Steve-Wall** [comment]
Awesome, thank you! 

This also fixed the issue I was still having here: https://github.com/LeoNatan/LNPopupController/issues/261

You're a legend : )

**Comment by LeoNatan** [comment]
Good. 
Why app are you developing?

**Comment by Steve-Wall** [comment]
I'm working on a music app (supports video also) for some friends - still haven't launched but working on that : )
