### ISSUE TITLE
Issues with UI adaptivity

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#27]
This one was introduced very recently. One of the symptoms is that UIPopoverPresentationController's adaptivity behaviour has stopped working when presented inside the popup controller.

Steps to reproduce:
Inside DemoPopupContentViewController add

```swift
- (IBAction)presentVC:(UIButton *)sender {
    UIViewController *testVC = [UIViewController new];
    UINavigationController *nc = [[UINavigationController alloc] initWithRootViewController:testVC];
    
    nc.modalPresentationStyle = UIModalPresentationPopover;
    
    UIPopoverPresentationController *popoverController = nc.popoverPresentationController;
    
    if (popoverController != nil) {
        popoverController.sourceView = sender;
        popoverController.sourceRect = sender.bounds;
        popoverController.permittedArrowDirections = UIPopoverArrowDirectionAny;
    }
    
    [self presentViewController:nc animated:YES completion:nil];
}
```

On iPad Air 2 simulator present the test view controller and change the multitasking mode to 50/50 so that the horizontal size class becomes Regular. 

Expected: the presented popover transforms to fullscreen (the screenshot was taken from an older version of the library)
Actual: the popover style remains (the recent version)

<img width="1440" alt="screen shot 2015-11-11 at 9 38 51 am" src="https://cloud.githubusercontent.com/assets/611542/11078460/30a7ed8e-885a-11e5-8f1c-f6339aac8e14.png">

<img width="1440" alt="screen shot 2015-11-11 at 9 38 23 am" src="https://cloud.githubusercontent.com/assets/611542/11078559/c5d701b0-885a-11e5-9a33-00cf740596a1.png">

**Comment by MosheBerman** [comment]
I've seen this issue in another app where I presented a view controller with the popover transition, and then activated split-screen multitasking, then rotated the device. Boom, same bug. Could be Apple's bug?

**Comment by LeoNatan** [comment]
I honk this is a bug in Apple's framework. Having adapted some of my UI to multitasking, the system is very buggy. Will close for now.

**Comment by MosheBerman** [comment]
I've solved this by implementing `willTransitionToTraitCollection:withTransitionCoordinator:`. Nothing to do with this library, but more to do with your implementation of Apple's framework code.

**Comment by Kastet** [comment]
@MosheBerman would you please explain how exactly to implement `willTransitionToTraitCollection:withTransitionCoordinator:`. `UIPopoverPresentationController` is adaptive by it's nature so I don't really get how you possible can solve it implementing the above method.
