### ISSUE TITLE
Disable swipe down gestures on pop up view controller

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#270]
I have on top screen music time scroller and every-time I want to scroll I accidentally dismiss the view. I also have a music list there and every time I reach top of the tableview my Popup VC is dismissing. So I want to turn off completely swipe gestures because they are very sensible and just use the button on top. How could I do that?

**Comment by LeoNatan** [comment]
Set the gesture recognized and implement the methods you need.

**Comment by iDevelopper** [comment]
You can disable the swipe down like this:

```
        targetVC.popupContentView.popupInteractionGestureRecognizer.delegate = self
        // ...

    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        return false
    }

```

**Comment by LeoNatan** [comment]
This will also disable the opening swipe. It should be done in smarter way, such as implementing `gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)` and returning `false`.
