### ISSUE TITLE
Custom Close Button

### ISSUE THREAD

**Issue by ggirotto** [LeoNatan/LNPopupController#271]
I've seen that its possible to set `closeButtonStyle = .round`, but it's possible to define a custom close button? I want to set my navigationbar left bar button item as the one who sends the popUpBar to compact mode, but I have not figured out how to do it, not even found a function that sends the popupbar to compact mode.

**Comment by iDevelopper** [comment]
You can set the close button style to none:
```
        targetVC.popupContentView.popupCloseButtonStyle = .none
```
And in your popupContentViewController who is embedded in a navigation controller if I understand:
```
    @IBAction func closePopup(_ sender: UIBarButtonItem) {
        self.navigationController?.popupPresentationContainer?.closePopup(animated: true, completion: nil)
    }
```

**Comment by LeoNatan** [comment]
Exactly what @iDevelopper said. The framework comes with two predefined close buttons, but all they do is call the `closePopup` method internally. So if you want a custom button, set the button style to `.none`, which means no button is provided by the framework, and roll your own. In it, call `closePopup` on your own.
