### ISSUE TITLE
Labels' frames in RTL

### ISSUE THREAD

**Issue by amosavian** [LeoNatan/LNPopupController#272]
Hi,

Labels are rendered on artwork when I set language to a right to left language.

![img_5e701a56e5c0-1](https://user-images.githubusercontent.com/6725192/40830428-ac71e750-659b-11e8-954d-4ce5e3ba4800.jpeg)

**Comment by LeoNatan** [comment]
Hi, thanks for opening this issue. I will be traveling to WWDC and will take a week of vacation after. I will look at this when I am back.

**Comment by amosavian** [comment]
@LeoNatan Hi, Any chance to get this fixed?

**Comment by LeoNatan** [comment]
I will take a look.

**Comment by amosavian** [comment]
I found the problem. Replace this line:

https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/Private/LNPopupBar.m#L708

with this code:
```objective-c
    UIUserInterfaceLayoutDirection layoutDirection = [UIView userInterfaceLayoutDirectionForSemanticContentAttribute:self.semanticContentAttribute];
    if(layoutDirection == UIUserInterfaceLayoutDirectionLeftToRight)
    {
        titleInsets->right += width;
    }

```

**Comment by amosavian** [comment]
My snippet lacks proper left (between buttons and labels) inset.

**Comment by LeoNatan** [comment]
It's more complex than that. I have already fixed it.

**Comment by amosavian** [comment]
Thanks very much, it's fixed now.
