### ISSUE TITLE
UITableViewController scrolls behind status bar if presented as popup

### ISSUE THREAD

**Issue by pdehne** [LeoNatan/LNPopupController#275]
When I present an UITableViewController using presentPopupBarWithContentViewController and scroll the table view up the scrolled up content becomes visible behind the status bar:

![iphone se - 2018-06-24 at 10 48 12](https://user-images.githubusercontent.com/1521198/41817687-56680d6e-77a0-11e8-926e-011a723a8ca3.png)

Is there a way to prevent this?

I am using Xcode 9.4, iOS 11.4 on an iPhone SE.

Many thanks!

**Comment by LeoNatan** [comment]
The presentation is full screen. Why do you have a custom bar instead of a navigation bar (in navigation controller)?

**Comment by pdehne** [comment]
Many thanks for taking a look!

I present the UITableViewController directly, so there is not custom bar. What looks like a custom bar is actually a section header of the table view controller.

You can reproduce this easily if, in your example project, in FirstViewController.m, you comment out

`UIViewController* demoVC = [DemoPopupContentViewController new];`

and uncomment

`UIViewController* demoVC = [self.storyboard instantiateViewControllerWithIdentifier:@"SettingsTableViewController"];`

The settings table view controller as the popup view controller in the example project will shows the same behaviour.

I tried a lot of things now, wrapping the table view controller in a navigation controller and hiding the navigation bar, setting edgesForExtendedLayout to UIRectEdgeNone, changing content insets and more. Nothing seems to work. Maybe its not possible to use a table view controller this way. I'll try a plain old view controller with a child table view that is positioned in the safe area next.

**Comment by LeoNatan** [comment]
If you present a table view fullscreen, you should have the same problems. If you are using `UITableViewController`, I am not sure what your options are. If you embed in a navigation controller and hide the bar, you have the same exact problem. 

If you use a `UIViewController` with a table view, you can add a `UIVisualEffectView` (or any other view to close the gap), and using auto layout, set it to have the same height as the safe area guide, and have the top anchor be equal to the safe area guide top anchor. This will create an effect similar to Apple's Maps app.

**Comment by LeoNatan** [comment]
I am closing this issue as it is not a problem with the framework, but feel free to continue the discussion.
