### ISSUE TITLE
Missing popupItem in custom popup bar view controller

### ISSUE THREAD

**Issue by tomaszpieczykolan** [LeoNatan/LNPopupController#276]
#### Description
`containingPopupBar.popupItem` is equal to `nil` in `LNPopupCustomBarViewController` subclasses.

#### Steps to Reproduce
1. Create a subclass of `LNPopupCustomBarViewController`
2. Override `popupItemDidUpdate` function to get notified when `containingPopupBar.popupItem` is updated
3. `containingPopupBar.popupItem` is always equal to `nil`

#### Device, OS and Xcode Versions
I'm using my own CocoaPods fork, unmodified (besides adding podspec) and updated to the latest version of LNPopupController (2.5.23)
Reproduced on iPhone SE simulator running iOS 11.4
Xcode 9.4.1

**Comment by LeoNatan** [comment]
Could you elaborate where the issue lies?

**Comment by LeoNatan** [comment]
Thanks for looking into it, btw!

**Comment by tomaszpieczykolan** [comment]
Please take a look at #278 

As I said before, I don't know the codebase of LNPopupController. I spent maybe an hour trying to figure out where the problem is.

This pull request fixes the issue for me.

**Comment by LeoNatan** [comment]
Thanks, I’ll take a look soon.

**Comment by LeoNatan** [comment]
This was solved by PR. Thanks @tomaszpieczykolan !
