### ISSUE TITLE
how to open childViewController on half parentViewController?

### ISSUE THREAD

**Issue by Ramiz69** [LeoNatan/LNPopupController#280]

**Comment by iDevelopper** [comment]
Which childViewController?

**Comment by Ramiz69** [comment]
I have a parent viewcontroller and I want to modally introduce a new controller to half the screen, but when I click on the parent's area, the modal controller decreases to the size I need

**Comment by LeoNatan** [comment]
I am not sure I understand the requirement. It is currently not possible to present the popup only half way.
