### ISSUE TITLE
Moving dismiss Chevron (circle) to the right side of view?

### ISSUE THREAD

**Issue by yetdog** [LeoNatan/LNPopupController#282]
#### Description
Attempting to find how to adjust positioning of Chevron. In this case, the circle stype.
The Chevron is currently positioned to the top left side. I'd like to switch to the top right.

#### Device, OS and Xcode Versions
iOS 10 & 11

**Comment by LeoNatan** [comment]
Not possible. These buttons are provided as is. You can create a custom button instead of the system-provided ones, but you will have to manage them on your own.

**Comment by LeoNatan** [comment]
If you do wish to implement the button on your own, take a look at another of my projects for a chevron: https://github.com/LeoNatan/LNChevronView

**Comment by iDevelopper** [comment]
Is this issue is relative to RTL? If so, @LeoNatan could add the missing feature, no?

**Comment by LeoNatan** [comment]
@iDevelopper RTL should already be supported as expected.

**Comment by iDevelopper** [comment]
Then this issue is not relative to RTL...

@yetdog did not provide the information.

**Comment by LeoNatan** [comment]
🤷🏻‍♂️

**Comment by LeoNatan** [comment]
Just to update 🤣 that this has been possible for a while now. There is a relatively new position property that can be set, with a leading center and trailing values to position the close button accordingly.
