### ISSUE TITLE
Navigation Items don't change properly

### ISSUE THREAD

**Issue by ggirotto** [LeoNatan/LNPopupController#283]
#### Description
Inside my app navigation flow, I've noticed that the navigation items do not change properly when trying to perform a push segue in the last part of the flow. In the last screen, it should appear only the back button, but the `cancel` and `new` buttons remain in the navigation bar. I've built an example project and recorded a video reproducing the error below.

#### Steps to Reproduce
Both project and video are attached below.

#### Device, OS and Xcode Versions
XCode 9.2, Simulator iOS 11.2, Device iOS 11.3.1

Vídeo - https://www.youtube.com/watch?v=O-Apw0pFYmI&feature=youtu.be
[PopupBug.zip](https://github.com/LeoNatan/LNPopupController/files/2217183/PopupBug.zip)

**Comment by LeoNatan** [comment]
Thanks, I will take a look.

**Comment by ggirotto** [comment]
Hi @LeoNatan. I've spent some hours investigating and I've found that when I remove the modal presentation segues from the project that I've attached above and replace them with the framework function `presentPopupBarWithContentViewController` the problem disappears. I don't know yet what is happening but it seems to be some conflict between iOS present modal segues and the framework `presentPopupBarWithContentViewController` function. I hope this helps you with the investigation. Also, I've attached the new project below if you want to take a look.
[PopupBugObjc.zip](https://github.com/LeoNatan/LNPopupController/files/2236800/PopupBugObjc.zip)

**Comment by ggirotto** [comment]
Hello again @LeoNatan. I've gone a little further and found another detail that may help in your investigation. The bug explained in the original post only happens when the modal presentation is made through segues in the storyboard. I've made a test presenting the modal view controllers through code like `navigationController.present(viewController, animated: true)` and the bug simply disappeared. I still have no idea why, but this may help.

**Comment by LeoNatan** [comment]
This seems like an Apple bug. The navigation controller seems to misbehave under the particular condition that the demo project displays. It still reproduces under Xcode 10.2/iOS 12.2 beta, so I suggest opening a bug report with Apple.

**Comment by iDevelopper** [comment]
This is not an iOS bug and this behaviour is completely normal. The last view controller is pushed by the navigation controller (show uses push in this case as the controller who show the last one is a navigation controller).

**Comment by LeoNatan** [comment]
The problem isn't that the controller is pushed, but that the navigation items remain as they are. I am not sure it's the intended behavior.

**Comment by iDevelopper** [comment]
> Declaration
@property(nonatomic, strong) UIBarButtonItem *rightBarButtonItem;
Discussion
The contents of this property always refer to the first bar button item in the rightBarButtonItems array. Assigning a new value to this property replaces the first item in the rightBarButtonItems array with the new value. Setting this property to nil removes the first item in the array. If the bar button item is already in the array, it is moved from its current location to the front of the array.

The last view controller should set its own right button item or the last one is used.
