### ISSUE TITLE
defaultFrameForBottomDockingView

### ISSUE THREAD

**Issue by yinqiangw** [LeoNatan/LNPopupController#284]
- (UIView *)bottomDockingViewForPopupBar {
    return self.containerView;
}

- (CGRect)defaultFrameForBottomDockingView {
    CGRect bottomViewFrame = self.containerView.frame;
    
    if (self.containerView.hidden) {
        bottomViewFrame.origin = CGPointMake(bottomViewFrame.origin.x, self.view.bounds.size.height);
    } else {
        bottomViewFrame.origin = CGPointMake(0, self.view.bounds.size.height - bottomViewFrame.size.height);
    }
    
    return bottomViewFrame;
}

-----------

It doesn't work

**Comment by LeoNatan** [comment]
So do you want me to guess what doesn't work?
Please use proper English to describe your problem. Attach images to display what isn't working if necessary.
