### ISSUE TITLE
Popup horizontal padding

### ISSUE THREAD

**Issue by mglal** [LeoNatan/LNPopupController#285]
Can I configure the outer padding of the Popup, for example to have right and left padding. And if it applicable to make outer shadow for it?

**Comment by LeoNatan** [comment]
This is not possible at this point. I've long wanted to implement something like that, but haven't had the time.

**Comment by LeoNatan** [comment]
Closing this issue as I don't think it is a use-case that will be implemented. It is now possible to create custom popup bar controllers with completely custom view hierarchy, and this can be achieved that way.
