### ISSUE TITLE
NSLayoutContraint Issue

### ISSUE THREAD

**Issue by allanmacatingrao** [LeoNatan/LNPopupController#286]
#### Description
NSLayoutConstraint Issue on creating custom popup bar when presenting the popup bar.

#### Steps to Reproduce
1. Create custom LNPopupCustomBarViewController
2. On Storyboard set the height of the custom controller to 100
3. Add 2 labels Top, Middle and UIview at the bottom
4. Add Constraints to each labels and uiview, top, bottom, left, right and set the hugging priority of the top label to 251, add height constraint to uiview
5. then present to popbar

#### Device, OS and Xcode Versions
iPhone, iOS 9, xcode: Version 9.4.1 (9F2000)

<img width="535" alt="screen shot 2018-08-10 at 3 24 09 pm" src="https://user-images.githubusercontent.com/4327024/43944443-7d2f2050-9cb1-11e8-91ee-43e80a2a5e6f.png">
<img width="534" alt="screen shot 2018-08-10 at 3 24 13 pm" src="https://user-images.githubusercontent.com/4327024/43944444-7da460ea-9cb1-11e8-99fd-b295924f0d1a.png">
<img width="528" alt="screen shot 2018-08-10 at 3 24 18 pm" src="https://user-images.githubusercontent.com/4327024/43944445-7de0682e-9cb1-11e8-8a06-ae73d4a50093.png">

**Comment by LeoNatan** [comment]
Could you please check with the latest version of the framework? I made some changes to how custom bar controllers are laid out.
