### ISSUE TITLE
How to listen to popupPresentationState ?

### ISSUE THREAD

**Issue by Abdulaziz1993** [LeoNatan/LNPopupController#287]

**Comment by Abdulaziz1993** [comment]
I would like to run setNavigationBarHidden(true, animated: true) when the controller opens pop up. I have searched for delegates but I see only previewingDelegate which has nothing to do with pop up. I would really appreciate your support

**Comment by LeoNatan** [comment]
There is no way currently to listen to state changes.
One workaround is to `viewWillAppear`/`viewDidAppear` of the presented controller, but that is not optimal.

I am considering some kind of callback system, but not sure yet how and where to implement.

**Comment by LeoNatan** [comment]
No hesitation, just no time to implement. I will look at it soon.

**Comment by LeoNatan** [comment]
I’m working on a solution. As usual, things got more complex than expected. I am going on a vacation and will push after that.

**Comment by cpvbruno** [comment]
Any update?

**Comment by iDevelopper** [comment]
A workaround could be to add your own targets and selectors to handle the gesture recognizers messages:
```objective-c
    [targetVC.popupContentView.popupInteractionGestureRecognizer addTarget:self action:@selector(handlePan:)];
    [targetVC.popupBar.popupOpenGestureRecognizer addTarget:self action:@selector(handleTap:)];

- (void)handlePan:(UIPanGestureRecognizer *)pgr {
    if (pgr.state == UIGestureRecognizerStateBegan) {
        LNPopupPresentationState state = self.tabBarController.popupPresentationState; // if your container VC is a tab bar controller
        BOOL hidden = state == LNPopupPresentationStateOpen ? NO : YES;
        [self.navigationController setNavigationBarHidden:hidden animated:YES];
    }
}

- (void)handleTap:(UITapGestureRecognizer *)pgr {
    [self.navigationController setNavigationBarHidden:YES animated:YES];
}
```
And a custom button to close the popup content.

**Comment by LeoNatan** [comment]
I might add a delegate for the popup controller soon, where these events will be notified. We'll see.

**Comment by LeoNatan** [comment]
Implemented. There is now a delegate, as well as the `popupPresentationState` property is now KVO compliant, so you can listen to popup state changes as you prefer.
