### ISSUE TITLE
Submitting to iTC without modifying info.plist causes an error

### ISSUE THREAD

**Issue by MosheBerman** [LeoNatan/LNPopupController#29]
I downloaded the framework as a git submodule and built my app. Then I tried uploading to iTC. I received an error about missing version keys in the info.plist. It turns out that the framework target doesn't have the required version numbers in its info.plist. I've fixed this and submitted a PR #28.

**Comment by MosheBerman** [comment]
I'll add that I don't know if you made this change intentionally or if Xcode coughed and swallowed those plist entries. I've seen Xcode 7 wipe out version numbers before.

**Comment by LeoNatan** [comment]
👍
