### ISSUE TITLE
Observer for preferredContentSize

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#290]
#### Question
What is for observing preferredContentSize keyPath change exactly? And when this method:
```
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context
```
can be fired?

**Comment by LeoNatan** [comment]
Not sure I understand the question.

`preferredContentSize` is observes by the auto layout system.

**Comment by LeoNatan** [comment]
It is fired by the system when a setter of this property is used. In the map scene demo, I only set the size once:
```
preferredContentSize = CGSize(width: -1, height: 65)
```

However, if I wanted to change the size of the popup bar, after it has been presented, that observer would fire and the framework would resize the bar as requested.
