### ISSUE TITLE
iOS 12.1 beta 2 tab bar distorted

### ISSUE THREAD

**Issue by MacMark** [LeoNatan/LNPopupController#296]
#### Description
The tab bar is broken with iOS 12.1 beta 2.

#### Steps to Reproduce
Use iOS 12.1 beta 2 and run the LNPopupController demo project.

#### Device, OS and Xcode Versions
iPhone X, iOS 12.1 beta 2, Xcode 10.1 beta 2.

![screen shot 2018-10-08 at 15 58 02](https://user-images.githubusercontent.com/626963/46613313-37748380-cb13-11e8-9057-26b0348f8013.png)
 
![screen shot 2018-10-08 at 16 01 01](https://user-images.githubusercontent.com/626963/46613431-83bfc380-cb13-11e8-96dc-4c8a6d582890.png)

**Comment by LeoNatan** [comment]
Already fixed in master.

**Comment by MacMark** [comment]
Thanks Leo :-)

**Comment by LeoNatan** [comment]
Happy coding! I will release a new version soon.

**Comment by MacMark** [comment]
Good to hear. Great tool by the way. Love it.
