### ISSUE TITLE
Semantic issue when compile on Xcode 10.0

### ISSUE THREAD

**Issue by codemonza** [LeoNatan/LNPopupController#297]
#### Description
On Xcode 10.0, errors when compiling. 
Semantic Issue
../LNPopupController/LNPopupController/Private/MarqueeLabel.m:1311:1: Implementing deprecated method
../LNPopupController/LNPopupController/Private/MarqueeLabel.m:1344:1: Implementing deprecated method

@property(nonatomic) CGFloat minimumFontSize NS_DEPRECATED_IOS(2_0, 6_0) __TVOS_PROHIBITED; // deprecated - use minimumScaleFactor. default is 0.0
@property(nonatomic) BOOL adjustsLetterSpacingToFitWidth NS_DEPRECATED_IOS(6_0,7_0) __TVOS_PROHIBITED;

#### Steps to Reproduce
On Xcode 10.0, compile & run

#### Device, OS and Xcode Versions
Device: Macbook Pro
OS: High Sierra
Xcode: 10.0

**Comment by LeoNatan** [comment]
Don't update the project or take the latest commit.
