### ISSUE TITLE
Compile errors occurred when using xcode 6.4

### ISSUE THREAD

**Issue by waniwang** [LeoNatan/LNPopupController#3]
Should I use xcode7?
<img width="643" alt="2015-08-28 2 56 25" src="https://cloud.githubusercontent.com/assets/2967208/9540775/bda27b24-4d94-11e5-8fa2-6fba41732cc7.png">

**Comment by LeoNatan** [comment]
Hi,

As stated in the Readme, the demo project is only compatible with Xcode 7. The framework itself should compile on Xcode 6. 

Thanks

**Comment by waniwang** [comment]
Thanks!
