### ISSUE TITLE
Change player to minified state via code

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#30]
I would like to press a button in the player view and then put the player into minified state. Exactly the same what the dismiss chevron button in the upper left of the example does. How can I call this from my own code?

**Comment by LeoNatan** [comment]
Did you take a look at the header file?

You have ```- (void)closePopupAnimated:(BOOL)animated completion:(nullable void(^)())completion;``` exactly for this purpose.

**Comment by funkenstrahlen** [comment]
I am sorry, I should have read through the manual before.
