### ISSUE TITLE
UITabBar Icons Attach to Animating LNPopupBar

### ISSUE THREAD

**Issue by gulabry** [LeoNatan/LNPopupController#303]
#### Description

The icons on a UITabBarController are animating up when you first show a LNPopupBar. This issue exists only on iOS 12.1

#### Steps to Reproduce
Have a UITabBarController with custom icons and then show a LNPopBar above it. When the bar animates into the view, the tab bar icons follow it.

#### iOS 12.1
<img width="443" alt="screen shot 2018-10-31 at 4 10 16 pm" src="https://user-images.githubusercontent.com/5587644/47824559-c310b700-dd43-11e8-8e7f-0349dd86d33c.png">

#### iOS 12.0
<img width="463" alt="screen shot 2018-10-31 at 4 10 21 pm" src="https://user-images.githubusercontent.com/5587644/47824565-cb68f200-dd43-11e8-8c91-daff0c0608c0.png">

#### Device, OS and Xcode Versions
iOS 12.1
Xcode 10 & 10.1

**Comment by LeoNatan** [comment]
Please use search.

**Comment by iDevelopper** [comment]
@gulabry , see #302 !
