### ISSUE TITLE
iOS 12.1 CollectionView bottom inset

### ISSUE THREAD

**Issue by ahmedraad** [LeoNatan/LNPopupController#304]
I've notices when update xcode to 10.1, when LNPopupBar is presented the uicollectionview cells still behind the bar, which means bottom inset didn't changed

![screen shot 2018-11-01 at 10 50 57 am](https://user-images.githubusercontent.com/17860965/47839521-0dd21380-ddc4-11e8-91e7-1a6722bdbd5d.png)

iOS 12.1
Xcode 10.1
Swift 4.2

**Comment by LeoNatan** [comment]
Can you attach a sample project?

**Comment by LeoNatan** [comment]
Seems like you are using an old version. Please update to the latest version. If you think you are running the latest version, see #302 for more information on Carthage bug that prevented updating.

**Comment by ahmedraad** [comment]
Yeah, it works now after updating, thanks
