### ISSUE TITLE
Crash on startup on iOS 11 

### ISSUE THREAD

**Issue by johnswifttt** [LeoNatan/LNPopupController#305]
#### Description
I launch your example app `LNPopupControllerExample` from Xcode and the app crashes upon starting. This also happens to my own app. Please see other comment for images of the crash.

#### Steps to Reproduce
Launch your example app `LNPopupControllerExample` on iOS 11.

#### Device, OS and Xcode Versions
iPhone 8 (11.0.1) Simulator
iOS 11
Xcode 10.1
LNPopupController 2.5.26

**Comment by johnswifttt** [comment]
Picture of crash: 
![crash](https://user-images.githubusercontent.com/10701375/47937623-b1e8b700-deb7-11e8-814b-d6530beec742.png)

**Comment by LeoNatan** [comment]
Oh no. I’ll fix this as soon as possible. Please use the previous version until then.

**Comment by johnswifttt** [comment]
@LeoNatan Thank you for quick response!! What version would you suggest using? Also how do I revert back to an old version using Carthage?

**Comment by LeoNatan** [comment]
Released a new version with a fix. Just update to the latest version.

**Comment by johnswifttt** [comment]
It works!

Just want to thank you for this library and for your commitment to constantly updating it. Awesome work, truly!!!

**Comment by LeoNatan** [comment]
Cheers, happy coding!
