### ISSUE TITLE
Apple close match

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#308]
Hi @LeoNatan ,

Do you intend to modify your framework so that the user interface resembles that of Apple's music application?

I would try to do this. What about to use some parts of your code?

Regards,

**Comment by LeoNatan** [comment]
?

**Comment by iDevelopper** [comment]
Sorry, updated.

**Comment by LeoNatan** [comment]
What is missing currently?

**Comment by iDevelopper** [comment]
The deck presentation for example.

**Comment by iDevelopper** [comment]
The image animation from the popup bar to the final position.

**Comment by LeoNatan** [comment]
That’s something that has been asked many times before. It’s not possible currently and would require a lot of changes. 

Another one that I started work on but haven’t had time to finish is interactive transitions. 

What else have you seen that so not matching?

**Comment by LeoNatan** [comment]
#143 #211 #225

**Comment by iDevelopper** [comment]
Just would like to do that (I have a advanced project) using some parts of your code for the safe area insets! Then the project is written in Swift and Obj C for your nice work!
