### ISSUE TITLE
Crash on startup, iOS 10

### ISSUE THREAD

**Issue by wiencheck** [LeoNatan/LNPopupController#309]
App works fine on iOS 12, but on iOS 10 I get crash at app launch, XCode shows this line:
<img width="1418" alt="zrzut ekranu 2018-11-10 o 08 32 18" src="https://user-images.githubusercontent.com/25985996/48298772-309ab100-e4c3-11e8-9339-d7db3236c629.png">

Error log:
```
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb) 
```

I'm using the newest, 2.6.4 version

**Comment by wiencheck** [comment]
I have just downgraded the framework to 2.5.27 and the crash is gone, so there is definitely some nasty bug in newest version.

**Comment by LeoNatan** [comment]
Yes, that's a good idea. I will look at this today. Thanks

**Comment by iDevelopper** [comment]
additionalSafeAreaInsets property does not exist for iOS < 11!

**Comment by LeoNatan** [comment]
Fixed.
