### ISSUE TITLE
Title in popup item not aligned correctly when RTL

### ISSUE THREAD

**Issue by RazeeHJ** [LeoNatan/LNPopupController#311]
The title and subtitle text is not aligned correctly when using RTL support. Are there any changes I need to do ?  I would like to see the title and subtitle starting from right side, the label starts there however the alignment is not correct.
![screen shot 2018-12-20 at 10 38 57 am 3](https://user-images.githubusercontent.com/6938201/50270703-8a3bb700-0443-11e9-94d1-0e566f8126b4.png)

**Comment by LeoNatan** [comment]
Can you please edit the photo to show how you expect it to look?

Also, play around with `semanticContentAttribute` and `barItemsSemanticContentAttribute` if the pop up bar.

**Comment by RazeeHJ** [comment]
I want to see this:
![screen shot 2018-12-20 at 10 38 57 am 3](https://user-images.githubusercontent.com/6938201/50273258-3e8d0b80-044b-11e9-8005-57e9523b88ab.png)

And this is my configuration:

tabBarController?.popupBar.semanticContentAttribute = .forceRightToLeft
tabBarController?.popupBar.barItemsSemanticContentAttribute = .forceRightToLeft

**Comment by LeoNatan** [comment]
I will test later to see if something broke.

**Comment by RazeeHJ** [comment]
In this image you can see that the title label position is correct but the alignment of the text is not setup correctly. It should start from right
![screen shot 2018-12-20 at 11 38 41 am 3](https://user-images.githubusercontent.com/6938201/50273489-e4d91100-044b-11e9-8584-6d9934932dfe.png)

**Comment by LeoNatan** [comment]
OK, I made some changes. I'll release a new version.

**Comment by LeoNatan** [comment]
Try with 2.7.1
