### ISSUE TITLE
Subtitle alignment issue on XS Max

### ISSUE THREAD

**Issue by RazeeHJ** [LeoNatan/LNPopupController#313]
There is an issue with the alignment of the subtitle when pop up bar is open, this problem is only on iPhone XS Max
<img width="376" alt="screen shot 2018-12-31 at 7 26 09 pm" src="https://user-images.githubusercontent.com/6938201/50563957-375edb00-0d32-11e9-8d96-52166d69307d.png">

**Comment by iDevelopper** [comment]
I think you will have to elaborate a bit!

**Comment by RazeeHJ** [comment]
As you can see on the image the Subtitle is covered under the arrow when the view is popped up. But when I run on an iphone the alignment is correct as you can see on the attached view.
<img width="363" alt="screen shot 2018-12-31 at 9 11 58 pm" src="https://user-images.githubusercontent.com/6938201/50565524-cd99fd80-0d40-11e9-9aa6-6d8db2a9f848.png">

**Comment by LeoNatan** [comment]
What is this "subtitle"? Is this a view that you have added to the content view controller? If so, how have you set up its constraints?

**Comment by RazeeHJ** [comment]
It is from the library: popupItem.subtitle

**Comment by LeoNatan** [comment]
I don't understand what you are saying. The subtitle appears in the popup bar, not under the close button in the content view.

**Comment by RazeeHJ** [comment]
Problem solved, it was a mistake from my side

**Comment by LeoNatan** [comment]
👍
