### ISSUE TITLE
uncaught exception  error occur 

### ISSUE THREAD

**Issue by tariqul000** [LeoNatan/LNPopupController#314]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[/LNPopupController.DemoMusicPlayerController popupItem]: unrecognized selector sent to instance 0x101f6b4c0'
 when i test in simulator no error found but when i run project in iphone it will make crash

**Comment by LeoNatan** [comment]
I need more context. How are you running? How are you integrating into you project?

**Comment by tariqul000** [comment]
Thanks for your quick response, I can solve that this issue with your library  include in my project, fast time I only include LNPopupController.framework but it also need to drag and drop LNPopupController.xcodeproj file and then add LNPopupController.framework and it will work.
