### ISSUE TITLE
Dynamically changing the height doesn't change the height of the docking view

### ISSUE THREAD

**Issue by KristofColpaert** [LeoNatan/LNPopupController#316]
Hi! Thanks for the great work you're doing with this library.

I've seen you've added a way to change the height of the popupBar dynamically in code ([issue 161](https://github.com/LeoNatan/LNPopupController/issues/161)). This indeed changes the height of the popupBar, but it doesn't change the height of the docking view that pushes up the actual ViewController. 

Any ideas how to resize the popupBar as well as the docking view that pushes up the ViewController? 

Thanks, 

Kristof

**Comment by LeoNatan** [comment]
Hello
Could you please elaborate what you mean by "doesn't change the height of the docking view"

Could you please provide a screenshot with an explanation what you are seeing vs. what you expect to see?

Thanks

**Comment by LeoNatan** [comment]
Ping

**Comment by KristofColpaert** [comment]
We've solved the issue by dismissing the popup controller instead of hiding it trough a different preferredContentSize.

**Comment by iDevelopper** [comment]
I did not quite understand the question but I can notice that when we change the height of the custom popup bar (while the rotation for example in viewWillTransitionToSize), the safe area is not updated. Also, viewWillTransition is not called in LNPopupCustomBarViewController subclass itself.

**Comment by LeoNatan** [comment]
@iDevelopper Could you please open an issue and attach a demo project that demonstrates this?

**Comment by iDevelopper** [comment]
Done. #319
