### ISSUE TITLE
How to set an image on albumArt from API call a url

### ISSUE THREAD

**Issue by RazeeHJ** [LeoNatan/LNPopupController#317]
I wonder how I can set my albumArt with an image from an api call a url string basically?

**Comment by LeoNatan** [comment]
Something like SDWebImage provides a block-based callback API, where your callback is called several times, depending on image cache and placeholder.

**Comment by RazeeHJ** [comment]
I am using sdwebImage for other purposes but wasn't sure if it would work with this albumartwork

**Comment by LeoNatan** [comment]
It would, but don't use the UIImageView extension. Instead, use their URL-based API and update the popup item.

**Comment by RazeeHJ** [comment]
> It would, but don't use the UIImageView extension. Instead, use their URL-based API and update the popup item.

Works perfectly good, thank you
