### ISSUE TITLE
Dynamically changing the custom popup bar height safe area issue

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#319]
#### Description
When we change the height of the custom popup bar (while the rotation for example in viewWillTransitionToSize), the safe area is not updated.

Also, viewWillTransition is not called in LNPopupCustomBarViewController subclass itself.

#### Steps to Reproduce
https://github.com/iDevelopper/LNPopupControllerExample

In Maps example. I added a bottom label and change the height on rotation.

**Comment by LeoNatan** [comment]
Thanks

**Comment by LeoNatan** [comment]
Fixed:

![gif](https://user-images.githubusercontent.com/2270433/54911149-8150fa80-4ef6-11e9-92ea-7d402e46f17a.gif)

`-willTransitionToTraitCollection:withTransitionCoordinator:` and `-viewWillTransitionToSize:withTransitionCoordinator:` are both called correctly. Setting the size there like so works correctly:

```swift
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
	super.viewWillTransition(to: size, with: coordinator)
	
	coordinator.animate(alongsideTransition: { [unowned self] context in
		self.preferredContentSize = CGSize(width: -1, height: self.traitCollection.horizontalSizeClass == .regular ? 100 : 65)
	}, completion: nil)
}
```

**Comment by LeoNatan** [comment]
Also fixed an issue where safe area insets were not maintained correctly.

**Comment by LeoNatan** [comment]
v2.7.2 is out with a fix for this.
