### ISSUE TITLE
How to show popup bar on the UITabbar inside UIViewcontroller?

### ISSUE THREAD

**Issue by satyzkmr** [LeoNatan/LNPopupController#32]
![img_1626](https://cloud.githubusercontent.com/assets/4285172/12199716/684aef52-b640-11e5-81a1-aeaba651a089.jpg)
![img_1627](https://cloud.githubusercontent.com/assets/4285172/12199717/6876834c-b640-11e5-91f8-51d9fa69aded.jpg)
How to pass the bottomdock view and frame?

**Comment by LeoNatan** [comment]
I don't understand what you want here; why are you constantly changing the title?

**Comment by satyzkmr** [comment]
Sorry for doing that, I need to show popup bar over UITabbar which is inside UIViewcontroller. When I did that the bottom layout is corrected automatically

**Comment by LeoNatan** [comment]
Use UITabBarController

**Comment by satyzkmr** [comment]
Can we achieve this without using UITabBarController?

**Comment by LeoNatan** [comment]
Yes. Did you read the documentation? Specifically, the *Popup Container View Controllers* section.
