### ISSUE TITLE
State restoration in LNPopupController

### ISSUE THREAD

**Issue by markotl88** [LeoNatan/LNPopupController#320]
Hello Leo,
Is it somehow possible to preserve popBar's **_contentViewController_ state,** when _contentViewController_ is presented with method 
`- (void)presentPopupBarWithContentViewController:(UIViewController*)controller openPopup:(BOOL)openPopup animated:(BOOL)animated completion:(nullable void(^)(void))completion;
`
##### Description
```
let playerViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: String(describing: PodcastPlayerViewController.self)) as? PodcastPlayerViewController
tabBarController.presentPopupBar(withContentViewController: playerViewController, animated: true, completion: nil)
```
tabBarController and playerViewController have their restoration identifiers set, everything is ok if use `tabBarController.present(playerViewController, animated: true, completion: nil)`
but is it possible to set restorationIdentifier to LNPopupController somehow?

**Comment by LeoNatan** [comment]
Out of scope and will probably not implement this.
If you want to restore state, I suggest you track this manually in your app and perform the steps to restore (such as presenting the popup bar and/or opening the popup).
