### ISSUE TITLE
How to Dismiss popup View Controller?

### ISSUE THREAD

**Issue by yarodevuci** [LeoNatan/LNPopupController#323]
I have tried:

 self.closePopup(animated: true, completion: nil)
self.dismissPopupBar(animated: true, completion: nil)
            
navigationController?.closePopup(animated: true, completion: nil)

Nothing works.. Any idea?

**Comment by yarodevuci** [comment]
Worked for me
popupPresentationContainer?.dismissPopupBar(animated: true, completion: nil)

**Comment by LeoNatan** [comment]
You call `dismissPopupBar` on the presenting controller.
