### ISSUE TITLE
Darken background while opening popup view 

### ISSUE THREAD

**Issue by dohait** [LeoNatan/LNPopupController#325]
#### Description
Hi! First of all thanks for your great framework. 

I am new to Objective C. Is there a way to darken the background while opening the popup view and make it clear again when it closes to the popup bar? 

#### Device, OS and Xcode Versions
Does not matter.

**Comment by LeoNatan** [comment]
Hello,

This is not possible right now. I think this is a future PR by @coolstar

(I will be reviewing the other PR soon, I promise!)

**Comment by dohait** [comment]
Is there a workaround? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDevelopper** [comment]
There is my fork.

**Comment by LeoNatan** [comment]
This will be implemented in 3.0.

**Comment by LeoNatan** [comment]
Closing in favor of #348.
