### ISSUE TITLE
How to Turn Off Automatic Bottom Adjustment

### ISSUE THREAD

**Issue by johnswifttt** [LeoNatan/LNPopupController#327]
#### Description
How do I turn off the automatic bottom adjustment (bottom layout)? I have a collectionView that is full screen and when I present the popupBar, the collectionView animates up to make space for the popupBar automatically. I don't want the collectionView to move up. In this case, I want the popupBar to simply go over my collectionView. 

I look at your documentation but I could find was this:
> The framework attempts to correct the top and bottom layout guides of the container controller and its child controllers as the popup bar is presented and dismissed.

#### Device, OS and Xcode Versions
iOS 12.1
Xcode 10.1
Swift 4.0

**Comment by LeoNatan** [comment]
Can't you change the `contentInsetAdjustmentBehavior` property of the scrollview to be `UIScrollViewContentInsetAdjustmentNever`?

**Comment by johnswifttt** [comment]
Thanks for reply! @LeoNatan 

I just tried `collectionView.contentInsetAdjustmentBehavior = .never` like you suggested but it doesn't work. The entire view still shifts when the popupBar is presented/dismissed. Please see below for what exactly I'm doing.

This is how I set `contentInsetAdjustmentBehavior`:
```
override func viewDidLoad() {
     super.viewDidLoad()
        
     collectionView.contentInsetAdjustmentBehavior = .never
}
```

This is how I size the collectionView cell. I have two different options. Depending on the option, the cell size is incorrect after dismissing the 
```
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
    // Option 1: After popup dismisses, the size of the cell is incorrect.
    return CGSize(width: collectionView.frame.width, height: collectionView.frame.height)
    
    // Option 2: After popup dismisses, the size of the cell is correct.
    return CGSize(width: view.frame.width, height: view.frame.height)
}
```

This is my Storyboard layout:
<img width="782" alt="Screen Shot 2019-03-14 at 11 58 21 AM" src="https://user-images.githubusercontent.com/10701375/54371936-acaf2c00-4650-11e9-8c09-34398a170e9e.png">

**Comment by LeoNatan** [comment]
Ah I see, you are layout out the collection view against the safe area. There is no way to disable that. You should lay your collection view out against the super view, and then the `contentInsetAdjustmentBehavior` should work.

**Comment by johnswifttt** [comment]
Interesting, that works. It seems that anything that is pinned to the bottom safe area is animated/moved with the popupBar. 

I just ran a new test with your suggestion:
1. I pinned the `collectionView` to the super view.
2. I pinned the `image` to the super view 
3. **I pinned `MY BUTTON` to the bottom safe area.**

The only one that now animates.moves when the popupBar is presented/dismissed is 3. `MY BUTTON`. Everything else stays put.

<img width="911" alt="Screen Shot 2019-03-14 at 12 27 30 PM" src="https://user-images.githubusercontent.com/10701375/54374115-d5392500-4654-11e9-8df1-38b60de57993.png">

**Comment by johnswifttt** [comment]
Thank you for helping. Last question, is there a way to shut off this behavior? @LeoNatan

**Comment by LeoNatan** [comment]
No such setting. The whole point of the safe area guide/margin is that it tells the layout system where it is safe to put important elements. Your "My Button" is laid against the safe area, meaning you want it to be placed where it is safe to put content. When the popup bar appears, that safe area is extended to include the bar's height.

BTW, if you are making changes following my recommendation, I strongly suggest you thoroughly check your app, especially on iPhone XS/XS Max devices, in both portrait and landscape.

**Comment by LeoNatan** [comment]
Closing the issue as it seems to have been resolved. But we can keep the discussion.
