### ISSUE TITLE
Closing popup Programmatically causes layout of popupBar to break

### ISSUE THREAD

**Issue by wiencheck** [LeoNatan/LNPopupController#328]
I attached a video of this issue, the first time I'm closing the view by dragging it down, second time is done programmatically by calling
`containerController?.closePopup(animated: animated, completion: nil)`

Container controller is the one with popupBar, but it's taking full screen so I don't think it's the issue

https://gfycat.com/LongNeighboringFlyingsquirrel

**Comment by LeoNatan** [comment]
Hello

How are you presenting the popup bar? What is the bottom docking view? I would like to reproduce this.

**Comment by LeoNatan** [comment]
Not able to reproduce this in the demo project. I've seen issues related to layout when some constraints are used, but I don't remember the specific configuration. If you are able, please provide a demo project, or a detailed description on how to reproduce the issue.

**Comment by LeoNatan** [comment]
Ping
