### ISSUE TITLE
iPhone XS bottom spacing

### ISSUE THREAD

**Issue by ggirotto** [LeoNatan/LNPopupController#329]
#### Description
Extra bottom spacing at iPhone XS when not using with TabBar

#### Steps to Reproduce
Just present a VC using the LNPopupController framework in iPhone XS
A project reproducing the bug is attached
[LNPopupBug.zip](https://github.com/LeoNatan/LNPopupController/files/3005034/LNPopupBug.zip)
Such as a image showing the bug

![IMG_1327](https://user-images.githubusercontent.com/11745745/54946633-4c08d480-4f17-11e9-88d8-7096f74b422a.png)

#### Device, OS and Xcode Versions
Latest iOS and XCode versions

**Comment by LeoNatan** [comment]
Hello,

This is not a bug, the system is behaving as expected. If you wish to cover this, you should either define a bottom docking view (with the appropriate frame), or add a view and constraint its height to the safe area  layout guide's bottom.

You can see an example of the above in the maps example in the example project.
