### ISSUE TITLE
Info.plist is missing CFBundleShortVersionString

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#33]
I can not submit an app using LNPopupController via Carthage as it is missing the `CFBundleShortVersionString` in `Info.plist` of LNPopupController.

![screen shot 2016-01-09 at 11 53 03](https://cloud.githubusercontent.com/assets/144173/12215692/a29e1e68-b6c7-11e5-93e2-3386553ca87d.png)

How can I fix that? Is this an error on my side or can this be done via the Carthage package automatically so it is fixed for everyone using this?

**Comment by funkenstrahlen** [comment]
I just realised there is a newer version that might fix the problem according to commits. Will test that now.

**Comment by funkenstrahlen** [comment]
Looks like this is fixed in the repo here already but not released as a new version yet.

**Comment by LeoNatan** [comment]
Done.

**Comment by funkenstrahlen** [comment]
Thanks a lot!
