### ISSUE TITLE
cocoapods pod

### ISSUE THREAD

**Issue by retrokid** [LeoNatan/LNPopupController#330]
#### Description

there is a cocoapod at this link:

https://cocoapods.org/pods/LNPopupController

i installed via that link and it always crashed whenever i call .popupItem.title
or self.tabBarController?.presentPopupBar(withContentViewController 

after that i remove pod and i use manual installation as described in readme.md and now it works.

I just want you to know that pod is not working. At least not for me.

#### Device, OS and Xcode Versions

xcode 10.1 - swift 4 - iphone se ios 12.1.4

**Comment by LeoNatan** [comment]
Hello,

As [explained in the readme](https://github.com/LeoNatan/LNPopupController#cocoapods), CocoaPods is not supported. It has never been supported, so that pod is not official.

Please use the official methods described in the readme.

Thanks
