### ISSUE TITLE
Dismissing popupController is causing cellForItemAt to be called?

### ISSUE THREAD

**Issue by JayceBryce** [LeoNatan/LNPopupController#332]
#### Description
This is a very weird issue and might be something I'm doing wrong. When I have the popUp bar present in its lowered state I have a close button which I can tap and it dismisses. The issue is when I tap the close button while present in a view controller with a collection view for some reason cellForItemAt gets called and my cells load again? It's almost like I'm calling reloadData but I am not. I tried looking at the call stack and can't seem to understand why this is happening? 

#### Device, OS and Xcode Versions
I'm using simulator with devices 11.0 and up

**Comment by LeoNatan** [comment]
Can you upload an example project? I think this is by design by Apple, but want to make sure. Thanks

**Comment by LeoNatan** [comment]
Thinking about it, it is by design. When you hide the bar, the collection view gets notified of additional space available at the bottom, and it asks it’s delegate for more cells. Try printing the indices of the cells it asks for.

**Comment by JayceBryce** [comment]
Thanks for the response. Is there a way we can stop this from happening? Basically when I close the popupBar my collection view "scrolls" to a random cell which is really weird and not suppose to happen.

**Comment by Enatalicio** [comment]
@LeoNatan Just following up on this issue. Thanks

**Comment by JayceBryce** [comment]
@LeoNatan Just checking in to see if you had a chance to take a look?

**Comment by LeoNatan** [comment]
I'm not sure if there is something to look. I suspect you have some logic that invalidates the entire collection layout when the safe area changes. While I don't have collection views in my example project, there is a table view, which should behave similarly. You can see that no scrolling happens when the bar appears and disappears.

**Comment by JayceBryce** [comment]
@LeoNatan Thanks for explanation, however the issue still persists. When I open the popupBar or dismiss the popupBar, my collectionView's `cellForItem` is called at times. I set some breakpoints to see why. Please see this screenshot with the call stack below:

<img width="1677" alt="cellForItem" src="https://user-images.githubusercontent.com/37093552/55908738-37c80700-5ba8-11e9-88a8-a4f8ee1227c6.png">

From the picture, it shows that `LNPopupController` is in fact doing something to make my collectionView call `cellForItem`. This shouldn't happen.

How can I prevent this from happening?

**Comment by JayceBryce** [comment]
@LeoNatan ^^^ Please see above, Thanks!

**Comment by LeoNatan** [comment]
I am not sure what you want me to look at. In the "reason" screenshot above, I am laying out the view. The system has decided to fill its cache with more cells. I explained why this is happening above. I asked you to log which index paths are requested in `cellForItemAtIndexPath:`.

**Comment by JayceBryce** [comment]
Thanks for the response. We have a total of 4 collection view cells. When we close the bar the issue occurs when the cells seem to scroll and the index paths that always print is this: 

`[0, 0]
  [0, 1]`

@LeoNatan

**Comment by LeoNatan** [comment]
What do you mean scroll? You mean jump around?
Can you create a sample project with the behavior showing and upload here?

**Comment by JayceBryce** [comment]
### Sample Project
@LeoNatan Great suggestion! I decided to use your sample project. It seems I have replicated what is occurring in my app. Basically, `cellForRowAt` is called after closing the popup bar in the Music Player sample.  

### Overview:
Below, please see the following:
1. A picture of `cellForRowAt` being called after dismissing the popup bar
2. How to replicate this behavior

#### 1. A picture of `cellForRowAt` being called after dismissing the popup bar
![Screen_Shot_2019-04-15_at_2_27_33_PM](https://user-images.githubusercontent.com/37093552/56157173-d8456f00-5f8c-11e9-822a-160df08aca57.png)

#### 2. How to replicate this behavior
These are the steps:
1. Make any button in the popup bar dismiss the popup bar when tapped. So in `DemoMusicPlayerController`, I made the pause button actually dismiss the popup bar like so:
```
let pause = UIBarButtonItem(image: UIImage(named: "pause"), style: .plain, target: self, action: #selector(DemoMusicPlayerController.didTapCloseButton(_:)))

@objc func didTapCloseButton(_ sender: UIBarButtonItem) {
    popupPresentationContainer?.dismissPopupBar(animated: true, completion: nil)
}
```

2. Launch the app, and select Apple Music (Demo App) example. 
3. Select a cell so that the popup bar opens. Leave the popup bar small.
4. Scroll all the way to the bottom of the table view. 
5. Tap the pause button (which now closes the popup by calling `dismissPopupBar ` as shown above).
6. `cellForRowAt` is now called inside of `DemoAlbumTableViewController`. Set a breakpoint to see this.

### Summary

In my project I have a collection view with paging enabled. So every cell takes up the entire screen and you page between cells. When the behavior described above occurs in my app, the collection view changes cells automatically (it seems to scroll) without the user doing anything. Simply by dismissing the popup bar, my collection view changes cells and this is visible to the user which isn't ideal. Ultimately, when the popup bar is closed, I want my collection view to not do anything in terms of changing cells (scrolling to a different cell)-- it should not change at all.

Does this clarify the issue I'm having? Please let me know your thoughts on this

**Comment by JayceBryce** [comment]
@LeoNatan Looking forward to hearing your thoughts on above ^ --- thank you!

**Comment by LeoNatan** [comment]
There is no need for these bumps. I will look at it when I have time. Please.

**Comment by JayceBryce** [comment]
![Screen_Shot_2019-04-20_at_1_33_50_PM-2](https://user-images.githubusercontent.com/37093552/56460474-41542a80-6371-11e9-94e1-ad3a814580cc.png)

I tried looking into this more, to see why in my app, my collection view scrolls when I either open/close the popup bar. It seems that my `scrollViewDidScroll` is called which means that the collection view scrolled after I open the popup bar. Interesting, not sure why that is. 

Hopefully, you can look into this soon - we really want to launch a feature. I'm doing all I can to look into this but it's hard to figure out 😓

**Comment by LeoNatan** [comment]
I looked at the demo project and it behaves exactly as intended by the system.

When the bar hides, it reduces the controller's safe area, which in turn updates the [adjustedContentInset](https://developer.apple.com/documentation/uikit/uiscrollview/2902259-adjustedcontentinset?language=objc), which causes the table view to scroll down, which in turn asks for a cell. This is what you are seeing in the demo project. It looks to me like you don't understand how safe area works and how it influences scroll views. This is not the place to learn that. I suggest starting with WWDC 2017 and 2018 videos.

You said that your collection view is jumping around. This doesn't happen in the example table view, nor a quick example I ran with a `UICollectionViewController`. As before, the safe area is updated, which causes the scroll view to relayout, and in the case of a table and collection views, to refill the new space with more content, which is a call to the delegate for items.

At no point did you say why this is bothering you. `cellForItemAtIndexPath:` is intended to be called multiple times by the system, and thus should be very quick to set up a cell. If you have side-effects in that method, which cause performance or other issues, you should work to improve your code.

**Comment by LeoNatan** [comment]
If you must, you can set the scroll view's `contentInsetAdjustmentBehavior` to `.never`, which will stop safe area adjustment from influencing the scroll view, but that will most likely break your UI, so I absolutely discourage you from doing it.
