### ISSUE TITLE
iOS 9, 10 support has been dropped in 2.9.0+

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#335]
Hi guys,

I am planning to clean up the code and drop support for 9, 10. I will create a stabilized version with iOS 13 support, and that will be the last to support legacy OSes.

After that, I plan to clean the code from legacy and maybe rewrite some of the presentation stuff as time permits.

**Comment by coolstar** [comment]
Don't forget we should merge #321 first :P

**Comment by LeoNatan** [comment]
I haven’t forgotten. I am thinking how to make it more generalized to any docking view.

**Comment by djmixroman** [comment]
Maybe it makes sense to merge the changes of the @coolstar before drop down the support of iOS 9 and 10?

**Comment by LeoNatan** [comment]
Actually, I’m not sure about that. Adding such a big feature would require a long stabilization period, which I have neither the capacity for not the interest. iOS 9 and 10 are very outdated in their API.

**Comment by LeoNatan** [comment]
Seems like the dev tools are broken for iOS 10 anyway:
https://twitter.com/LeoNatan/status/1140695880015777792
and Apple is abandoning the iOS 8/9 simulator runtime after Xcode 11:
https://twitter.com/xenadu02/status/1140093901438689280

More nails in the ⚰️.

**Comment by iDevelopper** [comment]
In Music demo, it crash when selecting a music cell on iOS 10.3.1, not verified with iOS 11 & 12 yet:

<img width="1512" alt="Capture d’écran 2019-08-25 à 17 55 55" src="https://user-images.githubusercontent.com/1782450/63652568-3582d580-c762-11e9-815d-e05fdea96a49.png">

**Comment by LeoNatan** [comment]
The Music storyboard no longer compiles for iOS 10. That's the demo app, it is unrelated to the framework itself.

**Comment by wimbledon** [comment]
It would be nice to extend the iOS 9 and 10 support until next year. My apps still have a deployment target of iOS 9.0+.

**Comment by LeoNatan** [comment]
It's happening. With the planned 2.9.x release (iOS 14 support), iOS 9-11 support is removed. Only iOS 12 and above will be supported.

**Comment by coolstar** [comment]
@LeoNatan just wondering, are there any APIs we need that are only on iOS 12+?

I’d like to keep iOS 11 support, but I’m fine with dropping 10.x and lower

**Comment by LeoNatan** [comment]
I want to minimize the swizzled API usage to a minimum. I'll look at the stuff I removed (and still need to remove) and I'll see if iOS 11 complicates stuff. iOS 11 has support for safe areas, which is a big plus, but it's pretty broken. No promises, but I'll look favorably if it doesn't need extra swizzles over iOS 12.

**Comment by LeoNatan** [comment]
iOS 11 and above.
