### ISSUE TITLE
Label frames in RTL - barStyle compact

### ISSUE THREAD

**Issue by piesoftdev** [LeoNatan/LNPopupController#336]
The label frames(title and subtitle) are misplaced on the BarStyle compact when the application is set to RTL
![Simulator Screen Shot - iPhone 8 - 2019-06-17 at 15 08 08](https://user-images.githubusercontent.com/47597599/59603492-3966fb80-9112-11e9-9976-91ac30ac7a03.png)

**Comment by LeoNatan** [comment]
Thanks, I will try to reproduce and fix.
Is this issue only for compact bars?

**Comment by LeoNatan** [comment]
Works in prominent bar as well:

![Simulator Screen Shot - iPhone Xs Max - 2019-06-17 at 18 25 12](https://user-images.githubusercontent.com/2270433/59616556-58bf5200-912d-11e9-8652-242d4054244a.png)

**Comment by LeoNatan** [comment]
Ah, I managed to reproduce. It only occurs when there is one button on the bar.

**Comment by LeoNatan** [comment]
v2.7.2 is out with a fix for this.
