### ISSUE TITLE
UITabBar layout issues 

### ISSUE THREAD

**Issue by djmixroman** [LeoNatan/LNPopupController#338]
#### Description
Hi. I have UITabBar layout issues with iOS 12.3.1. This did happen also on iOS 12.0.1. Please take a look at the following little screen recording for demonstration:

[IMG_0008.TRIM.MOV.zip](https://github.com/LeoNatan/LNPopupController/files/3309348/IMG_0008.TRIM.MOV.zip)

#### Steps to Reproduce
I found this bug in my application and I thought that I messed up something, but then I reproduced it in your demo app.

```swift
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
	let popupContentController = storyboard?.instantiateViewController(withIdentifier: "DemoMusicPlayerController") as! DemoMusicPlayerController
	popupContentController.songTitle = titles[(indexPath as NSIndexPath).row]
	popupContentController.albumTitle = subtitles[(indexPath as NSIndexPath).row]
	popupContentController.albumArt = images[(indexPath as NSIndexPath).row]
		
	popupContentController.popupItem.accessibilityHint = NSLocalizedString("Double Tap to Expand the Mini Player", comment: "")
	tabBarController?.popupContentView.popupCloseButton.accessibilityLabel = NSLocalizedString("Dismiss Now Playing Screen", comment: "")
		
	tabBarController?.presentPopupBar(withContentViewController: popupContentController, animated: true, completion: nil)
	tabBarController?.popupBar.tintColor = UIColor(white: 38.0 / 255.0, alpha: 1.0)
	tabBarController?.popupBar.imageView.layer.cornerRadius = 5
	tabBarController?.popupInteractionStyle = .drag
        
        let vc = UIViewController()
        vc.hidesBottomBarWhenPushed = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
            self.tabBarController?.dismissPopupBar(animated: true, completion: nil)
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                self.navigationController?.pushViewController(vc, animated: true)
            }
        }
      
        
	tableView.deselectRow(at: indexPath, animated: true)
}
```

#### Device, OS and Xcode Versions
iPhone X, iOS 12.0.1 / 12.3.1, Xcode 10.2.1

**Comment by LeoNatan** [comment]
Thanks, I will take a look

**Comment by djmixroman** [comment]
@LeoNatan Any news?

**Comment by djmixroman** [comment]
I found this bug on https://forums.developer.apple.com/thread/113072

**Comment by LeoNatan** [comment]
Sorry, have been unable to look yet. I've seen an issue on iOS 13 where popping back to a tab bar controller causes some tab bar issues. I intend to look at this soon.

**Comment by LeoNatan** [comment]
I am unable to reproduce on a clean project with LNPopupController embedded, but I was able to reproduce on the Music demo.

**Comment by LeoNatan** [comment]
What's even more odd, pushing and pop reproduces the issue, but not using `self.performSegue(withIdentifier: "test", sender: nil)` (which also pushes a view controller.

**Comment by LeoNatan** [comment]
I can't reproduce this at all on iOS 13. This is most likely an iOS bug. The tab bar on iOS 12.1 and above is very buggy.

**Comment by LeoNatan** [comment]
Found a way to fix it, even if Apple bug. Maybe I should add another bullet as a feature of the framework; "Link this framework even if you don't need a popup, it will fix UIKit for you" 😂

**Comment by LeoNatan** [comment]
v2.7.2 out with this fix.
