### ISSUE TITLE
LNPopupController goes behind UINavigationBar

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [LeoNatan/LNPopupController#34]
I'm implementing this framework in my app, but somehow, when I slide it open, the view is placed behind the `UINavigationBar`. What am I doing wrong?

I present it like this: `[self presentPopupBarWithContentViewController:self.demoVC animated:YES completion:nil];`

**Comment by LeoNatan** [comment]
Make sure to present on the navigation controller, not on the VC (self).

**Comment by Sjoerdjanssenen** [comment]
I tried `self.navigationController` before, but then came to the realisation that I had a `UINavigationController` nested inside a `UISplitViewController`. What I had to do to solve this, was `self.navigationController.navigationController`.
