### ISSUE TITLE
TabBar height issue in version 2.7.2

### ISSUE THREAD

**Issue by piesoftdev** [LeoNatan/LNPopupController#340]
In my app I've a TabBar and when the LNPopup is not open then the tab bar is not positioned correctly, would you please able to look into this? Thank you

![Screen Shot 2019-07-31 at 3 04 27 PM](https://user-images.githubusercontent.com/47597599/62210339-96f29700-b3a4-11e9-85fc-112ed3fe3110.png)

**Comment by LeoNatan** [comment]
Hello,

Can you please provide a demo project that reproduces this?
