### ISSUE TITLE
Runtime crash when using the framework from Swift

### ISSUE THREAD

**Issue by mikhaelmina** [LeoNatan/LNPopupController#341]
Hi, I have included the framework in a swift project the manual way but I have a crash when accessing the `popupitem` method from the content view controller

the crash has also some notes:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AsanaRebel.AudioPlayerViewController popupItem]: unrecognized selector sent to instance`

sometimes I also get this after the crash in the logs:
`Shared Swift state for "App" has developed fatal errors and is being discarded. REPL definitions and persistent names/types will be lost`

Any ideas?
Appreciate your help
Mina

**Comment by LeoNatan** [comment]
That error tells me you have not linked the framework properly in your project.

**Comment by LeoNatan** [comment]
The example project already has a Swift example, which works as expected.

**Comment by LeoNatan** [comment]
Ping. Did you get it to work?

**Comment by mikhaelmina** [comment]
@LeoNatan Thanks for your answers, yes now it works fine the issue was the order of adding the framework and the xcodeproject, so I removed both and added them in the correct order:
1- Xcodeproject
2- Framework
otherwise xcode get confused i guess

Thanks,
Mina

**Comment by LeoNatan** [comment]
Great. Happy coding!
