### ISSUE TITLE
Get Interactive Transition Progress value

### ISSUE THREAD

**Issue by Kedar-27** [LeoNatan/LNPopupController#342]

**Comment by LeoNatan** [comment]
There is a template of a reason. Don't ignore it.

Also, use search before opening a new issue.

https://github.com/LeoNatan/LNPopupController/issues/211

**Comment by Kedar-27** [comment]
can you please provide me more detail...dont know how to use transition coordinator..please help

**Comment by LeoNatan** [comment]
Not possible at the moment. The issues are open.

**Comment by Kedar-27** [comment]
ok..if you find any, please provide me with one....badly stuck in the middle of a project. @LeoNatan

**Comment by LeoNatan** [comment]
Why not check out the demo project and how I have the blur there? That’s the best I can offer in the near future.

**Comment by iDevelopper** [comment]
@Kedar-27 , What about adding your own target:action to the popupInteractionGestureRecognizer?

```
[targetVC.popupContentView.popupInteractionGestureRecognizer addTarget:self action:@selector(handlePopupInteraction:)];
```
```
- (void)handlePopupInteraction:(UIPanGestureRecognizer *)pgr {
    CGPoint point = [pgr locationInView:pgr.view.superview];
    //...
}
```

**Comment by Kedar-27** [comment]
thank you @iDevelopper ..achieved this in swift by`

    @objc func handlePanGesture(gesture: UIPanGestureRecognizer?){
    
        guard let _: CGPoint? = gesture?.translation(in: view) else { return }
        
            if gesture?.state == .changed || gesture?.state == .ended {

            
            let percent = ((UIScreen.main.bounds.size.height - popupContentView.frame.height) / UIScreen.main.bounds.size.height)
            
            self.popupContentView.alpha = 1.0 - percent
            self.popupBar.alpha = percent
            
        }
        
    }



`

**Comment by LeoNatan** [comment]
Nice. Do you mind posting a video to show how it looks?

**Comment by iDevelopper** [comment]
Great! Thank You!
