### ISSUE TITLE
Presenting Custom Bar inside Popup Content View 

### ISSUE THREAD

**Issue by Kedar-27** [LeoNatan/LNPopupController#343]
can we achieve transition similar to this 
[https://imnotyourson.com/draggable-view-controller-interactive-view-controller/](url)

currently, popup bar is attached to the top of popup content view which causes unpleasant transition

**Comment by LeoNatan** [comment]
Read docs.

**Comment by LeoNatan** [comment]
You mean the fade out or the smooth pull of the pop up? The first is not possible. The purpose of this framework is to emulate the look and feel of the Apple Music app implement ration.

**Comment by Kedar-27** [comment]
not exactly concerned with animation.....just technically wanted the top constraint of popup content view to be aligned with top of of popup bar....is this possible

**Comment by iDevelopper** [comment]
@LeoNatan ,

> The purpose of this framework is to emulate the look and feel of the Apple Music app implementation.

This is not really the case now!

**Comment by LeoNatan** [comment]
It is the case, as much as I have time to work on it. The fork button is always available for anyone to press and do things differently.

**Comment by Kedar-27** [comment]
> not exactly concerned with animation.....just technically wanted the top constraint of popup content view to be aligned with top of popup bar....is this possible
> @LeoNatan

can you help me with this issue

**Comment by LeoNatan** [comment]
It's not possible. The content starts beneath the popup bar.

**Comment by Kedar-27** [comment]
@LeoNatan @iDevelopper  will this issue be fixed in future release?

**Comment by LeoNatan** [comment]
Not planned. Big changes are coming, we’ll see.

**Comment by Kedar-27** [comment]
can you please consider this in  v3.0
