### ISSUE TITLE
Bitcode verification error while exporting .ipa after archive

### ISSUE THREAD

**Issue by mikhaelmina** [LeoNatan/LNPopupController#345]
Hi,
I get this error while trying to export the .ipa after an archive:
Failed to verify bitcode in LNPopupController.framework/LNPopupController:
error: Cannot extract bundle from `/var/folders/71/8v5dzsfx36s03g5h4mgn2t7r0000gn/T/XcodeDistPipeline.~~~0UjP5u/Root/Payload/myapp.app/Frameworks/LNPopupController.framework/LNPopupController (i386)`

see screenshot:
![Screenshot 2019-08-21 12 12 55](https://user-images.githubusercontent.com/33283577/63423644-0b04e580-c40d-11e9-8e0b-5ff9c6d75c53.png)

the app builds and runs just fine, on-device and simulator but seems to have this issue only when exporting the .ipa

Appreciate your help,
Mina

**Comment by LeoNatan** [comment]
Hi,

Not sure what is happening. Bitcode support is enabled in the project settings. People have been submitting apps with LNPopupController for years. I fear it might be something on your end.

**Comment by mikhaelmina** [comment]
@LeoNatan for some reason the framework contains some simulator architecture: `i386 x86_64`
I added a run script to remove them, and then it worked and I can now export the .ipa file

https://stackoverflow.com/questions/46404236/failed-to-verify-bitcode-while-exporting-archive-for-ad-hoc-distribution-tried

**Comment by LeoNatan** [comment]
Yes, this is a known issue with closed-source frameworks. Did you add the framework in a precompiled form? Xcode usually cleans frameworks correctly when a project is added as a subproject with source available.

**Comment by mikhaelmina** [comment]
@LeoNatan I added the framework to the **"Embedded Binaries"** in the General tab of the target as you mentioned in the readme

**Comment by LeoNatan** [comment]
Maybe it's needed there too... 🤷‍♂️

When integrating with Carthage, they run their own script to do this. It's really stupid that Xcode doesn't just lipo out the unneeded architectures... 

Anyway, closing the issue as it has been resolved. Thanks
