### ISSUE TITLE
presentPopupBar does not release existing popup ViewController reference

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#347]
#### Description
I noticed the ViewController in the popupBar is not released from memory when another VC is presented via `presentPopupBar`. This causes a memory leak.

#### Steps to Reproduce
* Open the demo application
* Choose Apple Music demo
* Tap on a song. Then on another one. Repeat.
* Check memory debugger: `DemoMusicPlayerController` is in memory many times and not being cleared.

<img width="263" alt="Screen Shot 2019-08-25 at 14 18 47" src="https://user-images.githubusercontent.com/144173/63649933-5b997d00-c744-11e9-9ec7-98773c7f4fa3.png">

#### Device, OS and Xcode Versions
Xcode 11 beta 6, iOS 13
LNPopupController Version 2.8

**Comment by LeoNatan** [comment]
Uff, good catch! Will investigate!

**Comment by LeoNatan** [comment]
🙃

This only happens in the music demo, because there is a timer.

```
timer = Timer.scheduledTimer(timeInterval: 0.05, target: self, selector: #selector(DemoMusicPlayerController._timerTicked(_:)), userInfo: nil, repeats: true)
```

**Comment by LeoNatan** [comment]
If you want to test for your self, open FirstViewController.m, in `- (IBAction)_presentBar:(id)sender`, add `dispatch_after` at the end and present another view controller. You will see that the `DemoPopupContentViewController` instances are released.

**Comment by funkenstrahlen** [comment]
Oh I see. Sorry I didn’t catch that.
