### ISSUE TITLE
Memory reference circle starting with 2.8.0 release

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#349]
After updating `LNPopupController` to `2.8.0` I noticed a memory cycle issue in my app. The ViewController I present in the popup bar does no longer get freed after presenting a new ViewController with `presentPopupBar`. (This is why I initially opened #347 but learned this is a different issue.)

Because I was sure my app did not have this problem before I tracked down the issue to this commit in `LNPopupController`: 43046b5905c6489aba843feae8445d79ab8fd96f
As soon as I define this commit in my `Cartfile` as the version to use I see the issue.

After updating `LNPopupController` to this state I see the memory issue. In `2.7.4` it is working as expected.

I spend some time looking at the commit changes but I honestly do not understand how those changes could cause the issue.

#### Steps to Reproduce

This is the code I use to present a new `PlayerViewController` as the content view controller of my popup bar:

```swift
let playerViewController = UIStoryboard(name: "Player", bundle: nil).instantiateViewController(withIdentifier: "playerView") as! PlayerViewController
playerViewController.channel = channel
playerViewController.popupItem.accessibilityHint = NSLocalizedString("Double Tap to Expand the Mini Player", comment: "")
tabBar.popupContentView.popupCloseButton.accessibilityLabel = NSLocalizedString("Dismiss Now Playing Screen", comment: "")

tabBar.presentPopupBar(withContentViewController: playerViewController, openPopup: true, animated: true) {
    tabBar.popupBar.inheritsVisualStyleFromDockingView = false
}
```

I call this every time the user selects a new audio element to play. When this gets run multiple times it does not free the old PlayerViewController any more.

This is what I see when I bring up the memory inspector:

<img width="523" alt="Screen Shot 2019-08-26 at 01 24 52" src="https://user-images.githubusercontent.com/144173/63669960-b8944200-c7db-11e9-8f90-4efe8848e50c.png">

<img width="520" alt="Screen Shot 2019-08-26 at 01 24 58" src="https://user-images.githubusercontent.com/144173/63669954-b631e800-c7db-11e9-968c-82ec9fd2009f.png">

The reference cycle is caused by `_UIPageSheetPresentationController` and my `PlayerViewController`.

Do you have any idea what's going on?

#### Device, OS and Xcode Versions
Xcode 11 beta 6, iOS 13 simulator

**Comment by funkenstrahlen** [comment]
Both attributes causing the memory cycle are starting with an underline `_`. I do not use this pattern in my code so I assume this no reference cycle I explicitly cause in my code.

**Comment by LeoNatan** [comment]
_UIPageSheetPresentationController is the iOS 13 presentation controller for the card presentation.

Can I please ask you to reproduce this in a clean project? I am unable to reproduce in any of my demo app scenes. After you opened the previous one, I tried several scenarios and all worked as expected. Then I wondered why the music doesn't and noticed the timer.

**Comment by funkenstrahlen** [comment]
I understand this is difficult to fix without a way to reproduce. I will try to reproduce in a clean project and upload it here.

**Comment by funkenstrahlen** [comment]
I finally managed to reproduce the issue. The reference cycle is created when `popupBar` is used from within the content view controller `viewDidLoad` like this for example: `popupBar.imageView.layer.cornerRadius = 5`

Probably this is a non-issue because `popupBar` should never be called like this. I am happy to hear your thoughts. I think it is still a problem though because this works fine in 2.7.4.

#### Sample project

I created a sample project demonstrating the issue:

[PopupBarReferenceCycleDemo.zip](https://github.com/LeoNatan/LNPopupController/files/3540108/PopupBarReferenceCycleDemo.zip)

You will need to run `carthage update` before it builds. I deleted the `Carthage` folder before compressing to reduce the file size.

#### Steps to reproduce in sample project

* Click present multiple times
* Launch memory debugger

**Comment by funkenstrahlen** [comment]
I now moved this line of code `popupBar.imageView.layer.cornerRadius = 5` out of `viewDidLoad()` in my code to another place and this fixes the reference cycle in my app.

**Comment by LeoNatan** [comment]
Nope, that's a bug. Will investigate soon (a little sick at the moment).

**Comment by funkenstrahlen** [comment]
Thanks! Take your time and get well soon :)

**Comment by LeoNatan** [comment]
Wait, accessing the content view controller's popup bar is incorrect here, you know that, right? (Regardless of bug)

**Comment by LeoNatan** [comment]
The "interesting" popup bar is the container's.

**Comment by funkenstrahlen** [comment]
> Wait, accessing the content view controller's popup bar is incorrect here, you know that, right? (Regardless of bug)
> The "interesting" popup bar is the container's.

Yes I realized that I was doing this wrong now:

> I now moved this line of code `popupBar.imageView.layer.cornerRadius = 5` out of `viewDidLoad()` in my code to another place and this fixes the reference cycle in my app.

However I might not be the only one who has done it wrong (just because it did not cause any issues before). Therefore a fix for this reference cycle could help many others.

**Comment by LeoNatan** [comment]
There shouldn't be a reference cycle. I will investigate that.
I was just mentioning that you were doing it wrong. Actually a lot of people confuse the right targets. I wonder if it's a documentation fault.

**Comment by LeoNatan** [comment]
Seems like an Apple bug. It seems accessing the presentationController causes a memory leak somewhere.

https://github.com/LeoNatan/LNPopupController/blob/8b25fab18bfa74ee9c4d2c24c4ac8f79373790d4/LNPopupController/LNPopupController/Private/UIViewController%2BLNPopupSupport.m#L241

**Comment by LeoNatan** [comment]
I'll make a change to fix this for most cases.

**Comment by LeoNatan** [comment]
So I found an internal method that can retrieve an existing presentation controller without causing this memory leak. I will use that in v3.
