### ISSUE TITLE
Opening LNPopupController programmatically gives me a "see through" window

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [LeoNatan/LNPopupController#35]
When I initialise and open the `LNPopupController` instance in my app, I get a a window that's complete see-through on top of the presenting `UIViewController`.

    self.restVC = [RestaurantsViewController new];
    self.restVC.restaurants = [Restaurants fetchAll];
    
    UIBarButtonItem *title = [[UIBarButtonItem alloc] initWithCustomView:self.restLabel];
    self.restVC.popupItem.rightBarButtonItems = @[title];

    [self.navigationController presentPopupBarWithContentViewController:self.restVC openPopup:YES animated:NO completion:nil];

When I look in the logs I can see that `RestaurantsViewController` is indeed loaded. If I then collaps the view and reopen it, it's fine. Any ideas as to what's causing this?

**Comment by LeoNatan** [comment]
What is a see-through "window"? I think you are misusing the term "window". Please post a screenshot of the problem.

**Comment by LeoNatan** [comment]
I am unable to reproduce this issue. Please provide a demo project where this reproduces.
