### ISSUE TITLE
Regression: PopupItem BarButtonItems do not trigger target actions

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#350]
PopupItem BarButtonItems do not trigger target actions. This is a regression as it did work in older versions.

#### Steps to Reproduce
* Use the example project.
* Modify `DemoMusicPlayerController` and actually assign target actions to the UIBarButtonItems:

```
let pause = UIBarButtonItem(image: UIImage(named: "pause"), style: .plain, target: self, action: #selector(play))

// [...]


    @objc func play() {
        print("play")
    }
```

* Open the Demo app
* Select Apple Music demo
* Tap on demo song to reveal popup bar
* Press pause button in minified popup bar

**Expected:** Target action function `play()` is called.

**Actual:** The popup bar opens into full screen mode like when tapped anywhere else.

#### Device, OS and Xcode Versions
iOS 13.0 developer beta 8
lnpopupcontroller `2.8.2`

**Comment by LeoNatan** [comment]
Thanks, will look into this today.

**Comment by LeoNatan** [comment]
Out in v2.8.3

**Comment by funkenstrahlen** [comment]
Awesome, thank you :)
