### ISSUE TITLE
ScrollView Contentsize issue on iphone X

### ISSUE THREAD

**Issue by Kedar-27** [LeoNatan/LNPopupController#351]
I am having problem when my view contains tableView embeded in scrollView. When the popup bar is presented scrollview content size changes and it disturbs the content offset of scrollView
Any solution for this @LeoNatan

**Comment by LeoNatan** [comment]
You have a table view inside a scroll view? That's terrible and you should not do that.
You should be using a UITableViewController.

**Comment by LeoNatan** [comment]
UITableView itself is a scroll view, so putting that inside another scroll view is just not right.

**Comment by LeoNatan** [comment]
Check out the Music demo. That one has a table view, and is correctly maintained. For iOS < 11, there was something that was needed to be done in `viewDidLayoutSubviews`, but since 11 everything works.

**Comment by Kedar-27** [comment]
i am trying to create parallax header animation so integrated tableview in scrollView
[https://github.com/maxep/MXParallaxHeader](url)

**Comment by LeoNatan** [comment]
What?

https://github.com/maxep/MXParallaxHeader/blob/335616c87ba20c5af5f5bc572a761364950d3646/MXParallaxHeader/MXParallaxHeader.h#L135

The framework is implemented as a category over UIScrollView. That means that you should set `tableView.parallaxHeader.view = headerView`.

**Comment by LeoNatan** [comment]
Did it work?

**Comment by Kedar-27** [comment]
ohh... i did the other way.... i solved this issue by little trick on viewDidAppear
`self.navigationController?.presentPopupBar(withContentViewController: self.musicPlayerVC, animated: false)`
`self.navigationController?.dismissPopupBar(animated: false)`

and presented again manually

**Comment by LeoNatan** [comment]
I am sorry, I don't understand what you are doing. 😂

**Comment by Kedar-27** [comment]
`override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.presentBottomBar() 
}`
    

 
    `func presentBottomBar(){
        
        let customBottomBarstoryBoard = UIStoryboard(name: WRMusicBottomBar.storyboardName, bundle: nil)
        let customBottomBarVC = customBottomBarstoryBoard.instantiateViewController(withIdentifier: WRMusicBottomBar.storyboardIdentifier ) as! WRMusicBottomBar
        self.navigationController?.popupBar.customBarViewController = customBottomBarVC
        self.navigationController?.popupContentView.popupCloseButtonStyle = .none
        self.navigationController?.popupInteractionStyle = .drag
        
        
        self.navigationController?.popupContentView.isTranslucent = false
        self.navigationController?.popupContentView.popupInteractionGestureRecognizer.delegate = self
        self.navigationController?.popupContentView.popupInteractionGestureRecognizer.addTarget(self, action: #selector(handlePanGesture(gesture:)))
        self.navigationController?.popupBar.popupOpenGestureRecognizer.addTarget(self, action: #selector(handleTapGesture(recognizer:)))
        self.navigationController?.presentPopupBar(withContentViewController: self.musicPlayerVC, animated: false)
        self.navigationController?.dismissPopupBar(animated: false)
        
    }
    
    func hidePopupBar() {
        self.navigationController?.popupBar.isHidden = true
        self.view.layoutSubviews()
        
        self.navigationController?.dismissPopupBar(animated: true, completion: {
            
            self.view.frame.size.height = UIScreen.main.bounds.height 
            
        })
        
        
    }
    
    func showPopupBar(completion: @escaping () -> Void) {
        self.isPopupBarVisible = true
         self.navigationController?.presentPopupBar(withContentViewController: self.musicPlayerVC, animated: false, completion: {
            completion()
            
         })

        self.view.layoutSubviews()
        
    }`

**Comment by Kedar-27** [comment]
> `override func viewDidAppear(_ animated: Bool) { super.viewDidAppear(animated) self.presentBottomBar() }`
> 
> ```
> `func presentBottomBar(){
>     
>     let customBottomBarstoryBoard = UIStoryboard(name: WRMusicBottomBar.storyboardName, bundle: nil)
>     let customBottomBarVC = customBottomBarstoryBoard.instantiateViewController(withIdentifier: WRMusicBottomBar.storyboardIdentifier ) as! WRMusicBottomBar
>     self.navigationController?.popupBar.customBarViewController = customBottomBarVC
>     self.navigationController?.popupContentView.popupCloseButtonStyle = .none
>     self.navigationController?.popupInteractionStyle = .drag
>     
>     
>     self.navigationController?.popupContentView.isTranslucent = false
>     self.navigationController?.popupContentView.popupInteractionGestureRecognizer.delegate = self
>     self.navigationController?.popupContentView.popupInteractionGestureRecognizer.addTarget(self, action: #selector(handlePanGesture(gesture:)))
>     self.navigationController?.popupBar.popupOpenGestureRecognizer.addTarget(self, action: #selector(handleTapGesture(recognizer:)))
>     self.navigationController?.presentPopupBar(withContentViewController: self.musicPlayerVC, animated: false)
>     self.navigationController?.dismissPopupBar(animated: false)
>     
> }
> 
> func hidePopupBar() {
>     self.navigationController?.popupBar.isHidden = true
>     self.view.layoutSubviews()
>     
>     self.navigationController?.dismissPopupBar(animated: true, completion: {
>         
>         self.view.frame.size.height = UIScreen.main.bounds.height 
>         
>     })
>     
>     
> }
> 
> func showPopupBar(completion: @escaping () -> Void) {
>     self.isPopupBarVisible = true
>      self.navigationController?.presentPopupBar(withContentViewController: self.musicPlayerVC, animated: false, completion: {
>         completion()
>         
>      })
> 
>     self.view.layoutSubviews()
>     
> }`
> ```

i have created this inside base class and all my view controller will extend this class to inherit this properties

**Comment by LeoNatan** [comment]
But why present and dismiss in `viewDidAppear`? Only present when you need to.

**Comment by Kedar-27** [comment]
was initially doing the same... but presenting popup bar was decreasing the contentsize of mxScrollView...so was facing problem of content offset ...but rescrolling was correcting the content offset of scrollview..... so decided to try this
