### ISSUE TITLE
Module "LNPopupController" not found

### ISSUE THREAD

**Issue by tanvirhannan** [LeoNatan/LNPopupController#352]
#### Description

Every time I clone down my project from Github and build it, I receive a "Module LNPopupController is not found" error. I have to manually drag it into my project and add it was an embedded binary (this was how I integrated the module into my project in the first place). How can I get the module to permanently be in my project, so every time I clone down a version I do not have to manually add it again? I'm asking because I need my project to build in Jenkins, and my jenkins job keeps failing because it first needs the module to manually be added in.
#### Device, OS and Xcode Versions

Xcode 10.2

**Comment by LeoNatan** [comment]
Did you add it as a sub module (recommended)? If so, you need to recursively clone, or recursively update submodules after cloning.

If you just want to drag the framework to your own repo (not recommended), make sure you copy it to the repo first and then add it in Xcode. Also make sure to track the new files in git and commit them.

**Comment by tanvirhannan** [comment]
@LeoNatan Do I add the "LNPopupController.xcodeproj" into the submodule or the entire "LNPopupController" directory into the submodule?

**Comment by LeoNatan** [comment]
I suggest you read up on what submodules are and how they work.

**Comment by LeoNatan** [comment]
You can also use Carthage, which is supported.

**Comment by tanvirhannan** [comment]
@LeoNatan I understand how submodules work. However, when I tried adding just the .xcodeproj to my submodule my project couldn't find other files needed such as the Lnpopcontroller.h. Adding the whole directory, however, is more concerning because you can't specify which directory to go into within a submodule

**Comment by LeoNatan** [comment]
If you are trying to add the .xcodeproj to a submodule, you do not understand how submodules work, sorry.

**Comment by tanvirhannan** [comment]
@LeoNatan So you recommend adding the whole directory into it then?

**Comment by LeoNatan** [comment]
If you are adding anything manually to a submodule, you are doing it wrong. I recommend you read on how to add git submodules to your project.

**Comment by tanvirhannan** [comment]
@LeoNatan You have to manually add the files you want to into a submodule when you are first creating it, so every time you git submodule init/update the files within that submodule are loaded in

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by tanvirhannan** [comment]
@LeoNatan I see what you mean about adding LNPopupController as a submoduole. I was under the impression of creating a submodule and adding the LNPopupcontroller to it.

Anyways, I have added it as a submodule to my project, which in turn adds the Repo to my project upon initializing/updating it, however, I still need to drag the LNpopupcontroller.xcodeproject into my project for it to find the module. Are there any additional steps I need to take to fully remove this manual process?

**Comment by LeoNatan** [comment]
Once you add the framework to your project once, commit the changes. It should now work every time you clone.

**Comment by LeoNatan** [comment]
For example of how to integrate, you can check the demo project. That one doesn't use a submodule (of course), but it shows how to integrate the framework project with the customer project.
