### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by Kedar-27** [LeoNatan/LNPopupController#362]
When I simultaneously click on table view cell and bottom bar , bottom bar disappears and get this statement in debug description @LeoNatan 
Unbalanced calls to begin/end appearance transitions for <popupVC: 0x12de746c0>.

**Comment by LeoNatan** [comment]
What do you do when tapping a cell?

**Comment by Kedar-27** [comment]
i am presenting popup bar

`self.navigationController?.presentPopupBar(withContentViewController: self.musicPlayerVC, animated: false, completion: {
         })`
