### ISSUE TITLE
Including using package manager

### ISSUE THREAD

**Issue by tarunbhutani** [LeoNatan/LNPopupController#364]
#### Description
I'm trying to including the project using `package manager` but getting the below error

<img width="727" alt="Screenshot 2019-09-28 at 7 24 02 PM" src="https://user-images.githubusercontent.com/10242725/65815733-f98dd500-e225-11e9-9702-eea657df84d4.png">

#### Device, OS and Xcode Versions
Xcode 11

**Comment by LeoNatan** [comment]
SPM is not supported right now, as I am not really familiar with SPM. There was a PR adding support, but was closed. https://github.com/LeoNatan/LNPopupController/pull/359

Feel free to add support.
