### ISSUE TITLE
How can i remove the botton scroll inset that is added to all my view controllers?

### ISSUE THREAD

**Issue by mamady83** [LeoNatan/LNPopupController#368]
I have managed to move the dockview to the right of tabbar but the bottom inset which is added to the root VC in order to prevent the content from going behind the popupbar is now causing me trouble.
please tell me how i can remove this space from my scrolling views.
thanks in advance

Current View:
![Screen Shot 2019-10-24 at 12 54 32 PM](https://user-images.githubusercontent.com/17244791/67472094-6ea1ce00-f65d-11e9-866f-01864e0fe56d.png)

I would like to remove the space between the tabbar and the gray container (which is the last item in my list and the table has no insets)

Desired view:
![Screen Shot 2019-10-24 at 12 55 33 PM](https://user-images.githubusercontent.com/17244791/67472175-92651400-f65d-11e9-93e9-00caf8fdddfd.png)

**Comment by LeoNatan** [comment]
Hello,

Have you modified the framework to achieve this?

**Comment by mamady83** [comment]
> Hello,
> 
> Have you modified the framework to achieve this?

No i have used it via carthage
editted the dock view and moved it to right on ipad and changed tabbar width to achieve this

**Comment by LeoNatan** [comment]
Unfortunately, this isn't a supported scenario. You will have to fork the framework and change how the inset logic works.

**Comment by LeoNatan** [comment]
If you do this, look for the `_LNPopupSupportSetPopupInsetsForViewController` function calls and set those to `UIEdgeInsetsZero` instead of the popup bar height.

**Comment by mamady83** [comment]
Thanks, if you could provide this inset via a public method it would be useful i guess.

**Comment by LeoNatan** [comment]
It’s not really possible. The inset is not constant but the height of the bar, which is dynamic according to bar style and custom bar controller size.

**Comment by mamady83** [comment]
i guess as a quick workaround i can add a negative inset for each one of my lists since i have zero experience with objective-c

**Comment by LeoNatan** [comment]
That's not a good approach. Remember that insets can change depending on system layout.

You shouldn't be scared of Objective C.

**Comment by iDevelopper** [comment]
What about using a custom container view controller subclass and implementing these three properties?
```
/**
 * Popup presentation containment support in custom container view controller subclasses.
 */
@interface UIViewController (LNPopupCustomContainer)

/**
 * Return a view to dock the popup bar to, or @c nil to use the system-provided view.
 *
 * A default implementation is provided for @c UIViewController, @c UINavigationController and @c UITabBarController.
 * The default implmentation for @c UIViewController returns an invisible @c UIView instance, docked to the bottom. For @c UINavigationController, the toolbar is returned. For @c UITabBarController, the tab bar is returned.
 */
@property (nullable, nonatomic, strong, readonly) __kindof UIView* bottomDockingViewForPopupBar;

/**
 * Return the default frame for the docking view, when the popup is in hidden or closed state. If @c bottomDockingViewForPopupBar returns nil, this method is not called, and the default system-provided frame is used.
 *
 * A default implementation is provided for @c UIViewController, @c UINavigationController and @c UITabBarController.
 */
@property (nonatomic, readonly) CGRect defaultFrameForBottomDockingView;

/**
 * The insets for the bottom docking view from bottom of the container controller's view. By default, this is set to the container controller view's safe area insets in iOS 11 or @c UIEdgeInsetsZero otherwise. Currently, only the bottom inset is respected.
 *
 * The system calculates the position of the popup bar by summing the bottom bar height and the bottom of the insets.
 *
 * @warning This API is experimental and will probably change in the future. Use with care.
 */
@property (nonatomic, readonly) UIEdgeInsets insetsForBottomDockingView;

@end
```

**Comment by iDevelopper** [comment]
@mamady83 , this is a tabBar added to your view? Not a tabBarController?

**Comment by iDevelopper** [comment]
@LeoNatan ,
> It’s not really possible. The inset is not constant but the height of the bar, which is dynamic according to bar style and custom bar controller size.

What about creating a new property available (for example wantsAdditionalSafeAreaInsets of type BOOL)? If it is set to NO, you do not call the _LNPopupSupportSetPopupInsetsForViewController function.

**Comment by LeoNatan** [comment]
I guess that's possible but it sounds like a very limited use-case.

**Comment by iDevelopper** [comment]
This would allow users of the framework to develop applications that look like Apple Music app on iPad, like @mamady83 trying to do!
