### ISSUE TITLE
Pop Up Close Button Creating Dead Pixels. 

### ISSUE THREAD

**Issue by F-W-D** [LeoNatan/LNPopupController#369]
#### Description
The Pop Up Close Button is creating dead pixels on the iPhone 11 Pro, possibly others as well. Trying to remove the chevron does nothing and does not seem to render in iOS 13. Here is a picture:

![Chevron Dead Pixels - LNPopUpController](https://user-images.githubusercontent.com/16774936/67628491-0ce38e80-f82c-11e9-82df-c25f565a4ee0.png)

#### Steps to Reproduce
Try to use 
'popupController.popupContentView.popupCloseButtonStyle = .none'
Chevron does not disappear and causes dead pixels for layering UI Objects. 
Issue seems to be with iOS 13 which seems to ignore the chevron and close button styles.

#### Device, OS and Xcode Versions
Using Xcode 11.1, iPhone 11 Pro, iOS 13.1

**Comment by LeoNatan** [comment]
Hello,

This is odd. Can you please post the view hierarchy you are seeing? (Using `recursiveDescription` or Xcode's 3D view)
Can you reproduce this issue in the example project?

Thanks

**Comment by iDevelopper** [comment]
@F-W-D , what is popupController?

> 'popupController.popupContentView.popupCloseButtonStyle = .none'

**Comment by LeoNatan** [comment]
Agree with @iDevelopper 
Most likely, the incorrect `popupContentView` was used.
