### ISSUE TITLE
Status Bar keeps appearing when table view row is selected

### ISSUE THREAD

**Issue by msimonetta** [LeoNatan/LNPopupController#37]
Please help on this one - so weird..been at it for hours now.

**Comment by LeoNatan** [comment]
What happens when you select a cell? Do you push another controller? I cannot help without all the details.

**Comment by msimonetta** [comment]
Hi Leo,

This can be closed. I ended up solving late last night. I just set the preferStatusBarHidden value to TRUE in specific view controller. Easy fix, was too tired to think straight!

While I have you though, I'm noticing that when the bar is at the bottom of the screen, it is overlaying on top of the view that is currently present. That being said, i have a table view beneath it and i would like to automatically adjust the table view frame when the bar is there so that it doesn't scroll under it. (It's losing some of its height because of the bar being there - due to the table views frame bottom being at the bottom of the bar as opposed to snapping it to the top of it)..how can I fix this?

Regards,

Michael Simonetta

**Comment by LeoNatan** [comment]
You should set the ```contentInset``` of the table view with correct inset. Does this not happen automatically? Run the demo project and see, there the table view can be scrolled correctly.

**Comment by msimonetta** [comment]
Thanks Leo,

Final thing - I noticed when I call dismissPopupBar the popup bar
dismisses, but it seems as though that it's view controller is still
retained, as the AVPlayer I had playing a song within it keeps playing. Is
there a clean way to ensure that when I dismiss the popupbar that the view
controller it was a part of is removed completely as well?


Regards,

Michael Simonetta
