### ISSUE TITLE
Popupbar  goes behind UITabbar in first launch

### ISSUE THREAD

**Issue by mohamadyeganeh76** [LeoNatan/LNPopupController#371]
#### Description
I am using the latest version of the library installed via carthage

I am facing this issue only in ios 13 runnig iphone x and 11 (i.e iphone 8 and prior devices running ios13 are fine)

![Screen Shot 2019-11-05 at 9 22 34 AM](https://user-images.githubusercontent.com/17244791/68181973-23b57e00-ffae-11e9-8114-07143f2d64d3.png)

as you can see popupbar starts from the page inset and goes behind the tabbar. and with any action (updating the popup, pushing a viewController, clicking on the tabbar), popupbar moves to its correct position

![Screen Shot 2019-11-05 at 9 22 46 AM](https://user-images.githubusercontent.com/17244791/68182169-69724680-ffae-11e9-8ba5-100f252bf637.png)

Xcode version : 11.0

**Comment by LeoNatan** [comment]
Hello,

Can you reproduce this issue in the example project?
How are you presenting the popup bar and where?

Thanks

**Comment by mamady83** [comment]
Thanks for the hint,

I was presenting popup bar from `viewDidLoad` and after calling the present method from `viewDidLayoutSubviews` everything worked fine

**Comment by LeoNatan** [comment]
Hm, not sure that’s the best place to call it. Can you reproduce this in the example project? I will try to look and resolve this.

**Comment by tianzhaotong2012** [comment]
hello i meet the same problem, can u help me . my code is here https://github.com/tianzhaotong2012/ZTMusic
