### ISSUE TITLE
Text not staying central

### ISSUE THREAD

**Issue by pyropresents** [LeoNatan/LNPopupController#372]
#### Description

When launching podcast track the text/title is central, then shoots to the left and is barely visible, no idea why or how to fix.
![Issue](https://user-images.githubusercontent.com/8068715/68552441-039f1800-040f-11ea-8e44-473efd6643d7.png)

#### Device, OS and Xcode Versions
All devices in simulator, Catalina, Xcode 11.2

**Comment by LeoNatan** [comment]
Hello,

Are you able to reproduce this issue on the example app? Also, make sure you are running the latest version, not some old CocoaPods fork.

**Comment by pyropresents** [comment]
cocoa is 1.8.4, I'm not sure what you mean when you say reproduce it on an example app?  speedy reply by the way!

**Comment by LeoNatan** [comment]
The framework is at 2.8.5. Not sure what you expect me to do. Use the framework as described in the readme.

**Comment by LeoNatan** [comment]
I see v1 ended at 1.4.6. So no idea what 1.8.4 is.

**Comment by pyropresents** [comment]
> I see v1 ended at 1.4.6. So no idea what 1.8.4 is.

sorry, maybe i grabbed the wrong info, im new to alot of this. i tried to install it via terminal but that didnt work so run there mac app instead, im confused because you have just said i should be running a newer version, but in read me file it says i shouldnt even use cocoa pods with LnPopup

**Comment by LeoNatan** [comment]
That’s right, CocoaPods is not supported and never has been. Use Carthage or a sub module. You can use together with your existing CocoaPods stuff.

**Comment by LeoNatan** [comment]
You probably found an old fork that people have made.

**Comment by pyropresents** [comment]
so that would be why im running into this problem? if i use carthage this shouldnt happen?

**Comment by LeoNatan** [comment]
I haven’t seen this issue in very long time. Try and let me know.

**Comment by pyropresents** [comment]
> I haven’t seen this issue in very long time. Try and let me know.

ok, thanks for your time, i'll give it a go :-)

**Comment by LeoNatan** [comment]
Cheers

**Comment by pyropresents** [comment]
Although other dependencies are added via cocoa pods , this was added manually by dragging and dropping and then adding the framework to the embedded binaries (I’ve just been told as was done by someone else)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LeoNatan** [comment]
Can you please reproduce in the example project?

**Comment by pyropresents** [comment]
>Can you please reproduce in the example project?

@LeoNatan no problem, will be on comp in about hAlf hour, what’s best way to share it? Can I upload it to post? Or do I share a upload link to you? I’m a newbie on here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LeoNatan** [comment]
Once you reproduce, you can compress the folder and drag/drop the zip file here.

**Comment by pyropresents** [comment]
>Once you reproduce, you can compress the folder and drag/drop the zip file here.

@LeoNatan ok thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pyropresents** [comment]
> > Once you reproduce, you can compress the folder and drag/drop the zip file here.
> 
> @LeoNatan ok thanks
> 
> Sent with [GitHawk](http://githawk.com)

[DJ Pyro.zip](https://github.com/LeoNatan/LNPopupController/files/3831196/DJ.Pyro.zip)
Here ya go mate

**Comment by LeoNatan** [comment]
This is not the example project. I will not have time to dive in your own project. Please reproduce in the example project included in this repo: https://github.com/LeoNatan/LNPopupController/tree/master/LNPopupControllerExample
