### ISSUE TITLE
How to prevent/allow player from turning landscape when turning phone?

### ISSUE THREAD

**Issue by JayceBryce** [LeoNatan/LNPopupController#373]
#### Description

My current app allows only portrait/lanscape mode. Essentially when I present the player and it is open I would like to allow the users to turn their phone landscape.

This following code is inside my view controllers:

```
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.portrait
    }
    
    override var shouldAutorotate: Bool {
        return false
    }
```

Inside my player view controller ( which I use this library ) I have this code:

```
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.allButUpsideDown
    }
    
    override var shouldAutorotate: Bool {
        return true
    }
```

How would I go about achieving this goal of not allowing my VCs ( tabs) to only be portrait but when I have my player open I am able to turn landscape?

Thank you

**Comment by LeoNatan** [comment]
Hm, I don't think this is supported, at least not currently. This should work eventually if/when v3 is implemented, where I use custom presentation. It would require a major effort to implement this in the current version.

What I would suggest is, in your presenting controller, implement `supportedInterfaceOrientations` to return `.portrait` if the popup is closed or not presented, and `.allButUpsideDown` when the popup is open. You can then call `UIViewController.attemptRotationToDeviceOrientation()` to make the system query which interface orientations are supported.
