### ISSUE TITLE
Popup drag animation causes controller to get stuck under status bar

### ISSUE THREAD

**Issue by dancarasco** [LeoNatan/LNPopupController#374]
Popup is presented on a TabBarController which is parent of several child navigation controllers. The popup's content view controller is a regular UIViewController.

The UIViewController has prefersStatusBarHidden set to YES. Drag style is set to default (iOS 10.0+)

When **clicking** the arrow or popup bar to hide and show the VC, the status bar animation _works_ as expected:

![expected](https://user-images.githubusercontent.com/49026110/69385683-75ede300-0cc0-11ea-9617-f7cfae83749f.gif)

When slowly **dragging** the VC downwards, the status bar does _not_ update and gets stuck on top of the tab bar contents:

![unexpected](https://user-images.githubusercontent.com/49026110/69385908-2e1b8b80-0cc1-11ea-96c3-a855c9d44666.gif)

Have tried messing around with setNeedsStatusBarAppearanceUpdate() but no luck. Setting prefersStatusBarHidden to NO eliminates this problem.

Simulated on iPhone 8 with iOS 12.4+. Works as expected on iPhone X and above. Using latest LNPopupController framework.

**Comment by LeoNatan** [comment]
Thanks
Will look into it when I have time.

**Comment by LeoNatan** [comment]
Is it reproducible in the example project?

**Comment by dancarasco** [comment]
Thanks for the fast response @LeoNatan 

> Is it reproducible in the example project?

Yes - have set **prefersStatusBarHidden** to **YES** in the example project, and you can see the same behaviour occurs:

On **click**:

![expected_example](https://user-images.githubusercontent.com/49026110/69387180-5c02cf00-0cc5-11ea-9d0d-94471ffef161.gif)

The "Gallery" button re-appears in the _correct_ place.

On **drag**:

![unexpected_example](https://user-images.githubusercontent.com/49026110/69387216-7b016100-0cc5-11ea-9201-e30af36e6ef6.gif)

The "Gallery" button is further up than it should be.

**Comment by LeoNatan** [comment]
Thanks for checking. I will take a look.

**Comment by LeoNatan** [comment]
Will look into this tomorrow.

**Comment by LeoNatan** [comment]
Fixed in master, will release a new version soon.
