### ISSUE TITLE
Hide Popup bar for some view controllers in swift

### ISSUE THREAD

**Issue by bvsairam49** [LeoNatan/LNPopupController#375]
#### Description

First i want to thank you for the great framework.
I'm using Tabbar controller and I want to hide popup bar in some viewcontrollers/screens like settings screen or user profile screen. Whenever come out of those screens popup bar should visible automatically. is this possible currently? if yes please let me know how to achieve.
#### Device, OS and Xcode Versions

Xcode 10.2 and testing in a simulator

**Comment by iDevelopper** [comment]
- (void)dismissPopupBarAnimated:completion: 

Not the trick?

**Comment by LeoNatan** [comment]
@bvsairam49 There is no automatic way to do this, but as @iDevelopper has suggested, you can dismiss and present the popup bar without animation to achieve this. You need to set a delegate to your tab bar, and listen to changes in selected view controllers, and dismiss or present the bar accordingly.
