### ISSUE TITLE
how to show a progress in popupbar?

### ISSUE THREAD

**Issue by tianzhaotong2012** [LeoNatan/LNPopupController#379]

**Comment by tianzhaotong2012** [comment]
i can't find a example in https://github.com/LeoNatan/LNPopupController/tree/master/LNPopupControllerExample

**Comment by LeoNatan** [comment]
You set the `progressViewStyle` to either `.bottom` or `.top`, then set the `progress` of your popup item.

**Comment by tianzhaotong2012** [comment]
thanks for your answer.
but i use this code
self.popupItem.title = LOCSTR(@"未在播放");
    self.popupItem.image = [UIImage imageNamed:@"AppIcon60x60@3x"];
    self.popupBar.progressViewStyle = LNPopupBarProgressViewStyleTop;
    self.popupItem.progress = 0.4;

not work.Unfortunate

**Comment by LeoNatan** [comment]
`self.popupBar` is probably incorrect.
The correct `popupBar` is on the view controller which you present `self` on.

**Comment by tianzhaotong2012** [comment]
thanks
code ‘self.popupItem.image = [UIImage imageNamed:@"AppIcon60x60@3x"];’ is useful. 
so self.popupBar is also ok.
but still have problem.

**Comment by tianzhaotong2012** [comment]
https://github.com/LeoNatan/LNPopupController/blob/master/Supplements/rtl_english.png

excuse me . if i use the correct code, the progress bar will show on the popupItem.title just like this screenshot?

**Comment by LeoNatan** [comment]
The screenshot does not display the progress view.

**Comment by tianzhaotong2012** [comment]
yes， but i can't find an example . https://github.com/LeoNatan/LNPopupController/tree/master/LNPopupControllerExample
can u provide one in your example project by object C? 
thanks.

**Comment by LeoNatan** [comment]
In FirstViewController.m, change the following line:

```
targetVC.popupBar.progressViewStyle = [[[NSUserDefaults standardUserDefaults] objectForKey:PopupSettingsProgressViewStyle] unsignedIntegerValue];
```
to
```
targetVC.popupBar.progressViewStyle = LNPopupBarProgressViewStyleTop;
```

It will look like this:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-29 at 11 49 35](https://user-images.githubusercontent.com/2270433/73345862-82c51f00-428d-11ea-91a0-52b2b9121a29.png)

**Comment by tianzhaotong2012** [comment]
yes i see 
thanks

**Comment by tianzhaotong2012** [comment]
hello, excuse me.
how to set popupbar like the apple music.
i try this code but not satisfied. default background is white in my app.
vc.popupBar.backgroundColor = [UIColor colorWithWhite:230.0 / 255.0 alpha:0.9];
thanks

**Comment by LeoNatan** [comment]
Read the headers please.

**Comment by JacobDaneh** [comment]
This code works for me. I have a TabbarController and NavigationController:

`tabBarController?.popupBar.progressViewStyle = .bottom
tabBarController?.popupBar.progressView.tintColor = .red

DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
    self.tabBarController?.popupBar.progressView.progress = 0.34
}`
