### ISSUE TITLE
Properly remove and fully deallocate content view controller upon dismissing popup bar

### ISSUE THREAD

**Issue by msimonetta** [LeoNatan/LNPopupController#38]
Any help would be greatly appreciated - I have a view controller that has a table view of audio tracks that plays them via AVPlayer. When I call dismissPopupBar the audio keeps playing and makes me believe that the view controller and it's objects are still in memory.

**Comment by LeoNatan** [comment]
Hmm, I'll check. Have you put a breakpoint in your controller's dealloc/deinit and see that it is indeed not called?

**Comment by msimonetta** [comment]
I have. 

Regards,

Michael Simonetta

**Comment by LeoNatan** [comment]
@msimonetta Hi,

Just tested the demo project and both Swift and ObjC popup content view controllers are released. Your problem is likely due to bad memory management on your end. Let me know if you need help.
