### ISSUE TITLE
UIBarButtonSystemItemFixedSpace breaks the popupItem Buttons (iOS 13)

### ISSUE THREAD

**Issue by joshuaseltzer** [LeoNatan/LNPopupController#381]
#### Description
Adding a UIBarButtonItem defined as a system item with the type UIBarButtonSystemItemFixedSpace breaks the popup bar buttons completely.

#### Steps to Reproduce
In the Objective-C demo app, simply add the following code to create a fixed item Bar Button Item and add it to the left or right bar button items array on the PopupItem object:
```
UIBarButtonItem *spacerBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace target:nil action:nil];
    spacerBarButtonItem.width = 20.0;
```

Notice afterward that the buttons no longer respond to taps and the text on the popup bar now overlaps the buttons completely.

#### Workaround
I can simply create a regular bar button item with a blank title and set it's width like this:
```
UIBarButtonItem *spacerBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:nil style:UIBarButtonItemStylePlain target:nil action:nil];
        spacerBarButtonItem.width = 20.0;
```

#### Device, OS and Xcode Versions
iPhone 8 (Simulator), iOS 13.3, Xcode 11.3.1

**Comment by LeoNatan** [comment]
Fixed. Space bar button items do not generate views, which was causing a layout bug. Should look good now.

![Spacing](https://user-images.githubusercontent.com/2270433/89109428-bb66d080-d449-11ea-884a-fa2b8e0ecaf1.png)
