### ISSUE TITLE
PopupBar title color issue

### ISSUE THREAD

**Issue by mkeshnoda** [LeoNatan/LNPopupController#382]
Hi, i am using the version 2.8.5 and I can't change PopupBar's title color with the `titleTextAttributes`. Inside my ViewController, i am trying to change color like this 
`self.popupBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.red]`
**AND ALSO** 
`LNPopupBar.appearance().titleTextAttributes` doesn't appear.

**Swift 5
ios13 - ios12**

**Comment by LeoNatan** [comment]
Please looks at the example project. This functionality works.

**Comment by mkeshnoda** [comment]
I don't understand isn't this enough? `self.popupBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.red]`

**Comment by mkeshnoda** [comment]
in the console i am having 

```
(lldb) po _titleTextAttributes
 nil
```

**Comment by LeoNatan** [comment]
It should be enough. You are most likely applying it to the incorrect popup bar object. Please see the example project.

**Comment by iDevelopper** [comment]
@mkeshnoda , With which container controller do you present the popup bar? Is it self (your view controller) or a tab bar controller or a navigation controller? You have to access to the popup bar properties with the same controller. Example:
```swift
 self.tabBarController?.popupBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.red]
```
