### ISSUE TITLE
Refer to customBarViewController always gives `nil`

### ISSUE THREAD

**Issue by StackHelp** [LeoNatan/LNPopupController#383]
I am trying to use the custom controller as a `popupBar` and for that, I set up code like 

        let customPlayerBar = PlayerPopUpBarVC.instantiate()
        self.tabBarController?.popupBar.customBarViewController = customPlayerBar
        self.tabBarController?.presentPopupBar(withContentViewController: vc, openPopup: true, animated: true, completion: nil)

Now, the problem is when I'm trying to refer `customBarViewController`, it gives me `nil`

        if let customItem = self.tabBarController?.popupBar.customBarViewController as? PlayerPopUpBarVC { } // I got nil here 

So, What's the correct way to refer `customBarViewController` that we can change/ update elements that are part of it.

#### Device, OS and Xcode Versions

Simulator: iPhone 11, XCode Version 11.2.1, iOS 13
Device:  iPhone 7, XCode Version 11.2.1, iOS 13

**Comment by iDevelopper** [comment]
1. Is customPlayerBar inherit from LNPopupCustomBarViewController?

2. To update popupItem: popupItem is accessible from your vc (the popupContentViewController)

**Comment by StackHelp** [comment]
@iDevelopper 

1. Yes `class PlayerPopUpBarVC: LNPopupCustomBarViewController`

     class PlayerPopUpBarVC: LNPopupCustomBarViewController {
     @IBOutlet weak var songImageView: UIImageView!
     @IBOutlet weak var songTitleLabel: UILabel!

2. I don't understand this

**Comment by iDevelopper** [comment]
And what about po self.tabBarController.popupBar

**Comment by StackHelp** [comment]
@iDevelopper It's `nil` as well

**Comment by iDevelopper** [comment]
From which controller?

**Comment by StackHelp** [comment]
@iDevelopper playerViewController

        let vc = PlayerViewController.instantiate()

        let customPlayerBar = PlayerPopUpBarVC.instantiate()
        self.tabBarController?.popupBar.customBarViewController = customPlayerBar
        self.tabBarController?.presentPopupBar(withContentViewController: vc, openPopup: true, animated: true, completion: nil)


I am calling `if let customItem = self.tabBarController?.popupBar.customBarViewController as? PlayerPopUpBarVC { }` in `PlayerViewController` which is contentViewController

**Comment by iDevelopper** [comment]
In your playerViewController, which is the contentViewController, you simply access the popuItem like this:

self.popupItem

**Comment by StackHelp** [comment]
Here is the log in `playerViewController`

    (lldb) po self.popupPresentationContainer?.popupBar.customBarViewController
    nil

    (lldb) po self.popupPresentationContainer?.popupBar
    nil

    (lldb) po self.popupPresentationContainer
    nil

**Comment by iDevelopper** [comment]
I think you are in the viewDidLoad function, try in viewWillAppear.

**Comment by StackHelp** [comment]
@iDevelopper  But why?  If it's there in `popupPresentationContainer`, then whenever we call we should have to get it.

**Comment by iDevelopper** [comment]
popupPresentationContainer is set during the popup bar presentation. You probably load your playerViewController before the presentation...

**Comment by iDevelopper** [comment]
Do you need to access to popupPresentationContainer in viewDidLoad? Why?

**Comment by StackHelp** [comment]
I am loading it as it described in doc `    self.tabBarController?.presentPopupBar(withContentViewController: vc, openPopup: true, animated: true, completion: nil)`

**Comment by iDevelopper** [comment]
Yes, this is how you present the popup bar. But your vc (the player view controller) is already allocated and his view loaded. Then in viewDidLoad you can't have access to popupPresentationContainer. Search why his view is already loaded. Look at your instantiate() function... And put a breakpoint in viewDidLoad() function, you will see that the view is loaded before the popup bar presentation.

**Comment by StackHelp** [comment]
@iDevelopper I don't understand this scenario. can you help me If I am sharing my screen?

**Comment by iDevelopper** [comment]
You can share your screen but your code is welcome to understand. I ask the question again:

Do you need to access to popupPresentationContainer in viewDidLoad?

**Comment by StackHelp** [comment]
@iDevelopper I want it on a runtime, like when song loads or song change

**Comment by iDevelopper** [comment]
Can you present the popup bar and set currentMedia in the completion block? A least for the first song...

**Comment by StackHelp** [comment]
@iDevelopper  ok. Let me try

**Comment by StackHelp** [comment]
@iDevelopper Yes SIr, It worked. Now I understood that the thing is PlayerView Loads even before completing presentation of popupBar and that's why it's not even in hierarchy of controllers and that's why it produces `nil`. Thanks a lot for your help and giving this issue too much time.

**Comment by iDevelopper** [comment]
@StackHelp , glad to hear it works!

> I have checked you have a git repo for Swift version as well but I don't think it supports custom controller yet.

This framework support custom bars. But a little outdated, I will update with a new version soon. If you want to test?... The main difference with LN is that this framework uses fewer private APIs and animates views (such as image or controls), as the Apple Music application does.

**Comment by StackHelp** [comment]
@iDevelopper Yes, I will surely test it once you updated it. I like to do that.
