### ISSUE TITLE
Changing Docking View on Catalyst Removes Whole View

### ISSUE THREAD

**Issue by aidev1065** [LeoNatan/LNPopupController#385]
#### Description
Hi!
So I have a Podcast Player app on iOS and I've ported it over to macOS using UIKitForMac. Your library works well when connected to my tab bar. However, to make the Mac app feel more Mac-like, I've changed the tab bar to a toolbar.

Now without the following code, the popups still appear but there's a gap in between the bottom of the popup and the bottom of the screen. To remove this, I tried overriding `bottomDockingViewForPopupBar` and `defaultFrameForBottomDockingView` in my custom tab bar view controller. However, now when I call the popup to be presented, it completely removes every view. I've attached a before and after picture of calling the popup to be presented. The popup presents but the container view disappear.

#### Steps to Reproduce
Here is the code I used:
```swift
class CustomTabBarViewController: UITabBarController {
#if targetEnvironment(macCatalyst)
    override var bottomDockingViewForPopupBar: UIView? {
        return self.view
    }
    
    override var defaultFrameForBottomDockingView: CGRect {
        var bottomViewFrame = self.view.frame
        bottomViewFrame.origin = CGPoint(x: bottomViewFrame.origin.x, y: view.bounds.size.height)
        return bottomViewFrame
    }
#endif
}
```

#### Device, OS and Xcode Versions
I'm on Xcode 11.4.1 and macOS 10.15.4 
<img width="704" alt="Screen Shot 2020-04-19 at 8 03 32 PM" src="https://user-images.githubusercontent.com/28992343/79710126-e2254080-8278-11ea-8386-1b14f5639786.png">
<img width="704" alt="Screen Shot 2020-04-19 at 8 03 36 PM" src="https://user-images.githubusercontent.com/28992343/79710148-f2d5b680-8278-11ea-8685-b378993b8812.png">

**Comment by LeoNatan** [comment]
Hello,

I don't think returning the view itself is a good idea. Instead, on Mac add a transparent UIView to the bottom of your tab bar controller's view, and use that as your docking view. Wrap the addition of that view with `#if targetEnvironment(macCatalyst)` as you have done in your code too.

Let me know how it goes.

**Comment by aidev1065** [comment]
Hey! Thanks for the suggestion! It worked out if I set it to another small view. Thanks!!

**Comment by LeoNatan** [comment]
Great! Cool app!
