### ISSUE TITLE
iOS 13 tabbar layout delay when using setHidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by ibespaljkocs** [LeoNatan/LNPopupController#386]
#### Description
UITabbar has a layout delay if setHidesBottomBarWhenPushed is set to YES when opening another screen (e.g: details screen with no bottom tabbar). Layout delay happens on back action, when user returns to previous screen.
This is present only on iOS 13 when **not** using storyboards!

iOS 13 + storyboard -> OK.
iOS < 13 + storyboards -> OK.
iOS < 13 w/o storyboards -> OK (e.g: using nibs or manually creating UITabBarController)
Also, it works OK on any iOS if animations are turned off with [UIView setAnimationsEnabled:NO]

#### Steps to Reproduce
0. Do not use storyboard (except the LaunchScreen.storyboard)
1. Use a UITabBarController as a rootViewController of your main window
2. From selected tab, go to another UIViewController (e.g: DetailsVC) with option setHidesBottomBarWhenPushed set to YES, to hide the bottom bar.
4. On DetailsVC show PopupBar by calling [self.tabBarController presentPopupBarWithContentViewController:dummyVC animated:YES completion:nil];
5. Return to rootViewController with back action.

Behaviour: PopupBar is moved up as expected, but UITabbar is shown with some delay.
Video: https://drive.google.com/file/d/1mZCrRn07NXj0MT4ji4XD_HCG9wjFvibG/view

#### Device, OS and Xcode Versions
iPhone SE, iPhone 11 with iOS 13 (confirmed on 13.4.1 also)

**Comment by LeoNatan** [comment]
Heh, what an odd issue. I don't see why a storyboard presence would influence the layout timing, unless Apple is doing something fishy.

I don't have much time these days, but I will take a look when I can. Thanks

**Comment by ibespaljkocs** [comment]
Yes, sounds strange, I agree. 
I've just created a simple storyboard with only UITabBarController in it..then subclassed UITabBarController with custom class, assigned it to UITabBarController class in storyboard. Now it works like a charm!

**Comment by ivanrein** [comment]
@ibespaljkocs do you have a workaround for this?

**Comment by LeoNatan** [comment]
I'll look at this tomorrow. I haven't seen this reproduce, but will try to.

**Comment by LeoNatan** [comment]
Reproduced, investigating.

**Comment by LeoNatan** [comment]
Fixed. For some reason, when the tab bar is not created from a storyboard, the frame was being overridden. Should work well now.
