### ISSUE TITLE
SPM Support?

### ISSUE THREAD

**Issue by muhasturk** [LeoNatan/LNPopupController#387]
Quite simple to add Package.swift and point source files. 
Could you please add swift package manager support?

**Comment by LeoNatan** [comment]
Hello,
I don't have much experience with it. Would you be interested in submitting a PR and updating the docs with an explanation how to install?

Thanks

**Comment by muhasturk** [comment]
Ok, let me develop, will send PR.

**Comment by LeoNatan** [comment]
Just to be sure, does SPM guarantee a framework output with a module, so things like `@import LNPopupController;` are handled correctly?

Also, the framework currently has an asset catalog. SPM doesn't currently support assets. I read that Swift 5.3 will finally add that in SPM, so maybe best to wait until then.

**Comment by muhasturk** [comment]
You are right, 5.3 will add support for Binary Dependencies, we can wait until released.

https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md

**Comment by LeoNatan** [comment]
It’s mind boggling that it took so long to develop this. 🤦‍♂️

**Comment by fruitcoder** [comment]
Binary dependencies and resources are now supported in SPM :)

**Comment by LeoNatan** [comment]
Hmm, so it requires that all sources be in `Sources/`? :(

I might implement this using soft links, I don't like losing history on the files just for SPM.

**Comment by LeoNatan** [comment]
I've created the SPM branch with my attempt:

https://github.com/LeoNatan/LNPopupController/tree/SPM
https://github.com/LeoNatan/LNPopupController/blob/SPM/Package.swift

Can't get the build system to find my public headers. I am using `#import <LNPopupController/Header.h>` syntax for publicly exposed headers, but Xcode complains that it cannot find the header. I will not change the import syntax to `#import "Header.h"`.

@muhasturk @fruitcoder If you'd like to assist here, I'd be grateful.

**Comment by LeoNatan** [comment]
Got it working.

**Comment by fruitcoder** [comment]
Oh wow @LeoNatan that's amazing 🥳

**Comment by LeoNatan** [comment]
Cheers!

**Comment by funkenstrahlen** [comment]
Thank you for supporting this :)
