### ISSUE TITLE
Change height of Compact bar

### ISSUE THREAD

**Issue by johnswifttt** [LeoNatan/LNPopupController#388]
#### Description

Hello! This is simply a question. Is it possible to change the height of the `Compact` mini player bar? I really like the design of this bar style versus the `Prominent`. I just wish I could adjust the height of the `Compact` bar. If this is not possible, could you suggest how I could do this in a fork or maybe a PR to help you?

This is a picture of the `Compact` mini player. It would be great to increase the height.
<img width="372" alt="compact" src="https://user-images.githubusercontent.com/10701375/86982693-e5351c00-c157-11ea-8a9d-d5dbdb2c3719.png">

#### Steps to Reproduce
n/a

#### Device, OS and Xcode Versions
n/a

**Comment by iDevelopper** [comment]
You can use LNPopupBarContentViewController to customise your own popup bar. See the map scene in the example.

**Comment by johnswifttt** [comment]
> You can subclass LNPopupCustomBarViewController to customise your own popup bar. See the Demo - Custom Pupup Bar Scene (Swift) & MapScene.storyboard in the example.

@iDevelopper Oh so it looks like I can make the popup completely custom. It could look anyway I want. It looks like I need to use this API right?

```objective-c
- (void)setCustomBarViewController:(LNPopupCustomBarViewController*)customBarViewController
```

The call site is:
```swift
popupBar.customBarViewController = customMapBar
```

**Comment by LeoNatan** [comment]
Yeah, if you use the custom bar view controller, you will need to recreate the layout on your own.

Internally, I use https://github.com/cbpowell/MarqueeLabel for the labels.

If you still want to fork, you can look into changing `LNPopupBarHeightCompact` in Private/LNPopupBar.m and how that is used to determine the height. You might need to modify the layout method to make it look better with a higher bar.

**Comment by johnswifttt** [comment]
@iDevelopper Thank you for pointing me in the right direction! 

@LeoNatan Thank you for answering! This is awesome! I think I may talk with designer and who knows, come up with something completely custom and have fun with it. Awesome library and hope you continue to maintain it!

**Comment by LeoNatan** [comment]
Thank you for the kind words!
