### ISSUE TITLE
Swipe to Dismiss Mini Popup Bar

### ISSUE THREAD

**Issue by johnswifttt** [LeoNatan/LNPopupController#389]
#### Description
Hi there! This is a simple question. I was wondering if we could swipe to dismiss the mini popup bar. 

I read the documentation and it states:
> Once a popup bar is presented with a content view controller, the user can swipe or tap the popup at any point to present the content controller. After finishing, the user dismisses the popup by either swiping or tapping the popup close button.

However, this seems to refer only to the full screen popup right? 

I was thinking maybe in the mini player like this one, if a user swipes down on it, it dismisses the mini popup completely. I could add a button that when the user taps, I programmatically close the popup for them.  
<img width="372" alt="compact" src="https://user-images.githubusercontent.com/10701375/87176134-aada9480-c2a7-11ea-8c78-df65835ea67a.png">

Is there a way to do this? (I know it's not standard behavior in Apple Music which doesn't let you dismiss the mini-player at all. It's just stuck there until you close the app. However, there are some apps that allow for swiping away, such as Calm (meditation app).)

Thank you!

#### Steps to Reproduce
n/a

#### Device, OS and Xcode Versions
n/a

**Comment by LeoNatan** [comment]
Hello,

It's not possible within the framework itself, but you can implement this on your own. Add a gesture recognizer on the popup bar. Set it up so it requires the failure of the popup bar's pan gesture recognizer and when your gesture recognizer fires, dismiss the popup bar.

**Comment by johnswifttt** [comment]
Thank you for quick reply and explanation. I could try that, but I wonder if I can control the swipe down so it looks good as user swipes away. For example, if you swipe down only a little, the mini player will swipe down only that much but not dismiss, etc. This is similar to how you did the swipe up in a really nice way.

Maybe this is more complicated than simple swipe gesture. If it is, I might not try to implement it lol

**Comment by LeoNatan** [comment]
That would require touching the bar frame, and I wouldn’t recommend it.

**Comment by johnswifttt** [comment]
lol gotcha, I'll follow your recommendation 🙂I personally don't like forking libraries and customizing too much due to future releases not being compatible. 

In this case, it seems the best way to do it is to create a custom bar with `LNPopupCustomBarViewController` and implement a gesture on it. 

Thank you again for explanation! That answers my question very clearly!

**Comment by LeoNatan** [comment]
Please note that even with a custom bar, the positioning of the bar is handled by the system.

**Comment by johnswifttt** [comment]
Ok understood, thanks for pointing that out 💯🙂

**Comment by LeoNatan** [comment]
Closing the issue as I think it's solved. Thanks
