### ISSUE TITLE
setToolBarHidden to YES issue.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#394]
#### Description
In your demo project, just set the navigation controller toolbar hidden.
```
- (UIViewController*)_targetVCForPopup
{
    UIViewController* targetVC = self.navigationController == nil ? self.splitViewController != self.view.window.rootViewController ? self.splitViewController : nil : nil;
    
    if(targetVC == nil)
    {
        targetVC = self.tabBarController;
        if(targetVC == nil)
        {
            targetVC = self.navigationController;
            
            if(targetVC == nil)
            {
                targetVC = self;
            }
            else {
                [self.navigationController setToolbarHidden:YES];
            }
        }
    }
    return targetVC;
}
```

The toolbar is not completely hidden.

And test with the drag option to open the popup content view.

#### Device, OS and Xcode Versions
Xcode 12.4 iOS 13 & 14 Simulator

**Comment by LeoNatan** [comment]
I'm not seeing an issue.

![gif](https://user-images.githubusercontent.com/2270433/89816631-92cc8e00-db4f-11ea-8739-cb996e7c44e7.gif)

**Comment by iDevelopper** [comment]
![RPReplay_Final1597119410](https://user-images.githubusercontent.com/1782450/89857881-8b33d600-db9d-11ea-9be4-8d2b771ed5d0.gif)

**Comment by iDevelopper** [comment]
Same issue using the last version: 2.9.5

**Comment by LeoNatan** [comment]
Maybe it's again a difference between a controller created in code vs storyboard. I'll look again soon.

**Comment by LeoNatan** [comment]
Please try with v2.10.0.
