### ISSUE TITLE
v. 2.9.5: Missing LNPreviewToContextMenu.xcodeproj

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#395]
#### Description
The submodule download does not seem to work.

**Comment by LeoNatan** [comment]
You need to update your submodules.

**Comment by iDevelopper** [comment]
How to do that? When I download the repo to test your example, I expect it to work in Xcode when I open it.

**Comment by LeoNatan** [comment]
No. When you clone, you need to use `--recurse-submodules`, or if you cloned without, use `git submodule update --init --recursive`. Download won't work because GitHub are too dumb to include submodule content 🤷‍♂️
