### ISSUE TITLE
UIButton action in bar controller is ignored in 2.10.0

### ISSUE THREAD

**Issue by MacMark** [LeoNatan/LNPopupController#397]
#### Description
UIButton action not triggered anymore in CustomBarViewController. It worked in 2.8.5 but not in 2.10.0 anymore.
#### Steps to Reproduce
Use an UIButton in the UIViewController that you use for setCustomBarViewController. Touch the button. The action of that button is not triggered. Instead the full screen controller is presented.

#### Device, OS and Xcode Versions
iPhone X, iOS 14, Xcode 12 beta 4

**Comment by LeoNatan** [comment]
Hmm

Thanks, will have a look soon!

**Comment by LeoNatan** [comment]
Sorry, I can't reproduce.

In the demo app, I added the following code to the custom bar controller's `viewDidLoad()` method:

```
if #available(iOS 14.0, *) {
	let button = UIButton(type: .system, primaryAction: UIAction.init(handler: { action in
		print("tapped")
	}))
	button.setTitle("BUTTON", for: .normal)
	button.sizeToFit()
	view.addSubview(button)
}
```

The button can be tapped.

**Comment by MacMark** [comment]
When visually debugging the view hierarchy i see an additional empty UIView in front of the custom bar controller with 2.10.x. Could this be an issue?

**Comment by LeoNatan** [comment]
Could you post a view hierarchy dump from Xcode 12? File -> Export View Hierarchy, and post the pointer of the offending view.

But I am not seeing this behavior in the demo app, so I'm not sure if it's something in the framework.

**Comment by MacMark** [comment]
Sorry for my late answer, i was busy updating some apps for iOS 14.

The address of the view in the attached hierarchy is 0x7fe1adff7c00.
[Popup.viewhierarchy.zip](https://github.com/LeoNatan/LNPopupController/files/5128721/Popup.viewhierarchy.zip)
<img width="774" alt="popup" src="https://user-images.githubusercontent.com/626963/91284053-b4528a00-e78b-11ea-811b-9e3a6cdcf001.png">
Behind that view is the play button which cannot be activated in my case with 2.10.1.

**Comment by LeoNatan** [comment]
Thank you!
I made some changes with later releases. Do you mind providing the same with the latest version? Will help me debug the issue better. Thanks

**Comment by MacMark** [comment]
This is the same situation recorded with 2.10.5:
[Popup-2-10-5.viewhierarchy.zip](https://github.com/LeoNatan/LNPopupController/files/5131201/Popup-2-10-5.viewhierarchy.zip)
<img width="671" alt="popup-2-10-5" src="https://user-images.githubusercontent.com/626963/91332256-3793d000-e7cc-11ea-97dd-ae181a73bdb4.png">

**Comment by LeoNatan** [comment]
Please notice that that view has `User Interaction Enabled Off`. That is not the view stealing your touches.

**Comment by LeoNatan** [comment]
I do t see anything in the framework causing this. The demo project works as expected. Try debugging the touch handling to see who finally takes it.

**Comment by MacMark** [comment]
When i break in LNPopupOpenTapGesutreRecognizer.m at the line
```if([touch.view isKindOfClass:[UIControl class]])```
po touch.view
<_LNPopupBarContentView: 0x7fd2e260f100; frame = (0 0; 414 61); layer = <CALayer: 0x6000006b68a0>>
it does not have my UIButton in touch.view.

Do i have to configure the PopUpController differently in 2.10.x than in 2.8.x?

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
	if([touch.view isKindOfClass:[UIControl class]])
	{
		return NO;
	}
	
	if([self.forwardedDelegate respondsToSelector:_cmd])
	{
		return [self.forwardedDelegate gestureRecognizer:gestureRecognizer shouldReceiveTouch:touch];
	}
	
	return YES;
}
```

**Comment by LeoNatan** [comment]
It does use it. There is a “maps” demo scene which has a custom bar controller. This is where I added a button to test. My money is on something broken on your end. Nothing changed with regards to bar controllers.

**Comment by iDevelopper** [comment]
Hi @MacMark ,
I tested too, added a button to the Maps Demo Scene custom bar controller.
[LNPopupControllerExample[66172].viewhierarchy.zip](https://github.com/LeoNatan/LNPopupController/files/5137492/LNPopupControllerExample.66172.viewhierarchy.zip)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-27 at 17 55 50](https://user-images.githubusercontent.com/1782450/91466246-2069e680-e88f-11ea-959b-71f1cf7464c4.png)

**Comment by MacMark** [comment]
I do not understand yet what might be wrong in my controller because it works with 2.8.x and just by replacing 2.8.x with 2.10.x it gets into this issue.

I will compare the sample custom bar controller with my controller.

**Comment by iDevelopper** [comment]
@MacMark ,
What about LOTAnimationView? Can you provide here the source code?

**Comment by MacMark** [comment]
Hi @iDevelopper, 
LOTAnimationView comes from https://github.com/airbnb/lottie-ios/releases/tag/2.5.3

**Comment by MacMark** [comment]
I have to find why the UIButton is not in touch.view with 2.10.5 although it is with 2.8.5 and also with the 2.10.5 sample code:
<img width="815" alt="Screenshot 2020-08-28 at 16 34 11" src="https://user-images.githubusercontent.com/626963/91579898-95e7bc80-e94c-11ea-929a-b440fdf7db27.png">
<img width="823" alt="Screenshot 2020-08-28 at 16 30 56" src="https://user-images.githubusercontent.com/626963/91579907-98e2ad00-e94c-11ea-9c45-d7ea8954737d.png">
<img width="764" alt="Screenshot 2020-08-28 at 16 27 36" src="https://user-images.githubusercontent.com/626963/91579920-9c763400-e94c-11ea-9ea0-49b5cf040e41.png">

**Comment by iDevelopper** [comment]
@MacMark ,
Have you tested without LOTAnimationView?

**Comment by MacMark** [comment]
When i put a 2nd button in there that does nothing, my play button gets the touch and works and the touch.view contains my PlayPauseButton on the above break point just like with 2.8.5. How is such a side effect possible?
<img width="371" alt="image" src="https://user-images.githubusercontent.com/626963/91584804-7902b780-e953-11ea-9606-dc00cada4b80.png">

**Comment by LeoNatan** [comment]
The custom bar controller is added directly to the popup up bar content view:
https://github.com/LeoNatan/LNPopupController/blob/139a067cba92a3a1fff25c5e5c59c15591e314f0/LNPopupController/LNPopupController/Private/LNPopupBar.m#L1161

@MacMark Let's try an experiment. Could you create a new subclass of the custom bar controller, with no logic in it, just a button? Let's see if that button works.

**Comment by MacMark** [comment]
As long as the custom controller has also a normal UIButton (it might even be hidden) the PlayPauseButton (subclass of LottieButton which is in turn a subclass of UIButton) works as normal (receives the touch because it is in touch.view).
I gave the normal button now an action which just removes the normal button from the view hierarchy.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/626963/91589659-68097480-e95a-11ea-92a8-426b8e94a578.png">
Now the fun part: The PlayPauseButton works as often as i like until i use the normal button: The normal button is removed and now the PlayPauseButton is not recognized anymore.
The touch.view is only correct (i. e. contains the touched control, not the _LNPopupBarContentView) as long as i have a direct subclass of UIButton in my controller.

**Comment by LeoNatan** [comment]
WTF is going on. I can't explain it.
Can you check and see if your special button (not the normal one) has a gesture recognizer? Have you added a gesture recognizer elsewhere in your bar controller's view hierarchy?

**Comment by iDevelopper** [comment]
@MacMark ,
Can you provide a small project reproducing this issue (with the lottieButton in it)?

**Comment by MacMark** [comment]
I paused the app via Xcode, selected the PlayPauseButton and then printed its description

<img width="609" alt="image" src="https://user-images.githubusercontent.com/626963/91636305-c89ebd00-e9ff-11ea-9eef-40fabba714ac.png">

Printing description of $43:
<PlayPauseButton: 0x7fc4f6c152c0; baseClass = UIButton; frame = (364 9; 40 40); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x600000652bc0>>

(lldb) po 0x7fc4f6c152c0
<PlayPauseButton: 0x7fc4f6c152c0; baseClass = UIButton; frame = (364 9; 40 40); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x600000652bc0>>

(lldb) po [(id)(0x7fc4f6c152c0) class]
PlayPauseButton

(lldb) po [(id)(0x7fc4f6c152c0) superclass]
LottieButton

(lldb) po [[(id)(0x7fc4f6c152c0) superclass] superclass]
UIButton

@LeoNatan This should be the view hierarchy according to [Apple's docs](https://developer.apple.com/library/archive/technotes/tn2239/_index.html#//apple_ref/doc/uid/DTS40010638-CH1-SUBSECTION34):
```
(lldb) po [(id)(0x7fc4f6c152c0) recursiveDescription]
<PlayPauseButton: 0x7fc4f6c152c0; baseClass = UIButton; frame = (364 9; 40 40); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x600000652bc0>>
   | <UIImageView: 0x7fc4f6d09b50; frame = (2 2; 36 36); clipsToBounds = YES; hidden = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000603060>>
   | <LOTAnimationView: 0x7fc4f6fef550; frame = (2 2; 36 36); clipsToBounds = YES; userInteractionEnabled = NO; layer = <CALayer: 0x6000007f6800>>
   |    | <LOTCompositionContainer: 0x600003218cc0> (layer)
   |    |    | <CALayer: 0x6000007ef200> (layer)
   |    |    |    | <LOTLayerContainer: 0x600003518870> (layer)
   |    |    |    |    | <CALayer: 0x6000007e8d60> (layer)
   |    |    |    |    |    | <CALayer: 0x6000007eb960> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007d65e0> (layer)
   |    |    |    |    |    |    |    | <CAShapeLayer: 0x6000007d42e0> (layer)
   |    |    |    | <LOTLayerContainer: 0x600003518900> (layer)
   |    |    |    |    | <CALayer: 0x6000007d7460> (layer)
   |    |    |    |    |    | <CALayer: 0x6000007d43e0> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007d7fa0> (layer)
   |    |    |    |    |    |    |    | <CAShapeLayer: 0x6000007d6be0> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007d70a0> (layer)
   |    |    |    |    |    |    |    | <CAShapeLayer: 0x6000007d7b40> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007d6540> (layer)
   |    |    |    | <LOTLayerContainer: 0x600003518990> (layer)
   |    |    |    |    | <CALayer: 0x6000007d06c0> (layer)
   |    |    |    |    |    | <CALayer: 0x6000007defe0> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007dc440> (layer)
   |    |    |    |    |    |    |    | <CAShapeLayer: 0x6000007dc500> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007debe0> (layer)
   |    |    |    |    |    |    |    | <CAShapeLayer: 0x6000007defc0> (layer)
   |    |    |    | <LOTLayerContainer: 0x600003518a20> (layer)
   |    |    |    |    | <CALayer: 0x6000007dee20> (layer)
   |    |    |    |    |    | <CALayer: 0x6000007db660> (layer)
   |    |    |    |    |    |    | <CALayer: 0x6000007da240> (layer)
   |    |    |    |    |    |    |    | <CAShapeLayer: 0x6000007da4e0> (layer)
```

@iDevelopper I will try and provide a small sample reproducing it.

**Comment by SalarDastan** [comment]
> This is the same situation recorded with 2.10.5, the play button is not getting the user's touch. Something is intercepting it since 2.10.x (i did not try 2.9.x). The button works when i use to 2.8.5.
> Printing description of $19:
> <_LNPopupBarShadowView: 0x7ff83bb294b0; frame = (0 0; 828 61); alpha = 0; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x60000267b5e0>>
> [Popup-2-10-5.viewhierarchy.zip](https://github.com/LeoNatan/LNPopupController/files/5131201/Popup-2-10-5.viewhierarchy.zip)
> <img alt="popup-2-10-5" width="671" src="https://user-images.githubusercontent.com/626963/91332256-3793d000-e7cc-11ea-97dd-ae181a73bdb4.png">
> 
> But there's also good news: The layout issues i experienced with 2.10.1 are fixed :-)

Hello may i ask you how did u generate that file and What is it used for?

**Comment by MacMark** [comment]
The problem seems to be that the height of the view of the custom controller shrinks to zero:
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/626963/91659153-7a0c2400-eace-11ea-813e-e80d5578dfc1.png">

**Comment by MacMark** [comment]
This is a minimal project showing my problem. The popup and the play button work fine (it logs a debug output). As soon as the blue button is hit, it removes itself from superview and the play button stops working because the setPreferredContentSize in LNPopupCustomBarViewController seems to go to zero height. This was not the case with 2.8.5. Proof: Replace 2.10.5 in the Podfile with 2.8.5 and run "pod install". Run the project again. And it will work fine.
[PopupMinTest.zip](https://github.com/LeoNatan/LNPopupController/files/5146869/PopupMinTest.zip)
<img width="484" alt="image" src="https://user-images.githubusercontent.com/626963/91660540-decb7c80-ead6-11ea-82de-f0f047fb4b23.png">

**Comment by LeoNatan** [comment]
Do you correctly set the `preferredContentSize` property of your view controller properly?

**Comment by LeoNatan** [comment]
Check what size is returned from your calculation.

**Comment by MacMark** [comment]
It is 
(lldb) po size
(width = 444, height = 61)
on iPhone 11
<img width="804" alt="image" src="https://user-images.githubusercontent.com/626963/91689845-31ec1080-eb65-11ea-9346-e5be60d59f58.png">

**Comment by MacMark** [comment]
I guess i found the piece of code that set the frame's height to zero:
```frame.size.height = state < _LNPopupPresentationStateTransitioning ? _LNPopupBarHeightForBarStyle(_LNPopupResolveBarStyleFromBarStyle(self.popupBar.barStyle), self.popupBar.customBarViewController) : 0.0;```
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/626963/91694189-89da4580-eb6c-11ea-96d4-ee75e1557b9a.png">

**Comment by iDevelopper** [comment]
The problem seems to be there (LNPopupBar.m line 1161):

Replace:
```objective-c
	_customBarViewController.view.translatesAutoresizingMaskIntoConstraints = NO;
	[self.contentView addSubview:_customBarViewController.view];
	[NSLayoutConstraint activateConstraints:@[
		[self.contentView.leadingAnchor constraintEqualToAnchor:_customBarViewController.view.leadingAnchor],
		[self.contentView.trailingAnchor constraintEqualToAnchor:_customBarViewController.view.trailingAnchor],
		[self.contentView.centerXAnchor constraintEqualToAnchor:_customBarViewController.view.centerXAnchor],
	]];
```
with:
```objective-c
	_customBarViewController.view.translatesAutoresizingMaskIntoConstraints = NO;
	[self.contentView addSubview:_customBarViewController.view];
	[NSLayoutConstraint activateConstraints:@[
		[self.contentView.leadingAnchor constraintEqualToAnchor:_customBarViewController.view.leadingAnchor],
		[self.contentView.trailingAnchor constraintEqualToAnchor:_customBarViewController.view.trailingAnchor],
		//[self.contentView.centerXAnchor constraintEqualToAnchor:_customBarViewController.view.centerXAnchor],
        [self.contentView.topAnchor constraintEqualToAnchor:_customBarViewController.view.topAnchor],
        [self.contentView.bottomAnchor constraintEqualToAnchor:_customBarViewController.view.bottomAnchor]
	]];
```

**Comment by MacMark** [comment]
@iDevelopper I replaced the code like you suggested and **it works** with the demo project and also with my original app 👍 ✌️🎉 (And thus [my previous comment was wrong](https://github.com/LeoNatan/LNPopupController/issues/397#issuecomment-683615287)).

**Comment by iDevelopper** [comment]
@LeoNatan ,
The Maps Demo Scene works but there is a constraint issue (look at the debug view hierarchy).

However, with a tab bar controller, it not works. The vertical constraints of the custom bar view controller' view are ambiguous, and its height is equal to zero. This is why the button is misplaced (because I have set somme constraints to it) and is not triggered.

Here is a very small sample project that demonstrates the issue.
[LNCustomBarTest.zip](https://github.com/LeoNatan/LNPopupController/files/5149167/LNCustomBarTest.zip)

**Comment by LeoNatan** [comment]
It's like this for a reason. The fix should be different. I will take a look soon.

**Comment by iDevelopper** [comment]
Ah and what is the reason, please?

**Comment by LeoNatan** [comment]
There were multiple popup bar layout issues without this. I need to understand why the layout is failing in this case, but not in the example project. Could still be a user error.

**Comment by LeoNatan** [comment]
I think I'm starting to see where the issue is. In my demo scene, the controller has constraints that express its size, where as in the example, this isn't the case.

**Comment by LeoNatan** [comment]
I'm not sure adding a constraint is the right thing to do. It might just be the case that if you are using auto layout, you should have all the constraints yourself. If I add a height constraint in the framework, it breaks genuine cases where one might want to change the height of the bar using a constraint, and then rely on [`systemLayoutSizeFittingSize:`](https://developer.apple.com/documentation/uikit/uiview/1622624-systemlayoutsizefittingsize?language=objc) to calculate the `preferredContentSize` property.

**Comment by LeoNatan** [comment]
OK, I've made an improvement. Please test.

The system now takes into account `translatesAutoresizingMaskIntoConstraints` of the controller's view and lays it in the popup bar accordingly.

**Comment by iDevelopper** [comment]
Now, after updating the example project with the 2.10.6 release:
[LNCustomBarTest.zip](https://github.com/LeoNatan/LNPopupController/files/5160615/LNCustomBarTest.zip)
There is no more effect, and no more shadow line on top of the popup bar. The bar is completely transparent.

**Comment by MacMark** [comment]
When using 2.10.6 with my app the play button works again ✌️😍

**Comment by LeoNatan** [comment]
Just to make sure, the issue is that the bottom inset is not correctly set? Please open an issue.

**Comment by MacMark** [comment]
Yes, it is the bottom inset. Thx, i will open a new issue.
