### ISSUE TITLE
LNPopupController problem with UISearchController

### ISSUE THREAD

**Issue by MarvinNazari** [LeoNatan/LNPopupController#4]
Hi, LNPopupController dosent allow to click on keyboard, i have made a test project so u can test it, when u touch UISearchBar, keyboard shows up but its not clickable, it happens even when u don't present the popup bar!

[here u can check the test project](https://github.com/MarvinNazari/KeyboardProblem)

love the project btw!! awesome

**Comment by LudvigOdin** [comment]
Have the same problem here, didn't get it to work!

**Comment by LeoNatan** [comment]
@MarvinNazari @LudvigOdin Thanks guys, will look into it as soon as I can.

**Comment by MarvinNazari** [comment]
Hi @LeoNatan, any news on this? we really need to submit the app tomorrow :)

**Comment by LeoNatan** [comment]
@MarvinNazari I am looking at your demo project, and I don't see how this is the popup controller's fault. In fact, I removed the framework from your project, and the issue still occurs.

**Comment by MarvinNazari** [comment]
If u remove the framework completely from project it works as it should.

**Comment by MarvinNazari** [comment]
also from embedded binaries in project General setting

**Comment by LeoNatan** [comment]
I deleted the files entirely from disk, and cleaned all build folders and derived data. I see the same issue as before, when running on iOS 9 simulator.

**Comment by MarvinNazari** [comment]
Can u check it with iOS 8?

**Comment by LeoNatan** [comment]
I see a different problem on my own demo project with a search bar (different to the problem I see in your project). Will investigate, but I am not sure if will have time, if it is something complex.

**Comment by MarvinNazari** [comment]
Yeah i have an issue with the searchBar on iOS 9, but that i can fix. On iOS 8, the keyboard is not clickable. and that happens when i add the LNPopupController to my project

**Comment by LeoNatan** [comment]
I am looking into it.

**Comment by LeoNatan** [comment]
Ha, found the problem and fixed. Will push in a minute.

**Comment by MarvinNazari** [comment]
Oh thanks man :) awesome!!! :heart:
