### ISSUE TITLE
Change progress bar color

### ISSUE THREAD

**Issue by msimonetta** [LeoNatan/LNPopupController#40]
How do I achieve changing the progress bar color?

**Comment by LeoNatan** [comment]
The progress bar uses the tint color of the bar. Change that to change the progress bar color.

**Comment by msimonetta** [comment]
This did not work - can I get a code snippet on how to achieve this please.

**Comment by LeoNatan** [comment]
Take a look at the demo project. Notice when tapping the style button, the progress bar color also changes.

**Comment by yarodevuci** [comment]
@LeoNatan what if i only need progress view color not bar tint?

**Comment by LeoNatan** [comment]
@yarodevuci You can use appearance API to set the tint color of the progress view when contained in a LNPopupBar.

**Comment by yarodevuci** [comment]
@LeoNatan Can you specify how can I access to progress view? navigationController?.popupBar. ?

**Comment by LeoNatan** [comment]
Use appearance API.

```objc
[[UIProgressView appearanceWhenContainedIn:[LNPopupBar class], nil] setProgressTintColor:[UIColor greenColor];
```

Or the Swift equivalent.

**Comment by yarodevuci** [comment]
UIProgressView.appearance(whenContainedInInstancesOf: [LNPopupBar.self]).tintColor = .red

Thank you

**Comment by patwhitehead1** [comment]
I'm getting an issue when trying to change the progress color. The first time I update it, it works fine. But any time I try to change it, it still shows the old color.

My code:
UIProgressView.appearance(whenContainedInInstancesOf: [LNPopupBar.self]).tintColor = progressColor

Have you come across this issue before with UIAppearance?

**Comment by patwhitehead1** [comment]
Currently I present the popup once, and just update it with new info as the user listens to new tracks. The progress color is based on the associated artwork with each track.

Side note, this framework has been a huge help as we develop our app, so thanks for making this available!

**Comment by LeoNatan** [comment]
@patwhitehead1 Please open a new issue. I will expose the progress view as a property of the bar, so you can update it.

**Comment by LeoNatan** [comment]
For now, you can use KVC to get to it: `[[self.popupBar valueForKey:@"progressView"] setTintColor:[UIColor redColor]]`

**Comment by patwhitehead1** [comment]
Thanks!

[Added new issue here](https://github.com/LeoNatan/LNPopupController/issues/315)

Using KVC for now, and it's working as expected. Thanks for the workaround.
