### ISSUE TITLE
PopupCloseButton - Proposal for a new feature.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#401]
Hi @LeoNatan ,
Add a vibrancy effect to popupCloseButton chevron button.

#### Device, OS and Xcode Versions
Like the chevron button in Apple Music App.

**Comment by LeoNatan** [comment]
I don't think I can add vibrancy in a general-purpose way.
Vibrancy assumes that the vibrant visual effect view is embedded in another visual effect view. This cannot be guaranteed. 

Instead, users should set the close button style to `LNPopupCloseButtonStyleNone` and implement the vibrant variant themselves, using https://github.com/LeoNatan/LNChevronView or their own assets.

**Comment by iDevelopper** [comment]
I tried but anyway the expected result is not possible with LNChevronView because the two sub-views (left and right) overlap in the center of the chevron view.

**Comment by LeoNatan** [comment]
If you have a fix, please submit a PR to LNChevronView and I’ll accept it. 

I’ve been looking at the music app and don’t see vibrancy. Are you sure it’s not just transparent?

**Comment by iDevelopper** [comment]
I have no fix as I want to keep the animation (up, flat, down) so need the two views (left, right) and they must be superimposed. Just transparent, what do you mean?

**Comment by LeoNatan** [comment]
I mean `.color = .black; .alpha = 0.3` and then the color of the two views takes some of the color of the background, rather than implement with vibrancy. I'm not sure that Apple uses vibrancy in Music.

**Comment by iDevelopper** [comment]
It doesn't do the trick! I am pretty sure that Apple uses a vibrancy... We can use a vibrancy with alpha = 1 otherwise we can see the view are superimposed.

**Comment by LeoNatan** [comment]
On macOS, it is possible to have a view have special vibrancy properties. I’ll look later.

**Comment by iDevelopper** [comment]
You mean we can take a look at the debug hierarchy views of Apple App?

**Comment by iDevelopper** [comment]
Don't pay attention, my last question doesn't make sense! I think...

**Comment by LeoNatan** [comment]
No, I mean on macOS, NSView has the [`allowsVibrancy` property](https://developer.apple.com/documentation/appkit/nsview/1483793-allowsvibrancy?language=objc), which basically makes anything drawn by a view to appear as if a template image.

**Comment by LeoNatan** [comment]
https://github.com/LeoNatan/Apple-Runtime-Headers/blob/9e1e35b4fe0d34d86aa5d0666fa9c0ca4b64c59b/iOS/PrivateFrameworks/UIKitCore.framework/UIView.h#L1595

But I don't know what it is or what values it can handle.

**Comment by iDevelopper** [comment]
Hi @LeoNatan ,
I don't know yet SwiftUI! How can I pass the blur view of the DemoMusicPlayerController to another classe (LNPopupCloseButton). I created a property in popupCloseButton.h:
```
/**
 * The content view visual effect view provided by the user for adding a vibrancy effect to the button.
 *
 * The value of this property will be ignored if @c style is set to @c LNPopupCloseButtonStyleRound.
 */
@property (nonatomic, strong) UIVisualEffectView* userContentEffectView;
```

**Comment by LeoNatan** [comment]
Hmm, probably not going to be easy. You need to travel the hierarchy.
