### ISSUE TITLE
Crash when attempting to lookup '_systemChromeShadowColor'

### ISSUE THREAD

**Issue by wstyres** [LeoNatan/LNPopupController#402]
#### Description
Crashlytics has been reporting several crashes ever since I've upgraded my project to use `2.10.0` (from `2.8.5`) 

#### Steps to Reproduce
Do not have steps to reproduce, the crash is showing up very frequently in my firebase console for iOS 13 devices (all iOS 13.x.x, range of devices.). I've provided a few crash logs below with all of them having the same exception reason. Can trace the commit back to https://github.com/LeoNatan/LNPopupController/commit/f4def261c36c5e99811ba25ad6abb84fa44c4d5a.

`Fatal Exception: NSUnknownKeyException
[UIColor valueForUndefinedKey:]: this class is not key value coding-compliant for the key _systemChromeShadowColor.`

#### Device, OS and Xcode Versions
https://pastebin.com/NLnRNw1U iOS 13.1.2 - iPhone XS
https://pastebin.com/pkw03Cd4 iOS 13.1.2 - iPhone 8 Plus
https://pastebin.com/tZVtq7Am iOS 13.0.0. - iPhone 11 Pro Max

**Comment by LeoNatan** [comment]
Oh no!
Thanks for reporting, will fix that right away. I've tested this framework on 13.5, but I guess older 13.x are different enough.

**Comment by LeoNatan** [comment]
Fixed in 2.10.5

**Comment by wstyres** [comment]
Thanks so much! I'll keep an eye on the crashes in my dashboard.

**Comment by LeoNatan** [comment]
Great, let me know.

**Comment by wstyres** [comment]
Looks like the issue is resolved. Thanks for the quick fix!

**Comment by LeoNatan** [comment]
Great, enjoy the framework.
May I ask what app you are using it for?
