### ISSUE TITLE
How to adjust the bottom bar frame when UITabBar is hidden?

### ISSUE THREAD

**Issue by cerupcat** [LeoNatan/LNPopupController#404]
I have a Mac Catalyst app where I'm hiding the bottom UITabBar (in favor of a toolbar).

With the tabbar, the LNPopupController shows properly above the toolbar at the bottom of the screen.
![Screen Shot 2020-08-27 at 7 30 30 PM](https://user-images.githubusercontent.com/204151/91514518-cfacba80-e89b-11ea-9507-c6329bafa123.png)

When I hide the UITabBar, the LNPopupController bar shows in the same place, when it should show at the bottom of the screen. Is there a way to move the bar down since the tabBar is hidden? I tried adjusting the tabBar.frame but that doesn't do anything.
![Screen Shot 2020-08-27 at 7 28 11 PM](https://user-images.githubusercontent.com/204151/91514521-d1767e00-e89b-11ea-9068-5495aa197de7.png)

**Comment by LeoNatan** [comment]
As mentioned in the readme, this is explicitly not supported. Apple does not support hiding the tab bar, nor does the framework.

**Comment by LeoNatan** [comment]
Perhaps explain better what you are trying to accomplish and we can think how to better architecture the controllers.

**Comment by cerupcat** [comment]
Thanks @LeoNatan.

I'm currently presenting from a UITabBarController. On Catalyst, I'm setting the tabbar.hidden = true so that it does not display. Since doing this doesn't actually change the tabbar frame, the bottom popup view isn't positioned how I'd like (as seen from the images above). Is there a way to make the bottomDockingView not become the tabBar and instead become another view within the UITabBarController to work around this issue? I've tried setting bottomDockingViewForPopupBar within a UITabBarController subclass, but it doesn't seem to be called.

**Comment by LeoNatan** [comment]
As I said, this is a bad idea. For example, if you hide the tab bar, it won’t stop the tab bar controller from decreasing the safe area on the bottom. 

You should present a different controller on Mac.

To answer your question, it should be possible to override `bottomDockingViewForPopupBar` with a different view, but there is no promise the system will behave as expected.

**Comment by cerupcat** [comment]
Ok thanks. I appreciate the feedback.
