### ISSUE TITLE
Bottom inset problem with 2.10.6

### ISSUE THREAD

**Issue by MacMark** [LeoNatan/LNPopupController#406]
I'm having some layout problems like with earlier version of 2.10.x (before 2.10.5): The bottom of the view controller behind the popup bar is covered by the popup bar **when the navigation bar on top is hidden**. In this screenshot 1 and a half row of the table are hidden by the popup bar which was not the case with 2.10.5

This is 2.10.6:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/626963/91956017-54686000-ed04-11ea-9cae-4f6dd50f3b94.png">

And that is 2.10.5:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/626963/91956203-9beeec00-ed04-11ea-9d7c-d05e307978da.png">

I would like to have the correct layout behavior of 2.10.5 😊

_Originally posted by @MacMark in https://github.com/LeoNatan/LNPopupController/issues/397#issuecomment-685403565_

**Comment by LeoNatan** [comment]
I'm unable to reproduce. 

In your view controller, implement `- (void)viewSafeAreaInsetsDidChange` and print the `view.safeAreaInsets` before and after presentation. If you see the safe area insets update correctly, you must be mismanaging your scroll view insets.

**Comment by MacMark** [comment]
You're right. I found this old hack on my side which was necessary before but is not needed any longer in the affected view controllers 😇
```
//hack for fixing wrong adjustedContentInset
    if (AppDelegate.tabBarController.stickyPlayer) {
        insets.bottom = -AppDelegate.tabBarController.stickyPlayer.view.frame.size.height;
    }
```

**Comment by LeoNatan** [comment]
Great
