### ISSUE TITLE
Exception is thrown when calling 'dismissPopupBar'

### ISSUE THREAD

**Issue by aclassen** [LeoNatan/LNPopupController#409]
#### Description
Exception is thrown when calling 'dismissPopupBar'.
`Exception	NSException *	"Cannot remove an observer <LNPopupController 0x7fb1bfe39b40> for the key path \"popupCloseButtonStyle\" from <LNPopupContentView 0x7fb1bfe39f30> because it is not registered as an observer."	0x00006000034a0360`
#### Steps to Reproduce
Call 'dismissPopupBar(animated: false)'

- Start example app 
- Choose SplitViewController
- Click "Dismiss Bar"
#### Device, OS and Xcode Versions
XCode Version 12.0 beta 6 (12A8189n)
Device : IPhone 8 13.7

**Comment by aclassen** [comment]
fixed, thx

**Comment by LeoNatan** [comment]
Yes, apologies. Latest release has this fixed.
