### ISSUE TITLE
Popup Content Controller with Navigation bar - UI issue

### ISSUE THREAD

**Issue by JozefLipovsky** [LeoNatan/LNPopupController#41]
Hi All,
I would like to use LNPopupController with content controller which is embeded in UINavigationController (or have own UINavigationBar at least).  

I am trying to do something similar as Instagram do with their Tabbar middle Button, but in my case I want  to create **Popup Bar with Dashboard View Controller as it's content view**. So I used the Tabbarcontroller delegate method to basically ignore that middle tab bar button tap and instead of that I instantiate Dashboard VC from storyboard like this:
``` objective-c
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
    
    if ([viewController isKindOfClass:[GRAVDashBoardPlaceholderController class]]) {
        UIStoryboard *dashboardStoryboard = [UIStoryboard storyboardWithName:@"Dashboard" bundle:nil];
        UIViewController *dashboardVC = (GRAVDashboardViewController *)[dashboardStoryboard instantiateInitialViewController];

        dashboardVC.popupItem.title = @"Recording test";
        dashboardVC.popupItem.subtitle = @"00:00:00";
        dashboardVC.popupItem.progress = 0;
        
        self.tabBarController.popupContentView.popupCloseButton.hidden = YES;
        [self.tabBarController presentPopupBarWithContentViewController:dashboardVC openPopup:YES animated:YES completion:nil];
        
        return NO;
    }
    
    return YES;
}
```

And this is what I want to achieve:
![1](https://cloud.githubusercontent.com/assets/1158136/12646599/5a7ce5ec-c5d1-11e5-9f1a-57351c5a60fe.gif)

I tried to:
 **1) embed Dashboard view in Navigation Controller (translucent set to NO) directly in Storyboard**
 **2) add Navigation Bar with autolayout constraints**
But Navigation bar looks always like this when I use `presentPopupBarWithContentViewController:openPopup:animated:completion:`

![snappyapp snappyapp today at 3 59 35 pm](https://cloud.githubusercontent.com/assets/1158136/12648001/2b9b34d4-c5d8-11e5-8a91-09217577a629.png)

This is well known behaviour since iOS7 [http://blog.jaredsinclair.com/post/61507315630/wrestling-with-status-bars-and-navigation-bars-on]  

I checked tons of stackoverflow discussions about this topic. The only way I was able to solve that navigation bar layout **(as seen on gif above)** after initial openPopup: was that I add NavigationBar with 20pts constraint to Top Layout Guide of DashboardVC and use `positionForBar:` delegate method to return `UIBarPositionTopAttached` :
``` objective-c
- (UIBarPosition)positionForBar:(id<UIBarPositioning>)bar {
    return UIBarPositionTopAttached;
}
```

**But here is the issue**. On both solutions stated above (correct and incorrect initial navbar height) with another UI update on the Dashboard i.e. when "start recording" button is pressed NavigationBar height change as well:
![2](https://cloud.githubusercontent.com/assets/1158136/12649443/e086a7e2-c5de-11e5-830e-961ed668846a.gif)   ![3](https://cloud.githubusercontent.com/assets/1158136/12649491/1514e7a8-c5df-11e5-95c8-513a8ebedbaf.gif)

I am not sure it this behaviour has something to do with the Dashboard autolayout constraints setup or anything else... **Any idea how to solve this? Or advice, what should I be focused on during troubleshooting? Thanks in advance**  :v:

**Comment by LeoNatan** [comment]
I am investigating why your "1" is not behaving correctly.

**Comment by LeoNatan** [comment]
Fixed. Use a `UINavigationController` as the popup content controller. The close button will be positioned correctly under the navigation bar.
