### ISSUE TITLE
UIHostingController gesture recognizer issue

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#411]
####  Description
Can't close the popup content by panning. The pan gesture recognizer does not transition to the UIGestureRecognizerStateChanged on iOS 13.5.
It works on iOS 14.
I don't know if this issue is relative to the framework or SwiftUI, as it works with UIKit (Demo - Testing Scene or Maps).

#### Steps to Reproduce
Run the Demo - Music Scene example. Choose a song. Open the popup content. Swipe down to close.
 
#### Device, OS and Xcode Versions
Simulator iPhone 11 Pro Max, iOS 13.5, Xcode 12.0 beta 6.

**Comment by LeoNatan** [comment]
I’ll take a look. SwiftUI JS it’s own gesture recognizer a and they mess things up. I tried working around that, but only tested on iOS 14. Will look what’s going on in iOS 13.

**Comment by LeoNatan** [comment]
Fixed I. Latest release.
