### ISSUE TITLE
po in console not working.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#415]
#### Description
For example, I am in `- (UIEdgeInsets)_vSAIFS`

(lldb) po self.popupPresentationContainerViewController.view.superview.safeAreaInsets
error: Header search couldn't locate module LNPopupController

error: <user expression 0>:1:6: property 'popupPresentationContainerViewController' not found on object of type 'UIViewController *'
self.popupPresentationContainerViewController.view.superview.safeAreaInsets
     ^
(lldb) 

Any idea?

#### Steps to Reproduce
Run the Demo example application

#### Device, OS and Xcode Versions
Xcode 12 beta 6.

**Comment by LeoNatan** [comment]
Bug in Xcode, use [] syntax.

**Comment by iDevelopper** [comment]
Thanks!
