### ISSUE TITLE
Safe Area Insets Incorrect for Custom Popup Bar

### ISSUE THREAD

**Issue by Sherlouk** [LeoNatan/LNPopupController#416]
#### Description

First off just wanted to say huge thanks for creating and maintaining this lib, it's been an absolute huge help for my project!

I've noticed that the safe area insets (.bottom) size does not match the size of my custom popup bar.

Specifically I've got a custom `LNPopupCustomBarViewController` in which I override the `preferredContentSize` with a fixed height of 80. I then present my popup bar on top of my tab bar controller, when I do so I see a call to `viewSafeAreaInsetsDidChange` where the output of `view.safeAreaInsets.bottom` is 31.

Strangely (?), if I update the preferred size of my docked popup bar to (for example) 90, this does increase the size of the bottom inset to 41 (so the same +10 on both values). So it seems that potentially something else is affecting the size calculation which is being used.

I will add that if I artificially set `additionalSafeAreaInsets` to be the content size minus the insets this library creates, then everything looks perfect. Though doing this on every page in our app is a bit... well... yano 😂 

#### Steps to Reproduce

I'm opening this issue a bit prematurely to see if there's something super stupid I'm doing that can be easily fixed but I'm happy to try and create a sample app with just this problem in if that's helpful.

The important details seem to be though:

Create new class which extends `LNPopupCustomBarViewController`. Implement `preferredContentSize` and replace with following code:

```
    override var preferredContentSize: CGSize {
        get {
            return CGSize(
                width: UIView.layoutFittingExpandedSize.width,
                height: 80
            )
        }
        set {
            
        }
    }
```

Then to display it I just have this simplified code:

```
        tabBarController?.popupBar.customBarViewController = AudioPlayerDockedViewController.create()
        tabBarController?.presentPopupBar(
            withContentViewController: AudioPlayerFullscreenViewController.create(),
            openPopup: false,
            animated: true,
            completion: nil
        )
```

Once I execute that code, `viewSafeAreaInsetsDidChange` gets called with the incorrect information.

The view controller hierarchy is `UITabBarController -> UINavigationController -> UIViewController`

Hope that's helpful but if you do need me to try and sample app this or provide more information then just let me know!

#### Device, OS and Xcode Versions

Xcode 12, Beta 3 (12A8169g)
Simulator - iPhone 8 (iOS 14)
Lib Version 2.10.9 installed via Swift Package Manager

Cheers in advance and huge thanks for maintaining this project 🙌

**Comment by LeoNatan** [comment]
Hello,

Can you please try with the latest version of the framework? There were changes in this area specifically. Thanks

**Comment by Sherlouk** [comment]
Thanks for mega quick response @LeoNatan - confirmed on 2.10.11 though and the problem still happens 😭

**Comment by LeoNatan** [comment]
OK, thanks, I will take a look.

**Comment by LeoNatan** [comment]
Seems to work for me for all container controller combinations:

![Simulator Screen Shot - iPhone 11 Pro (iOS 13 5) - 2020-09-12 at 20 39 12](https://user-images.githubusercontent.com/2270433/93001509-2a027800-f538-11ea-952b-84d06ebd42a2.png)
![Simulator Screen Shot - iPhone 11 Pro (iOS 13 5) - 2020-09-12 at 20 39 20](https://user-images.githubusercontent.com/2270433/93001511-2d95ff00-f538-11ea-9b06-4715b6bc96f4.png) 
![Simulator Screen Shot - iPhone 11 Pro (iOS 13 5) - 2020-09-12 at 20 39 23](https://user-images.githubusercontent.com/2270433/93001512-2e2e9580-f538-11ea-92ba-c3d4e30864de.png)
![Simulator Screen Shot - iPhone 11 Pro (iOS 13 5) - 2020-09-12 at 20 39 26](https://user-images.githubusercontent.com/2270433/93001514-2ec72c00-f538-11ea-8590-a08bc22ce03f.png)

**Comment by LeoNatan** [comment]
Likewise with iPhone 8 on iOS 14:

![Simulator Screen Shot - iPhone 8 (iOS 14 0) - 2020-09-12 at 20 42 40](https://user-images.githubusercontent.com/2270433/93001573-99786780-f538-11ea-8f50-4c187d2415e1.png)
![Simulator Screen Shot - iPhone 8 (iOS 14 0) - 2020-09-12 at 20 42 44](https://user-images.githubusercontent.com/2270433/93001575-9c735800-f538-11ea-8bc7-91036771b86b.png)
![Simulator Screen Shot - iPhone 8 (iOS 14 0) - 2020-09-12 at 20 42 46](https://user-images.githubusercontent.com/2270433/93001578-9d0bee80-f538-11ea-8954-f0ed2e354c67.png)
![Simulator Screen Shot - iPhone 8 (iOS 14 0) - 2020-09-12 at 20 42 49](https://user-images.githubusercontent.com/2270433/93001580-9da48500-f538-11ea-831f-8e4620bc8b7d.png)

**Comment by Sherlouk** [comment]
Working on reproducing it in a sample app now 👍

**Comment by LeoNatan** [comment]
Great, thank you!

**Comment by Sherlouk** [comment]
Ahh... found the problem (though doesn't move me closer to a solution just yet!)

This is the line that breaks it! (We set this when we setup our tab bar controller)
`tabBarController?.tabBar.isTranslucent = false`

I've also got a sample app ready - I'm happy to push up to GitHub if you want it, or can try and add that one line to your project and see if it all breaks for you? Let me know which is easiest for you! 😄 

Thanks again

**Comment by LeoNatan** [comment]
Please note that non-translucent bars are not supported by the framework. This is noted in the readme, and I will not be looking into it. There are way too many bugs in iOS itself.

Instead, set a background color to your tab bar.

**Comment by Sherlouk** [comment]
Really sorry there Leo, I didn't even recall I had that enabled so didn't pick up on it in the README.

I'll make the changes on my side to remove that code!

Really appreciate the quick response!

**Comment by LeoNatan** [comment]
No worries.
When making this change in your app, make sure all layout there is correct. If you use safe areas and constraints, it will probably go smooth, but if you position stuff manually, you probably want to check that everything is positioned correctly.
Thanks

**Comment by LeoNatan** [comment]
May I ask what app you are working on? Thanks

**Comment by Sherlouk** [comment]
I've removed the troublesome line from my actual app and all the layout is working as expected, got to love Auto Layout when it works 😄

Working on a bit of a tech demo for an internal project which will hopefully be going live, using a podcast player as the source of that.

**Comment by LeoNatan** [comment]
Amazing! Good luck and happy coding!
