### ISSUE TITLE
UITabBar is too narrow on iOS 12 devices w/o home button when building with iOS 14 SDK

### ISSUE THREAD

**Issue by antiraum** [LeoNatan/LNPopupController#417]
When building a project that has LNPopupController (2.10.11) integrated (just adding it to the project is sufficient) with the iOS 14 SDK (GM), a UITabBar has only half the height on devices without home button running iOS 12.

**Comment by iDevelopper** [comment]
Do you use the tab bar in conjunction with a UITabBarController object, or as a standalone control in your project?

**Comment by antiraum** [comment]
with `UITabBarController`

defining `LNPopupControllerEnforceStrictClean` resolves the issue

**Comment by iDevelopper** [comment]
If you define `LNPopupControllerEnforceStrictClean`, a lot of features won't work properly.

**Comment by LeoNatan** [comment]
Hmmm
And it only happens with Xcode 12? Can you post a screenshot please of the problem?
Thanks

**Comment by antiraum** [comment]
![Simulator Screen Shot - iPhone Xs iOS 12 4 - 2020-09-16 at 14 12 10](https://user-images.githubusercontent.com/52741/93335386-ab068b80-f826-11ea-99a3-d311d42cac19.png)

**Comment by LeoNatan** [comment]
OK, thanks, will look into it soon.

**Comment by LeoNatan** [comment]
I can't seem to reproduce on iOS 12.4. Can you please attach a demo project?

**Comment by antiraum** [comment]
Please find a demo project attached. It has a `UITabBarController` as initial view controller. After adding the `LNPopupController` framework the bug occurs when running on a iOS 12.4 Simulator with Home Indicator, e.g., iPhone Xs.

[LNPopUpiOS12TabBar.zip](https://github.com/LeoNatan/LNPopupController/files/5234566/LNPopUpiOS12TabBar.zip)

**Comment by LeoNatan** [comment]
Fixed in 2.10.12

**Comment by antiraum** [comment]
perfect, thx!
