### ISSUE TITLE
Possible bug when opening popup when navbar is hidden

### ISSUE THREAD

**Issue by MhmdSalah** [LeoNatan/LNPopupController#419]
#### Description

The bug appears when you initiate the popupBar with container viewcontroller that has navbar hidden then when pushing other viewcontrollers the navbas is unhidden
please watch this video to understand the issue
https://youtu.be/ABnvj1p7qfc

#### Steps to Reproduce

my main VC hides navbar but all other vcs show it
this is how i implemented it
override func viewWillAppear(_ animated: Bool) {
        self.navigationController?.setNavigationBarHidden(false, animated: true)
    }

 override func viewWillDisappear(_ animated: Bool) {
        self.navigationController?.setNavigationBarHidden(false, animated: true)
    }

#### Device, OS and Xcode Versions

Xcode 12.0.1 ios 14 using simulator

**Comment by LeoNatan** [comment]
Hello

Can you reproduce this issue in the example project? Thanks

**Comment by MhmdSalah** [comment]
Hello! thank you for replying. I was not able to reproduce the issue in the example project.

It seems to be an issue in my case only. I was able to solve it in my app. If you want to further investigate here is how to reproduce it in a new project:
- Create a main navigationcontroller with a main viewcontroller1
- Create viewcontroller2 with a segue from viewcontroller1
- In viewcontroller1 hide the navbar by setNavigationBarHidden true in viewwillapper
- In viewcontroller2 show the navbar by setting setNavigationBarHidden false in viewwillapper
- show the popup from viewcontroller1 while the navbar is hidden then go to viewcontroller2 by triggering segue

I have implemented a solution for my app by using this in my popup

```
override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)

        self.navWasHidden = (self.popupPresentationContainer as! UINavigationController).isNavigationBarHidden
        (self.popupPresentationContainer as! UINavigationController).setNavigationBarHidden(true, animated: true)
	}
    
    override func viewWillDisappear(_ animated: Bool) {
        (self.popupPresentationContainer as! UINavigationController).setNavigationBarHidden(self.navWasHidden, animated: true)
    }
```

**Comment by LeoNatan** [comment]
Let me see if I can reproduce.

**Comment by MhmdSalah** [comment]
I was able to reproduce in a new very simple project.

here is the repo
https://bitbucket.org/dark7wizard/lnpopuptest/src/master/
`git clone https://dark7wizard@bitbucket.org/dark7wizard/lnpopuptest.git`

**Comment by LeoNatan** [comment]
Great, keep it alive. I will take a look soon. Thanks!

**Comment by LeoNatan** [comment]
Fixed. Please try the latest release
