### ISSUE TITLE
Changing background color does not work

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#42]
I want to customize the looks of my popup bar:

```swift
LNPopupBar.appearance().titleTextAttributes = [NSForegroundColorAttributeName : UIColor.whiteColor()]
LNPopupBar.appearance().subtitleTextAttributes = [NSForegroundColorAttributeName : UIColor.whiteColor()]
LNPopupBar.appearance().barStyle = UIBarStyle.Black
LNPopupBar.appearance().tintColor = UIColor.whiteColor()
```

All settings work except the background color aka barStyle. My popupbar is still red like the tabBar underneath it. I want it to be black.

![screen shot 2016-01-29 at 14 22 36](https://cloud.githubusercontent.com/assets/144173/12676579/c63d8594-c693-11e5-9658-acd95bca1ec2.png)

**Comment by LeoNatan** [comment]
Try using `barTintColor`.

**Comment by funkenstrahlen** [comment]
Works perfectly! Thanks a lot!

**Comment by morad** [comment]
Having hard time here, so LNPopupBar.appearance().barTintColor = UIColor.whatever works on first time initial..

But cannot update the barTintColor... only works the first time when it gets initialized... any thoughts?

**Comment by LeoNatan** [comment]
@morad Changing the bar tint color using `appearance()` will only modify future popup bars. Instead, update the actual popup bar's bar tint color.
