### ISSUE TITLE
Can't compile v.2.10.22 for Mac

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#420]
#### Description
Two swift compiler errors in DemoMusicPlayerController.swift

#### Steps to Reproduce
git clone https://github.com/LeoNatan/LNPopupController.git --recurse-submodules
Open the project in Xcode.
Run for My Mac

#### Device, OS and Xcode Versions
Mac Book Pro, Mac OS Catalina 10.15.6, Xcode 12.0

**Comment by LeoNatan** [comment]
What compile issue?

<img width="1004" alt="Screen Shot 2020-10-28 at 11 03 41" src="https://user-images.githubusercontent.com/2270433/97414971-4f431e00-190d-11eb-9a45-f5d1f732f2f1.png">

Next time, please make sure your environment is clean and include the compile errors.

**Comment by LeoNatan** [comment]
You might need Xcode 12.2 with latest SDK (including Catalyst UIKit which is similar to iOS 14.0), due to Apple's nonsense.

**Comment by iDevelopper** [comment]
Sorry,

But Xcode 12.0 includes Catalyst. I do not understand...

Thanks.

**Comment by LeoNatan** [comment]
I don’t understand either. If you have compile issues, why not post them here?

**Comment by iDevelopper** [comment]
<img width="1552" alt="Capture d’écran 2020-10-28 à 10 19 55" src="https://user-images.githubusercontent.com/1782450/97416826-3a638c00-1907-11eb-9485-e522eed84110.png">

**Comment by iDevelopper** [comment]
Ok I will download Xcode 12.2, thanks.

**Comment by LeoNatan** [comment]
So you see in the screenshot. Xcode 12.0 and 12.1 come with old macOS SDK, which doesn’t include iOS 14 Catalyst SDK, only iOS 13.x. If you comment that out, it will work. If you want to develop for Catalyst and Big Sur, you should download Xcode 12.2 beta.

**Comment by LeoNatan** [comment]
Xcode 12.1.1 still only contains the old macOS SDK 🤦‍♂️
So you need Xcode 12.2 beta 3 and above to be able to target iOS 14 SDK on macOS.

**Comment by iDevelopper** [comment]
Hello @LeoNatan ,

Thank you for this information. I had decided to wait for the final version anyway.

Another question: Can we publish applications to the Apple Store with Xcode 12.0 beta 3? Besides in general with beta versions of Xcode?

Thanks.

**Comment by LeoNatan** [comment]
Only to TestFlight. Otherwise, AppStore will reject builds from beta Xcode. 

The new Xcode will probably arrive soon, with macOS Big Sur.

**Comment by iDevelopper** [comment]
Ok, thanks a lot.

**Comment by iDevelopper** [comment]
So we can't publish applications for Mac Catalyst 14.2 yet?

**Comment by LeoNatan** [comment]
No. Catalyst 14.0 is only on Big Sur anyway, but you can’t even ask if(@available()) with Xcode 14.1. 🤦‍♂️
