### ISSUE TITLE
InteractionGesture States Delegate

### ISSUE THREAD

**Issue by Ikloo** [LeoNatan/LNPopupController#421]
Hello!
Thanks for your framework, it's awesome!

Could you provide methods to LNPopupPresentationDelegate from `popupInteractionGestureRecognizer` states? (ex: started, panning, finished, etc).
Or call current will/did appear will/did disappear methods when gesture changes state?

Thanks so much!

**Comment by LeoNatan** [comment]
Hello,

You already get the appearance callbacks for the popup content controller.
You have access to the interaction gesture recognizer, so you can use `addTarget(_:action:)` to listen to state changes to the gesture recognizer. Is this not enough?

**Comment by Ikloo** [comment]
Sure, I can use `addTarget(_:action:)`. Thanks!
But current `will/did appear` & `will/did disappear` methods don't call at incorrect sequence. 
For example: When I start to hide popup content `willDissapearPopupContent` doesn't call, only `didDissapearPopupContent` after.

**Comment by LeoNatan** [comment]
Hmm will take a look, thanks!

**Comment by LeoNatan** [comment]
I can't reproduce this. Will/did appear/disappear seems to be called correctly for the content view controller (not the presenting view controller!), and likewise, the delegate reports the popup state transitions correctly. Regarding the latter, if it had failures, the SwiftUI wrapper of this framework, [LNPopupUI](https://github.com/LeoNatan/LNPopupUI), would have been completely broken, as it relies on this exclusively to maintain its state. Please try again with the latest version.
