### ISSUE TITLE
Question about Package.swift

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#424]
Hello Leo,

#### Description
Why this:
```
			exclude: [
				"LNPopupControllerExample",
				"Supplements"
			],
```
does not exclude anything?

I mean Hiding / Ignoring Directories from Xcode when Opening Swift Packages.

**Comment by LeoNatan** [comment]
Hello Patrick,

What do you mean? It should exclude those folders from compilation.

**Comment by iDevelopper** [comment]
Yes but not from Xcode showing all. It's unpleasant, isn't it?

**Comment by iDevelopper** [comment]
Since we provide a path and some excludes, Xcode should show in the project navigator, only what we need...

**Comment by LeoNatan** [comment]
Hehe, you can open a feedback with Apple if you think it's not behaving correctly. I think this is the intended behavior.

**Comment by iDevelopper** [comment]
Ah! Thank for your feedback, surprised!

**Comment by LeoNatan** [comment]
SPM is very broken, and changes constantly. So who knows what each new Xcode release will bring.
