### ISSUE TITLE
Dismiss Popupbar with a button inside itself

### ISSUE THREAD

**Issue by toninospiderman123** [LeoNatan/LNPopupController#425]
Hi Leo,

Would it be possible to dismiss it with button inside my LNPopupCustomBarViewController, i tried in this way:

```
class MiniContentViewController: LNPopupCustomBarViewController {

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var closeButton: UIButton!
    
    fileprivate func updateConstraint() {

        self.preferredContentSize = view.systemLayoutSizeFitting(UIView.layoutFittingCompressedSize)
    }
    @IBAction func closeController(_ sender: Any) {
        
        self.dismissPopupBar(animated: true, completion: nil)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = AppStyle.Palette.colorPrimary
        view.translatesAutoresizingMaskIntoConstraints = false
        
        titleLabel.font = UIFont.init(name: AppStyle.Font.fontBodyMedium, size: 18)
        updateConstraint()
    }
    
    override func popupItemDidUpdate() {
        titleLabel.text = containingPopupBar.popupItem?.title
        imageView.image = containingPopupBar.popupItem?.image
    }

    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)

        coordinator.animate(alongsideTransition: { [unowned self] context in
            updateConstraint()
        }, completion: nil)
    }
}
```

not only with "self.dismissPopupBar(animated: true, completion: nil)", i tried also to access from this class to parent view controller (the one I presented on), but when i print for example self.presentingViewController or self.presentedViewController or staff like, return nil.

Now, at the moment when I create the popubar I assign a tapgesture to the button inside the custom popupbar:

 ```
let customPoupBar = StoryboardSingleton.instance.instantiateCustomPopupBar()
 customPoupBar.view.backgroundColor = .clear
 let closecustomPoupBar = UITapGestureRecognizer(target: self, action: #selector(self.dismissPopup(_:)))
 customPoupBar.closeButton.addGestureRecognizer(closecustomPoupBar)
 baseWidgetViewController.tabBarController?.popupBar.customBarViewController = customPoupBar
 baseWidgetViewController.tabBarController?.presentPopupBar(withContentViewController: ContentRouter.assembleModule(withId: id), openPopup: true, animated: true, completion: nil)
```

and this is my closecustomPoupBar

```
@objc func dismissPopup(_ sender: UITapGestureRecognizer){
        baseWidgetViewController.tabBarController?.dismissPopupBar(animated: true, completion: nil)
}
```

I don't want to repeat this in those classes that don't use my base view, so i would dismiss it directly from MiniContentViewController (LNPopupCustomBarViewController)

I hope I have explained myself well.

thank's for your job

**Comment by LeoNatan** [comment]
Hm, right, I don't think there is an exposed way to reach the popup presenting controller from the custom bar view controller.

I should probably expose a `popupPresentationContainerViewController` to custom bar controllers for convenience. Will do that soon.

**Comment by LeoNatan** [comment]
Alright, fixed.

So now, in your custom bar controller, `popupPresentationContainer` will return the actual popup presentation container. You can then call `dismissPopupBar(animated: true)` to dismiss the bar.

**Comment by toninospiderman123** [comment]
Perfect, thank you
