### ISSUE TITLE
Color of bars.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#426]
Hello Leo,

#### Description
With Xcode 12.3 and iOS 14.3, all bars have turned yellow. Apparently with the simulator only.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-12-17 at 07 14 18](https://user-images.githubusercontent.com/1782450/102451362-9d84bb80-4038-11eb-8e63-584f87ad2512.png)

#### Steps to Reproduce
Run the demo application.

#### Device, OS and Xcode Versions
Simulator iPhone 11 Pro Max, iOS 14.3, Xcode 12.3 (12C33)

**Comment by iDevelopper** [comment]
This seems working:

https://developer.apple.com/forums/thread/669363?answerId=652566022#652566022

**Comment by LeoNatan** [comment]
Wow 🤦‍♂️
Thanks for the info. What isn’t buggy with Apple these days?

**Comment by iDevelopper** [comment]
Is there a human who tests new versions of Xcode? If so, is he color blind?
