### ISSUE TITLE
Problem with background color when using bar tint color

### ISSUE THREAD

**Issue by Bartozo** [LeoNatan/LNPopupController#427]
#### Description
The problem is that when you set Bar Tint Color for UITabBarController to something else than "Default" then the popUpBar 
won't be translucent. Here is my tabBarController configuration in Storyboards <img width="259" alt="Screenshot 2020-12-28 at 18 16 53" src="https://user-images.githubusercontent.com/10104462/103231740-dece7280-4938-11eb-9a19-62d01791ad1b.png">

And this is how it look's like with Bar Tint Color set to black. (The top view is popUpBar and the bottom view is TabBarController) As you can see they are no't the same.
<img width="67" alt="Screenshot 2020-12-28 at 18 20 17" src="https://user-images.githubusercontent.com/10104462/103231929-65834f80-4939-11eb-80c4-3c9f6039506e.png">

When bar tint is set to default then it looks fine
<img width="68" alt="Screenshot 2020-12-28 at 18 25 43" src="https://user-images.githubusercontent.com/10104462/103232197-1984da80-493a-11eb-81a2-aa0e103a717b.png">

#### Steps to Reproduce
1. Create UITabBarController and set its Tint Color property to something else than default (for example Black)
2. Create CustomBarViewController and set it to popupBar.customBarViewController property.
3. Update backgroundStyle for your popupBar (for example: tabBarController?.popupBar.backgroundStyle = .systemChromeMaterialDark)
4. Launch the app and see that it looks different.
NOTE: Looks like the popupBar view is not translucent when TabBarController has Bar Tint set to something else than default.

#### Device, OS and Xcode Versions
Xcode 12.2
iPhone 12 iOS 14.2

**Comment by LeoNatan** [comment]
Please provide a demo project that reproduces this issue. Thanks.

**Comment by Bartozo** [comment]
I will try to upload a demo project today, but if no't then it will be uploaded in few days.

**Comment by LeoNatan** [comment]
Great, thanks!

**Comment by LeoNatan** [comment]
Ping

**Comment by Bartozo** [comment]
I am sorry that it took so long.  Project is ready and its named sampleProject. It contains only ViewControllers that have scrollview with some content inside UITabBarController. 

So here are the screens that I have mentioned before.
This is how it looks like with tabBar set to dark style with black tint:
<img width="516" alt="Screenshot 2021-01-08 at 11 18 39" src="https://user-images.githubusercontent.com/10104462/104003837-44292b80-51a3-11eb-88d8-70a63954edf0.png">

and without black tint (default value):
<img width="560" alt="Screenshot 2021-01-08 at 11 19 15" src="https://user-images.githubusercontent.com/10104462/104003893-5905bf00-51a3-11eb-9c19-e14952fad7ed.png">
:

I have tested this on many devices (including real device) and also on different iOS versions and the results were always the same. 

[sampleProject.zip](https://github.com/LeoNatan/LNPopupController/files/5786552/sampleProject.zip)

**Comment by LeoNatan** [comment]
Thanks, I will take a look soon.

**Comment by LeoNatan** [comment]
Fixed in 2.10.27
