### ISSUE TITLE
I need an hasBeenMinified() delegate method

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#43]
When my lnpopup view is fullscreen, I set the status bar color according to the coverart image (so the status bar is visible).

However if the player is minified I need to update the status bar color again, so it matches the color of my navigation bar of the rest of the app.

This kinda works if I use this method to set my status bar color:

```objc
- (UIStatusBarStyle)preferredStatusBarStyle
{ 
    return UIStatusBarStyleLightContent; 
}
```

However this does not play nice with controllers inside `UINavigationController`s. So I use this method now:

`[[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];`

However this does not change the status bar color when the popup is minified. Therefore I need a delegate to be called whenever the popup is minified, so I can force an update of the status bar color.

**Comment by funkenstrahlen** [comment]
I think I stick to the `preferredStatusBarStyle()` way. Works best.

**Comment by LeoNatan** [comment]
It is best. This is the preferred and modern way to manage status bar style.
