### ISSUE TITLE
What is the proper way to get coordinates of the Popup Close Button?

### ISSUE THREAD

**Issue by darkForestCat** [LeoNatan/LNPopupController#432]
#### Question  
I am using rounded close button.What is the proper way to get it's center, minX  and minY,  frame or something that could help me  drawing my stuff behind it :)

**Comment by LeoNatan** [comment]
Hello,

There are several approaches you can take. The button is accessible to you from `popupContentView.popupCloseButton`. You can then calculate where it is and do what you need to do. A better approach is to implement [`positionPopupCloseButton(_:)`](https://github.com/LeoNatan/LNPopupController/blob/23502e5bdf69fae82a808fe6e6125df3209a383b/LNPopupController/LNPopupController/UIViewController%2BLNPopupSupport.h#L101) and position the close button in your hierarchy. You then take ownership of the button and its position.
