### ISSUE TITLE
how can I implement custom Bottom? 

### ISSUE THREAD

**Issue by maulikshah09** [LeoNatan/LNPopupController#435]
I read your post and saw your code but not getting anything I have tried loat but your document is not good. I know your demo is working perfectly. also I tried to download but project not running. I have download swift package then project is running.

**Comment by LeoNatan** [comment]
If you clone the project, you need to recursively update submodules. 

You can check the demo project with two examples of different custom bar setups.

**Comment by maulikshah09** [comment]
I have successfully implemented... but I want more customise and facing 2-3 issues. 

Tabbar code.
=========================

 let customMapBar = exploreStoryBoard.instantiateViewController(withIdentifier: "PopUpSongsInfo") as? PopUpSongsInfo
        customMapBar?.view.backgroundColor = .clear
        popupBar.customBarViewController = customMapBar
        popupContentView.popupCloseButtonStyle = .none
        popupContentView.backgroundStyle = .regular
        popupInteractionStyle = .default
        popupContentVC = exploreStoryBoard.instantiateViewController(withIdentifier: "SongsQueueVC") as? SongsQueueVC
        tabBarController?.popupBar.barStyle = .default
      
        tabBarController?.presentPopupBar(withContentViewController: self.popupContentVC, animated: false, completion: nil)

<img width="463" alt="Screenshot 2021-03-14 at 9 37 38 AM" src="https://user-images.githubusercontent.com/11289579/111056888-f71a4c00-84a8-11eb-81fe-0251de0d9d37.png">


 let customMapBar = exploreStoryBoard.instantiateViewController(withIdentifier: "PopUpSongsInfo") as? PopUpSongsInfo
        customMapBar?.view.backgroundColor = .clear
        popupBar.customBarViewController = customMapBar
        popupContentView.popupCloseButtonStyle = .none
        popupContentView.backgroundStyle = .regular
        popupInteractionStyle = .default
        popupContentVC = exploreStoryBoard.instantiateViewController(withIdentifier: "SongsQueueVC") as? SongsQueueVC
        tabBarController?.popupBar.barStyle = .default
      
        self.presentPopupBar(withContentViewController: self.popupContentVC, animated: false, completion: nil)
        
        
<img width="470" alt="Screenshot 2021-03-14 at 9 39 27 AM" src="https://user-images.githubusercontent.com/11289579/111056919-30eb5280-84a9-11eb-9e8e-9d866f1f1cf8.png">
