### ISSUE TITLE
Mac Catalyst Snap & Drag Issue

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#438]
Hello Leo,

#### Description
[<UINSWindowProxy 0x600002195710> valueForUndefinedKey:]: this class is not key value coding-compliant for the key currentEvent
in
-_popupBarPresentationByUserPanGestureHandler_began:

#### Steps to Reproduce
Run the example.

#### Device, OS and Xcode Versions
macOS Big Sur 11.2.3, Xcode 12.5 beta 3 (12E5244e)

**Comment by LeoNatan** [comment]
Hey

Thank you!
Will take a look. I recently fixed a crash on Catalyst, maybe it introduced a new one, or there were originally more issues.

**Comment by LeoNatan** [comment]
Have you tried with the latest version? I can't reproduce.

**Comment by LeoNatan** [comment]
I think you have an old version of the code. This issue is what I fixed. Cheers

**Comment by iDevelopper** [comment]
2.10.32

**Comment by LeoNatan** [comment]
https://github.com/LeoNatan/LNPopupController/releases/tag/2.10.33

**Comment by iDevelopper** [comment]
Sorry, yes I can see your commits in 2.10.33. It was fixed.
