### ISSUE TITLE
UITabBar layout issues on IOS 13 and 14

### ISSUE THREAD

**Issue by law-cell** [LeoNatan/LNPopupController#439]
Description

please watch this photo.

![Simulator Screen Shot - iPhone 11 - 2021-04-13 at 01 11 23](https://user-images.githubusercontent.com/59221817/114434836-0c90ac00-9bf6-11eb-9f68-62b36487e3cb.png)

It is normal in TabBarViewController

and I change the code from:
bottomViewFrame.origin = CGPoint(x: bottomViewFrame.minX, y: view.bounds.height - bottomViewFrame.height)
to:
bottomViewFrame.origin = CGPoint(x: bottomViewFrame.minX, y: view.bounds.height - 150)

I can see that it is normal but in the different position.
![simulator_screenshot_44073A35-0E57-4278-80BD-4D0C2289D978](https://user-images.githubusercontent.com/59221817/114435220-82951300-9bf6-11eb-8186-01f312243fcb.png)

Device, OS and Xcode Versions
I try it on several devices and different versions of IOS, which has no change.

**Comment by law-cell** [comment]
<img width="204" alt="截屏2021-04-13 上午1 27 04" src="https://user-images.githubusercontent.com/59221817/114435953-5e860180-9bf7-11eb-92fb-979a2b497d36.png">

I add only a UITabBar in a UIViewController.

**Comment by LeoNatan** [comment]
I don't understand what you are doing.
Are you using a `UITabBarController` or just a `UITabBar` in side a regular `UIViewController`?

You should be using `UITabBarController`, as that is the only one supported. If you want to use `UITabBar` directly, you need to implement a lot of things, such as https://github.com/LeoNatan/LNPopupController/blob/9cde3c060c9e66b52f4949b18b315876d6004420/LNPopupController/LNPopupController/UIViewController%2BLNPopupSupport.h#L272 and maintain this on your own. It won't be enough, as there is a lot of custom code to support `UITabBarController`.

**Comment by LeoNatan** [comment]
Clearly, the framework works. Run the example project and see if you see the issue there.

**Comment by law-cell** [comment]
@LeoNatan, thanks, I am using a UITabBar inside a regular UIViewController.

So, you mean I'd be better using a UITabBarController?

**Comment by LeoNatan** [comment]
Yes. It just does what you are trying to do, in a standard way.

**Comment by law-cell** [comment]
Thanks again!
