### ISSUE TITLE
Title and subtitle doesn't appear in bar.

### ISSUE THREAD

**Issue by davidosorio** [LeoNatan/LNPopupController#44]
If I open a navigation controller instead a single view controller, then the bar doesn't show any button or information.

`let nav = UINavigationController(rootViewController: popupContentController)
tabBarController?.presentPopupBarWithContentViewController(nav, animated: true, completion: nil)`

You can reproduce in the example project.
![simulator screen shot 2 feb 2016 15 34 49](https://cloud.githubusercontent.com/assets/2844659/12754275/8c6d155a-c9c2-11e5-8685-9b5dafe926de.png)

**Comment by LeoNatan** [comment]
You need to set the properties of `nav` instead of the controller embedded in it.
