### ISSUE TITLE
v 2.10.34 question

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#440]
Hey,

What is the real enhancement?

I can't see any UI updates when testing this new version.

What should I see? What is the purpose?

Cheers

**Comment by LeoNatan** [comment]
As the release notes state, support for pointer interaction was added. 

https://developer.apple.com/documentation/uikit/pointer_interactions

**Comment by LeoNatan** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/pointers/

**Comment by iDevelopper** [comment]
Sorry but I can't show it in your sample.

**Comment by LeoNatan** [comment]
https://github.com/LeoNatan/LNPopupController/blob/master/Supplements/pointer_interaction.gif
