### ISSUE TITLE
Default highlight on bar in not working

### ISSUE THREAD

**Issue by sakibk** [LeoNatan/LNPopupController#441]
The default highlight on customBarVC is not working. I have tried overriding wantsDefaultHighlightGestureRecognizer inside, and setting its value to true, but inefficiently. Also, adding custom longTouchGesture to view inside customBarVC is not working even after setting delegate (popupContentView.popupInteractionGestureRecognizer.delegate) and returning true for gestureRecognizerShouldBegin and false for shouldRequireFailureOf and shouldBeRequiredToFailBy. 

I have read other issues, and I could not find a solution. Please correct me if I am doing something wrong. 
Thank You!

**Comment by LeoNatan** [comment]
Hello,

I tried reproducing in my example project, and it works there:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-19 at 13 47 27](https://user-images.githubusercontent.com/2270433/115224961-383ff480-a116-11eb-8104-37a08c799d11.png)

Perhaps the way you construct your custom popup bar view hierarchy is interfering.

Please share more information on your view hierarchy, and, preferably, please attach a demo project reproducing the issue.

**Comment by sakibk** [comment]
I have created the same hierarchy - TabBarController-NavigationController-ViewController-customBarPlayer(copy from the project where I have the issue), but unfortunately was not able to reproduce the issue. But what I have noticed is that I am actually missing one "overlay" in my project. You can find it on pictures
<img width="1654" alt="Screen Shot 2021-04-19 at 3 35 30 PM" src="https://user-images.githubusercontent.com/5898766/115253774-fd958680-a12c-11eb-94af-98385052d81f.png">
<img width="1608" alt="Screen Shot 2021-04-19 at 3 34 13 PM" src="https://user-images.githubusercontent.com/5898766/115253789-01c1a400-a12d-11eb-9c98-302e0f9fe034.png">

**Comment by LeoNatan** [comment]
Unfortunately, this does not help me. Perhaps you have a view that catches the touches responsible for the highlight. Or you have a view with a gesture recognizer, which is fighting with the highlight gesture recognizer. The last you can solve with the delegate methods.

**Comment by LeoNatan** [comment]
Ping

**Comment by sakibk** [comment]
Thank you for your activity, I have found the issue. Giving custom popupBar view backgroundColor a solid color value prevents work of highlight view.

**Comment by sakibk** [comment]
even custom touch gesture is not working on custom bars with views having solid backgroundcolor

**Comment by LeoNatan** [comment]
It works, you just don’t see it because your background color is hiding the highlight view. I suggest setting a background color to the bar itself.

**Comment by sakibk** [comment]
That make sense haha 😄. Thank you!
And thing regarding custom highlight view, with custom gesture recognizer? What is proper way to achive it?

**Comment by LeoNatan** [comment]
You should disable the framework one (by overriding the property), and then you can your own gesture recognizer to your own custom view, and handle it there. There is nothing by the framework that should block that.

**Comment by sakibk** [comment]
I did that, but that was also not working for me. By saying my own custom view, you mean one outside of the customBarViewController?

**Comment by LeoNatan** [comment]
Any sub view of the custom bar controller, including the .view property.

**Comment by sakibk** [comment]
Great, I have found out. Thank you for your help!

**Comment by sakibk** [comment]
I have one more question. Is it possible to change scroll down to dismiss sensitivity, or at least minimum scroll down offset in order for the full player to dismiss without customizing and implementing the whole swipe?

**Comment by LeoNatan** [comment]
Unfortunately, it is not exposed. It’s at 27% right now:

https://github.com/LeoNatan/LNPopupController/blob/1b803db790ec596b2fa576e7390d582ad69ff0d1/LNPopupController/LNPopupController/Private/LNPopupController.m#L575

**Comment by sakibk** [comment]
It would be very good if you plan it for the next release, I can also create MR for this one.

Additionally, it would also be good to have the same threshold for .drag style, so it is not just directional (directional + some fixed/proportional amount scrolled in direction of opening/closing - exposed property which is 0 by default). I can also create MR for this one if you would agree.

**Comment by LeoNatan** [comment]
Not planned right now. Please open an enhancement request.

**Comment by LeoNatan** [comment]
Playing around with the drag interaction, it seems Apple’s recent implementation is less sensitive, so a small swipe doesn’t close it. I might look at the physics of this.

**Comment by iDevelopper** [comment]
I confirm.
