### ISSUE TITLE
layout of BarButtonItems issue

### ISSUE THREAD

**Issue by law-cell** [LeoNatan/LNPopupController#442]
when I set images of trailingBarButtonItems and leadingBarButtonItems
this happened
![Simulator Screen Shot - iPhone 11 - 2021-04-22 at 22 05 19](https://user-images.githubusercontent.com/59221817/115728187-dc47cb00-a3b6-11eb-850d-ae16d90ba745.png)

when I set one of two buttonitems
the position of the button looks good
![simulator_screenshot_57083D69-9FBB-40B1-BF25-A5C37F32A6B8](https://user-images.githubusercontent.com/59221817/115728381-0dc09680-a3b7-11eb-8f98-69556d6d0027.png)

#### Steps to Reproduce

func setMiniPlayer(){
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let demoVC = storyboard.instantiateViewController(withIdentifier: "playerVC")
        
        self.popupNextButtonItem = UIBarButtonItem(image: UIImage(named: "next"), style: .plain, target: nil, action: nil)
        self.popupPlayButtonItem = UIBarButtonItem(image: UIImage(named: "play.fill"), style: .plain, target: nil, action: nil)
        
        
        self.musicImage = UIImage.init(named: "genre1")
        
        self.popupBar.barStyle = .prominent
        demoVC.popupItem.title = "Hello World"
        demoVC.popupItem.subtitle = "And a subtitle!"
        //demoVC.popupItem.progress = 0.34
        demoVC.popupItem.trailingBarButtonItems = [self.popupNextButtonItem!]
        demoVC.popupItem.leadingBarButtonItems = [self.popupPlayButtonItem!]
        demoVC.popupItem.image = musicImage
        
        self.presentPopupBar(withContentViewController: demoVC, animated: true, completion: nil)
    }

#### Device, OS and Xcode Versions
ios 13
iPhone 11

**Comment by LeoNatan** [comment]
Hello,

If you run the example project, do you get the same behavior?

Thanks

**Comment by LeoNatan** [comment]
It looks like your button images might be too big. Are you using images from your catalog? Instead, try using `UIImage(systemName: "...")` instead.

**Comment by law-cell** [comment]
> It looks like your button images might be too big. Are you using images from your catalog? Instead, try using `UIImage(systemName: "...")` instead.

Oh, that's my bad. As you said, my images are too big. Sorry.
Thanks for your time.

**Comment by law-cell** [comment]
![Simulator Screen Shot - iPhone 11 - 2021-04-22 at 22 16 45](https://user-images.githubusercontent.com/59221817/115730525-f682a880-a3b8-11eb-8daf-3cb347f52165.png)

It works now!  
I am a novice.
Sorry for wasting your time

**Comment by LeoNatan** [comment]
No problem. If you want to use custom images, you need to make sure they are the correct size for toolbars (25pt x 25pt).
