### ISSUE TITLE
Expose controls for marquee settings

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#449]
Originally posted by @SotaJoe in https://github.com/LeoNatan/LNPopupController/discussions/448

**Comment by iDevelopper** [comment]
What about a dataSource for the labels? I think it is not a good idea to manage the Marquee Labels inside the framework.

**Comment by LeoNatan** [comment]
Data source is not planned. If users want a custom label, they should create a custom bar controller, and set up the labels there.

**Comment by SotaJoe** [comment]
AH! Sorry about my duplicate request - Can't say enough great things about this library, @LeoNatan! Love your work!

**Comment by LeoNatan** [comment]
Implemented in the latest releases of LNPopupController and LNPopupUI. Enjoy!
