### ISSUE TITLE
UINavigationBar positioned wrong in child (contained) UINavigationController

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#45]
My LNPopupController presents an UINavigationController. When the popup becomes fullscreen for the first time everything looks fine.

![simulator screen shot 04 feb 2016 13 38 33](https://cloud.githubusercontent.com/assets/144173/12815159/ae43b1d8-cb44-11e5-8308-954d348ac13f.png)

However if I minify the popup bar and max it again, the UINavigationBar is displayed wrong.

![simulator screen shot 04 feb 2016 13 38 39](https://cloud.githubusercontent.com/assets/144173/12815157/aa0fa0c2-cb44-11e5-9c2e-aca262ab8e3b.png)

Any idea why this happens and how I could fix that?

**Comment by JozefLipovsky** [comment]
seems to be related to this one #41, make sure you are using latest version.... I have just tested this in my app and it's working fine when VC is embeded in UINavigationController

**Comment by funkenstrahlen** [comment]
I am using the latest version. This did not fix it.

However my view hierarchy looks like this, which might be the problem why the fix does not work for me.

popup presents: `UIViewController` -> `UIPageViewController` as subview -> `UINavigationController` -> `UIViewController`

**Comment by LeoNatan** [comment]
From the screenshots above, I see this is not the latest version. Please update to latest version.

**Comment by funkenstrahlen** [comment]
I am currently trying to figure this out

```bash
➜  xenim-ios-app git:(feature/chat) carthage update
*** Fetching LNPopupController
*** Checking out LNPopupController at "v1.3"
*** xcodebuild output can be found in /var/folders/8r/nl9r6g3s2j36ljrhdnky9ng40000gn/T/carthage-xcodebuild.Np529A.log
*** Building scheme "LNPopupController" in LNPopupController.xcodeproj
```

Carthage says I have the current version.

However it is really hard to find out if the code actually has this version, because there is no version number fixed in any files of the repository to crosscheck.

I only found something in `Info.plist`, but it is outdated: https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/Info.plist#L10

**Comment by funkenstrahlen** [comment]
I just took a look right in the code and can confirm that the version carthage did checkout actually includes this patch: https://github.com/LeoNatan/LNPopupController/commit/ac6d3f92c820097bda374413ea83142c481ed37f

So I assume carthage did build 1.3 correctly.

How can you see my build uses an older version?

**Comment by LeoNatan** [comment]
Hmm, because the popup dismiss button is on top of the bar. But I see you are embedding a navigation controller in a view controller. This all might be iOS fault. Please move the content controller to be a navigation controller directly.

**Comment by funkenstrahlen** [comment]
Unfortunately I can not do that because the UINavigationController is just one of my views inside a UIPageViewController. So the popup content controller has to be either the UIPageViewController directly or a UIViewController containing it.

Would also be nice if you could update the version string in Info.plist

**Comment by funkenstrahlen** [comment]
If I swipe the UIPageViewController left and right, the UINavigationBar is displayed correctly. It just breaks if the popup is minified. I assume Apples code does not handle the additional top space correctly.

**Comment by LeoNatan** [comment]
That's what I fear. There are many issues with embedding navigation controllers that just don't work well. Unfortunately there is little I can do. Will take a look but will likely close this as an Apple bug.

**Comment by funkenstrahlen** [comment]
> That's what I fear. There are many issues with embedding navigation controllers that just don't work well. Unfortunately there is little I can do. Will take a look but will likely close this as an Apple bug.

I understand.

This is how it behaves:

![wb20jkadax](https://cloud.githubusercontent.com/assets/144173/12821720/debe8f16-cb64-11e5-9358-8a788bb56328.gif)
