### ISSUE TITLE
How to use when there are multiple navigation controllers

### ISSUE THREAD

**Issue by ibhavin** [LeoNatan/LNPopupController#450]
Basically, I have sidemenu in my app. When I change the view from sidemenu it also changes its navigation controller. So, how can reinitialize popupcontroller?

**Comment by iDevelopper** [comment]
@ibhavin ,

What do you use for the side menu?

**Comment by LeoNatan** [comment]
You should probably present on the side menu controller directly. If it’s not a controller, it’s probably not a good framework to use.
