### ISSUE TITLE
Feature request: Change marquee scroll speed and expose other behavior/appearance properties?

### ISSUE THREAD

**Issue by SotaJoe** [LeoNatan/LNPopupController#452]
#### Description

Currently, there is no way to change the scroll speed of the marquee title nor subtitle. The default scrolling speed is very slow and takes up to half a minute to scroll an entire line of text that is just 50 characters long. I would like to formally request access to properties to customize the label appearance and behavior (default values are provided by the MarqueeLabel framework beginning at line 234 of "MarqueeLabel.m" file), with great emphasis on the ability to customize scrolling speed of the marquee.

#### Steps to Reproduce

Run the LNPopupController library and assign a 50 character (or greater) title and subtitle. Observe the slow scrolling speed. There is no way currently to change the speed of scrolling.

#### Device, OS and Xcode Versions

Mac OS 11.4, Xcode 12.5

iOS 14.6, iPhone 12 Pro

**Comment by LeoNatan** [comment]
I already opened an issue. https://github.com/LeoNatan/LNPopupController/issues/449
