### ISSUE TITLE
LNPopupController 2.10.x will be the last to support iOS 12.x and below

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#456]
Guys, it is time. LNPopupController 2.11.x will drop support for iOS 12 and below. I am making changes, and do not want to deal with support and shims for these legacy systems anymore. The good news is that, at least from looking at beta 1, iOS 15 is fully supported by the latest LNPopupController 2.10.x release. If you absolutely must support old iOS, use that release until it breaks. Going forward, **LNPopupController will support iOS 13.0 and above only.**

**Comment by iDevelopper** [comment]
Hello,

So we can't build LNPopupController 2.11.0 with the latest version of Xcode (12.5.1)? Right?

**Comment by LeoNatan** [comment]
Why not?
This is about iOS, not Xcode.

**Comment by iDevelopper** [comment]
Did you try? I have some errors at compile time in each (# or @)available(iOS 15.0, *) check.

**Comment by LeoNatan** [comment]
Oh no
Will fix that soon. Thanks for reporting!

**Comment by iDevelopper** [comment]
And for UIColor.systemBrownColor too, in static void LNInitializeDemoColors(void) function.

Property 'systemBrownColor' not found on object of type 'UIColor'.
