### ISSUE TITLE
setNeedsStatusBarAppearanceUpdate() has no effect

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#46]
I present a UIViewController as a popup. I want to change the status bar color dynamically.

I have implemented `preferredStatusBarStyle()` and an `updateStatusBarStyle(style: UIStatusBarStyle)` method to set a new style.

```swift
    override func preferredStatusBarStyle() -> UIStatusBarStyle {
        return statusBarStyle
    }

    func updateStatusBarStyle(style: UIStatusBarStyle) {
        statusBarStyle = style
        self.setNeedsStatusBarAppearanceUpdate()
    }
```

`self.setNeedsStatusBarAppearanceUpdate()` is called as I can see by debugging. However the status bar color does not change.

The status bar only updates its style correctly, if I minify the popup and max again.

![o4wiaxrekp](https://cloud.githubusercontent.com/assets/144173/12817976/1a1a8020-cb55-11e5-8893-b41834154d25.gif)

**Comment by LeoNatan** [comment]
I'll investigate when I have some time.

**Comment by LeoNatan** [comment]
As a workaround, call `setNeedsStatusBarAppearanceUpdate()` on the appropriate `popupPresentationContainerViewController`.

**Comment by funkenstrahlen** [comment]
Works perfectly now! Thanks a lot for the fix! :smiley:

**Comment by LeoNatan** [comment]
Great!!
