### ISSUE TITLE
Xcode 12 compile broken

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#462]
Did you try? I have some errors at compile time in each (# or @)available(iOS 15.0, *) check.

_Originally posted by @iDevelopper in https://github.com/LeoNatan/LNPopupController/issues/456#issuecomment-870338080_

**Comment by LeoNatan** [comment]
Fixed in 2.11.1 @iDevelopper

**Comment by iDevelopper** [comment]
Yes, thanks.

However I don't understand #if __IPHONE_OS_VERSION_MAX_ALLOWED> __IPHONE_14_5, as there is already a version of iOS 14.6 and there will be a 14.7. Is this an Apple inconsistency? And also there is no Simulator for version 14.6.

**Comment by LeoNatan** [comment]
That’s the SDK version. There is no public 14.6 or 14.7 SDK.

**Comment by iDevelopper** [comment]
So we must consider that there will be no bug when we test an application that works on iOS 14.5 on iOS 14.6 or 14.7?

**Comment by LeoNatan** [comment]
I am sorry, I don't understand what you are saying. Xcode 12.x only comes with SDK Version 14.5, so the logic says "if SDK version is above 14.5, compile this". I don't think there will be a later 14.x SDK, so this logic will be fine. Once Xcode 13 has been out for a while, I will require Xcode 13 for the framework and remove these lines.

**Comment by LeoNatan** [comment]
That can also be used. Want to create a quick PR with that line?

**Comment by LeoNatan** [comment]
I'll do it now.
