### ISSUE TITLE
How to remove that blur effect in popupbar?

### ISSUE THREAD

**Issue by CivelXu** [LeoNatan/LNPopupController#463]
I create a CustomBarView extend LNPopupCustomBarViewController class, I want remove hairline、blur effect any views inherit form super.

How can I achieve it

I find related issues  from https://github.com/LeoNatan/LNPopupController/issues/294

```
popupBar.isTranslucent = false
popupBar.backgroundColor = .clear
```
Use this api does not work

**Comment by CivelXu** [comment]
```
        containingPopupBar.subviews.forEach {
            if $0.isKind(of: UIVisualEffectView.self) {
                $0.isHidden = true
            }
        }
```
I can do it this way, but it's not very friendly.

**Comment by LeoNatan** [comment]
What happens if you use the new appearance API to configure the bar appearance to be opaque and set the background color in the appearance to clear?

**Comment by CivelXu** [comment]
I try to used this api in demo project  in `ManualLayoutCustomBarViewController.swift viewDidLoad`

```
        let appearance = LNPopupBarAppearance()
        appearance.configureWithTransparentBackground()
        containingPopupBar.standardAppearance = appearance
```

I expect there will be a transparent bar， but nothing happened.

**Comment by LeoNatan** [comment]
I just opened ManualLayoutCustomBarViewController.swift and added the following code to `viewDidLoad()`:

```swift
override func viewDidLoad() {
	super.viewDidLoad()

	let appearance = LNPopupBarAppearance()
        appearance.configureWithTransparentBackground()
        containingPopupBar.standardAppearance = appearance

	centeredButton.setTitle("Centered", for: .normal)
...
```

And it works as expected:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-29 at 13 11 36](https://user-images.githubusercontent.com/2270433/123780481-e9fc5e00-d8db-11eb-97c0-603033b00c88.png)

Notice the labels at the bottom sit on top of a transparent bar.

**Comment by LeoNatan** [comment]
Also behaves correctly in the second example:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-29 at 13 18 11](https://user-images.githubusercontent.com/2270433/123781054-7870df80-d8dc-11eb-997e-de22dbb6d811.png)
