### ISSUE TITLE
The popupCloseButton can't be dragged, only tapped

### ISSUE THREAD

**Issue by svenoaks** [LeoNatan/LNPopupController#464]
The popup close button only responds to tap. If the popupInteractionStyle  == .drag or .snap, I feel that the button itself should also be draggable. 

Other apps with similar UI element to LNPopup have the button draggable, and I find myself intuitively wanting to drag the button when I use apps such as these.

**Comment by LeoNatan** [comment]
Not as easy to achieve. The close button is added to the popup content view, which also includes the popup content controller's view, but the gesture recognizer is added to the content controller's view, so if a touch begins within the close button's view, the gesture recognizer is not consulted at all.

**Comment by LeoNatan** [comment]
Found a hack to allow this 🙂

**Comment by iDevelopper** [comment]
Why not just add the gesture recognizer to the popup content view?

**Comment by LeoNatan** [comment]
@iDevelopper That's how I did it historically, I think, because of conflicts with other gesture recognizers. Changing it now would require a lot of logic changes.
