### ISSUE TITLE
Build error when turning on Code Coverage

### ISSUE THREAD

**Issue by kieuquangloc** [LeoNatan/LNPopupController#470]
**Describe the Bug**
Build error when turning Code Coverage on

**To Reproduce**
1. Go to 'Edit Scheme'
2. Click on Side bar -> 'Tests'
3. Choose Options -> Gather cover for...
4. Build and See error

**Expected Behavior**
it should build successfull

**Screenshots**
<img width="947" alt="Screen Shot 2021-07-19 at 13 14 29" src="https://user-images.githubusercontent.com/8148640/126117637-6580bd12-d98e-43e3-9374-3185c2d97566.png">

**Build Error**
```
Ld /Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Products/Debug-iphonesimulator/PackageFrameworks/LNPopupController.framework/LNPopupController normal (in target 'LNPopupController' from project 'LNPopupController')
    cd /Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/SourcePackages/checkouts/LNPopupController
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Products/Debug-iphonesimulator/PackageFrameworks -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib -F/Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/Developer/Library/Frameworks -filelist /Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Intermediates.noindex/LNPopupController.build/Debug-iphonesimulator/LNPopupController.build/Objects-normal/x86_64/LNPopupController.LinkFileList -install_name @rpath/LNPopupController.framework/LNPopupController -dead_strip -Xlinker -object_path_lto -Xlinker /Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Intermediates.noindex/LNPopupController.build/Debug-iphonesimulator/LNPopupController.build/Objects-normal/x86_64/LNPopupController_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Intermediates.noindex/LNPopupController.build/Debug-iphonesimulator/LNPopupController.build/Objects-normal/x86_64/LNPopupController_dependency_info.dat -o /Users/myuser/Library/Developer/Xcode/DerivedData/readiOS-flfwdvpsdtvsjnhhmhrlhwowivei/Build/Products/Debug-iphonesimulator/PackageFrameworks/LNPopupController.framework/LNPopupController

Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in LNPopupController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by LeoNatan** [comment]
This doesn’t look like a framework issue but a build issue for n your end. How are you integrating the framework in your project?

**Comment by kieuquangloc** [comment]
Hi @LeoNatan I am using https://github.com/LeoNatan/LNPopupController#swift-package-manager, I am trying to enable Code Coverage can you create an example project with SPM and enable code Coverage?

**Comment by kieuquangloc** [comment]
[testLNPopupController.zip](https://github.com/LeoNatan/LNPopupController/files/6838952/testLNPopupController.zip)
<img width="1724" alt="Screen Shot 2021-07-19 at 14 55 19" src="https://user-images.githubusercontent.com/8148640/126123770-4c7aeef3-117b-4e7f-98f3-32711f3ac8ae.png">
@LeoNatan , here is my test project, hope it can help you to have a quick build

**Comment by kieuquangloc** [comment]
[testLNPopupController.zip](https://github.com/LeoNatan/LNPopupController/files/6838974/testLNPopupController.zip)
<img width="1724" alt="Screen Shot 2021-07-19 at 14 59 10" src="https://user-images.githubusercontent.com/8148640/126124190-cecb7f3e-63d5-4361-a1eb-8bcec46a7b0e.png">
Updated: @LeoNatan , here is my test project, hope it can help you to have a quick build

**Comment by LeoNatan** [comment]
Look here:
https://forums.swift.org/t/undefined-symbols-llvm-profile-runtime-when-building-a-package-with-code-coverage-turned-on/49701

It seems, if you link as static library, it should work. LNPopupController offers a static target in the package. Try that.

**Comment by kieuquangloc** [comment]
@LeoNatan yes, confirmed, it works when I switch to use static package, thank you @LeoNatan 
<img width="921" alt="Screen Shot 2021-07-19 at 15 13 38" src="https://user-images.githubusercontent.com/8148640/126126524-88987584-d89d-4f76-8703-a5b4518ea226.png">
