### ISSUE TITLE
Present popup bar with navigation controller issue.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#471]
Hello,

Issue when presenting the popup bar with a navigation controller and toolbar hidden:
FirstViewController.m, line 195 added
```objc
	if(targetVC == nil)
	{
		targetVC = self.navigationController;
                 self.navigationController.toolbar.hidden = YES; // added
		if(targetVC == nil)
		{
			targetVC = self;
		}
	}
```

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-26 at 17 19 34](https://user-images.githubusercontent.com/1782450/127015065-ed82368d-4981-46f0-b5b7-8ce50712e6df.png)

Xcode 12.5.1 - iOS 14.5 - Simulator iPhone 11 Pro Max

**Comment by pirogman** [comment]
Yep, I'm having same problems on my project. It sometimes leaves that space, but in other transitions to the same screen where the pup is shown - all good. Maybe there is a way to adjust the position so I can fix it when it's misplaced?

**Comment by LeoNatan** [comment]
Thanks, will take a look.

**Comment by LeoNatan** [comment]
@iDevelopper You managed to confuse me. The problem is on your end.

```
self.navigationController.toolbar.hidden = YES;
```

This is not supported by Apple!

What you should do instead is:

```
self.navigationController.toolbarHidden = YES;
```

You are not supposed to touch a navigation bar or a tab bar's properties directly.

**Comment by iDevelopper** [comment]
@LeoNatan ,

Sorry, i'm confused too!
