### ISSUE TITLE
LNPopupCustomBarViewController custom view not appear corrently

### ISSUE THREAD

**Issue by vinayak-nickelfox** [LeoNatan/LNPopupController#472]
Hi I'm try to add custom popup bar and by clicking on custom view I'm presenting expended view.
I create a view controller of subclass LNPopupCustomBarViewController. But when I present the bar it only show the gray view at the bottom instead of my custom view controller.

```
        if let popupVC = MiniAudioViewController.newInstance,
           let expendedVC = ExpendedAudioViewController.newInstance {
   
            expendedVC.popupBar.customBarViewController = popupVC
            expendedVC.popupBar.barStyle = .custom
            
            self.tabBarController?.presentPopupBar(withContentViewController: expendedVC, animated: true, completion: nil)
        }
```
Moreover in custom popup viewcontroller `func popupItemDidUpdate()` is not calling as well. Please help as I'm stuck on this for so many days.

 
![IMG_E55C997B08C3-1](https://user-images.githubusercontent.com/50827434/127625837-5ead7e65-21e6-4765-a696-872d5b46b96e.jpeg)

**Comment by iDevelopper** [comment]
The popup bar is accessible from the container view controller that presents it. Try this:
```swift
        if let popupVC = MiniAudioViewController.newInstance,
           let expendedVC = ExpendedAudioViewController.newInstance {
   
            self.tabBarController?.popupBar.customBarViewController = popupVC
            
            self.tabBarController?.presentPopupBar(withContentViewController: expendedVC, animated: true, completion: nil)
        }
```
And in this case (custom popup bar) you don't need to set the barStyle property to custom.

**Comment by vinayak-nickelfox** [comment]
@iDevelopper Great It's working now. Now I want to open the expended view by clicking on popup view. Can you help me to with it
