### ISSUE TITLE
Podspec file

### ISSUE THREAD

**Issue by Ricowere** [LeoNatan/LNPopupController#477]
Hey guys,

I've been checking the documentation about the Cocoapods support. Unfortunately in our company we have a mixed setup that force us to not being able to get rid of it. And also it's not scalable for us to have multiple DM.

We will go with cocoapods support and we will be hosting in our repository our podspec for it. That's why this issue, I will share here how the podspec looks like just in case (with little extra effort) it would be useful for you.

```ruby
Pod::Spec.new do |spec|
    spec.name = "LNPopupController"
    spec.version = "2.12.3"
    spec.summary = "LNPopupController Podspec"
    spec.homepage = "https://github.com/LeoNatan/LNPopupController"
    spec.license  = "Commercial license"
    spec.authors = { "David Rico" => 'david.rico@flakecreative.co.uk' }
  
    spec.platform = :ios, "13.0"
    spec.requires_arc = true
    spec.source = { git: "https://github.com/LeoNatan/LNPopupController", :tag => spec.version }
    spec.swift_version = "5.0"
  
    spec.module_map = 'LNPopupController.modulemap'
    spec.public_header_files = [
      'LNPopupController/LNPopupController.h', 
      'LNPopupController/LNPopupController/*.h']
    spec.private_header_files = 'LNPopupController/LNPopupController/Private/*.h'
    spec.source_files = [
      'LNPopupController/LNPopupController.h', 
      'LNPopupController/LNPopupController/**/*.{swift,h,m}', 
      'LNPCSwiftRefinements/**/*.swift']
  end
```

In your documentation you mention;

> CocoaPods is not supported. **_There are many reasons for this._** Instead of CocoaPods, use Carthage. You can continue using CocoaPods for for your other dependencies and Swift Package Manager for LNPopupController.

I was testing the integration with the example provided on your side and I wasn't able to spot any malfunctioning issue. So maybe there's something I cannot see 😄  Really appreciated if you could provide some insights about it 🙏 

Hope this helps guys! I think I didn't mention how awesome is this library!!

There's attached below a working example with cocoapods. In case you would like to give it a try.

[LNPopupController.zip](https://github.com/LeoNatan/LNPopupController/files/7001531/LNPopupController.zip)
_Note: Unzip it on the project's root file. I've just attached the changes for brevity._

**Comment by LeoNatan** [comment]
Sorry, CocoaPods is not supported and will not be supported. Please try to use the Swift Package Manager package. That’s the way forward.
