### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rastaman111** [LeoNatan/LNPopupController#479]
My application does not have a tabBarController, only a navigationController, and when I click on the bottom plate, a new window opens, the navigationController remains, how can I hide it? I attach a photo

![image](https://user-images.githubusercontent.com/15727518/132813435-9ee355c3-1fe0-49c7-90f3-d9897dbc0b0c.png)
![image](https://user-images.githubusercontent.com/15727518/132813454-ebebe053-efb7-4f01-b0d1-954c10cc8345.png)
![image](https://user-images.githubusercontent.com/15727518/132813462-5ea5c62a-5215-48a1-ba3c-67cbead2d36d.png)

**Comment by iDevelopper** [comment]
Who is self in your code?

It should be the navigation controller.

**Comment by rastaman111** [comment]
> Who is self in your code?
> 
> 
> 
> It should be the navigation controller.

I didn't understand what you told me.  Show an example of Swift code please

**Comment by LeoNatan** [comment]
You are presenting the bar on the wrong controller. As @iDevelopper said, you need to present it on the navigation bar.

**Comment by rastaman111** [comment]
> You are presenting the bar on the wrong controller. As @iDevelopper said, you need to present it on the navigation bar. 

how can i put a window on the navigation bar, i have 2 screens per application.  0-navigation bar, 1-root, 2-detail, do you suggest between 1 and 2 to insert a navigation bar?

**Comment by LeoNatan** [comment]
I am sorry, I don't understand what you are saying. You keep saying "window", but I don't think you mean a [window](https://developer.apple.com/documentation/uikit/uiwindow).

If you want the popup bar to appear above the navigation bar, you should present it like this:

```swift
self.navigationController.presentPopupBar(withContentViewController: popupContentViewController, animated: true, completion: nil)
```
