### ISSUE TITLE
dismissPopupBarAnimated(true, completion: nil) does not call deinit of contentViewController

### ISSUE THREAD

**Issue by funkenstrahlen** [LeoNatan/LNPopupController#48]
Why is `deinit` of my contentViewController which I present as popupBar not called when I call `dismissPopupBarAnimated(true, completion: nil)` to dismiss the popupbar?

**Comment by LeoNatan** [comment]
Did you put a line of code in the `deinit`? I noticed that the Swift compiler optimizes the `deinit` function if there is nothing in there or just a breakpoint. Put a `print` call and see if it is called then. From my tests, the lib manages memory correctly.

**Comment by LeoNatan** [comment]
Did you test?

**Comment by funkenstrahlen** [comment]
Not yet. Will have time tomorrow.

**Comment by funkenstrahlen** [comment]
Works using the example code in this repository. So this is an issue with my code.

**Comment by funkenstrahlen** [comment]
Did not define a delegate as weak reference. Could fix it now!
