### ISSUE TITLE
Crash on Xcode 13. Can't open app

### ISSUE THREAD

**Issue by johnswifttt** [LeoNatan/LNPopupController#482]
**Describe the Bug**
I can't run my app on an actual phone after updating to Xcode 13. Here is the crash log in the console:
```
dyld[374]: Library not loaded: @rpath/LNPopupController.framework/LNPopupController
  Referenced from: /private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/MyApp
  Reason: tried: '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/System/Library/Frameworks/LNPopupController.framework/LNPopupController' (no such file)
Library not loaded: @rpath/LNPopupController.framework/LNPopupController
  Referenced from: /private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/MyApp
  Reason: tried: '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopupController' (no such file), '/private/var/containers/Bundle/Application/9B29C285-353C-4396-A000-E0A25FD86C11/MyApp.app/Frameworks/LNPopupController.framework/LNPopup
```

Any thoughts on this? Is it because of `dynamic` vs `static` library? I'm using `dynamic`

**To Reproduce**
1. Get Xcode 13
2. Get an actual iPhone on iOS 15. Don't use a simulator.
3. Install LNPopupController with SPM and select `dynamic` option only. The version I have is `2.12.6`
4. Run the app and it will crash

**Expected Behavior**
n/a

**Screenshots**
n/a

**Additional Context**
n/a

**Comment by LeoNatan** [comment]
Yes, this seems like an issue with Xcode. Make sure in your project settings, General -> Frameworks, Libraries and Embedded Content, make sure that LNPopupController is maked as "Embed & Sign". I have a feeling it's "Do Not Embed" for you.

**Comment by johnswifttt** [comment]
Yep, you're right! Thank you!

So for my app I chose:

**Dynamic:**
<img width="381" alt="dynamic" src="https://user-images.githubusercontent.com/10701375/134823407-91b9e317-c551-4519-a516-0a99294d0d9a.png">

I changed this to **Embed & Sign**:
<img width="506" alt="embed" src="https://user-images.githubusercontent.com/10701375/134823406-fd43473a-41a5-4885-8ae1-6dfcac55e718.png">

It seems that `Static` worked without changing anything Embed/Sign, but I believe you said to use `Dynamic` for app in an older issue.

Thanks for helping!

**Comment by LeoNatan** [comment]
It’s a personal preference.

but I do believe this is an Xcode bug. The common case is that you want a dylib/framework to be embedded and signed.

**Comment by johnswifttt** [comment]
Got ok, I was referring to this issue btw: https://github.com/LeoNatan/LNPopupController/issues/422

Is using `Dynamic` a best practice for your library in a regular app?

**Comment by LeoNatan** [comment]
I prefer dynamic frameworks (dylibs) for many reasons. It’s one of these ethereal battles like spaces or tabs 😆. You can Google for “static vs dynamic linking what is better” and see the arguments for that or that. But both will work just as fine for you, just need to make sure Xcode is set up correctly. 👍

**Comment by johnswifttt** [comment]
ooooh I see, I thought it was a requirement to use `Dynamic` lol Thank you for clarifying that! As always, great library and love the work being put in to maintain it.

**Comment by LeoNatan** [comment]
Thank you for the kind words! Happy coding! Also check out LNPopupUI if you dabble in SwiftUI.
