### ISSUE TITLE
Tab Bar Appearance Issue on iOS 15

### ISSUE THREAD

**Issue by johnswifttt** [LeoNatan/LNPopupController#483]
**Describe the Bug**
I just updated my app to iOS 15 and latest version of this library. It seems that now whenever the popup bar is presented, my tab bar has appearance issues. Basically, the font changes and also background color. 

This is the code I always had for standard setup:
```swift
 final class MainTabBarController: UITabBarController {

     override func viewDidLoad() {
         super.viewDidLoad()

         configureAppearance()
      }

      private func configureAppearance() {
           UITabBar.appearance().layer.borderWidth = 0.0
           UITabBar.appearance().clipsToBounds = true
           
           self.tabBar.unselectedItemTintColor = UIColor.darkGray
           self.tabBar.barTintColor = UIColor.letterGray
           
           let tabFont = UIFont.systemFont(ofSize: 10, weight: .heavy)
           UITabBarItem.appearance().setTitleTextAttributes([NSAttributedString.Key.font: tabFont], for: .normal)
           UITabBarItem.appearance().setTitleTextAttributes([NSAttributedString.Key.font: tabFont], for: .selected)
       }
}
```

I tried the new API's to customize popup bar and also tried commenting it all out. Either way issues happen. This is new code for popup bar:

```swift
    func configurePopupBar() {
        mainTabBarController.popupContentView.popupCloseButtonStyle = .none
        
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = .center
        
        let appearance = LNPopupBarAppearance()
        appearance.backgroundColor = .customGray
        appearance.marqueeScrollEnabled = true
        appearance.titleTextAttributes = [.foregroundColor: UIColor.white,
                                          .font: UIFont.systemFont(ofSize: 13, weight: .heavy),
                                          .paragraphStyle: paragraph]
        appearance.subtitleTextAttributes = [.foregroundColor: UIColor.customBlack,
                                             .font: UIFont.systemFont(ofSize: 10, weight: .heavy),
                                             .paragraphStyle: paragraph]
        
        let appearanceProxy = LNPopupBar.appearance()
        appearanceProxy.inheritsAppearanceFromDockingView = false
        appearanceProxy.progressViewStyle = .top
        appearanceProxy.tintColor = .white
        appearanceProxy.barStyle = .compact
        appearanceProxy.standardAppearance = appearance
    }
```

**To Reproduce**
1. Use iOS 15 and actual phone (not simulator)
2. Use library version `2.12.6` and `dynamic` with SPM
3. Use the code above. Once the popup bar is presented for the first time, the tab bar will get messed up in terms of appearance. 

**Expected Behavior**
n/a

**Screenshots**
n/a

**Additional Context**
n/a

**Comment by LeoNatan** [comment]
Checkout this issue.

**Comment by johnswifttt** [comment]
yeah I did. Do you think we have to use `UITabBarAppearance` and `UITabBarItemAppearance` now? These are new API's from Apple whereas above my code uses older API's

**Comment by johnswifttt** [comment]
yeah I did. Do you think we have to use UITabBarAppearance and UITabBarItemAppearance now? These are new API's from Apple whereas above my code uses older API's

**Comment by johnswifttt** [comment]
Hm yeah seems like an Apple bug. If I find solution will post here

**Comment by LeoNatan** [comment]
Your code in the first post doesn’t make sense and won’t work. You are using the appearance proxy wrong. 

`appearance().layer`

That makes zero sense. The appearance proxy is intended to aggregate setter calls, which are then applied to **new instances** of the class after initialization. How do you expect that proxy object to return a layer?

Also, you call the appearance proxy after your view has loaded, so the tab bar has already been instantiated. If you have the objects, just apply the customization to those.

**Comment by johnswifttt** [comment]
yes `appearance().layer` was a "hack" to hide the top line border of the tab bar and it did work. I'm switching to new API's such as:
```swift
        let appearance = UITabBarAppearance()
        appearance.configureWithOpaqueBackground()
        appearance.backgroundColor = .authorGray
        appearance.shadowImage = nil
        appearance.shadowColor = nil
```

still need to see if everything will work

**Comment by LeoNatan** [comment]
Yes, that API works.
