### ISSUE TITLE
Custom TabBar Size

### ISSUE THREAD

**Issue by drewg233** [LeoNatan/LNPopupController#492]
**Describe the Bug**
I have a project where we set the tab bar size to be bigger than default. Unfortunately this does not seem to work well with `LNPopupController`. 

**To Reproduce**
In the storyboard, have a `UITabBarController` as the initial view. Then set its class to `MainTabBarController` defined below.

```
class MainTabBarController: UITabBarController {
    
    let barHeight = CGFloat(120)
    let hapticGenerator = UIImpactFeedbackGenerator(style: .light)
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        UITabBarItem.appearance().titlePositionAdjustment = UIOffset(horizontal: 0, vertical: -10)
        hapticGenerator.prepare()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        var tabFrame = self.tabBar.frame
        tabFrame.size.height = barHeight
        tabFrame.origin.y = self.view.frame.size.height - barHeight
        self.tabBar.frame = tabFrame
    }
    
    override func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        hapticGenerator.impactOccurred()
    }
}
```

**Expected Behavior**
The library accounts for the tab bar size and adjusts the y position top be on top of the tab bar.

**Screenshots**
<img src="https://user-images.githubusercontent.com/6364990/140193248-afadcdb8-0dfe-4e0c-9ec7-da5412c5aa49.png" width="300"/>

**Comment by LeoNatan** [comment]
This isn’t supported, and is actively discouraged by Apple in its documentation. 

you can try implementing this property in your tab bar controller subclass, but it’s not guaranteed to work as expected. 

https://github.com/LeoNatan/LNPopupController/blob/a9696a10488574cc90531d246eb451d694eb84b9/LNPopupController/LNPopupController/UIViewController%2BLNPopupSupport.h#L286

another suggestion would be to move the super call of `viewDidLayoutSubviews` to after manipulating the tab bar’s frame. 

Even if you get it to work with the above workarounds, I cannot guarantee it won’t break in the future.

**Comment by LeoNatan** [comment]
Logically, you yourself are using the default tab bar controller’s layout method to put a default tab bar size, but complain the framework can’t guess you made a change after layout.

**Comment by drewg233** [comment]
Appreciate your response! We will go with the `super.viewDidLayoutSubviews` after setting the frame for now. Understanding that this could break in the future. Thank you!

**Comment by LeoNatan** [comment]
I looked at the source, and I am using the frame of the tab bar as the position of the popup bar. It will probably continue to work. But be careful. Modifying the tab bar has been know to be buggy with Apple. For example, setting the tab bar as hidden used to create a lot of issues.
