### ISSUE TITLE
'popupBar' adjusting for 'bottomDockingView' only after presenting 'contentViewController'

### ISSUE THREAD

**Issue by KevinVitale** [LeoNatan/LNPopupController#51]
I'm trying to add a `popupBar` with a custom `bottomDockingView` (essentially, my player controls view). 

However, I'm seeing some odd behavior: the `popupBar` isn't *initially* respecting the location of the `bottomDockingView`. It's only after I open `contentViewController` (_calling_ `presentPopupBarWithContentViewController`) and then closing it, does the `popupBar` appear connected to the `bottomDockingView` correctly.

<hr/>
##### When presenting the `contentViewController` for the very first time
<img width="376" alt="first_bar" src="https://cloud.githubusercontent.com/assets/276137/13180541/dd268148-d6f6-11e5-9d25-58defe570dab.png">

<hr/>
##### After calling `presentPopupBarWithContentViewController` then closing it
<img width="376" alt="second_bar" src="https://cloud.githubusercontent.com/assets/276137/13180542/dd397adc-d6f6-11e5-8397-1416af3f5b18.png">

<hr/>

If it helps any: the initial state of the view hierarchy (i.e, simply launching the app) indicates the `bottomDockingView` is sitting where it should, but above all other views (including the `popupBar`). Thus, until I figure out what I'm doing wrong, I'm moving the z-position of the `bottomDockingView` to be below the `popupBar`, so at least I can open (then close) its `contentViewController`.

Any insight into what I'm doing wrong? Thanks.

**Comment by LeoNatan** [comment]
Hi,

Have you  also implemented the `defaultFrameForBottomDockingView` method? It tells the system where to position the popup bar.

**Comment by KevinVitale** [comment]
@LeoNatan Yep. Looks like this.

```
extension ViewController {
    override public func bottomDockingViewForPopup() -> UIView {
        return _playerDockingView
    }

    override public func defaultFrameForBottomDockingView() -> CGRect {
        var bottomViewFrame = _playerDockingView.frame
        if _playerDockingView.hidden {
            bottomViewFrame.origin = CGPoint(x: 0, y: view.frame.size.height)
        } else {
            bottomViewFrame.origin = CGPoint(x: 0, y: view.frame.size.height - _playerDockingView.frame.size.height)
        }
        return bottomViewFrame
    }
}
```

**Comment by KevinVitale** [comment]
@LeoNatan: I've created a test project that recreates the issue I'm seeing: 
https://github.com/KevinVitale/TestPopUP

Anything you can do to point me in the right direction would be very helpful! Thanks for your time, and for the project (it's splendid).

**Comment by LeoNatan** [comment]
Thanks, this will be helpful! Will look soon.

**Comment by KevinVitale** [comment]
Any feedback on this? Much appreciated.

**Comment by LeoNatan** [comment]
Fixed.

**Comment by KevinVitale** [comment]
Many, many thanks!
