### ISSUE TITLE
Safe area insets are broken in iOS 16 when building with Xcode 14 beta

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#513]
![Screenshot](https://user-images.githubusercontent.com/2270433/174988839-c79a10b0-6e9b-45b9-8d83-5ef9d156c439.png)

**Comment by MacMark** [comment]
@LeoNatan I updated the LNPopUpController to use this fix. The fix works. But this version make my tab bar appear with a grey background when i do presentPopupBarWithContentViewController. How could i fix this?

Before presenting the tab bar has a black background:
<img width="569" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/626963/187692085-ff352216-102e-4a29-a124-2813586ad31e.png">

After presenting it has a grey background and i count two less layers in the tab bar:
<img width="860" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/626963/187692261-6eefaab6-b586-420c-867c-1ff25c76c8ca.png">

**Comment by MacMark** [comment]
I added a dedicated bug report: https://github.com/LeoNatan/LNPopupController/issues/514
