### ISSUE TITLE
Safe area insets are not maintained correctly in iOS 16

### ISSUE THREAD

**Issue by alexwhb** [LeoNatan/LNPopupController#519]
I'm experiencing the same issue as [here](https://developer.apple.com/forums/thread/708156?login=true#reply-to-this-question), but only inside the LNPopupUI. I'm doing something a little strange where I have a navigation view inside the LNPopup View, but it has worked for me just fine on iOS 15 and below. 

Wondering if anyone has experienced the same issue and has any advice on how to solve. 

[Here's what it looks like in my app](https://user-images.githubusercontent.com/4073691/192586952-f5dd0819-2481-4df0-b778-0f13711bd6be.mp4)

I also realized another very interesting detail.. if you are in the LNPopup view then lock you screen then come back.. this weird navigation behavior goes away and it works as it did on iOS 15.

**Comment by LeoNatan** [comment]
I’ve transferred the issue to LNPopupController, where it should be handled.

**Comment by alexwhb** [comment]
@LeoNatan Thanks for your further investigation into this. Ya it's honestly strange how blatant this bug seems to be, you'd think Apple would have caught it early on in their beta testing. I reported it to them yesterday incase they, somehow, haven't already encountered this bug. Hopefully that does something and they patch this issue in their next release. 🤞

Also it makes sense that it should be in the LNPopupController project. I'll look for it there. Thanks for letting me know.

**Comment by LeoNatan** [comment]
Fixed in 2.14.0.

**Comment by LeoNatan** [comment]
Fixed in 1.4.0 (LNPopupUI)

**Comment by alexwhb** [comment]
@LeoNatan you are truly my hero !!!! Thank you so much!!!
