### ISSUE TITLE
Status Bar + UINavigationController doesn't play nicely.

### ISSUE THREAD

**Issue by MosheBerman** [LeoNatan/LNPopupController#52]
The Apple Music app doesn't use a UINavigationController here, so perhaps this wasn't an anticipated edge case, but whenever I pass a UINavigationController as the popup view controller, the navigation bar doesn't adjust for the status bar.

**Comment by MosheBerman** [comment]
I was able to get this to work with these two steps:

- Add a `UINavigationBar` to the view hierarchy and apply the following constraints: 
  - Center X in Superview 
  - Equal Width to Superview
  - Height greater than or equal to 44. (==44 breaks the `prompt` property of the `navigationItem`.)
  - Top space to Top Layout Guide is 0.
- Implement `UIBarPositioningDelegate`'s `positionForBar:` method. Return `UIBarPositionTopAttached`.

I don't know if this is a bug or standard implementation, but it's worth discussing before closing.

**Comment by LeoNatan** [comment]
I am unable to reproduce the issue as described.

![nobug](https://cloud.githubusercontent.com/assets/2270433/13352833/b060bf50-dc98-11e5-81f4-c31bf6196be4.gif)

Are you sure you are using the latest code of the library? If you are presenting a navigation controller directly, it should work as in the image above. If you are embedding a navigation controller inside another controller, this is not supported - see issue #45.

**Comment by MosheBerman** [comment]
Definitely not sure that it's the latest code, an update might fix. For now I worked around as outlined above, but I'll check out the latest version.

**Comment by LeoNatan** [comment]
Great, let me know.
