### ISSUE TITLE
UIView+LNPopupSupportPrivate.m - Line 296 - valueForUndefinedKey:]: this class is not key value coding-compliant for the key backgroundTransitionProgress

### ISSUE THREAD

**Issue by haarj** [LeoNatan/LNPopupController#520]
**Describe the Bug**
When calling ```[self dismissPopupBarAnimated:YES completion:^{
     
    }];```
I get the crash in the title.
So far this is happening in iOS 14 only. 
**To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by LeoNatan** [comment]
Hmm, thanks, will take a look

**Comment by haarj** [comment]
Thanks @LeoNatan. Love love love this feature!

**Comment by LeoNatan** [comment]
Fixed in latest release.

**Comment by haarj** [comment]
Thanks, @LeoNatan! 🙌
