### ISSUE TITLE
Use the -beginAppearanceTransition:animated: and -endAppearanceTransition APIs

### ISSUE THREAD

**Issue by rastaman111** [LeoNatan/LNPopupController#521]
Hello!
My project started talking about this warning in one of the latest updates to your library

Crashlisting says that crashes happen on iOS 15 and 16 and on all possible devices

How can I fix this or is it on your side?

How to call VC showed in the screenshot

[ViewController] Calling -viewWillAppear: directly on a view controller is not supported, and may result in out-of-order callbacks and other inconsistent behavior. Use the -beginAppearanceTransition:animated: and -endAppearanceTransition APIs on UIViewController to manually drive appearance callbacks instead. Make a symbolic breakpoint at UIViewControllerAlertForAppearanceCallbackMisuse to catch this in the debugger. View controller: <SoundBar.RxViewControllerPlayer: 0x11e07cc00>

[ViewController] Calling -viewDidAppear: directly on a view controller is not supported, and may result in out-of-order callbacks and other inconsistent behavior. Use the -beginAppearanceTransition:animated: and -endAppearanceTransition APIs on UIViewController to manually drive appearance callbacks instead. Make a symbolic breakpoint at UIViewControllerAlertForAppearanceCallbackMisuse to catch this in the debugger. View controller: <SoundBar.RxViewControllerPlayer: 0x11e07cc00>

[](url)
<img width="1035" alt="Снимок экрана 2022-11-06 в 22 09 06" src="https://user-images.githubusercontent.com/15727518/200190181-78568f26-a0b3-403d-93b5-f57d3c3af187.png">

**Comment by rastaman111** [comment]
I am using the latest version of the library

**Comment by LeoNatan** [comment]
Hello, these warnings are harmless and can be ignored. Basically, I take charge over the public view lifecycle callbacks, so you get the correct timing, which is not possible with the system APIs. I’ll try to find a way to suppress those warnings.

**Comment by LeoNatan** [comment]
Fixed in latest release. Please test and let me know.

**Comment by rastaman111** [comment]
@LeoNatan Hi

Great job, this warning stopped appearing
