### ISSUE TITLE
Incorrect popupPresentationState returned after delegate call

### ISSUE THREAD

**Issue by spike-hue** [LeoNatan/LNPopupController#526]
**Describe the Bug**
Hello, awesome library! I think this may might be a bug with `popupPresentationState` :

I am using `LNPopupPresentationDelegate` to observe changes on `popupPresentationState`. 

When the popup bar is made smaller (mini bar), these delegates get called:
1. `popupPresentationController(_:willClosePopupWithContentController:animated:)`
2. `popupPresentationController(_:didClosePopupWithContentController:animated:)`

The issue is that when I check the `popupPresentationState` inside these delegates, the `popupPresentationState` is equal to `LNPopupPresentationStateOpen = 3`. I believe the `popupPresentationState` should instead be `LNPopupPresentationStateBarPresented = 1`.

Could you please check on this? 

**To Reproduce**
1. Go to sample app in this project
2. Add delegate `tabBarController?.popupPresentationDelegate = self` inside of `DemoAlbumTableViewController`
4. Conform to delegates and add print statements (see screenshot in `Screenshots`)
5. Launch the app
6. Go to Demo Music app -> tap a song -> open the player full -> then swipe down to make it small (mini)
7. Notice the print statements show `LNPopupPresentationState(rawValue: 3)`. This is the issue which I think should be `LNPopupPresentationStateBarPresented = 1` instead.

**Expected Behavior**
Please see description above.

**Screenshots**
This is how I set it up in your sample app included in the project. I added the delegate to `DemoAlbumTableViewController` and printed out the `popupPresentationState` inside of delegates upon making the popup bar smaller (mini).
<img width="1470" alt="sample" src="https://user-images.githubusercontent.com/10701375/201494947-38143034-21e2-4fd9-9737-8acd52041cb3.png">

**Additional Context**

Tested on:
- LNPopupController 2.13.7 installed with SPM
- Xcode 14.1
- iOS 16.1.1 
- Physical iPhone (not simulator)

**Comment by spike-hue** [comment]
@LeoNatan Any thoughts on this? Is what I wrote clear?

**Comment by LeoNatan** [comment]
Hello,

I will investigate soon.

**Comment by LeoNatan** [comment]
Hello, sorry for the long delay. Fixed in 2.14.7.

I tweaked the timing of all the delegate methods to be correct. So the value you see in `will` delegate methods will be the state before the relevant action started, while in `did` delegate methods, the state will be the expected end value.

**Comment by spike-hue** [comment]
Thank you @LeoNatan!! Looks like it working!

**Comment by spike-hue** [comment]
Thank you @LeoNatan!! Looks like it's working! ❤️
