### ISSUE TITLE
SPM resource management is not working

### ISSUE THREAD

**Issue by 0si43** [LeoNatan/LNPopupController#527]
**Describe the solution you'd like**
- create 3 libraries in Package.swift(referring the same targets)
  - implicit
  - static
  - dynamic

**Additional context**
- SPM(Swift Package Manager)/Xcode can assume library type when a library has no explicit linking setting
- (build on Xcode, Xcode Cloud, Xcode Previews……)
- I've experimented build error caused explicit linking setting
  - static setting prevent to build on Xcode Previews
  - dynamic setting prevent to build on Xcode Cloud

**Comment by LeoNatan** [comment]
What do you mean “dynamic setting prevent to build on Xcode Cloud”? That makes no sense, I’m sorry. Your PR complicates the package, but I see no reason why it’s necessary.

**Comment by LeoNatan** [comment]
Post the exact error you are getting when building.

**Comment by 0si43** [comment]
@LeoNatan 
🫡Okay, let me explain in detail. 

The exact error message is below.

```
ITMS-90334: Invalid Code Signature Identifier. The identifier "LNPopupController-55554944823d173b292035d5a9f68255954da87b" in your code signature for "LNPopupController" must match its Bundle Identifier "LNPopupController"
```

This error is caused by explicitly specifying `LibraryType`.
Removing the library type means Xcode will link the package statically if the package is only imported by one target.

To be more specific, please see thread below.

https://developer.apple.com/forums/thread/708284?answerId=732491022#732491022

**Comment by LeoNatan** [comment]
So this is an Apple bug 🤦‍♂️ what a silly, garbage company. They are really incapable of doing anything right these days. 

But I'm not convinced I should accept the PR. Perhaps just remove the static altogether. It was needed in the past due to another Apple bug. 🤦‍♂️

**Comment by LeoNatan** [comment]
> refactor how your targets are structured, reducing the reliance on the package to a single target, so that this becomes the first scenario I described where Xcode can safely link the library statically while avoiding the code signing error, as well as avoiding duplicate symbol issues.

This isn't possible for my library, because SPM does not support mixed languages. 🤦‍♂️

**Comment by LeoNatan** [comment]
I'm sorry, I won't dirty up the framework and package for Apple bugs. Please fork, if you must, and make the change for your builds. I'd suggest using a proper CI solution, one not build by Apple.
