### ISSUE TITLE
Failing builds on Azure Pipeline with Xcode 14.

### ISSUE THREAD

**Issue by darecki** [LeoNatan/LNPopupController#533]
**Describe the Bug**
We've been using the library for a long time. Azure Pipeline is used as our CI/CD. Everything was fine until we wanted to migrate the pipeline to Xcode 14. LNPopupController is the single library in our setup that causes the problem. 

**To Reproduce**
1. Create a dummy project.
2. Add LNPopupController as a dependency through SPM.
3. Run Azure Pipeline build.

**Expected Behavior**
Build succeeds.

**Screenshots**
-

**Additional Context**
Again, everything works fine on Xcode 13. It only breaks on Xcode 14.

**Comment by LeoNatan** [comment]
?

You haven’t even added an error to your bug report. What do you expect me to do?

**Comment by darecki** [comment]
I found out that using the static version of the product (`LNPopupController-Static`) solves the issue. Not sure what's the difference between Xcode 13 and Xcode 14 in this aspect, but I'm happy to close the issue.
