### ISSUE TITLE
iOS 17: New “Floating" Popup Bar Style

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#538]
![IMG_5512](https://github.com/LeoNatan/LNPopupController/assets/2270433/a10c8dae-732f-4608-8be6-6e378c648827)

**Comment by iDevelopper** [comment]
Hello,

Do you think it's a toolbar? It is really very white and transparent at the same time!

**Comment by LeoNatan** [comment]
It’s almost done implementing it. The floating background is actually the standard system chrome material, while the tab bar has a thin material. 

I’m not sure yet how to implement so the tab bar gets the thin material automatically.

**Comment by LeoNatan** [comment]
WIP so far:

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-24 at 15 07 26](https://github.com/LeoNatan/LNPopupController/assets/2270433/bcb898eb-0468-4561-8d68-7cc710862d11)

**Comment by LeoNatan** [comment]
It's now almost pixel accurate. I think it's good enough for me, considering there are more capabilities in my framework than Apple's implementation (limited to Music).

![Uploading Simulator Screenshot - iPhone 14 Pro Max - 2023-08-25 at 16.46.36.png…]()

The only thing left is to decide how to deal with the `UITabBar`/`UIToolbar` appearance. By default, if user does not changes to the bottom view's appearance, this is how the floating popup bar will look like:

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-25 at 16 49 15](https://github.com/LeoNatan/LNPopupController/assets/2270433/59db7868-c363-4dc7-9478-efd45c65faea)

As you can see, the tab bar's separator is there and the material is the default chrome material. I don't like this. I can probably do the bare minimum of hiding the separator, so it would look like this by default:

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-25 at 16 49 41](https://github.com/LeoNatan/LNPopupController/assets/2270433/e516f1a8-e84a-43ab-9acf-5fea89b8325f)

Still not optimal, because there is not enough contrast between the tab bar and the floating popup bar, but much better. The issue with automatic effect modification is that the user might have changed the appearance of the bottom bar manually. So maybe I could limit my modification to only if the bottom bar has the default appearance.

**Comment by LeoNatan** [comment]
Out now in 2.15.0. Enjoy!

**Comment by iDevelopper** [comment]
Hello,

There is a crash when setting _toolbar.compactAppearance to nil in LNPopupBar.m
<img width="1792" alt="Capture d’écran 2023-08-30 à 09 23 09" src="https://github.com/LeoNatan/LNPopupController/assets/1782450/ef7359ff-de9f-4659-b141-94bae47660b1">

**Comment by LeoNatan** [comment]
I’ll investigate, thanks @iDevelopper

**Comment by LeoNatan** [comment]
@iDevelopper What are you reporting exactly? I don't understand.

Calling `self.navigationController.toolbar.compactAppearance = nil;` works just fine.

**Comment by iDevelopper** [comment]
I just ran the example (target LNPopupControllerExample), nothing more. Under iOS 17.0 on device iPhone 14 Pro & simulator, Xcode Version 15.0 beta 8 (15A5229m). The crash occurs following the execution of line 283 _toolbar.compactAppearance = nil; in LNPopupBar.m.

**Comment by LeoNatan** [comment]
Made changes to the shadow under the floating bar that required a surprising amount of changes to support. 🤣 Will push soon. 

![IMG_5846](https://github.com/LeoNatan/LNPopupController/assets/2270433/679dad75-9e5e-4258-8d55-288c30cf01a5)
![IMG_5845](https://github.com/LeoNatan/LNPopupController/assets/2270433/27be883d-e74b-4cd2-b5c4-38ac62ab494b)
