### ISSUE TITLE
Example App Crashes on launch

### ISSUE THREAD

**Issue by gtokman** [LeoNatan/LNPopupController#540]
# Description
I downloaded the project and ran the example on simulator and a crash occurred on launch in `viewDidLoad`.

# Screenshot
<img width="1140" alt="CleanShot 2023-08-30 at 12 21 16@2x" src="https://github.com/LeoNatan/LNPopupController/assets/12258850/03800fa1-af74-453e-a351-06a6adc39778">

**Comment by LeoNatan** [comment]
Thanks, someone else reported this, but couldn’t reproduce. @iDevelopper 
What OS/hardware?

Thanks!

**Comment by gtokman** [comment]
I can run the non pop target fine, but the pop up window example crashes every time. I saw you noted a few things about iOS 17 vs 16. But I don't have the new Xcode installed yet to try it.

Xcode 14.3.1
M1 - Ventura 13.5.1

**Comment by LeoNatan** [comment]
Thanks, I’ll look again.

**Comment by iDevelopper** [comment]
I can run the non pop target fine also, but the up & down buttons do nothing.

**Comment by iDevelopper** [comment]
Device iOS 17.0, Xcode version 15.0 beta 8 (15A5229m), iPhone 14 Pro simulator or device too, Mac Ventura 13.4.1 (c).

**Comment by LeoNatan** [comment]
I see `obj` is `nil` for some reason. For me, it doesn't reproduce ever. I will add a check to make sure this crashing flow doesn't happen.

**Comment by LeoNatan** [comment]
So apparently, iPhone 13 mini, iPhone 14 Pro and iPhone 14 Pro Max behave differently internally. 🤦‍♂️

I think I have fixed this in the latest release. Please test and let me know @gtokman @iDevelopper @jiangdi0924

**Comment by jiangdi0924** [comment]
> So apparently, iPhone 13 mini, iPhone 14 Pro and iPhone 14 Pro Max behave differently internally. 🤦‍♂️
> 
> I think I have fixed this in the latest release. Please test and let me know @gtokman @iDevelopper @jiangdi0924

@LeoNatan  i hava test in real device iPhone 14 iOS 17 beta,  works fine and is very smooth!!! 🙂

**Comment by LeoNatan** [comment]
Great, thank you for confirming. Will close the issue for now; let me know if there are more issues.

**Comment by iDevelopper** [comment]
There is a bug when (TabBarController + Navigation Controller) when push next with hidesBottomBarWhenPushed = true.
If we cancel the back animation (swipe) and come back again, the background view disappears.

**Comment by LeoNatan** [comment]
Hi @iDevelopper 
Could you please record a video of the problem and upload it? Thanks

**Comment by iDevelopper** [comment]
Yes,

https://github.com/LeoNatan/LNPopupController/assets/1782450/badc285d-eee9-492d-a51b-16e348857edf

**Comment by LeoNatan** [comment]
Thanks!

**Comment by LeoNatan** [comment]
@iDevelopper I found the issue and will fix it in the next release. Thanks for reporting!
