### ISSUE TITLE
Style question

### ISSUE THREAD

**Issue by rastaman111** [LeoNatan/LNPopupController#541]
Hello
I want to change barStyle in real time from prominent to floating, and from floating to prominent

But I faced such problem

Еhat when I return from floating to prominent, the background of the bar does not return to the default state

Attached screenshots, pay attention to 1 and 3
<img width="435" alt="Снимок экрана 2023-09-06 в 10 08 37" src="https://github.com/LeoNatan/LNPopupController/assets/15727518/a08058b8-4db9-4bc0-b464-a37016ace63f">
<img width="432" alt="Снимок экрана 2023-09-06 в 10 08 52" src="https://github.com/LeoNatan/LNPopupController/assets/15727518/e9130d97-5096-4af6-baa4-7226cd40dc7e">

<img width="431" alt="Снимок экрана 2023-09-06 в 10 09 05" src="https://github.com/LeoNatan/LNPopupController/assets/15727518/18856828-c2f9-43ce-bd5f-2e115e1371d9">

**Comment by LeoNatan** [comment]
Hello,

This should work as expected. Have you changed the standard appearance by any chance?
Perhaps you can post a small sample project, reproducing the issue. 

Thanks

**Comment by rastaman111** [comment]
The first screen is me showing the Bar, on the second screen I change the style
<img width="844" alt="Снимок экрана 2023-09-06 в 19 04 49" src="https://github.com/LeoNatan/LNPopupController/assets/15727518/5f80aef7-16f0-4c14-9065-4aa6eed1a1d6">
<img width="743" alt="Снимок экрана 2023-09-06 в 19 04 59" src="https://github.com/LeoNatan/LNPopupController/assets/15727518/98d19ff4-dc4a-42ec-aa15-d95d725516c5">

**Comment by LeoNatan** [comment]
Hmm, maybe it’s getting confused with the toolbar style. Could you please create a small project recreating the issue? I am on vacation and will look at it once I’m home. Thanks

**Comment by rastaman111** [comment]
yes, okay, one of these days I'll throw off the demo

**Comment by rastaman111** [comment]
I also noticed that the floating style does not accept appearance

**Comment by LeoNatan** [comment]
It does. It just has its own settings for the floating background.

**Comment by LeoNatan** [comment]
https://github.com/LeoNatan/LNPopupController/blob/43e71be8e7b802f7d1d0bc9a8cc62f036cd7c8d7/LNPopupController/LNPopupController/LNPopupBarAppearance.h#L71

**Comment by rastaman111** [comment]
Attached a test project, it repeats the bug
[TestLNPopup.zip](https://github.com/LeoNatan/LNPopupController/files/12546306/TestLNPopup.zip)

**Comment by LeoNatan** [comment]
Fixed in 2.15.6

Please try and let me know.

**Comment by rastaman111** [comment]
Hi, I checked the new version, everything works for a long time, super👍🏼
