### ISSUE TITLE
SwiftUI preview does not compile with missing required module 'LNPopupController_ObjC

### ISSUE THREAD

**Issue by iDylanK** [LeoNatan/LNPopupController#543]
**Describe the Bug**
SwiftUI previews (without LNPopupControllers) do not compile with missing required module 'LNPopupController_ObjC

**To Reproduce**
1. Add LnPopupController using SPM
2. Try to build any swiftui preview.

**Additional Context**
```
 Compile Swift source files (arm64):
    error: emit-module command failed with exit code 1 (use -v to see invocation)
    error: fatalError
    
    
    Compile X.swift (arm64):
    <unknown>:0: error: missing required module 'LNPopupController_ObjC'
```

**Comment by LeoNatan** [comment]
Hello,

What happens if you add LNPopupUI instead? In the demo project of LNPopupUI, I am able to see previews with the popup bar, or at least was possible the last time I tried. 

If your project compiles normally with LNPopupController, but fails to build previews, I'd lay the blame with Xcode.

Please test with LNPopupUI, and then we'll see what we can be done for LNPopupController. 

Thanks

**Comment by LeoNatan** [comment]
https://github.com/LeoNatan/LNPopupUI

**Comment by LeoNatan** [comment]
Also, which variant did you use, the dynamic framework or static library? I remember some issues in the past complaining about one or the other.

**Comment by LeoNatan** [comment]
See this issue here:

https://github.com/LeoNatan/LNPopupUI/issues/23

**Comment by iDylanK** [comment]
Thank you for your quick response. 
We started using SwiftUI for some new views in our large UIKit based application, so we need to keep using LNPopupController. Inside these new SwiftUI views, LNPopupController is not used.

The project itself compiles without any problems. 

I tried adding it statically, but unfortunately this does not resolve this issue.

**Comment by LeoNatan** [comment]
Could you please create a small project recreating the issue?

I'm not sure what I can do if it's an Apple bug. SPM still does not support mixed-language targets, so I have to split the library into two targets, and import one from the other.

**Comment by LeoNatan** [comment]
Maybe I can export the LNPopupController-ObjC target, but that seems ugly to me.

**Comment by iDylanK** [comment]
Our project is split into multiple sub packages, one of which is a Presentation package.
The presentation package includes the LNPopupController package in its package.swift file.

If I add LNPopupController to the 'Package dependencies' of the whole project it seems to work. 

In a demo project however, it also works when LNPopupController is only included in the sub package.
So the issue might also be specific to our project, but I can't figure it out just yet.

**Comment by LeoNatan** [comment]
🤦‍♂️

Everything is so broken with Apple toolchains. Could you post the whole log?

Another thing I can suggest which will solve the issue for sure is bringing LNPopupController as a git submodule and adding it as a subproject of your presentation project.

**Comment by LeoNatan** [comment]
Hello,

Has there been progress on this issue?

**Comment by LeoNatan** [comment]
Please try build 2.15.21. I made a change to the Package.json that might fix this.

**Comment by LeoNatan** [comment]
Closing the issue for now. Let me know if I can help further.
