### ISSUE TITLE
Floating background color

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#544]
**Describe the Bug**
/// A color to use for the bar floating background. This color is composited over `floatingBackgroundEffect`.
@property (nonatomic, readwrite, copy, nullable) UIColor* floatingBackgroundColor;

This does not seem to be the case. The background color is under the effect.

**Comment by LeoNatan** [comment]
You need to call configureWithOpaqueFloatingBackground to get just a color, just like the system bars.

**Comment by LeoNatan** [comment]
If you are seeing a bug, please post a screenshot.

**Comment by LeoNatan** [comment]
Ah I think I understand what you mean. That’s the text that Apple uses in their header files, but it’s implemented to how I did it.

**Comment by LeoNatan** [comment]
I see on my iOS 17 device that the color under the popup bar does not look like it does under the tab bar. So there is a bug. Will look into it, thanks!

**Comment by LeoNatan** [comment]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-10-05 at 22 24 21](https://github.com/LeoNatan/LNPopupController/assets/2270433/8bd1eb22-a2d5-4b23-95e7-2c874106c795)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-10-05 at 22 26 28](https://github.com/LeoNatan/LNPopupController/assets/2270433/86ba736f-c990-4e59-b22c-de877ba1c041)
 
I will push soon.

**Comment by LeoNatan** [comment]
@iDevelopper Please test with 2.15.15. Thanks for reporting!

**Comment by iDevelopper** [comment]
It seems to be better 😊
