### ISSUE TITLE
RTL layout issues

### ISSUE THREAD

**Issue by Omarbasaleh** [LeoNatan/LNPopupController#548]
The layout for title and subtitle labels are not correct. The issue started from version `2.15.17`.

Also the second bar button item (play/pause) is not working in RTL.

**Screenshots**
<br>
`2.15.17` and above

<img width="407" alt="Screenshot 2023-11-13 at 1 41 57 PM" src="https://github.com/LeoNatan/LNPopupController/assets/29621925/0812185a-3c0a-4e99-bf42-834272579278">

<br><br>
`2.15.15`

<img width="406" alt="Screenshot 2023-11-13 at 1 42 14 PM" src="https://github.com/LeoNatan/LNPopupController/assets/29621925/5ce3cf99-a57e-4078-a680-9ec8105730be">

**Comment by LeoNatan** [comment]
Thank you,
I will take a look soon, when I can.

**Comment by LeoNatan** [comment]
Please test with the latest release. Thanks and happy coding!

**Comment by Omarbasaleh** [comment]
Works perfectly 👍
Thank you for the quick response
