### ISSUE TITLE
Content controller is displaying under the navigation bar

### ISSUE THREAD

**Issue by akac** [LeoNatan/LNPopupController#55]
I have a UINavigationController with a UIVC as its content controller. I call:
`	[self presentPopupBarWithContentViewController:self.mapNavigationController animated:YES completion:nil];
`
and it all works great. I get my viewDidLayoutSubviews - I alter the table content insets and all is good!

However when I open the content controller either by tapping on the button or swiping up, the content is under the navigation controller's navbar. 

Now in your sample, you present the popupbar on the self.navigationController if there is no tab bar - and true, if I set it to navigationBar…it overlays the navigation Bar correctly…but then I don't get any changes to my bottom layout guide to offset the tableview content offsets. 

There has to be a way to make both work…

**Comment by LeoNatan** [comment]
Can you provide a demo project?

**Comment by akac** [comment]
I'll try, but it may be a few days. Not sure if this helps:
![xcode001](https://cloud.githubusercontent.com/assets/364743/13680267/10614408-e6b5-11e5-9dba-c65c75562f8c.png)

**Comment by LeoNatan** [comment]
I don't think this is enough. Create a small project with no real data, just a demonstration of the problem. I'll take a look.
