### ISSUE TITLE
xcode manual build error

### ISSUE THREAD

**Issue by Nododo** [LeoNatan/LNPopupController#552]
xcode manual build

error：

Build input file cannot be found: '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-ccrjvudpbqjhgogckewynfovcute/Build/Products/Debug-iphoneos/LNPopupController.framework/Headers/LNPopupController-Swift.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

**Comment by LeoNatan** [comment]
Hello,
Unfortunately, I don’t understand what you are trying to do when you get this error. 
Please formulate a coherent question and provide exact steps to reproduce your issue. 
Thanks

**Comment by LeoNatan** [comment]
@Nododo Take a look at the demo project included in the repo. It shows you how to achieve the "drag framework and kink it in an enclosing project". You will probably find it easier to just use Swift Package Manager.
