### ISSUE TITLE
Popup Bar title and subtitle layout/visibility with MarqueeLabel enabled.

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#553]
**Describe the Bug**
When the title is not scrollable and the subtitle is, the title of the popup bar disappears for a few seconds when the subtitle starts to scroll, then reappears. This happens when the content view popup has been opened and closed at least once. It's the same thing if the subtitle is smaller than the title, the subtitle disappears.

**To Reproduce**
1. Select a scene.
2. If one of the titles is not scrollable, open the content and close it. Else go back and select again a scene.
3. Have a look to the issue

**Expected Behavior**
One of the titles must not disappear.

**Screenshots**
https://github.com/LeoNatan/LNPopupController/assets/1782450/d35cb926-b896-419d-9fef-690cfd45b733

**Additional Context**
iOS 17.1.2, iPhone 14 Pro.

**Comment by LeoNatan** [comment]
Hello,

Thank you! I will investigate soon.

**Comment by LeoNatan** [comment]
Fixed in 2.17.1. Please try. Thank you for reporting!
