### ISSUE TITLE
Swiping down on a .popupInteractionStyle(.drag) popup causes both the popup and the tabBar to hide

### ISSUE THREAD

**Issue by Cleover** [LeoNatan/LNPopupController#554]
**Describe the Bug**
When swiping down at the bottom of a popup on a popup with .popupInteractionStyle(.drag) set, it is possible to cause both the popup and the tabBar to become hidden.

**To Reproduce**
I have created a extremely basic SwiftUI app to show this bug, https://pastie.io/ukxbjx.swift

1. Scroll down on bottom of popup

**Expected Behavior**
You would not be able to scroll down on a popup to cause this bug

**Screenshots**
Demo App Bug:
https://github.com/LeoNatan/LNPopupUI/assets/40129637/760f1b34-275f-4eaf-aeaa-5099a8310314
Prod App Bug:
https://github.com/LeoNatan/LNPopupUI/assets/40129637/cb8da042-cfe4-4d0e-9b35-ea9b4ea14ec8

**Additional Context**
1. This does not happen when .popupInteractionStyle(.drag) is not added, it seems like a bug only when dragging is enabled on popups.
2. There are also other outcomes of this bug, such as it showing the popup fully, but removing the ability to close it by dragging / clicking on the chevron.
https://github.com/LeoNatan/LNPopupUI/assets/40129637/3385eed3-79cc-40ae-9b32-c837bcb71ec1

**Comment by LeoNatan** [comment]
2.18.2 out with a fix for this issue. Cheers

**Comment by Cleover** [comment]
Works like a charm, thanks!
