### ISSUE TITLE
Swipe down

### ISSUE THREAD

**Issue by rastaman111** [LeoNatan/LNPopupController#555]
Hello, I noticed that when scrolling down the screen does not behave like for example Apple Music, you have to use force to close the screen. 
Is it possible to make it smooth somehow?

**Comment by LeoNatan** [comment]
Hello,

The framework offers different interaction styles you can set, including `.snap`, which is the default, and `.drag`, which will behave as you request. My feeling is you'd like to keep the snap behavior for opening and the drag behavior for closing? You can achieve this by setting an object that conforms to the `LNPopupPresentationDelegate` protocol as the `popupPresentationDelegate`, and changing the interaction style depending on the state of the popup (if open, change to `.drag`, or otherwise, change to `.snap`.

**Comment by rastaman111** [comment]
Okay, I'll try it and write down what happens

**Comment by rastaman111** [comment]
I like how the .drag style works, but I don’t like when you drag down and the popupBar is visible at the top
If it was visible like in normal style it would be cool

**Comment by LeoNatan** [comment]
The drag style is modeled after the iOS 8 Music app (yes, the framework has been that long in development). There are no real plans to make changes to how the drag interaction style works.

**Comment by LeoNatan** [comment]
You can also try the customized snap, where you play around with the amount of pull needed to close the popup. Might find something you like.

**Comment by rastaman111** [comment]
yes, I tried to customize, the default was 0.32, I set it to 0.24, but this is still not the behavior that I would like to get

**Comment by rastaman111** [comment]
> The drag style is modeled after the iOS 8 Music app (yes, the framework has been that long in development). There are no real plans to make changes to how the drag interaction style works.

It's too bad that there are no plans for modernization, it's a very cool library. There is something to strive for

**Comment by LeoNatan** [comment]
Well, the real modernization needed is to make the framework use actual controller presentation, and then use a sheep presentation controller (like the music app currently to uses). That is a very big task that I haven’t found the time or will to go through in several years.

**Comment by LeoNatan** [comment]
I’ve also been less and less inclined to follow one to one Apple’s wonky design changes of the Music and Podcasts miniplayers. As time goes by, I prefer to choose my own defaults and let more customization for users. But customizing transitions in the current state is really not possible.

**Comment by rastaman111** [comment]
Ok, then I’ll wait, maybe time will suddenly appear and I’ll be able to make at least one new steel to hide the sheet😉
