### ISSUE TITLE
Miniplayer disappears sometimes and popup is not opened.

### ISSUE THREAD

**Issue by iDylanK** [LeoNatan/LNPopupController#557]
**Describe the Bug**
After opening the popup using openPopup, the miniplayer sometimes disappears and the popup is not opened. 

**To Reproduce**
1. Open the popup using a button (openPopup)
2. Close the popup by dragging
3. Immediately open the popup again using the button click (openPopup)
4. The MiniPlayer disappears and the popup is not opened. This state is unrecoverable. 

Sometimes it requires a few attempts.

**Comment by LeoNatan** [comment]
Hello,

Please attach a small project that reproduces this issue. 

Thanks

**Comment by iDylanK** [comment]
Hi,

At the moment I can't reproduce it in a demo project. I will try again next week! Thanks.

**Comment by LeoNatan** [comment]
Closing for now. Please reopen if you manage to reproduce. Also make sure you are using the latest version. 

Thanks

**Comment by iDylanK** [comment]
Fixed by updating to v1.18! Thanks again.
