### ISSUE TITLE
Wrong subtitle label layout on RLT

### ISSUE THREAD

**Issue by Omarbasaleh** [LeoNatan/LNPopupController#561]
**Describe the Bug**
Wrong subtitle label starting point in RLT when `marqueeScrollEnabled` is true.

<img width="407" alt="Screenshot 2024-02-16 at 8 20 07 PM" src="https://github.com/LeoNatan/LNPopupController/assets/29621925/a12bbd08-b03b-473b-9b07-a70adb844cdd">

**Comment by LeoNatan** [comment]
Hello,

thank you for this report. Will look into this soon.

**Comment by LeoNatan** [comment]
2.18.5

**Comment by Omarbasaleh** [comment]
Working fine.. thank you
