### ISSUE TITLE
Hiding popup var always animates.

### ISSUE THREAD

**Issue by Omarbasaleh** [LeoNatan/LNPopupController#562]
**Describe the Bug**
Hiding popup var always animated even though I am using `dismissPopupBar(animated: false)`

https://github.com/LeoNatan/LNPopupController/assets/29621925/34b1e61d-78d3-4941-ba77-06aaf97c268a

it was working fine on `v2.16.4`

**Comment by LeoNatan** [comment]
Fixed. Will look to fix the other issue with the label and release a version for you to try. Thanks

**Comment by LeoNatan** [comment]
2.18.5
