### ISSUE TITLE
Unsafe build flags

### ISSUE THREAD

**Issue by rastaman111** [LeoNatan/LNPopupController#563]
Hello
I use SPM
Updated to 2.18.5 and got an error
"The package product 'LNPopupController' cannot be used as a dependency of this target because it uses unsafe build flags."
<img width="495" alt="Снимок экрана 2024-02-17 в 22 41 21" src="https://github.com/LeoNatan/LNPopupController/assets/15727518/8736147b-8ff4-416a-8d42-a40abd527f5b">

**Comment by LeoNatan** [comment]
Huh 🤦‍♂️

Thanks for pointing this out, I added something in one of the last commits. I will remove it and release a new version.

**Comment by LeoNatan** [comment]
2.18.6

**Comment by rastaman111** [comment]
Works👍🏼
