### ISSUE TITLE
prefersHomeIndicatorAutoHidden not called

### ISSUE THREAD

**Issue by mmdumi** [LeoNatan/LNPopupController#566]
**Describe the Bug**
I'm trying to control the home indicator appearance when presenting a controller from inside LNPopupController framework.

**To Reproduce**
I've attached a sample project to easily test this behaviour.
1. In `ViewController` line: 31 - if you call `presentPopupBar` you will see that `prefersHomeIndicatorAutoHidden` inside PresentedViewController is NOT called
2. In `ViewController` line: 32 - if you call `present(controller` you will see that `prefersHomeIndicatorAutoHidden` inside PresentedViewController IS called correctly

**Additional Context**
Uploaded sample project.
[Test.zip](https://github.com/LeoNatan/LNPopupController/files/14371516/Test.zip)

Thank you

**Comment by LeoNatan** [comment]
Hello,

Indeed, this is a use case I have not looked into. Will try to provide it soon. 

Thanks
