### ISSUE TITLE
No type or protocol named 'UIObjectTraitDefinition' error when trying to build xcode

### ISSUE THREAD

**Issue by aajibade1** [LeoNatan/LNPopupController#567]
**Describe the Bug**
Hello. I use SPM to import latest release into xcode, however, when trying to build project, get the following error. 
No type or protocol named 'UIObjectTraitDefinition'. Can locally import and remove definition but it seems declaration is missing. 
Stems from the file Private/LNPopupBarAppearance+Private.h

**To Reproduce**
1. Create a Dummy project in Xcode
2. Add LNPopupController as a dependency through SPM
3. Build dummy project
4. Build fails and error is generated

**Expected Behavior**
Build Succeeds

**Screenshots**
![Capture d’écran 2024-03-15 à 17 18 29](https://github.com/LeoNatan/LNPopupController/assets/57687424/3d8137fd-a4d0-4e3f-9529-b187ee7d3dea)
![Capture d’écran 2024-03-15 à 17 18 37](https://github.com/LeoNatan/LNPopupController/assets/57687424/0fecdba5-5244-4a0b-9274-d6a7542f78c4)

**Additional Context**
Not sure if Xcode version but i'm running on Xcode 14.3.1 (Ventura 13.6.5) and Swift-tools-version: 5.5

**Comment by LeoNatan** [comment]
Hello,

The issue does indeed stem from using an old version of Xcode, without the latest version of the iOS SDK. While the framework supports older versions of iOS, it requires Xcode 15 in order to compile. This is not a bug.

Please be aware that starting in April 2024, Apple will require that apps be built against the iOS 17 SDK, meaning you will need to use the latest Xcode.

> ITMS-90725: SDK version issue - This app was built with the iOS 16.1 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

At this point, there is no reason to put additional work to support old Xcode versions in this framework.

Thanks

**Comment by aajibade1** [comment]
Great. Thanks!

**Comment by hell001** [comment]
> Hello,
> 
> The issue does indeed stem from using an old version of Xcode, without the latest version of the iOS SDK. While the framework supports older versions of iOS, it requires Xcode 15 in order to compile. This is not a bug.
> 
> Please be aware that starting in April 2024, Apple will require that apps be built against the iOS 17 SDK, meaning you will need to use the latest Xcode.
> 
> > ITMS-90725: SDK version issue - This app was built with the iOS 16.1 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.
> 
> At this point, there is no reason to put additional work to support old Xcode versions in this framework.
> 
> Thanks

@LeoNatan For those of us that do not publish to the App Store (private apps) and are stuck on Xcode 14 (work policy), are you able to point in the right direction on how to fix this error? Or at least point in the right direction. Even if you don't add it to the main repo, our office can fork the project and use separately with the fix

**Comment by LeoNatan** [comment]
@hell001 I’m not sure these days what is missing from the modern SDK. You’ll just have to follow the compile errors and remove portions of the code that are not available. I cannot comment on how much functionality will be impacted. As far as I remember, the above code is something I was considering implementing but never got to it. So it might be a simple removal of useless code.
