### ISSUE TITLE
Cannot archive on UIKit project

### ISSUE THREAD

**Issue by sereivoanyong** [LeoNatan/LNPopupController#571]
When I try to archive on the project that uses UIKit, it fails.

Undefined symbol: ___fixUIHostingViewHitTest

This is due to the SwiftUI import check in SwiftRefinement.swift
```
#if canImport(SwiftUI)
import SwiftUI

@_cdecl("__fixUIHostingViewHitTest")
internal
func fixUIHostingViewHitTest() {
...
}
#endif
```

And the call to `___fixUIHostingViewHitTest` in UIViewController+LNPopupSupportPrivate.m doesn't check for SwiftUI import (wrap in `canImport(SwiftUI)`).

**Comment by LeoNatan** [comment]
Nice catch, thanks. Please try with the latest release.

**Comment by LeoNatan** [comment]
Seems like the issue still reproduces. Investigating.

**Comment by LeoNatan** [comment]
I think the issue isn’t that SwiftUI cannot be imported, but that the optimizer strips the C symbol. I think I have a solution.

**Comment by sereivoanyong** [comment]
This is the quickest response. 😁 Thank you so much.

**Comment by LeoNatan** [comment]
Cheers, happy coding!
