### ISSUE TITLE
Apple blocking access to UINavigationBar's backdropGroupName

### ISSUE THREAD

**Issue by llsc12** [LeoNatan/LNPopupController#578]
### Describe the Bug:

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UINavigationBar's backdropGroupName ivar is prohibited. This is an application bug'

Unfortunately, Apple is blocking more ivars in iOS 18.

<img width="928" alt="image" src="https://github.com/user-attachments/assets/aa79257a-7f2a-4ab2-a8b1-5aa4402f4cc6">

I've highlighted the line causing the exception. Thanks.

### Reproduction:

Using the controller in any way causes this exception.

### Expected Behavior:

N/A

**Comment by LeoNatan** [comment]
Looks like you are using an old version of the framework. Please update to the latest version.

**Comment by LeoNatan** [comment]
Compare how the files looks now, vs your version:

https://github.com/LeoNatan/LNPopupController/blob/623263d466d8fc03e3ac13a16f68d228c86e2f62/LNPopupController/LNPopupController/Private/UIView%2BLNPopupSupportPrivate.mm#L101

Notice the different extension, different key name, etc.
