### ISSUE TITLE
iOS 18.1 betas 4/5 are known to be buggy 🤷‍♂️

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#579]
Latest beta changes something and `setToolbarHidden:animated:` broke. `hidesBottomBarWhenPushed` seems buggy too.

**Comment by LeoNatan** [comment]
Actually, this seems like a bug in iOS 18.1 b4, unrelated to the framework.

**Comment by LeoNatan** [comment]
FB15234633


https://github.com/user-attachments/assets/d00eac64-8e87-4587-8be9-06e9b85a3e53

🤦‍♂️

**Comment by LeoNatan** [comment]
Beta 5 does not fix the issue.

**Comment by iDevelopper** [comment]
Swipe to show the previous controller I can note the following message in the console:

**Failed to create 0x132 image slot (alpha=1 wide=1) (client=0xa7cbe5bd) [0x5 (os/kern) failure]**

 Also, in the debug view hierarchy, the toolbar appears well, alpha = 1 and is not hidden.

**Comment by LeoNatan** [comment]
Fixed in beta 6.
