### ISSUE TITLE
Bottom docking view should respect tabBar.isHidden property

### ISSUE THREAD

**Issue by dive** [LeoNatan/LNPopupController#58]
Hi,

UITabBar can be hidden with `.hidden` property, but in this case `bottomBarFrame` still will be calculated with default UITabBar height (including `frame.origin`). You can see it [here](https://github.com/LeoNatan/LNPopupController/blob/50121d10edcc872e1605f2c81e4faf2c018ca8af/LNPopupController/LNPopupController/Private/UIViewController%2BLNPopupSupportPrivate.m#L261-L268):
```
- (CGRect)defaultFrameForBottomDockingView
{
	CGRect bottomBarFrame = self.tabBar.frame;	
	bottomBarFrame.origin = CGPointMake(0, self.view.bounds.size.height - bottomBarFrame.size.height);
	return bottomBarFrame;
}
```

I think `.origin` should be calculated with additional check for visibility, something like this:
```
- (CGRect)defaultFrameForBottomDockingView
{
	CGRect bottomBarFrame = self.tabBar.frame;	
	bottomBarFrame.origin = CGPointMake(0, self.view.bounds.size.height - (self.tabBar.isHidden ? 0 : bottomBarFrame.size.height));
	return bottomBarFrame;
}
```

Regards,
Artem

**Comment by LeoNatan** [comment]
Hi,

This goes against Apple's guidelines, and is not supported. 

> You should never attempt to manipulate the UITabBar object itself stored in this property.

If you must support this, you can subclass `UITabBarController` and implement `defaultFrameForBottomDockingView` yourself, taking into account whether the tab bar is hidden or not.

Thanks
