### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=2, address=0x16d4f3d00)

### ISSUE THREAD

**Issue by fahimrahmanbooom** [LeoNatan/LNPopupController#582]
### Describe the Bug:

I'm getting a crash here. It started from iOS 18.

```
//Ignore nested calls to _showBarWithTransition:isExplicit:duration:
		if(@available(iOS 18.0, *))
		{
			[self sBWT:transition iE:isExplicit d:duration r:reason];
		}
		else
		{
			[self sBWT:transition iE:isExplicit d:duration];
		}
		return;
```

### Reproduction:

When I run the project, it crashes and points to this code.

### Expected Behavior:

The code should not crash at the beginning.

**Comment by LeoNatan** [comment]
Hello,
Which project are you running? There is an example project that works on iOS 18 and below. I know people are running the framework on iOS 18, so likely a user error. Start by running that demo project and see if it works for you. Also, please post a full stacktrace of the crash.
Thanks
