### ISSUE TITLE
Slow launches

### ISSUE THREAD

**Issue by rastaman111** [LeoNatan/LNPopupController#584]
### Describe the Bug:

I constantly get this message when I launch the application, but I don't see any dependencies in UI

I get from 1 to 3 of them as on the screen

Perhaps this is not a bug

### Reproduction:

1. Logged into the app
2. Received this message

### Expected Behavior:

No message data

### Screenshots and/or Videos:

<img width="887" alt="Снимок экрана 2024-10-29 в 13 40 33" src="https://github.com/user-attachments/assets/58b46de7-91d2-4a42-974a-a34b65cb6fc6">

**Comment by LeoNatan** [comment]
This is not related to this framework. The framework does not perform any I/O. You are just seeing this in the stack trace because it swizzles that particular method.

**Comment by LeoNatan** [comment]
If you have a full stack trace of where the runtime issue is produced, we can think together why it happens. You can verify this doesn't occur normally by running the included demo project in this repository.
