### ISSUE TITLE
Bug: Stuck on endless loop when on iPad with Split View

### ISSUE THREAD

**Issue by BLeeEZ** [LeoNatan/LNPopupController#585]
### Describe the Bug:

First of all: Thank you very much for this great project. I am using this project for Amperfy (https://github.com/BLeeEZ/amperfy) for a while now.
I have tested v2.20.5 on macOS, iOS and horizontal/landscape iPadOS and it works fine except for iPadOS Split View.
In iPadOS SplitView, LNPopupController seems like to get stuck in an endless loop (100% CPU load without visual progress). In the following I share a screenshot of the simulator debugger stack trace when pressing debugger pause at some time:
<img width="655" alt="Bildschirmfoto 2024-11-04 um 20 59 00" src="https://github.com/user-attachments/assets/7aa29f14-3a0a-45ef-b248-68b6e8f2321b">

### Reproduction:

1. Open a project with LNPopupController on an iPad
2. Press the "..." button in iPadOS and press "Split View"
3. Select another app to show on the other half of the screen:

<img width="951" alt="Bildschirmfoto 2024-11-04 um 21 09 43" src="https://github.com/user-attachments/assets/7b66a71d-dbe1-407c-82bb-d74ea309735b">

4. Press on the Popup Bar.
5. App freezes on 100% CPU load.

### Expected Behavior:

Open the embedded view, like it does on macOS, iOS and horizontal/landscape iPadOS

**Comment by LeoNatan** [comment]
Hello,
Could you reproduce this issue in a small proejct?
I have thoroughly tested the framework with all the various iPad multitasking modes, and for me, it works as it should.
Thanks

**Comment by LeoNatan** [comment]
You can also test the included demo project with multitasking and different settings to see if you can find a configuration that reproduces the issue.

**Comment by BLeeEZ** [comment]
Thank you for your fast reply. The problem is somewhere inside my view that should be presented.
I am sorry for the inconvenience.

**Comment by LeoNatan** [comment]
No worries. If you have trouble figuring it out, you can open a discussion and we can ponder together.
