### ISSUE TITLE
Error not Loaded

### ISSUE THREAD

**Issue by chlebta** [LeoNatan/LNPopupController#6]
Hello, I've dragged and dropped LNPopupController.xcoderoj into my project then I added the Framework to binary. Finally,  in .m file I've  added `@import LNPopupController;`.
Now when I run my project I get  this error : 

```
dyld: Library not loaded: @rpath/LNPopupController.framework/LNPopupController
  Referenced from: /private/var/mobile/Containers/Bundle/Application/811B7095-DA53-4F0E-B48D-D22765AAFD7E/flimee.app/flimee
  Reason: image not found

```

Did I missed something here ?

**Comment by LeoNatan** [comment]
See if issue #5 helps you.

**Comment by LeoNatan** [comment]
@chlebta Did that other issue I linked help you?

**Comment by chlebta** [comment]
Nope we don't have some issue I got this error ** Reason: image not found**

**Comment by LeoNatan** [comment]
I am sorry, you must have done something wrong. I tested this on several devices, and cannot reproduce the issue. Make sure you added the framework to your project's embedded binaries. Make sure "Embed Frameworks" step exists in your build phases, and that the framework is found in that phase.

Perhaps compare with the demo project, which should work.
