### ISSUE TITLE
Assertion fail when switch to another view controller.

### ISSUE THREAD

**Issue by b2github** [LeoNatan/LNPopupController#60]
Assertion fail when switch to another view controller when using with UITabBarController.
It happen if popupBar not show on current tab then switch to other tab will crash the app.

```
- (void)_movePopupBarAndContentToBottomBarSuperview
{
	NSAssert(_bottomBar.superview != nil, @"Bottom docking view must have a superview before presenting popup.");
	[_popupBar removeFromSuperview];
	[_bottomBar.superview insertSubview:_popupBar belowSubview:_bottomBar];
	[_popupBar.superview bringSubviewToFront:_popupBar];
	[_popupBar.superview bringSubviewToFront:_bottomBar];
	[_popupBar.superview insertSubview:self.popupContentView belowSubview:_popupBar];
}
```

Cheers

**Comment by LeoNatan** [comment]
When using a tab bar controller, you must present the popup bar from tab bar controller, not on the internal controller.

**Comment by b2github** [comment]
Sorry, I mean it crash if popup bar not show.

The _bottomBar variable is set with present popup bar and it looks like it set back to nil when dismiss.

any advise?

Cheers

ps.
I already show popupbar from UIBarBarController.

**Comment by LeoNatan** [comment]
Can you please create a demo project?

**Comment by LeoNatan** [comment]
I think I reproduced. Investigating.

**Comment by b2github** [comment]
Sorry that I didn't provide you a demo project.
Thanks you very much for fixing this bug.

Cheers
