### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITabBarController popupContentViewController]:

### ISSUE THREAD

**Issue by mahmoud-amer-m** [LeoNatan/LNPopupController#61]
I've this error while trying to present the popupbar
I've implemented DemoPopupContentViewController like in the example

- (void)presentBarEngine
{
    UIViewController* targetVC = self.tabBarController;
    if(targetVC == nil)
    {
        targetVC = self.navigationController;
        
        if(targetVC == nil)
        {
            targetVC = self;
        }
    }
    
    if(targetVC.popupContentViewController != nil)
    {
        return;
    }
    
    DemoPopupContentViewController* demoVC = [DemoPopupContentViewController new];
    demoVC.popupItem.title = @"test title";
    demoVC.popupItem.subtitle = @"test subtitle";
    demoVC.popupItem.progress = (float) arc4random() / UINT32_MAX;
    
    [targetVC presentPopupBarWithContentViewController:demoVC animated:YES completion:nil];
}

**Comment by LeoNatan** [comment]
I don't understand what the problem is. Please form your question better.

**Comment by mahmoud-amer-m** [comment]
I'm not using storyboards, and I got this error
-[UITabBarController popupContentViewController]: unrecognized selector sent to instance 0x7ff75b933d80
while presenting the popupbar

**Comment by LeoNatan** [comment]
I think you have not integrated the framework properly in your project.

**Comment by mahmoud-amer-m** [comment]
I've added it to my cartfile and I got no errors while importing the module in my viewcontroller

**Comment by LeoNatan** [comment]
The error indicates that a method I expose in my categories is not compiled. 

If you run the demo project, does it work as expected?

**Comment by LeoNatan** [comment]
This is not an issue with framework. It's a problem on your end. Please take a look at the demo project and see how that links the framework in.
