### ISSUE TITLE
Bottom layout guide correction doesn't work for UISplitViewController

### ISSUE THREAD

**Issue by semyonvlasov** [LeoNatan/LNPopupController#63]
Bottom layout guide correction doesn't work for master view controller when using UISplitViewController  as a child VC of UITabBarController.
Maybe the reason is that the func _LNPopupSupportFixInsetsForViewController uses property ".childViewControllers" for recursive correction but UISplitViewController hasn't that propery.

**Comment by LeoNatan** [comment]
Thanks, will have a look soon.
