### ISSUE TITLE
Bottom layout guide correction doesn't work with UITableViewController

### ISSUE THREAD

**Issue by semyonvlasov** [LeoNatan/LNPopupController#65]
Bottom layout guide correction doesn't work with UITableViewController. If I create storyboard UIViewController with UITableView and it's bottom constraint at bottom layout guide all works fine. However if I create storyboard UITableViewController correction doesn't work after popup bar appears. 

Here the screenshots with storyboard and application behavior. 
-NMCFriendsVC with list of friends (50 items from 0 to 49) is subclass of UITableViewController.
-NMCSongsVC with list of songs (50 items from 0 to 49) is subclass of UIViewController with custom added UITableView IBOutlet connected to bottom layout guide.

- All tables are scrolled to the end of list but -NMCFriendsVC display row 50 (friend 49) under popup bar

![img_0061](https://cloud.githubusercontent.com/assets/18718777/14907864/c573ccc0-0df8-11e6-8b7c-de83b6a81479.PNG)
![img_0062](https://cloud.githubusercontent.com/assets/18718777/14907863/c573466a-0df8-11e6-91cb-271629a96247.PNG)

![2016-04-29 10 39 14](https://cloud.githubusercontent.com/assets/18718777/14907850/b40b280c-0df8-11e6-98ae-20df255f2223.png)
![2016-04-29 10 39 36](https://cloud.githubusercontent.com/assets/18718777/14907851/b40c4d4a-0df8-11e6-96a1-f98d31d95b30.png)

**Comment by semyonvlasov** [comment]
It's not a big problem, I will just replace UITableVCs with UIVCs in my storyboard, but You should know the issue. 
You've made really great component, thanks :)

**Comment by LeoNatan** [comment]
This sounds like the intended behavior. After the controller is presented, the popup presentation will not modify the insets. This is how Apple does it. When you present a popup bar, make sure to update your table view's content insets. I do the same in my music app in the demo project:

```swift
override func viewDidLayoutSubviews() {
	super.viewDidLayoutSubviews()
		
	let insets = UIEdgeInsetsMake(topLayoutGuide.length, 0, bottomLayoutGuide.length, 0)
	tableView.contentInset = insets
	tableView.scrollIndicatorInsets = insets
}
```
