### ISSUE TITLE
Best way to adjust bar frame

### ISSUE THREAD

**Issue by morad** [LeoNatan/LNPopupController#66]
Gents,

Trying to figure out the best way to adjust the height of the mini docked player along with barbuttonitems position vertically. any tips without hacking it? 

Screenshot explains what I have after adjusting LNPopupBarHeight value from 40 to 80. you can see things are not aligned with barbuttomitems.

![screen shot 2016-05-01 at 8 36 52 pm](https://cloud.githubusercontent.com/assets/66266/14943270/b2fa5f92-0fdc-11e6-8f5d-a6ab45eff884.png)

**Comment by LeoNatan** [comment]
Hey,

As you can see, it is not supported. You will need to hack it. Take a look at `LNPopupBar`, specifically at `initWithFrame:` and `_layoutTitles`.

I will not be supporting this in the framework. The LNPopupBarHeight will remain 40. But feel free to ask questions here if you them,

Thanks,
Leo

**Comment by LeoNatan** [comment]
@justin999 Thanks for pointing that out! It is indeed possible to create custom popup bars now. However, note that the default behavior is not supported with custom bar controllers?
