### ISSUE TITLE
Docking to a view issue

### ISSUE THREAD

**Issue by snooppok** [LeoNatan/LNPopupController#67]
Hello.
Thanks for your amazing framework, you really made a great job.

I have an issue with docking the popup bar to a bottom view. 
My view is 0px attached to the bottom of the main VC (without margin) with an auto layout constraint (not bottom layout but buttom of superview).

I set up the LNPopupController in the viewDidAppear of my main VC. When I run my app, it appears correctly, with the appropriate animation.

When I use a pan gesture to open the pop over, it appears correctly and the docking view is moving downward out of the screen correctly.
But I encounter an issue when I tap on the popup bar, instead of using pan gesture : the view in the pop over is ok, but the docking Y position changes instantly in (something like "origin.y - <docking view height>") and then moves downward to it's original position at the bottom of my screen (but inside the screen).
At the end of the whole animation , the docking view is still displayed on the screen above all VC (including the pop over).

A small detail that may help you: when I pan slightly the pop over view, the docking view disappear. When I go to iphone sleeping mode and get back in the app the docking view appears again.

Could you please help me on this one ? Your help will be very appreciated.

Thanks you !

**Comment by LeoNatan** [comment]
Thanks for the report. Will take a look when I have some free time. Can you attach a demo project?

**Comment by snooppok** [comment]
Here it is :)
Just a small project with 2 VC, 1 docking view in the main VC. Same issue. Let me know.
Thanks !

[TestLN.zip](https://github.com/LeoNatan/LNPopupController/files/249706/TestLN.zip)

**Comment by LeoNatan** [comment]
Seems to be related to autolayout. Without it, everything works as expected. Investigating.

**Comment by snooppok** [comment]
Thank you LN. 
Just tried you fix. It partially removed the issue.
When I click on the popup bar, the dock is moving out of the screen ok. But, then, if you let the popover open, switch to ios home and get back in the app, the docking view is bought back on the popover view. It's like the constraints were refresh. Arg!

so sorry to bother you :) let me know if you can find any solution.
 Again, thanks again for your quick feedbacks.

**Comment by LeoNatan** [comment]
Oh no :-(
Will look.

**Comment by snooppok** [comment]
great, thank. Look forward to read you.

**Comment by LeoNatan** [comment]
@snooppok Please test now. I think I found the error and fixed.

**Comment by snooppok** [comment]
Looks great! Thanks a lot!
