### ISSUE TITLE
iOS 8 issue, UISplitViewController (LNPopupSupportPrivate)

### ISSUE THREAD

**Issue by b2github** [LeoNatan/LNPopupController#68]
Hi,

I want to report that I found an issue on iOS8.
This seem to works fine on iOS9.

I don't know why but on iOS8, in the implementation of UISplitViewController (LNPopupSupportPrivate). The _ln_popup_viewDidLayoutSubviews_SplitViewNastyApple is called even the viewcontroler is not UISplitViewContrller, and the app crash on [self _ln_popup_viewDidLayoutSubviews_SplitViewNastyApple];.

It's look like the iOS8 bug for me. 
What I did is adding the following empty implementation in the UISplitViewController (LNPopupSupportPrivate)

```
- (void)viewDidLayoutSubviews {

}
```

After adding this, it works and UISplitViewController (LNPopupSupportPrivate): _ln_popup_viewDidLayoutSubviews_SplitViewNastyApple is not be called on my UIViewController subclass.

I hope this help.

ps.
I never test this with the UISplitViewController on iOS8.

Cheers

**Comment by LeoNatan** [comment]
Damn, they added a method on iOS 9 but didn't on 8. OK, thanks for the report. Will solve soon.
