### ISSUE TITLE
MPNowPlayingInfoCenter not working properly

### ISSUE THREAD

**Issue by tin612** [LeoNatan/LNPopupController#77]
My app use your library but i can't show MPNowPlayingInfoCenter to lock screen in my app. In other view controllers i can add but in your controller i can't show it

**Comment by LeoNatan** [comment]
I am not familiar with this. What is it? What do you mean "can't"?

**Comment by tin612** [comment]
I use your library to implement my player view. But when i try to add info of a song to a lock screen, the info is not show at all.

**Comment by LeoNatan** [comment]
I don't see how this is related to the framework.

**Comment by tin612** [comment]
Okay let me check it again

**Comment by tin612** [comment]
i checked it but i can't add the info to the controller use your framework.
i add info on viewdidload
![image](https://cloud.githubusercontent.com/assets/13097339/15651842/3e3827e8-26ac-11e6-9d74-b8b822b52b2c.png)
and then i check again in control center of ios. it show nothing
![simulator screen shot may 30 2016 9 20 25 pm](https://cloud.githubusercontent.com/assets/13097339/15651863/6467f89e-26ac-11e6-9f54-9f2e10b85765.png)

**Comment by LeoNatan** [comment]
Put a breakpoint in there and see if that method is called. You may be doing something wrong.
