### ISSUE TITLE
dismissPopupBarAnimated not working

### ISSUE THREAD

**Issue by MikeDyna** [LeoNatan/LNPopupController#80]
Hi,

first of all thx for this great implementation. It all works really nicely, except for the dismiss function.

I´m calling it from a button in:

```
let close = UIBarButtonItem(image: UIImage(named: "menu-close"), style: .Plain, target: self, action: .miniPlayerCloseButtonTapped)

self.popupItem.rightBarButtonItems = [close]
```

this calls:

```
func miniPlayerCloseButtonTapped(sender: AnyObject) {
		log.debug("Close")

		tabBarController?.dismissPopupBarAnimated(true, completion: nil)
}
```

but the PopupBar doesn´t dismiss. 

Any ideas?

**Comment by MikeDyna** [comment]
I found the solution, so i´m gonna leave it here for anyone struggling with the same problem.

```
popupPresentationContainerViewController?.dismissPopupBarAnimated(true, completion: nil)
```

**Comment by yetdog** [comment]
Thanks! Was having this exact issue and @MikeDyna's solution fixed!
