### ISSUE TITLE
I cannot add swipe gesture

### ISSUE THREAD

**Issue by hirengohel** [LeoNatan/LNPopupController#81]
i want to change song using swipe gesture but i cannot do that.

**Comment by LeoNatan** [comment]
I don't understand what you are trying to do, so how can I help? State your problem more clearly.

**Comment by rajatk** [comment]
I think OP is asking about using Swipe to change tracks from the popup bar. Spotify allows this. I was curious about this too.

**Comment by LeoNatan** [comment]
The popup bar is exposed, so you can add additional swipe gesture recognizers. However, do this with care, as there are other gesture recognizers active on the bar. So you have to use the delegate methods to ensure other gesture recognizers are not affected by yours.
