### ISSUE TITLE
Content controller is displaying under the navigation bar

### ISSUE THREAD

**Issue by neekeetab** [LeoNatan/LNPopupController#83]
Hi! I've got similar issue to #55. To replay it, first tap search bar, then close it and try to open content controller.
Demo: https://github.com/neekeetab/PopupTest
Thanks!

**Comment by neekeetab** [comment]
Solved it by bringing popupContentView to front:
`self.navigationController!.view.bringSubviewToFront(self.navigationController!.popupContentView)`

**Comment by LeoNatan** [comment]
This might be an issue with the framework. I'll keep open for now, until I can test.

**Comment by DCDJ** [comment]
Just ran into this too. I can re-create it:

If the popup is presented whilst the navigation bar is still **hidden**, it'll be underneath. So then you have to run this:

self.navigationController!.setNavigationBarHidden(false, animated: false)
self.navigationController!.view.bringSubview(toFront: self.navigationController!.popupContentView)
self.navigationController!.view.bringSubview(toFront: self.navigationController!.popupBar!)

Hope that may be of some help

**Comment by LeoNatan** [comment]
Above commits referenced this issue by mistake.

**Comment by LeoNatan** [comment]
@neekeetab @DCDJ Please test now.

**Comment by DCDJ** [comment]
@LeoNatan Works. Thanks!
