### ISSUE TITLE
Update popup bar labels without without rebuilding the whole view

### ISSUE THREAD

**Issue by macecchi** [LeoNatan/LNPopupController#84]
I noticed that updating the title or the subtitle of the popup bar makes a call to `[LNPopupBar _layoutTitles]`. This might be unnecessary sometimes and has become an issue with my app.

I'm using the popup bar to display a timer that, along with the progress bar, displays the remaining time in the title (e.g.: Remaining: 00:01:59).The title is updated every second with the new remaining time, and the subtitle - which is a description of the current timer - remains the same.

However, because the whole view is redrawn every second when I update the title, this stops my subtitle from animating its marquee, as the view is recreated before the marquee can even start animating. I notice that if I pause the timer - therefore without updating the labels - the subtitle animates correctly.

Is there a way to accomplish this?

**Comment by LeoNatan** [comment]
Hmm, this is an interesting issue.

The reason they are updated together in `_layoutTitles` is to cause the marquees to start animating together, which is the desired behavior in cases different than yours. I agree that this is not good for you.

The question is, how to introduce an API to allow you to override this for your usecase. I will have to think about it. For now, fork the project, and change `_layoutTitles` to fit your usecase.

**Comment by macecchi** [comment]
Thanks for your reply! I agree with you that this should be a specific case. 

I'll do as you suggested and work on this in my own fork. Maybe I'll have an idea of how to introduce this too :)

**Comment by LeoNatan** [comment]
@macecchi Well finally it came! 😄 In branch 2_0, there is now [`coordinateMarqueeScroll`](https://github.com/LeoNatan/LNPopupController/blob/v2_0/LNPopupController/LNPopupController/LNPopupBar.h#L69) on `LNPopupBar` which you can change to `NO` and that will no longer trigger a full layout pass on the labels. So if you update either the title or subtitle, the other one will remain scrolling.

**Comment by macecchi** [comment]
@LeoNatan That's awesome! I'll try it out! Thanks!
