### ISSUE TITLE
Possible to show buffered on popup item progress bar?

### ISSUE THREAD

**Issue by rajatk** [LeoNatan/LNPopupController#86]
In addition to showing progress I also want to show buffered region on this popup bar. Is that currently possible? I don't think the bar is currently exposed.

**Comment by LeoNatan** [comment]
The popup bar is exposed through `@property (nullable, nonatomic, strong, readonly) LNPopupBar* popupBar;`, however modifying the bar is not supported. I plan to make changes to bring iOS 10 look and feel support, but layout will remain internal.

**Comment by rajatk** [comment]
thank you @LeoNatan
