### ISSUE TITLE
Popup bar slips partly under tab bar, when in call status bar is present

### ISSUE THREAD

**Issue by rajatk** [LeoNatan/LNPopupController#87]
I can't consistently repro this issue, since it has to do with some order of operations about call status bar appearing and then collapsing full screen controller, but you should atleast be able to see broken constraint warnings when you launch the popup bar and simulate call bar (CMD + Y) in simulator.

```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7f94e7e730d0 V:|-(20)-[UIInputSetContainerView:0x7f94e7e6f130]   (Names: '|':UITextEffectsWindow:0x7f94e9929030 )>",
    "<NSLayoutConstraint:0x7f94e991f800 'UIInputWindowController-top' V:|-(0)-[UIInputSetContainerView:0x7f94e7e6f130]   (Names: '|':UITextEffectsWindow:0x7f94e9929030 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7f94e7e730d0 V:|-(20)-[UIInputSetContainerView:0x7f94e7e6f130]   (Names: '|':UITextEffectsWindow:0x7f94e9929030 )>
```

**Comment by LeoNatan** [comment]
Hmm. Interesting. Thanks for the report, will take a look.

**Comment by LeoNatan** [comment]
Hi,

I cannot reproduce this. The popup controller behaves correctly with the call-sized status bar. 
Also note that I do not use auto-layout in the framework other than a single view. This may be an issue with your code / setup.

Please provide a sample project where this reproduces.
