### ISSUE TITLE
Cannot get to editing mode of UITableViewCell when UITableView in LNPopupController

### ISSUE THREAD

**Issue by mikesimonetta** [LeoNatan/LNPopupController#92]
I have a UITableView within my LNPopupController. For whatever reason (I assume the popup controller is consuming the swipe gesture), I cannot slide to enter editing mode for an individual cell. Do we have a fix for this or can one be provided?

**Comment by LeoNatan** [comment]
I'll take a look.

**Comment by LeoNatan** [comment]
Fixed.

**Comment by mikesimonetta** [comment]
@LeoNatan do i need to pull updated repo in for the fix i assume?

**Comment by LeoNatan** [comment]
Yes. If you are using Carthage, I have not yet created a tag. I will do that as soon as I feel comfortable with iOS 10 look and feel.

**Comment by mikesimonetta** [comment]
New issue once I pulled in updated project..

“Cannot find protocol declaration for ‘CAAnimationDelegate’ in __MarqueeLabel.m”


Regards,

Michael Simonetta
Mobile Developer

CHAT 647 361 8401 x139
WRITE michaels@clearbridgemobile.com <http://clearbridgemobile.com/>
SURF clearbridgemobile.com <http://clearbridgemobile.com/>


CONFIDENTIALITY NOTICE: The e-mail transmission and any documents, file or previous e-mail messages attached to it may contain confidential and/or proprietary information. If you are not the intended recipient, you are hereby notified that any disclosure, dissemination, distribution or copying of this communication is strictly prohibited.

**Comment by mikesimonetta** [comment]
@LeoNatan  New issue once I pulled in updated project..

“Cannot find protocol declaration for ‘CAAnimationDelegate’ in __MarqueeLabel.m”

**Comment by LeoNatan** [comment]
Ahh
I used Xcode 8 to work on the project, and I guess that symbol is only defined in iOS 10 SDK. Without it, there is a warning in Xcode 8. I'll wrap it in `#ifdef` later.

**Comment by LeoNatan** [comment]
@mikesimonetta Fixed. Should compile now with Xcode 7.x
