### ISSUE TITLE
Is there a way to check if the popupcontroller is already being presented?

### ISSUE THREAD

**Issue by glennposadas** [LeoNatan/LNPopupController#97]
I got a music player embedded inside that popupcontroller, and my issue is that whenever I call the **presentPopupBarWithContentViewController**, my music player adds another instance, so there are multiple songs being played. Thanks!

- right now, I can check if the popupbar is existing by having a boolean variable in my singleton class.

**Comment by LeoNatan** [comment]
You can check the `popupPresentationState` property on the popup container controller.
